using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace runnerDotNet
{
    public class dalTable_Hubkoratec218206166241compute1_dbo_csi_po_mst : tDALTable
    {
        public XVar clientid;
        public XVar VariationNumber;
        public XVar po_num;
        public XVar site_ref;
        public XVar act_brokerage;
        public XVar act_duty;
        public XVar act_freight;
        public XVar act_insurance;
        public XVar act_local_freight;
        public XVar auto_receive_demanding_site_po;
        public XVar auto_ship_demanding_site_co;
        public XVar auto_voucher;
        public XVar brk_alloc_meth;
        public XVar brk_alloc_percent;
        public XVar brk_alloc_type;
        public XVar brokerage_amt;
        public XVar brokerage_amt_t;
        public XVar brokerage_vend_num;
        public XVar builder_po_num;
        public XVar builder_po_orig_site;
        public XVar builder_po_printed;
        public XVar buyer;
        public XVar charfld1;
        public XVar charfld2;
        public XVar charfld3;
        public XVar contains_only_tax_free_matls;
        public XVar CreateDate;
        public XVar CreatedBy;
        public XVar curr_code;
        public XVar datefld;
        public XVar decifld1;
        public XVar decifld2;
        public XVar decifld3;
        public XVar delterm;
        public XVar dist_date;
        public XVar drop_seq;
        public XVar drop_ship_no;
        public XVar duty_alloc_meth;
        public XVar duty_alloc_percent;
        public XVar duty_alloc_type;
        public XVar duty_amt;
        public XVar duty_amt_t;
        public XVar duty_vend_num;
        public XVar eff_date;
        public XVar est_brokerage;
        public XVar est_duty;
        public XVar est_freight;
        public XVar est_insurance;
        public XVar est_local_freight;
        public XVar exch_rate;
        public XVar exp_date;
        public XVar fixed_rate;
        public XVar fob;
        public XVar freight;
        public XVar freight_t;
        public XVar freight_vend_num;
        public XVar frt_alloc_meth;
        public XVar frt_alloc_percent;
        public XVar frt_alloc_type;
        public XVar frt_tax_code1;
        public XVar frt_tax_code2;
        public XVar include_tax_in_cost;
        public XVar ins_alloc_meth;
        public XVar ins_alloc_percent;
        public XVar ins_alloc_type;
        public XVar ins_vend_num;
        public XVar insurance_amt;
        public XVar insurance_amt_t;
        public XVar inv_date;
        public XVar inv_num;
        public XVar InWorkflow;
        public XVar loc_frt_alloc_meth;
        public XVar loc_frt_alloc_percent;
        public XVar loc_frt_alloc_type;
        public XVar loc_frt_vend_num;
        public XVar local_freight_amt;
        public XVar local_freight_amt_t;
        public XVar logifld;
        public XVar fldm_charges_t;
        public XVar misc_charges;
        public XVar msc_tax_code1;
        public XVar msc_tax_code2;
        public XVar NoteExistsFlag;
        public XVar order_date;
        public XVar po_cost;
        public XVar prepaid_amt;
        public XVar prepaid_t;
        public XVar print_price;
        public XVar process_ind;
        public XVar received;
        public XVar RecordDate;
        public XVar RowPointer;
        public XVar sales_tax;
        public XVar sales_tax_2;
        public XVar sales_tax_t;
        public XVar sales_tax_t2;
        public XVar ship_addr;
        public XVar ship_code;
        public XVar source_site_co_num;
        public XVar stat;
        public XVar supply_web_po_stat;
        public XVar synchronized_to_bus;
        public XVar tax_code1;
        public XVar tax_code2;
        public XVar terms_code;
        public XVar trans_nat;
        public XVar trans_nat_2;
        public XVar type;
        public XVar UpdatedBy;
        public XVar vend_lcr_num;
        public XVar vend_num;
        public XVar vend_order;
        public XVar whse;
        public XVar DLDeleteIndicator;
        public XVar tp_id;
        public XVar tp_posted;
        public XVar sc_id;
        public XVar sc_posted;
        public XVar sf_id;
        public XVar sf_posted;
        public XVar mg_id;
        public XVar mg_posted;
        public XVar uf_uet1;
        public XVar uf_uet2;
        public XVar uf_uet3;
        public XVar uf_uet4;
        public XVar uf_uet5;
        public XVar uf_uet6;
        public XVar uf_uet7;
        public XVar uf_uet8;
        public XVar uf_uet9;
        public XVar uf_uet10;
        public XVar tp_posted_date;
        public XVar tp_rev;
        public XVar tp_rcvd;
        public XVar tp_closed;
        public XVar tp_re_post;
        public static void Init()
        {
            XVar dalTablecsi_po_mst = XVar.Array();
            dalTablecsi_po_mst["clientid"] = new XVar("type", 202, "varname", "clientid", "name", "clientid", "autoInc", "0");
            dalTablecsi_po_mst["VariationNumber"] = new XVar("type", 20, "varname", "VariationNumber", "name", "VariationNumber", "autoInc", "0");
            dalTablecsi_po_mst["po_num"] = new XVar("type", 202, "varname", "po_num", "name", "po_num", "autoInc", "0");
            dalTablecsi_po_mst["site_ref"] = new XVar("type", 202, "varname", "site_ref", "name", "site_ref", "autoInc", "0");
            dalTablecsi_po_mst["act_brokerage"] = new XVar("type", 14, "varname", "act_brokerage", "name", "act_brokerage", "autoInc", "0");
            dalTablecsi_po_mst["act_duty"] = new XVar("type", 14, "varname", "act_duty", "name", "act_duty", "autoInc", "0");
            dalTablecsi_po_mst["act_freight"] = new XVar("type", 14, "varname", "act_freight", "name", "act_freight", "autoInc", "0");
            dalTablecsi_po_mst["act_insurance"] = new XVar("type", 14, "varname", "act_insurance", "name", "act_insurance", "autoInc", "0");
            dalTablecsi_po_mst["act_local_freight"] = new XVar("type", 14, "varname", "act_local_freight", "name", "act_local_freight", "autoInc", "0");
            dalTablecsi_po_mst["auto_receive_demanding_site_po"] = new XVar("type", 20, "varname", "auto_receive_demanding_site_po", "name", "auto_receive_demanding_site_po", "autoInc", "0");
            dalTablecsi_po_mst["auto_ship_demanding_site_co"] = new XVar("type", 20, "varname", "auto_ship_demanding_site_co", "name", "auto_ship_demanding_site_co", "autoInc", "0");
            dalTablecsi_po_mst["auto_voucher"] = new XVar("type", 20, "varname", "auto_voucher", "name", "auto_voucher", "autoInc", "0");
            dalTablecsi_po_mst["brk_alloc_meth"] = new XVar("type", 202, "varname", "brk_alloc_meth", "name", "brk_alloc_meth", "autoInc", "0");
            dalTablecsi_po_mst["brk_alloc_percent"] = new XVar("type", 14, "varname", "brk_alloc_percent", "name", "brk_alloc_percent", "autoInc", "0");
            dalTablecsi_po_mst["brk_alloc_type"] = new XVar("type", 202, "varname", "brk_alloc_type", "name", "brk_alloc_type", "autoInc", "0");
            dalTablecsi_po_mst["brokerage_amt"] = new XVar("type", 14, "varname", "brokerage_amt", "name", "brokerage_amt", "autoInc", "0");
            dalTablecsi_po_mst["brokerage_amt_t"] = new XVar("type", 14, "varname", "brokerage_amt_t", "name", "brokerage_amt_t", "autoInc", "0");
            dalTablecsi_po_mst["brokerage_vend_num"] = new XVar("type", 202, "varname", "brokerage_vend_num", "name", "brokerage_vend_num", "autoInc", "0");
            dalTablecsi_po_mst["builder_po_num"] = new XVar("type", 202, "varname", "builder_po_num", "name", "builder_po_num", "autoInc", "0");
            dalTablecsi_po_mst["builder_po_orig_site"] = new XVar("type", 202, "varname", "builder_po_orig_site", "name", "builder_po_orig_site", "autoInc", "0");
            dalTablecsi_po_mst["builder_po_printed"] = new XVar("type", 20, "varname", "builder_po_printed", "name", "builder_po_printed", "autoInc", "0");
            dalTablecsi_po_mst["buyer"] = new XVar("type", 202, "varname", "buyer", "name", "buyer", "autoInc", "0");
            dalTablecsi_po_mst["charfld1"] = new XVar("type", 202, "varname", "charfld1", "name", "charfld1", "autoInc", "0");
            dalTablecsi_po_mst["charfld2"] = new XVar("type", 202, "varname", "charfld2", "name", "charfld2", "autoInc", "0");
            dalTablecsi_po_mst["charfld3"] = new XVar("type", 202, "varname", "charfld3", "name", "charfld3", "autoInc", "0");
            dalTablecsi_po_mst["contains_only_tax_free_matls"] = new XVar("type", 20, "varname", "contains_only_tax_free_matls", "name", "contains_only_tax_free_matls", "autoInc", "0");
            dalTablecsi_po_mst["CreateDate"] = new XVar("type", 135, "varname", "CreateDate", "name", "CreateDate", "autoInc", "0");
            dalTablecsi_po_mst["CreatedBy"] = new XVar("type", 202, "varname", "CreatedBy", "name", "CreatedBy", "autoInc", "0");
            dalTablecsi_po_mst["curr_code"] = new XVar("type", 202, "varname", "curr_code", "name", "curr_code", "autoInc", "0");
            dalTablecsi_po_mst["datefld"] = new XVar("type", 135, "varname", "datefld", "name", "datefld", "autoInc", "0");
            dalTablecsi_po_mst["decifld1"] = new XVar("type", 14, "varname", "decifld1", "name", "decifld1", "autoInc", "0");
            dalTablecsi_po_mst["decifld2"] = new XVar("type", 14, "varname", "decifld2", "name", "decifld2", "autoInc", "0");
            dalTablecsi_po_mst["decifld3"] = new XVar("type", 14, "varname", "decifld3", "name", "decifld3", "autoInc", "0");
            dalTablecsi_po_mst["delterm"] = new XVar("type", 202, "varname", "delterm", "name", "delterm", "autoInc", "0");
            dalTablecsi_po_mst["dist_date"] = new XVar("type", 135, "varname", "dist_date", "name", "dist_date", "autoInc", "0");
            dalTablecsi_po_mst["drop_seq"] = new XVar("type", 20, "varname", "drop_seq", "name", "drop_seq", "autoInc", "0");
            dalTablecsi_po_mst["drop_ship_no"] = new XVar("type", 202, "varname", "drop_ship_no", "name", "drop_ship_no", "autoInc", "0");
            dalTablecsi_po_mst["duty_alloc_meth"] = new XVar("type", 202, "varname", "duty_alloc_meth", "name", "duty_alloc_meth", "autoInc", "0");
            dalTablecsi_po_mst["duty_alloc_percent"] = new XVar("type", 14, "varname", "duty_alloc_percent", "name", "duty_alloc_percent", "autoInc", "0");
            dalTablecsi_po_mst["duty_alloc_type"] = new XVar("type", 202, "varname", "duty_alloc_type", "name", "duty_alloc_type", "autoInc", "0");
            dalTablecsi_po_mst["duty_amt"] = new XVar("type", 14, "varname", "duty_amt", "name", "duty_amt", "autoInc", "0");
            dalTablecsi_po_mst["duty_amt_t"] = new XVar("type", 14, "varname", "duty_amt_t", "name", "duty_amt_t", "autoInc", "0");
            dalTablecsi_po_mst["duty_vend_num"] = new XVar("type", 202, "varname", "duty_vend_num", "name", "duty_vend_num", "autoInc", "0");
            dalTablecsi_po_mst["eff_date"] = new XVar("type", 135, "varname", "eff_date", "name", "eff_date", "autoInc", "0");
            dalTablecsi_po_mst["est_brokerage"] = new XVar("type", 14, "varname", "est_brokerage", "name", "est_brokerage", "autoInc", "0");
            dalTablecsi_po_mst["est_duty"] = new XVar("type", 14, "varname", "est_duty", "name", "est_duty", "autoInc", "0");
            dalTablecsi_po_mst["est_freight"] = new XVar("type", 14, "varname", "est_freight", "name", "est_freight", "autoInc", "0");
            dalTablecsi_po_mst["est_insurance"] = new XVar("type", 14, "varname", "est_insurance", "name", "est_insurance", "autoInc", "0");
            dalTablecsi_po_mst["est_local_freight"] = new XVar("type", 14, "varname", "est_local_freight", "name", "est_local_freight", "autoInc", "0");
            dalTablecsi_po_mst["exch_rate"] = new XVar("type", 14, "varname", "exch_rate", "name", "exch_rate", "autoInc", "0");
            dalTablecsi_po_mst["exp_date"] = new XVar("type", 135, "varname", "exp_date", "name", "exp_date", "autoInc", "0");
            dalTablecsi_po_mst["fixed_rate"] = new XVar("type", 20, "varname", "fixed_rate", "name", "fixed_rate", "autoInc", "0");
            dalTablecsi_po_mst["fob"] = new XVar("type", 202, "varname", "fob", "name", "fob", "autoInc", "0");
            dalTablecsi_po_mst["freight"] = new XVar("type", 14, "varname", "freight", "name", "freight", "autoInc", "0");
            dalTablecsi_po_mst["freight_t"] = new XVar("type", 14, "varname", "freight_t", "name", "freight_t", "autoInc", "0");
            dalTablecsi_po_mst["freight_vend_num"] = new XVar("type", 202, "varname", "freight_vend_num", "name", "freight_vend_num", "autoInc", "0");
            dalTablecsi_po_mst["frt_alloc_meth"] = new XVar("type", 202, "varname", "frt_alloc_meth", "name", "frt_alloc_meth", "autoInc", "0");
            dalTablecsi_po_mst["frt_alloc_percent"] = new XVar("type", 14, "varname", "frt_alloc_percent", "name", "frt_alloc_percent", "autoInc", "0");
            dalTablecsi_po_mst["frt_alloc_type"] = new XVar("type", 202, "varname", "frt_alloc_type", "name", "frt_alloc_type", "autoInc", "0");
            dalTablecsi_po_mst["frt_tax_code1"] = new XVar("type", 202, "varname", "frt_tax_code1", "name", "frt_tax_code1", "autoInc", "0");
            dalTablecsi_po_mst["frt_tax_code2"] = new XVar("type", 202, "varname", "frt_tax_code2", "name", "frt_tax_code2", "autoInc", "0");
            dalTablecsi_po_mst["include_tax_in_cost"] = new XVar("type", 20, "varname", "include_tax_in_cost", "name", "include_tax_in_cost", "autoInc", "0");
            dalTablecsi_po_mst["ins_alloc_meth"] = new XVar("type", 202, "varname", "ins_alloc_meth", "name", "ins_alloc_meth", "autoInc", "0");
            dalTablecsi_po_mst["ins_alloc_percent"] = new XVar("type", 14, "varname", "ins_alloc_percent", "name", "ins_alloc_percent", "autoInc", "0");
            dalTablecsi_po_mst["ins_alloc_type"] = new XVar("type", 202, "varname", "ins_alloc_type", "name", "ins_alloc_type", "autoInc", "0");
            dalTablecsi_po_mst["ins_vend_num"] = new XVar("type", 202, "varname", "ins_vend_num", "name", "ins_vend_num", "autoInc", "0");
            dalTablecsi_po_mst["insurance_amt"] = new XVar("type", 14, "varname", "insurance_amt", "name", "insurance_amt", "autoInc", "0");
            dalTablecsi_po_mst["insurance_amt_t"] = new XVar("type", 14, "varname", "insurance_amt_t", "name", "insurance_amt_t", "autoInc", "0");
            dalTablecsi_po_mst["inv_date"] = new XVar("type", 135, "varname", "inv_date", "name", "inv_date", "autoInc", "0");
            dalTablecsi_po_mst["inv_num"] = new XVar("type", 202, "varname", "inv_num", "name", "inv_num", "autoInc", "0");
            dalTablecsi_po_mst["InWorkflow"] = new XVar("type", 20, "varname", "InWorkflow", "name", "InWorkflow", "autoInc", "0");
            dalTablecsi_po_mst["loc_frt_alloc_meth"] = new XVar("type", 202, "varname", "loc_frt_alloc_meth", "name", "loc_frt_alloc_meth", "autoInc", "0");
            dalTablecsi_po_mst["loc_frt_alloc_percent"] = new XVar("type", 14, "varname", "loc_frt_alloc_percent", "name", "loc_frt_alloc_percent", "autoInc", "0");
            dalTablecsi_po_mst["loc_frt_alloc_type"] = new XVar("type", 202, "varname", "loc_frt_alloc_type", "name", "loc_frt_alloc_type", "autoInc", "0");
            dalTablecsi_po_mst["loc_frt_vend_num"] = new XVar("type", 202, "varname", "loc_frt_vend_num", "name", "loc_frt_vend_num", "autoInc", "0");
            dalTablecsi_po_mst["local_freight_amt"] = new XVar("type", 14, "varname", "local_freight_amt", "name", "local_freight_amt", "autoInc", "0");
            dalTablecsi_po_mst["local_freight_amt_t"] = new XVar("type", 14, "varname", "local_freight_amt_t", "name", "local_freight_amt_t", "autoInc", "0");
            dalTablecsi_po_mst["logifld"] = new XVar("type", 20, "varname", "logifld", "name", "logifld", "autoInc", "0");
            dalTablecsi_po_mst["m_charges_t"] = new XVar("type", 14, "varname", "fldm_charges_t", "name", "m_charges_t", "autoInc", "0");
            dalTablecsi_po_mst["misc_charges"] = new XVar("type", 14, "varname", "misc_charges", "name", "misc_charges", "autoInc", "0");
            dalTablecsi_po_mst["msc_tax_code1"] = new XVar("type", 202, "varname", "msc_tax_code1", "name", "msc_tax_code1", "autoInc", "0");
            dalTablecsi_po_mst["msc_tax_code2"] = new XVar("type", 202, "varname", "msc_tax_code2", "name", "msc_tax_code2", "autoInc", "0");
            dalTablecsi_po_mst["NoteExistsFlag"] = new XVar("type", 20, "varname", "NoteExistsFlag", "name", "NoteExistsFlag", "autoInc", "0");
            dalTablecsi_po_mst["order_date"] = new XVar("type", 135, "varname", "order_date", "name", "order_date", "autoInc", "0");
            dalTablecsi_po_mst["po_cost"] = new XVar("type", 14, "varname", "po_cost", "name", "po_cost", "autoInc", "0");
            dalTablecsi_po_mst["prepaid_amt"] = new XVar("type", 14, "varname", "prepaid_amt", "name", "prepaid_amt", "autoInc", "0");
            dalTablecsi_po_mst["prepaid_t"] = new XVar("type", 14, "varname", "prepaid_t", "name", "prepaid_t", "autoInc", "0");
            dalTablecsi_po_mst["print_price"] = new XVar("type", 20, "varname", "print_price", "name", "print_price", "autoInc", "0");
            dalTablecsi_po_mst["process_ind"] = new XVar("type", 202, "varname", "process_ind", "name", "process_ind", "autoInc", "0");
            dalTablecsi_po_mst["received"] = new XVar("type", 20, "varname", "received", "name", "received", "autoInc", "0");
            dalTablecsi_po_mst["RecordDate"] = new XVar("type", 135, "varname", "RecordDate", "name", "RecordDate", "autoInc", "0");
            dalTablecsi_po_mst["RowPointer"] = new XVar("type", 202, "varname", "RowPointer", "name", "RowPointer", "autoInc", "0");
            dalTablecsi_po_mst["sales_tax"] = new XVar("type", 14, "varname", "sales_tax", "name", "sales_tax", "autoInc", "0");
            dalTablecsi_po_mst["sales_tax_2"] = new XVar("type", 14, "varname", "sales_tax_2", "name", "sales_tax_2", "autoInc", "0");
            dalTablecsi_po_mst["sales_tax_t"] = new XVar("type", 14, "varname", "sales_tax_t", "name", "sales_tax_t", "autoInc", "0");
            dalTablecsi_po_mst["sales_tax_t2"] = new XVar("type", 14, "varname", "sales_tax_t2", "name", "sales_tax_t2", "autoInc", "0");
            dalTablecsi_po_mst["ship_addr"] = new XVar("type", 202, "varname", "ship_addr", "name", "ship_addr", "autoInc", "0");
            dalTablecsi_po_mst["ship_code"] = new XVar("type", 202, "varname", "ship_code", "name", "ship_code", "autoInc", "0");
            dalTablecsi_po_mst["source_site_co_num"] = new XVar("type", 202, "varname", "source_site_co_num", "name", "source_site_co_num", "autoInc", "0");
            dalTablecsi_po_mst["stat"] = new XVar("type", 202, "varname", "stat", "name", "stat", "autoInc", "0");
            dalTablecsi_po_mst["supply_web_po_stat"] = new XVar("type", 202, "varname", "supply_web_po_stat", "name", "supply_web_po_stat", "autoInc", "0");
            dalTablecsi_po_mst["synchronized_to_bus"] = new XVar("type", 20, "varname", "synchronized_to_bus", "name", "synchronized_to_bus", "autoInc", "0");
            dalTablecsi_po_mst["tax_code1"] = new XVar("type", 202, "varname", "tax_code1", "name", "tax_code1", "autoInc", "0");
            dalTablecsi_po_mst["tax_code2"] = new XVar("type", 202, "varname", "tax_code2", "name", "tax_code2", "autoInc", "0");
            dalTablecsi_po_mst["terms_code"] = new XVar("type", 202, "varname", "terms_code", "name", "terms_code", "autoInc", "0");
            dalTablecsi_po_mst["trans_nat"] = new XVar("type", 202, "varname", "trans_nat", "name", "trans_nat", "autoInc", "0");
            dalTablecsi_po_mst["trans_nat_2"] = new XVar("type", 202, "varname", "trans_nat_2", "name", "trans_nat_2", "autoInc", "0");
            dalTablecsi_po_mst["type"] = new XVar("type", 202, "varname", "type", "name", "type", "autoInc", "0");
            dalTablecsi_po_mst["UpdatedBy"] = new XVar("type", 202, "varname", "UpdatedBy", "name", "UpdatedBy", "autoInc", "0");
            dalTablecsi_po_mst["vend_lcr_num"] = new XVar("type", 202, "varname", "vend_lcr_num", "name", "vend_lcr_num", "autoInc", "0");
            dalTablecsi_po_mst["vend_num"] = new XVar("type", 202, "varname", "vend_num", "name", "vend_num", "autoInc", "0");
            dalTablecsi_po_mst["vend_order"] = new XVar("type", 202, "varname", "vend_order", "name", "vend_order", "autoInc", "0");
            dalTablecsi_po_mst["whse"] = new XVar("type", 202, "varname", "whse", "name", "whse", "autoInc", "0");
            dalTablecsi_po_mst["DLDeleteIndicator"] = new XVar("type", 20, "varname", "DLDeleteIndicator", "name", "DLDeleteIndicator", "autoInc", "0");
            dalTablecsi_po_mst["tp_id"] = new XVar("type", 202, "varname", "tp_id", "name", "tp_id", "autoInc", "0");
            dalTablecsi_po_mst["tp_posted"] = new XVar("type", 16, "varname", "tp_posted", "name", "tp_posted", "autoInc", "0");
            dalTablecsi_po_mst["sc_id"] = new XVar("type", 202, "varname", "sc_id", "name", "sc_id", "autoInc", "0");
            dalTablecsi_po_mst["sc_posted"] = new XVar("type", 16, "varname", "sc_posted", "name", "sc_posted", "autoInc", "0");
            dalTablecsi_po_mst["sf_id"] = new XVar("type", 202, "varname", "sf_id", "name", "sf_id", "autoInc", "0");
            dalTablecsi_po_mst["sf_posted"] = new XVar("type", 16, "varname", "sf_posted", "name", "sf_posted", "autoInc", "0");
            dalTablecsi_po_mst["mg_id"] = new XVar("type", 202, "varname", "mg_id", "name", "mg_id", "autoInc", "0");
            dalTablecsi_po_mst["mg_posted"] = new XVar("type", 16, "varname", "mg_posted", "name", "mg_posted", "autoInc", "0");
            dalTablecsi_po_mst["uf_uet1"] = new XVar("type", 202, "varname", "uf_uet1", "name", "uf_uet1", "autoInc", "0");
            dalTablecsi_po_mst["uf_uet2"] = new XVar("type", 202, "varname", "uf_uet2", "name", "uf_uet2", "autoInc", "0");
            dalTablecsi_po_mst["uf_uet3"] = new XVar("type", 202, "varname", "uf_uet3", "name", "uf_uet3", "autoInc", "0");
            dalTablecsi_po_mst["uf_uet4"] = new XVar("type", 202, "varname", "uf_uet4", "name", "uf_uet4", "autoInc", "0");
            dalTablecsi_po_mst["uf_uet5"] = new XVar("type", 202, "varname", "uf_uet5", "name", "uf_uet5", "autoInc", "0");
            dalTablecsi_po_mst["uf_uet6"] = new XVar("type", 202, "varname", "uf_uet6", "name", "uf_uet6", "autoInc", "0");
            dalTablecsi_po_mst["uf_uet7"] = new XVar("type", 202, "varname", "uf_uet7", "name", "uf_uet7", "autoInc", "0");
            dalTablecsi_po_mst["uf_uet8"] = new XVar("type", 202, "varname", "uf_uet8", "name", "uf_uet8", "autoInc", "0");
            dalTablecsi_po_mst["uf_uet9"] = new XVar("type", 202, "varname", "uf_uet9", "name", "uf_uet9", "autoInc", "0");
            dalTablecsi_po_mst["uf_uet10"] = new XVar("type", 202, "varname", "uf_uet10", "name", "uf_uet10", "autoInc", "0");
            dalTablecsi_po_mst["tp_posted_date"] = new XVar("type", 135, "varname", "tp_posted_date", "name", "tp_posted_date", "autoInc", "0");
            dalTablecsi_po_mst["tp_rev"] = new XVar("type", 3, "varname", "tp_rev", "name", "tp_rev", "autoInc", "0");
            dalTablecsi_po_mst["tp_rcvd"] = new XVar("type", 16, "varname", "tp_rcvd", "name", "tp_rcvd", "autoInc", "0");
            dalTablecsi_po_mst["tp_closed"] = new XVar("type", 16, "varname", "tp_closed", "name", "tp_closed", "autoInc", "0");
            dalTablecsi_po_mst["tp_re_post"] = new XVar("type", 16, "varname", "tp_re_post", "name", "tp_re_post", "autoInc", "0");
            GlobalVars.dal_info["Hubkoratec218206166241compute1_dbo_csi_po_mst"] = dalTablecsi_po_mst;
        }

        public  dalTable_Hubkoratec218206166241compute1_dbo_csi_po_mst()
        {
            			this.m_TableName = "dbo.csi_po_mst";
            this.m_infoKey = "Hubkoratec218206166241compute1_dbo_csi_po_mst";
        }
    }
}