
		// admin_users
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_admin_users_import
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "user_name",
1, "password",
2, "user_group",
3, "active",
4, "email",
5, "email_notification",
6, "description",
7, "reset_date",
8, "two_factor",
9, "totp_secret",
10, "clientid" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "user_name", new XVar( 0, "import_field" ),
"password", new XVar( 0, "import_field1" ),
"user_group", new XVar( 0, "import_field2" ),
"active", new XVar( 0, "import_field3" ),
"email", new XVar( 0, "import_field4" ),
"email_notification", new XVar( 0, "import_field5" ),
"description", new XVar( 0, "import_field6" ),
"reset_date", new XVar( 0, "import_field7" ),
"two_factor", new XVar( 0, "import_field8" ),
"totp_secret", new XVar( 0, "import_field9" ),
"clientid", new XVar( 0, "import_field10" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "import_header" ),
"grid", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "import_header", "top",
"import_field", "grid",
"import_field1", "grid",
"import_field2", "grid",
"import_field3", "grid",
"import_field4", "grid",
"import_field5", "grid",
"import_field6", "grid",
"import_field7", "grid",
"import_field8", "grid",
"import_field9", "grid",
"import_field10", "grid" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "import_header", new XVar( 0, "import_header" ),
"import_field", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "import",
"type", "import",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "import-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "import-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "import_header", new XVar( "type", "import_header" ),
"import_field", new XVar( "field", "user_name",
"type", "import_field" ),
"import_field1", new XVar( "field", "password",
"type", "import_field" ),
"import_field2", new XVar( "field", "user_group",
"type", "import_field" ),
"import_field3", new XVar( "field", "active",
"type", "import_field" ),
"import_field4", new XVar( "field", "email",
"type", "import_field" ),
"import_field5", new XVar( "field", "email_notification",
"type", "import_field" ),
"import_field6", new XVar( "field", "description",
"type", "import_field" ),
"import_field7", new XVar( "field", "reset_date",
"type", "import_field" ),
"import_field8", new XVar( "field", "two_factor",
"type", "import_field" ),
"import_field9", new XVar( "field", "totp_secret",
"type", "import_field" ),
"import_field10", new XVar( "field", "clientid",
"type", "import_field" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}