
		// dbo.clients
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_clients_view
			{
				static public XVar options()
				{
					return new XVar( "pdf", new XVar( "pdfView", false ),
"details", new XVar( "dbo.client_authorizations", new XVar( "displayPreview", 1,
"previewPageId", "list" ),
"dbo.client_apps", new XVar( "displayPreview", 1,
"previewPageId", "list" ),
"dbo.client_connections", new XVar( "displayPreview", 1,
"previewPageId", "list" ),
"dbo.users", new XVar( "displayPreview", 1,
"previewPageId", "list" ),
"dbo.recordcounts", new XVar( "displayPreview", 1,
"previewPageId", "list" ),
"dbo.csi_site_mst", new XVar( "displayPreview", 1,
"previewPageId", "list" ),
"dbo.hk_invoice_mst", new XVar( "displayPreview", 2,
"previewPageId", "" ),
"dbo.incidents", new XVar( "displayPreview", 2,
"previewPageId", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "name",
1, "shortcode",
2, "date_created",
3, "active",
4, "onprem",
5, "sf_auto_create_accounts",
6, "sf_bill_to_only_sync",
7, "sl_master_site",
8, "num_days_incoming",
9, "num_days_outgoing",
10, "uet_auto_map",
11, "tp_inv_acct",
12, "tp_vend_stat",
13, "provision_date",
14, "termination_date",
15, "account_manager",
16, "service_manager",
17, "project_manager",
18, "primary_contact",
19, "primary_email",
20, "primary_phone",
21, "id",
22, "invoice_cycle",
23, "effective_invoice",
24, "next_invoice",
25, "last_invoice",
26, "termination_invoice",
27, "terms_days",
28, "sc_expense_process",
29, "email_flash",
30, "tp_distribution_date",
31, "tp_post_unreceived_po",
32, "tp_posttype",
33, "NotConsiderItem",
34, "tp_multisite",
35, "tp_consider_inv_acct",
36, "Shipment_Type",
37, "tp_consider_external_email",
38, "tp_consider_decimals",
39, "ship_flag" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "name", new XVar( 0, "integrated_edit_field1" ),
"shortcode", new XVar( 0, "integrated_edit_field2" ),
"date_created", new XVar( 0, "integrated_edit_field3" ),
"active", new XVar( 0, "integrated_edit_field4" ),
"onprem", new XVar( 0, "integrated_edit_field5" ),
"sf_auto_create_accounts", new XVar( 0, "integrated_edit_field" ),
"sf_bill_to_only_sync", new XVar( 0, "integrated_edit_field6" ),
"sl_master_site", new XVar( 0, "integrated_edit_field7" ),
"num_days_incoming", new XVar( 0, "integrated_edit_field8" ),
"num_days_outgoing", new XVar( 0, "integrated_edit_field9" ),
"uet_auto_map", new XVar( 0, "integrated_edit_field10" ),
"tp_inv_acct", new XVar( 0, "integrated_edit_field11" ),
"tp_vend_stat", new XVar( 0, "integrated_edit_field12" ),
"provision_date", new XVar( 0, "integrated_edit_field13" ),
"termination_date", new XVar( 0, "integrated_edit_field14" ),
"account_manager", new XVar( 0, "integrated_edit_field15" ),
"service_manager", new XVar( 0, "integrated_edit_field16" ),
"project_manager", new XVar( 0, "integrated_edit_field17" ),
"primary_contact", new XVar( 0, "integrated_edit_field18" ),
"primary_email", new XVar( 0, "integrated_edit_field19" ),
"primary_phone", new XVar( 0, "integrated_edit_field20" ),
"id", new XVar( 0, "integrated_edit_field21" ),
"invoice_cycle", new XVar( 0, "integrated_edit_field22" ),
"effective_invoice", new XVar( 0, "integrated_edit_field23" ),
"next_invoice", new XVar( 0, "integrated_edit_field24" ),
"last_invoice", new XVar( 0, "integrated_edit_field25" ),
"termination_invoice", new XVar( 0, "integrated_edit_field26" ),
"terms_days", new XVar( 0, "integrated_edit_field27" ),
"sc_expense_process", new XVar( 0, "integrated_edit_field28" ),
"email_flash", new XVar( 0, "integrated_edit_field29" ),
"tp_distribution_date", new XVar( 0, "integrated_edit_field30" ),
"tp_post_unreceived_po", new XVar( 0, "integrated_edit_field31" ),
"tp_posttype", new XVar( 0, "integrated_edit_field32" ),
"NotConsiderItem", new XVar( 0, "integrated_edit_field33" ),
"tp_multisite", new XVar( 0, "integrated_edit_field34" ),
"tp_consider_inv_acct", new XVar( 0, "integrated_edit_field35" ),
"Shipment_Type", new XVar( 0, "integrated_edit_field36" ),
"tp_consider_external_email", new XVar( 0, "integrated_edit_field37" ),
"tp_consider_decimals", new XVar( 0, "integrated_edit_field38" ),
"ship_flag", new XVar( 0, "integrated_edit_field39" ) ) ),
"pageLinks", new XVar( "edit", true,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "view_back_list",
1, "view_close",
2, "hamburger" ),
"top", new XVar( 0, "view_header" ),
"grid", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field1",
2, "integrated_edit_field3",
3, "integrated_edit_field4",
4, "integrated_edit_field5",
5, "tabs",
6, "details_preview1",
7, "details_preview",
8, "details_preview2",
9, "details_preview3",
10, "details_preview4",
11, "details_preview5",
12, "integrated_edit_field27",
13, "integrated_edit_field28",
14, "integrated_edit_field29",
15, "integrated_edit_field30",
16, "integrated_edit_field31",
17, "integrated_edit_field32",
18, "integrated_edit_field33",
19, "integrated_edit_field34",
20, "integrated_edit_field35",
21, "integrated_edit_field36",
22, "integrated_edit_field37",
23, "integrated_edit_field38",
24, "integrated_edit_field39" ),
"section", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field6",
2, "integrated_edit_field" ),
"section1", new XVar( 0, "integrated_edit_field11",
1, "integrated_edit_field12" ),
"section2", XVar.Array(),
"section3", XVar.Array(),
"section4", new XVar( 0, "integrated_edit_field8",
1, "integrated_edit_field9",
2, "integrated_edit_field10" ),
"section5", new XVar( 0, "integrated_edit_field22",
1, "integrated_edit_field23",
2, "integrated_edit_field26",
3, "integrated_edit_field25",
4, "integrated_edit_field24" ),
"section6", new XVar( 0, "custom_button",
1, "integrated_edit_field21",
2, "integrated_edit_field13",
3, "integrated_edit_field14",
4, "integrated_edit_field15",
5, "integrated_edit_field16",
6, "integrated_edit_field17",
7, "integrated_edit_field18",
8, "integrated_edit_field19",
9, "integrated_edit_field20" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array() ),
"itemForms", new XVar( "view_back_list", "below-grid",
"view_close", "below-grid",
"hamburger", "below-grid",
"view_header", "top",
"integrated_edit_field2", "grid",
"integrated_edit_field1", "grid",
"integrated_edit_field3", "grid",
"integrated_edit_field4", "grid",
"integrated_edit_field5", "grid",
"tabs", "grid",
"details_preview1", "grid",
"details_preview", "grid",
"details_preview2", "grid",
"details_preview3", "grid",
"details_preview4", "grid",
"details_preview5", "grid",
"integrated_edit_field27", "grid",
"integrated_edit_field28", "grid",
"integrated_edit_field29", "grid",
"integrated_edit_field30", "grid",
"integrated_edit_field31", "grid",
"integrated_edit_field32", "grid",
"integrated_edit_field33", "grid",
"integrated_edit_field34", "grid",
"integrated_edit_field35", "grid",
"integrated_edit_field36", "grid",
"integrated_edit_field37", "grid",
"integrated_edit_field38", "grid",
"integrated_edit_field39", "grid",
"integrated_edit_field7", "section",
"integrated_edit_field6", "section",
"integrated_edit_field", "section",
"integrated_edit_field11", "section1",
"integrated_edit_field12", "section1",
"integrated_edit_field8", "section4",
"integrated_edit_field9", "section4",
"integrated_edit_field10", "section4",
"integrated_edit_field22", "section5",
"integrated_edit_field23", "section5",
"integrated_edit_field26", "section5",
"integrated_edit_field25", "section5",
"integrated_edit_field24", "section5",
"custom_button", "section6",
"integrated_edit_field21", "section6",
"integrated_edit_field13", "section6",
"integrated_edit_field14", "section6",
"integrated_edit_field15", "section6",
"integrated_edit_field16", "section6",
"integrated_edit_field17", "section6",
"integrated_edit_field18", "section6",
"integrated_edit_field19", "section6",
"integrated_edit_field20", "section6" ),
"itemLocations", new XVar( "integrated_edit_field2", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field1", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field3", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field4", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field5", new XVar( "location", "grid",
"cellId", "c3" ),
"tabs", new XVar( "location", "grid",
"cellId", "c3" ),
"details_preview1", new XVar( "location", "grid",
"cellId", "c3" ),
"details_preview", new XVar( "location", "grid",
"cellId", "c3" ),
"details_preview2", new XVar( "location", "grid",
"cellId", "c3" ),
"details_preview3", new XVar( "location", "grid",
"cellId", "c3" ),
"details_preview4", new XVar( "location", "grid",
"cellId", "c3" ),
"details_preview5", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field27", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field28", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field29", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field30", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field31", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field32", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field33", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field34", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field35", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field36", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field37", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field38", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field39", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field7", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field6", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field11", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field12", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field8", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field9", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field10", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field22", new XVar( "location", "section5",
"cellId", "c1" ),
"integrated_edit_field23", new XVar( "location", "section5",
"cellId", "c1" ),
"integrated_edit_field26", new XVar( "location", "section5",
"cellId", "c1" ),
"integrated_edit_field25", new XVar( "location", "section5",
"cellId", "c1" ),
"integrated_edit_field24", new XVar( "location", "section5",
"cellId", "c1" ),
"custom_button", new XVar( "location", "section6",
"cellId", "c1" ),
"integrated_edit_field21", new XVar( "location", "section6",
"cellId", "c1" ),
"integrated_edit_field13", new XVar( "location", "section6",
"cellId", "c1" ),
"integrated_edit_field14", new XVar( "location", "section6",
"cellId", "c1" ),
"integrated_edit_field15", new XVar( "location", "section6",
"cellId", "c1" ),
"integrated_edit_field16", new XVar( "location", "section6",
"cellId", "c1" ),
"integrated_edit_field17", new XVar( "location", "section6",
"cellId", "c1" ),
"integrated_edit_field18", new XVar( "location", "section6",
"cellId", "c1" ),
"integrated_edit_field19", new XVar( "location", "section6",
"cellId", "c1" ),
"integrated_edit_field20", new XVar( "location", "section6",
"cellId", "c1" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "view_header", new XVar( 0, "view_header" ),
"view_back_list", new XVar( 0, "view_back_list" ),
"view_close", new XVar( 0, "view_close" ),
"hamburger", new XVar( 0, "hamburger" ),
"view_edit", new XVar( 0, "view_edit" ),
"integrated_edit_field", new XVar( 0, "integrated_edit_field1",
1, "integrated_edit_field2",
2, "integrated_edit_field3",
3, "integrated_edit_field4",
4, "integrated_edit_field5",
5, "integrated_edit_field",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39" ),
"details_preview", new XVar( 0, "details_preview",
1, "details_preview1",
2, "details_preview2",
3, "details_preview4",
4, "details_preview5",
5, "details_preview3" ),
"tabs", new XVar( 0, "tabs" ),
"custom_button", new XVar( 0, "custom_button" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field1",
2, "integrated_edit_field3",
3, "integrated_edit_field4",
4, "integrated_edit_field5",
5, "tabs",
6, "details_preview1",
7, "details_preview",
8, "details_preview2",
9, "details_preview3",
10, "details_preview4",
11, "details_preview5",
12, "integrated_edit_field27",
13, "integrated_edit_field28",
14, "integrated_edit_field29",
15, "integrated_edit_field30",
16, "integrated_edit_field31",
17, "integrated_edit_field32",
18, "integrated_edit_field33",
19, "integrated_edit_field34",
20, "integrated_edit_field35",
21, "integrated_edit_field36",
22, "integrated_edit_field37",
23, "integrated_edit_field38",
24, "integrated_edit_field39" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ),
"section", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field6",
2, "integrated_edit_field" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ),
"section1", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field11",
1, "integrated_edit_field12" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ),
"section2", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ),
"section3", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ),
"section4", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field8",
1, "integrated_edit_field9",
2, "integrated_edit_field10" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ),
"section5", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field22",
1, "integrated_edit_field23",
2, "integrated_edit_field26",
3, "integrated_edit_field25",
4, "integrated_edit_field24" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ),
"section6", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", true,
"fixedAtClient", true ) ),
"width", 1,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", true,
"customButtons", new XVar( 0, "New_Button2" ),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "view",
"breadcrumb", false,
"nextPrev", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", new XVar( 0, "New_Button2" ) ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "view",
"type", "view",
"layoutId", "nomenu",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "view-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1",
"colspan", 2 ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "view-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_back_list",
1, "view_close" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "hamburger" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "view-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ) ),
"section", "" ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field1",
2, "integrated_edit_field3",
3, "integrated_edit_field4",
4, "integrated_edit_field5",
5, "tabs",
6, "details_preview1",
7, "details_preview",
8, "details_preview2",
9, "details_preview3",
10, "details_preview4",
11, "details_preview5",
12, "integrated_edit_field27",
13, "integrated_edit_field28",
14, "integrated_edit_field29",
15, "integrated_edit_field30",
16, "integrated_edit_field31",
17, "integrated_edit_field32",
18, "integrated_edit_field33",
19, "integrated_edit_field34",
20, "integrated_edit_field35",
21, "integrated_edit_field36",
22, "integrated_edit_field37",
23, "integrated_edit_field38",
24, "integrated_edit_field39" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field6",
2, "integrated_edit_field" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section1", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field11",
1, "integrated_edit_field12" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section2", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section3", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section4", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field8",
1, "integrated_edit_field9",
2, "integrated_edit_field10" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section5", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field22",
1, "integrated_edit_field23",
2, "integrated_edit_field26",
3, "integrated_edit_field25",
4, "integrated_edit_field24" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section6", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "custom_button",
1, "integrated_edit_field21",
2, "integrated_edit_field13",
3, "integrated_edit_field14",
4, "integrated_edit_field15",
5, "integrated_edit_field16",
6, "integrated_edit_field17",
7, "integrated_edit_field18",
8, "integrated_edit_field19",
9, "integrated_edit_field20" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ) ),
"items", new XVar( "view_header", new XVar( "type", "view_header" ),
"view_back_list", new XVar( "type", "view_back_list" ),
"view_close", new XVar( "type", "view_close" ),
"hamburger", new XVar( "type", "hamburger",
"items", new XVar( 0, "view_edit" ) ),
"view_edit", new XVar( "type", "view_edit" ),
"integrated_edit_field1", new XVar( "field", "name",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field2", new XVar( "field", "shortcode",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field3", new XVar( "field", "date_created",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field4", new XVar( "field", "active",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field5", new XVar( "field", "onprem",
"type", "integrated_edit_field",
"orientation", 0 ),
"details_preview", new XVar( "type", "details_preview",
"table", "dbo.client_authorizations",
"items", XVar.Array(),
"popup", false,
"pageId", "list" ),
"details_preview1", new XVar( "type", "details_preview",
"table", "dbo.client_connections",
"items", XVar.Array(),
"popup", false,
"pageId", "list" ),
"details_preview2", new XVar( "type", "details_preview",
"table", "dbo.users",
"items", XVar.Array(),
"popup", false,
"pageId", "list" ),
"details_preview4", new XVar( "type", "details_preview",
"table", "dbo.csi_site_mst",
"items", XVar.Array(),
"popup", false,
"pageId", "list" ),
"details_preview5", new XVar( "type", "details_preview",
"table", "dbo.recordcounts",
"items", XVar.Array(),
"popup", false,
"pageId", "list" ),
"integrated_edit_field", new XVar( "field", "sf_auto_create_accounts",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field6", new XVar( "field", "sf_bill_to_only_sync",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field7", new XVar( "field", "sl_master_site",
"type", "integrated_edit_field",
"orientation", 0,
"updateOnEdit", false ),
"tabs", new XVar( "type", "tabs",
"titles", new XVar( 0, new XVar( "text", "Contacts",
"type", 0 ),
1, new XVar( "text", "Billings",
"type", 0 ),
2, new XVar( "text", "Salesforce",
"type", 0 ),
3, new XVar( "text", "Tipalti",
"type", 0 ),
4, new XVar( "text", "Magento",
"type", 0 ),
5, new XVar( "text", "Concur",
"type", 0 ),
6, new XVar( "text", "Syteline",
"type", 0 ) ),
"locations", new XVar( 0, "section6",
1, "section5",
2, "section",
3, "section1",
4, "section2",
5, "section3",
6, "section4" ),
"bsStyle", "default",
"panelType", 2 ),
"integrated_edit_field8", new XVar( "field", "num_days_incoming",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field9", new XVar( "field", "num_days_outgoing",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field10", new XVar( "field", "uet_auto_map",
"type", "integrated_edit_field",
"orientation", 0,
"updateOnEdit", false ),
"integrated_edit_field11", new XVar( "field", "tp_inv_acct",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field12", new XVar( "field", "tp_vend_stat",
"type", "integrated_edit_field",
"orientation", 0 ),
"details_preview3", new XVar( "type", "details_preview",
"table", "dbo.client_apps",
"items", XVar.Array(),
"popup", false,
"pageId", "list" ),
"integrated_edit_field13", new XVar( "field", "provision_date",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field14", new XVar( "field", "termination_date",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field15", new XVar( "field", "account_manager",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field16", new XVar( "field", "service_manager",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field17", new XVar( "field", "project_manager",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field18", new XVar( "field", "primary_contact",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field19", new XVar( "field", "primary_email",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field20", new XVar( "field", "primary_phone",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field21", new XVar( "field", "id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field22", new XVar( "field", "invoice_cycle",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field23", new XVar( "field", "effective_invoice",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field24", new XVar( "field", "next_invoice",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field25", new XVar( "field", "last_invoice",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field26", new XVar( "field", "termination_invoice",
"type", "integrated_edit_field",
"orientation", 0 ),
"custom_button", new XVar( "eventId", "New_Button2",
"label", new XVar( "text", "Send Provisional Email",
"type", 0 ),
"type", "custom_button" ),
"integrated_edit_field27", new XVar( "field", "terms_days",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field28", new XVar( "field", "sc_expense_process",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field29", new XVar( "field", "email_flash",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field30", new XVar( "field", "tp_distribution_date",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field31", new XVar( "field", "tp_post_unreceived_po",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field32", new XVar( "field", "tp_posttype",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field33", new XVar( "field", "NotConsiderItem",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field34", new XVar( "field", "tp_multisite",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field35", new XVar( "field", "tp_consider_inv_acct",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field36", new XVar( "field", "Shipment_Type",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field37", new XVar( "field", "tp_consider_external_email",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field38", new XVar( "field", "tp_consider_decimals",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field39", new XVar( "field", "ship_flag",
"type", "integrated_edit_field",
"orientation", 0 ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}