
		// dbo.client_apps
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_client_apps_list
			{
				static public XVar options()
				{
					return new XVar( "list", new XVar( "inlineAdd", true,
"detailsAdd", true,
"inlineEdit", true,
"spreadsheetMode", false,
"addToBottom", false,
"delete", true,
"updateSelected", false,
"addInPopup", null,
"clickSort", true,
"sortDropdown", false,
"showHideFields", false,
"reorderFields", false,
"fieldFilter", false,
"hideNumberOfRecords", false ),
"allDetails", new XVar( "linkType", 0 ),
"details", new XVar( "dbo.client_apps_table", new XVar( "displayPreview", 1,
"previewPageId", "list",
"showCount", true,
"hideEmptyChild", false,
"hideEmptyPreview", false,
"showProceedLink", true,
"printDetails", true ),
"dbo.client_connections", new XVar( "displayPreview", 1,
"previewPageId", "list",
"showCount", true,
"hideEmptyChild", false,
"hideEmptyPreview", false,
"showProceedLink", true,
"printDetails", true ),
"dbo.hk_client_inv_items", new XVar( "displayPreview", 1,
"previewPageId", "list",
"showCount", true,
"hideEmptyChild", false,
"hideEmptyPreview", false,
"showProceedLink", true,
"printDetails", true ) ),
"master", new XVar( "dbo.clients", new XVar( "preview", true ),
"dbo.apps", new XVar( "preview", true ),
"dbo.Clients_provisioning", new XVar( "preview", true ) ),
"listSearch", new XVar( "alwaysOnPanelFields", XVar.Array(),
"searchPanel", true,
"fixedSearchPanel", false,
"simpleSearchOptions", false,
"searchSaving", false ),
"totals", new XVar( "client", new XVar( "totalsType", "" ),
"app", new XVar( "totalsType", "" ),
"active", new XVar( "totalsType", "" ),
"profile_id", new XVar( "totalsType", "" ),
"effective_date", new XVar( "totalsType", "" ),
"termination_date", new XVar( "totalsType", "" ),
"email_flash", new XVar( "totalsType", "" ),
"status", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "client",
1, "app",
2, "active",
3, "profile_id",
4, "email_flash",
5, "status" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", new XVar( 0, "active",
1, "status",
2, "email_flash",
3, "termination_date",
4, "effective_date",
5, "profile_id",
6, "client",
7, "app" ),
"filterFields", new XVar( 0, "client",
1, "app" ),
"inlineAddFields", new XVar( 0, "client",
1, "app",
2, "active",
3, "profile_id",
4, "email_flash",
5, "status" ),
"inlineEditFields", XVar.Array(),
"fieldItems", new XVar( "client", new XVar( 0, "simple_grid_field",
1, "simple_grid_field5" ),
"app", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field7" ),
"active", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field8" ),
"profile_id", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field9" ),
"email_flash", new XVar( 0, "simple_grid_field6",
1, "simple_grid_field10" ),
"status", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field11" ) ),
"hideEmptyFields", XVar.Array(),
"fieldFilterFields", XVar.Array() ),
"pageLinks", new XVar( "edit", true,
"add", false,
"view", true,
"print", true ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "inline_add",
1, "inline_save_all",
2, "inline_cancel_all",
3, "delete",
4, "details_found",
5, "page_size",
6, "print_panel" ),
"below-grid", new XVar( 0, "pagination" ),
"left", new XVar( 0, "logo",
1, "expand_button",
2, "menu",
3, "search_panel",
4, "filter_panel" ),
"supertop", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb",
3, "simple_search",
4, "list_options",
5, "loginform_login",
6, "username_button" ),
"top", new XVar( 0, "master_info" ),
"grid", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field",
2, "simple_grid_field7",
3, "simple_grid_field1",
4, "simple_grid_field8",
5, "simple_grid_field2",
6, "simple_grid_field9",
7, "simple_grid_field3",
8, "simple_grid_field10",
9, "simple_grid_field6",
10, "simple_grid_field11",
11, "simple_grid_field4",
12, "details_preview",
13, "details_preview1",
14, "details_preview2",
15, "grid_checkbox_head",
16, "grid_checkbox",
17, "grid_alldetails_link",
18, "grid_details_link",
19, "grid_details_link1",
20, "grid_details_link2",
21, "grid_edit",
22, "grid_inline_edit",
23, "grid_inline_save",
24, "grid_inline_cancel",
25, "grid_view" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "inlineadd_link",
1, "saveall_link",
2, "cancelall_link",
3, "deleteselected_link",
4, "details_found",
5, "recsPerPage",
6, "print_friendly" ),
"below-grid", new XVar( 0, "pagination" ),
"top", new XVar( 0, "mastertable_block" ) ),
"itemForms", new XVar( "inline_add", "above-grid",
"inline_save_all", "above-grid",
"inline_cancel_all", "above-grid",
"delete", "above-grid",
"details_found", "above-grid",
"page_size", "above-grid",
"print_panel", "above-grid",
"pagination", "below-grid",
"logo", "left",
"expand_button", "left",
"menu", "left",
"search_panel", "left",
"filter_panel", "left",
"expand_menu_button", "supertop",
"collapse_button", "supertop",
"breadcrumb", "supertop",
"simple_search", "supertop",
"list_options", "supertop",
"loginform_login", "supertop",
"username_button", "supertop",
"master_info", "top",
"simple_grid_field5", "grid",
"simple_grid_field", "grid",
"simple_grid_field7", "grid",
"simple_grid_field1", "grid",
"simple_grid_field8", "grid",
"simple_grid_field2", "grid",
"simple_grid_field9", "grid",
"simple_grid_field3", "grid",
"simple_grid_field10", "grid",
"simple_grid_field6", "grid",
"simple_grid_field11", "grid",
"simple_grid_field4", "grid",
"details_preview", "grid",
"details_preview1", "grid",
"details_preview2", "grid",
"grid_checkbox_head", "grid",
"grid_checkbox", "grid",
"grid_alldetails_link", "grid",
"grid_details_link", "grid",
"grid_details_link1", "grid",
"grid_details_link2", "grid",
"grid_edit", "grid",
"grid_inline_edit", "grid",
"grid_inline_save", "grid",
"grid_inline_cancel", "grid",
"grid_view", "grid" ),
"itemLocations", new XVar( "simple_grid_field5", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"details_preview", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview1", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview2", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"grid_checkbox_head", new XVar( "location", "grid",
"cellId", "headcell_checkbox" ),
"grid_checkbox", new XVar( "location", "grid",
"cellId", "cell_checkbox" ),
"grid_alldetails_link", new XVar( "location", "grid",
"cellId", "cell_details" ),
"grid_details_link", new XVar( "location", "grid",
"cellId", "cell_details" ),
"grid_details_link1", new XVar( "location", "grid",
"cellId", "cell_details" ),
"grid_details_link2", new XVar( "location", "grid",
"cellId", "cell_details" ),
"grid_edit", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_inline_edit", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_inline_save", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_inline_cancel", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_view", new XVar( "location", "grid",
"cellId", "cell_icons" ) ),
"itemVisiblity", new XVar( "breadcrumb", 5,
"expand_menu_button", 2,
"print_panel", 5,
"expand_button", 5 ) ),
"itemsByType", new XVar( "page_size", new XVar( 0, "page_size" ),
"details_found", new XVar( 0, "details_found" ),
"breadcrumb", new XVar( 0, "breadcrumb" ),
"logo", new XVar( 0, "logo" ),
"menu", new XVar( 0, "menu" ),
"simple_search", new XVar( 0, "simple_search" ),
"pagination", new XVar( 0, "pagination" ),
"search_panel", new XVar( 0, "search_panel" ),
"list_options", new XVar( 0, "list_options" ),
"show_search_panel", new XVar( 0, "show_search_panel" ),
"hide_search_panel", new XVar( 0, "hide_search_panel" ),
"search_panel_field", new XVar( 0, "search_panel_field",
1, "search_panel_field1",
2, "search_panel_field2",
3, "search_panel_field3",
4, "search_panel_field4",
5, "search_panel_field5",
6, "search_panel_field6",
7, "search_panel_field7" ),
"expand_menu_button", new XVar( 0, "expand_menu_button" ),
"collapse_button", new XVar( 0, "collapse_button" ),
"print_panel", new XVar( 0, "print_panel" ),
"print_scope", new XVar( 0, "print_scope" ),
"print_button", new XVar( 0, "print_button" ),
"print_records", new XVar( 0, "print_records" ),
"export", new XVar( 0, "export" ),
"-", new XVar( 0, "-",
1, "-1",
2, "-2",
3, "-3" ),
"import", new XVar( 0, "import" ),
"advsearch_link", new XVar( 0, "advsearch_link" ),
"master_info", new XVar( 0, "master_info" ),
"print_details", new XVar( 0, "print_details" ),
"username_button", new XVar( 0, "username_button" ),
"loginform_login", new XVar( 0, "loginform_login" ),
"userinfo_link", new XVar( 0, "userinfo_link" ),
"logout_link", new XVar( 0, "logout_link" ),
"filter_panel", new XVar( 0, "filter_panel" ),
"filter_panel_field", new XVar( 0, "filter_panel_field",
1, "filter_panel_field1" ),
"inline_add", new XVar( 0, "inline_add" ),
"inline_save_all", new XVar( 0, "inline_save_all" ),
"inline_cancel_all", new XVar( 0, "inline_cancel_all" ),
"edit_selected", new XVar( 0, "edit_selected" ),
"delete", new XVar( 0, "delete" ),
"delete_selected", new XVar( 0, "delete_selected" ),
"adminarea_link", new XVar( 0, "adminarea_link" ),
"changepassword_link", new XVar( 0, "changepassword_link" ),
"grid_field", new XVar( 0, "simple_grid_field",
1, "simple_grid_field1",
2, "simple_grid_field2",
3, "simple_grid_field3",
4, "simple_grid_field6",
5, "simple_grid_field4" ),
"grid_field_label", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field7",
2, "simple_grid_field8",
3, "simple_grid_field9",
4, "simple_grid_field10",
5, "simple_grid_field11" ),
"details_preview", new XVar( 0, "details_preview",
1, "details_preview1",
2, "details_preview2" ),
"grid_checkbox", new XVar( 0, "grid_checkbox" ),
"grid_checkbox_head", new XVar( 0, "grid_checkbox_head" ),
"grid_alldetails_link", new XVar( 0, "grid_alldetails_link" ),
"grid_inline_cancel", new XVar( 0, "grid_inline_cancel" ),
"grid_inline_save", new XVar( 0, "grid_inline_save" ),
"grid_inline_edit", new XVar( 0, "grid_inline_edit" ),
"grid_edit", new XVar( 0, "grid_edit" ),
"grid_view", new XVar( 0, "grid_view" ),
"grid_details_link", new XVar( 0, "grid_details_link",
1, "grid_details_link1",
2, "grid_details_link2" ),
"expand_button", new XVar( 0, "expand_button" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox_head" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_details", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "client_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "app_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "active_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "profile_id_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "email_flash_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "status_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "edit_column",
1, "inlineedit_column",
2, "inline_save",
3, "inline_cancel",
4, "view_column" ),
"items", new XVar( 0, "grid_edit",
1, "grid_inline_edit",
2, "grid_inline_save",
3, "grid_inline_cancel",
4, "grid_view" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_details", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "grid_alldetails_link",
1, "grid_details_link",
2, "grid_details_link1",
3, "grid_details_link2" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "client_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "app_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "active_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "profile_id_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "email_flash_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "status_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_dpreview", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5,
6, 6,
7, 7,
8, 8 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "details_preview",
1, "details_preview1",
2, "details_preview2" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"footcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_details", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 9,
"height", 4 ) ) ),
"loginForm", new XVar( "loginForm", 0 ),
"page", new XVar( "verticalBar", true,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar( "details_found", new XVar( "tag", "DISPLAYING",
"type", 2 ) ) ),
"gridType", 0,
"recsPerRow", 1,
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", new XVar( 0, new XVar( "id", "main",
"horizontal", false ) ),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "list",
"breadcrumb", true ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"dataGrid", new XVar( "groupFields", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "list",
"type", "list",
"layoutId", "leftbar",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "list-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "inline_add",
1, "inline_save_all",
2, "inline_cancel_all",
3, "delete" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "details_found",
1, "page_size",
2, "print_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "list-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "pagination" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"left", new XVar( "modelId", "leftbar-menu",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c0" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c0", new XVar( "model", "c0",
"items", new XVar( 0, "logo",
1, "expand_button" ) ),
"c1", new XVar( "model", "c1",
"items", new XVar( 0, "menu",
1, "search_panel",
2, "filter_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"supertop", new XVar( "modelId", "leftbar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "simple_search",
1, "list_options",
2, "loginform_login",
3, "username_button" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "list-sidebar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c2", new XVar( "model", "c2",
"items", new XVar( 0, "master_info" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_icons" ),
1, new XVar( "cell", "headcell_checkbox" ),
2, new XVar( "cell", "headcell_details" ),
3, new XVar( "cell", "headcell_field" ),
4, new XVar( "cell", "headcell_field1" ),
5, new XVar( "cell", "headcell_field2" ),
6, new XVar( "cell", "headcell_field3" ),
7, new XVar( "cell", "headcell_field4" ),
8, new XVar( "cell", "headcell_field5" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_icons" ),
1, new XVar( "cell", "cell_checkbox" ),
2, new XVar( "cell", "cell_details" ),
3, new XVar( "cell", "cell_field" ),
4, new XVar( "cell", "cell_field1" ),
5, new XVar( "cell", "cell_field2" ),
6, new XVar( "cell", "cell_field3" ),
7, new XVar( "cell", "cell_field4" ),
8, new XVar( "cell", "cell_field5" ) ) ),
2, new XVar( "cells", new XVar( 0, new XVar( "cell", "cell_dpreview",
"colspan", 9 ) ),
"section", "body" ),
3, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_icons" ),
1, new XVar( "cell", "footcell_checkbox" ),
2, new XVar( "cell", "footcell_details" ),
3, new XVar( "cell", "footcell_field" ),
4, new XVar( "cell", "footcell_field1" ),
5, new XVar( "cell", "footcell_field2" ),
6, new XVar( "cell", "footcell_field3" ),
7, new XVar( "cell", "footcell_field4" ),
8, new XVar( "cell", "footcell_field5" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "client",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "client",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "app",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "app",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "active",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "active",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "profile_id",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "profile_id",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "email_flash",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "email_flash",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "status",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "status",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"cell_dpreview", new XVar( "model", "cell_dpreview",
"items", new XVar( 0, "details_preview",
1, "details_preview1",
2, "details_preview2" ) ),
"headcell_checkbox", new XVar( "model", "headcell_checkbox",
"items", new XVar( 0, "grid_checkbox_head" ) ),
"cell_checkbox", new XVar( "model", "cell_checkbox",
"items", new XVar( 0, "grid_checkbox" ) ),
"footcell_checkbox", new XVar( "model", "footcell_checkbox",
"items", XVar.Array() ),
"headcell_details", new XVar( "model", "headcell_details",
"items", XVar.Array() ),
"cell_details", new XVar( "model", "cell_details",
"items", new XVar( 0, "grid_alldetails_link",
1, "grid_details_link",
2, "grid_details_link1",
3, "grid_details_link2" ) ),
"footcell_details", new XVar( "model", "footcell_details",
"items", XVar.Array() ),
"headcell_icons", new XVar( "model", "headcell_icons",
"items", XVar.Array() ),
"cell_icons", new XVar( "model", "cell_icons",
"items", new XVar( 0, "grid_edit",
1, "grid_inline_edit",
2, "grid_inline_save",
3, "grid_inline_cancel",
4, "grid_view" ) ),
"footcell_icons", new XVar( "model", "footcell_icons",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "page_size", new XVar( "type", "page_size" ),
"details_found", new XVar( "type", "details_found" ),
"breadcrumb", new XVar( "type", "breadcrumb" ),
"logo", new XVar( "type", "logo" ),
"menu", new XVar( "type", "menu" ),
"simple_search", new XVar( "type", "simple_search" ),
"pagination", new XVar( "type", "pagination" ),
"search_panel", new XVar( "type", "search_panel",
"items", new XVar( 0, "search_panel_field",
1, "search_panel_field7",
2, "search_panel_field6",
3, "search_panel_field5",
4, "search_panel_field4",
5, "search_panel_field3",
6, "search_panel_field2",
7, "search_panel_field1" ),
"_flexiblePanel", true ),
"list_options", new XVar( "type", "list_options",
"items", new XVar( 0, "edit_selected",
1, "delete_selected",
2, "-3",
3, "advsearch_link",
4, "show_search_panel",
5, "hide_search_panel",
6, "-2",
7, "export",
8, "-1",
9, "import" ) ),
"show_search_panel", new XVar( "type", "show_search_panel" ),
"hide_search_panel", new XVar( "type", "hide_search_panel" ),
"search_panel_field", new XVar( "field", "active",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field1", new XVar( "field", "app",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field2", new XVar( "field", "client",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field3", new XVar( "field", "profile_id",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"expand_menu_button", new XVar( "type", "expand_menu_button" ),
"collapse_button", new XVar( "type", "collapse_button" ),
"print_panel", new XVar( "type", "print_panel",
"items", new XVar( 0, "print_scope",
1, "print_details",
2, "print_records",
3, "print_button" ) ),
"print_scope", new XVar( "type", "print_scope" ),
"print_button", new XVar( "type", "print_button" ),
"print_records", new XVar( "type", "print_records" ),
"export", new XVar( "type", "export" ),
"-", new XVar( "type", "-" ),
"import", new XVar( "type", "import" ),
"-1", new XVar( "type", "-" ),
"advsearch_link", new XVar( "type", "advsearch_link" ),
"-2", new XVar( "type", "-" ),
"master_info", new XVar( "type", "master_info",
"tables", new XVar( "dbo.clients", "true",
"dbo.apps", "true",
"dbo.Clients_provisioning", "true" ) ),
"print_details", new XVar( "type", "print_details",
"tables", new XVar( "dbo.client_apps_table", true,
"dbo.client_connections", true,
"dbo.hk_client_inv_items", true ) ),
"username_button", new XVar( "type", "username_button",
"items", new XVar( 0, "userinfo_link",
1, "logout_link",
2, "adminarea_link",
3, "changepassword_link" ) ),
"loginform_login", new XVar( "type", "loginform_login",
"popup", false ),
"userinfo_link", new XVar( "type", "userinfo_link" ),
"logout_link", new XVar( "type", "logout_link" ),
"filter_panel", new XVar( "type", "filter_panel",
"items", new XVar( 0, "filter_panel_field",
1, "filter_panel_field1" ) ),
"filter_panel_field", new XVar( "field", "client",
"type", "filter_panel_field" ),
"filter_panel_field1", new XVar( "field", "app",
"type", "filter_panel_field" ),
"inline_add", new XVar( "type", "inline_add" ),
"inline_save_all", new XVar( "type", "inline_save_all" ),
"inline_cancel_all", new XVar( "type", "inline_cancel_all" ),
"edit_selected", new XVar( "type", "edit_selected" ),
"-3", new XVar( "type", "-" ),
"delete", new XVar( "type", "delete" ),
"delete_selected", new XVar( "type", "delete_selected" ),
"adminarea_link", new XVar( "type", "adminarea_link" ),
"changepassword_link", new XVar( "type", "changepassword_link" ),
"search_panel_field4", new XVar( "field", "effective_date",
"type", "search_panel_field",
"required", false ),
"search_panel_field5", new XVar( "field", "termination_date",
"type", "search_panel_field",
"required", false ),
"search_panel_field6", new XVar( "field", "email_flash",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field7", new XVar( "field", "status",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"simple_grid_field", new XVar( "field", "client",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", false ),
"simple_grid_field5", new XVar( "type", "grid_field_label",
"field", "client" ),
"simple_grid_field1", new XVar( "field", "app",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", false ),
"simple_grid_field7", new XVar( "type", "grid_field_label",
"field", "app" ),
"simple_grid_field2", new XVar( "field", "active",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", false ),
"simple_grid_field8", new XVar( "type", "grid_field_label",
"field", "active" ),
"simple_grid_field3", new XVar( "field", "profile_id",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", false ),
"simple_grid_field9", new XVar( "type", "grid_field_label",
"field", "profile_id" ),
"simple_grid_field6", new XVar( "field", "email_flash",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", false ),
"simple_grid_field10", new XVar( "type", "grid_field_label",
"field", "email_flash" ),
"simple_grid_field4", new XVar( "field", "status",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", false ),
"simple_grid_field11", new XVar( "type", "grid_field_label",
"field", "status" ),
"details_preview", new XVar( "type", "details_preview",
"table", "dbo.client_apps_table",
"items", XVar.Array(),
"popup", false,
"hideEmptyPreview", false,
"proceedLink", true,
"pageId", "list" ),
"details_preview1", new XVar( "type", "details_preview",
"table", "dbo.client_connections",
"items", XVar.Array(),
"popup", false,
"hideEmptyPreview", false,
"proceedLink", true,
"pageId", "list" ),
"details_preview2", new XVar( "type", "details_preview",
"table", "dbo.hk_client_inv_items",
"items", XVar.Array(),
"popup", false,
"hideEmptyPreview", false,
"proceedLink", true,
"pageId", "list" ),
"grid_checkbox", new XVar( "type", "grid_checkbox" ),
"grid_checkbox_head", new XVar( "type", "grid_checkbox_head" ),
"grid_alldetails_link", new XVar( "type", "grid_alldetails_link" ),
"grid_inline_cancel", new XVar( "type", "grid_inline_cancel" ),
"grid_inline_save", new XVar( "type", "grid_inline_save" ),
"grid_inline_edit", new XVar( "type", "grid_inline_edit" ),
"grid_edit", new XVar( "type", "grid_edit" ),
"grid_view", new XVar( "type", "grid_view" ),
"grid_details_link", new XVar( "type", "grid_details_link",
"table", "dbo.client_apps_table",
"badge", true,
"hideIfNone", false,
"showCount", true ),
"grid_details_link1", new XVar( "type", "grid_details_link",
"table", "dbo.client_connections",
"badge", true,
"showCount", true,
"hideIfNone", false ),
"grid_details_link2", new XVar( "type", "grid_details_link",
"table", "dbo.hk_client_inv_items",
"badge", true,
"showCount", true,
"hideIfNone", false ),
"expand_button", new XVar( "type", "expand_button" ) ),
"dbProps", new XVar(  ),
"spreadsheetGrid", false,
"version", 14,
"pageWidth", "full",
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}