
		// dbo.csi_lc_rcpt_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_csi_lc_rcpt_mst_print
			{
				static public XVar options()
				{
					return new XVar( "pdf", new XVar( "pdfView", false ),
"master", new XVar( "dbo.tp_po", new XVar( "preview", true ) ),
"totals", new XVar( "clientid", new XVar( "totalsType", "" ),
"VariationNumber", new XVar( "totalsType", "" ),
"ref_type", new XVar( "totalsType", "" ),
"ref_num", new XVar( "totalsType", "" ),
"ref_line_suf", new XVar( "totalsType", "" ),
"ref_release", new XVar( "totalsType", "" ),
"lc_type", new XVar( "totalsType", "" ),
"rcvd_date", new XVar( "totalsType", "" ),
"date_seq", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"CreateDate", new XVar( "totalsType", "" ),
"CreatedBy", new XVar( "totalsType", "" ),
"exch_rate", new XVar( "totalsType", "" ),
"grn_num", new XVar( "totalsType", "" ),
"InWorkflow", new XVar( "totalsType", "" ),
"NoteExistsFlag", new XVar( "totalsType", "" ),
"qty_ordered", new XVar( "totalsType", "" ),
"qty_received", new XVar( "totalsType", "" ),
"rcvd_amt", new XVar( "totalsType", "" ),
"RecordDate", new XVar( "totalsType", "" ),
"RowPointer", new XVar( "totalsType", "" ),
"unit_cost", new XVar( "totalsType", "" ),
"UpdatedBy", new XVar( "totalsType", "" ),
"vch_amt", new XVar( "totalsType", "" ),
"vend_num", new XVar( "totalsType", "" ),
"voucher", new XVar( "totalsType", "" ),
"vouchered", new XVar( "totalsType", "" ),
"DLDeleteIndicator", new XVar( "totalsType", "" ),
"uf_uet1", new XVar( "totalsType", "" ),
"uf_uet2", new XVar( "totalsType", "" ),
"uf_uet3", new XVar( "totalsType", "" ),
"uf_uet4", new XVar( "totalsType", "" ),
"uf_uet5", new XVar( "totalsType", "" ),
"uf_uet6", new XVar( "totalsType", "" ),
"uf_uet7", new XVar( "totalsType", "" ),
"uf_uet8", new XVar( "totalsType", "" ),
"uf_uet9", new XVar( "totalsType", "" ),
"uf_uet10", new XVar( "totalsType", "" ),
"tp_id", new XVar( "totalsType", "" ),
"tp_posted", new XVar( "totalsType", "" ),
"sc_id", new XVar( "totalsType", "" ),
"sf_id", new XVar( "totalsType", "" ),
"mg_id", new XVar( "totalsType", "" ),
"mg_posted", new XVar( "totalsType", "" ),
"sf_posted", new XVar( "totalsType", "" ),
"sc_posted", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "clientid",
1, "ref_type",
2, "ref_num",
3, "ref_line_suf",
4, "ref_release",
5, "lc_type",
6, "rcvd_date",
7, "date_seq",
8, "site_ref",
9, "qty_ordered",
10, "qty_received",
11, "rcvd_amt",
12, "unit_cost",
13, "vch_amt",
14, "vend_num",
15, "voucher",
16, "vouchered" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "clientid", new XVar( 0, "simple_grid_field",
1, "simple_grid_field1" ),
"ref_type", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field10" ),
"ref_num", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field11" ),
"ref_line_suf", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field12" ),
"ref_release", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field13" ),
"lc_type", new XVar( 0, "simple_grid_field6",
1, "simple_grid_field14" ),
"rcvd_date", new XVar( 0, "simple_grid_field7",
1, "simple_grid_field15" ),
"date_seq", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field19" ),
"site_ref", new XVar( 0, "simple_grid_field9",
1, "simple_grid_field20" ),
"qty_ordered", new XVar( 0, "simple_grid_field16",
1, "simple_grid_field22" ),
"qty_received", new XVar( 0, "simple_grid_field17",
1, "simple_grid_field27" ),
"rcvd_amt", new XVar( 0, "simple_grid_field18",
1, "simple_grid_field28" ),
"unit_cost", new XVar( 0, "simple_grid_field21",
1, "simple_grid_field29" ),
"vch_amt", new XVar( 0, "simple_grid_field23",
1, "simple_grid_field30" ),
"vend_num", new XVar( 0, "simple_grid_field24",
1, "simple_grid_field31" ),
"voucher", new XVar( 0, "simple_grid_field25",
1, "simple_grid_field32" ),
"vouchered", new XVar( 0, "simple_grid_field26",
1, "simple_grid_field33" ) ),
"hideEmptyFields", XVar.Array() ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "print_pages",
1, "grid_inline_cancel",
2, "inline_add" ),
"below-grid", XVar.Array(),
"top", new XVar( 0, "print_header",
1, "print_subheader",
2, "master_info" ),
"grid", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field",
2, "simple_grid_field10",
3, "simple_grid_field2",
4, "simple_grid_field11",
5, "simple_grid_field3",
6, "simple_grid_field12",
7, "simple_grid_field4",
8, "simple_grid_field13",
9, "simple_grid_field5",
10, "simple_grid_field14",
11, "simple_grid_field6",
12, "simple_grid_field15",
13, "simple_grid_field7",
14, "simple_grid_field19",
15, "simple_grid_field8",
16, "simple_grid_field20",
17, "simple_grid_field9",
18, "simple_grid_field22",
19, "simple_grid_field16",
20, "simple_grid_field27",
21, "simple_grid_field17",
22, "simple_grid_field28",
23, "simple_grid_field18",
24, "simple_grid_field29",
25, "simple_grid_field21",
26, "simple_grid_field30",
27, "simple_grid_field23",
28, "simple_grid_field31",
29, "simple_grid_field24",
30, "simple_grid_field32",
31, "simple_grid_field25",
32, "simple_grid_field33",
33, "simple_grid_field26" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "print_pages",
1, "inline_cancel",
2, "inlineadd_link" ),
"below-grid", XVar.Array() ),
"itemForms", new XVar( "print_pages", "above-grid",
"grid_inline_cancel", "above-grid",
"inline_add", "above-grid",
"print_header", "top",
"print_subheader", "top",
"master_info", "top",
"simple_grid_field1", "grid",
"simple_grid_field", "grid",
"simple_grid_field10", "grid",
"simple_grid_field2", "grid",
"simple_grid_field11", "grid",
"simple_grid_field3", "grid",
"simple_grid_field12", "grid",
"simple_grid_field4", "grid",
"simple_grid_field13", "grid",
"simple_grid_field5", "grid",
"simple_grid_field14", "grid",
"simple_grid_field6", "grid",
"simple_grid_field15", "grid",
"simple_grid_field7", "grid",
"simple_grid_field19", "grid",
"simple_grid_field8", "grid",
"simple_grid_field20", "grid",
"simple_grid_field9", "grid",
"simple_grid_field22", "grid",
"simple_grid_field16", "grid",
"simple_grid_field27", "grid",
"simple_grid_field17", "grid",
"simple_grid_field28", "grid",
"simple_grid_field18", "grid",
"simple_grid_field29", "grid",
"simple_grid_field21", "grid",
"simple_grid_field30", "grid",
"simple_grid_field23", "grid",
"simple_grid_field31", "grid",
"simple_grid_field24", "grid",
"simple_grid_field32", "grid",
"simple_grid_field25", "grid",
"simple_grid_field33", "grid",
"simple_grid_field26", "grid" ),
"itemLocations", new XVar( "simple_grid_field1", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field14", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field15", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field19", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"simple_grid_field20", new XVar( "location", "grid",
"cellId", "headcell_field8" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "cell_field8" ),
"simple_grid_field22", new XVar( "location", "grid",
"cellId", "headcell_field9" ),
"simple_grid_field16", new XVar( "location", "grid",
"cellId", "cell_field9" ),
"simple_grid_field27", new XVar( "location", "grid",
"cellId", "headcell_field10" ),
"simple_grid_field17", new XVar( "location", "grid",
"cellId", "cell_field10" ),
"simple_grid_field28", new XVar( "location", "grid",
"cellId", "headcell_field11" ),
"simple_grid_field18", new XVar( "location", "grid",
"cellId", "cell_field11" ),
"simple_grid_field29", new XVar( "location", "grid",
"cellId", "headcell_field12" ),
"simple_grid_field21", new XVar( "location", "grid",
"cellId", "cell_field12" ),
"simple_grid_field30", new XVar( "location", "grid",
"cellId", "headcell_field13" ),
"simple_grid_field23", new XVar( "location", "grid",
"cellId", "cell_field13" ),
"simple_grid_field31", new XVar( "location", "grid",
"cellId", "headcell_field14" ),
"simple_grid_field24", new XVar( "location", "grid",
"cellId", "cell_field14" ),
"simple_grid_field32", new XVar( "location", "grid",
"cellId", "headcell_field15" ),
"simple_grid_field25", new XVar( "location", "grid",
"cellId", "cell_field15" ),
"simple_grid_field33", new XVar( "location", "grid",
"cellId", "headcell_field16" ),
"simple_grid_field26", new XVar( "location", "grid",
"cellId", "cell_field16" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "print_header", new XVar( 0, "print_header" ),
"print_subheader", new XVar( 0, "print_subheader" ),
"print_pages", new XVar( 0, "print_pages" ),
"master_info", new XVar( 0, "master_info" ),
"grid_field", new XVar( 0, "simple_grid_field",
1, "simple_grid_field2",
2, "simple_grid_field3",
3, "simple_grid_field4",
4, "simple_grid_field5",
5, "simple_grid_field6",
6, "simple_grid_field7",
7, "simple_grid_field8",
8, "simple_grid_field9",
9, "simple_grid_field16",
10, "simple_grid_field17",
11, "simple_grid_field18",
12, "simple_grid_field21",
13, "simple_grid_field23",
14, "simple_grid_field24",
15, "simple_grid_field25",
16, "simple_grid_field26" ),
"grid_field_label", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field10",
2, "simple_grid_field11",
3, "simple_grid_field12",
4, "simple_grid_field13",
5, "simple_grid_field14",
6, "simple_grid_field15",
7, "simple_grid_field19",
8, "simple_grid_field20",
9, "simple_grid_field22",
10, "simple_grid_field27",
11, "simple_grid_field28",
12, "simple_grid_field29",
13, "simple_grid_field30",
14, "simple_grid_field31",
15, "simple_grid_field32",
16, "simple_grid_field33" ),
"inline_add", new XVar( 0, "inline_add" ),
"grid_inline_cancel", new XVar( 0, "grid_inline_cancel" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_field", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "clientid_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "ref_type_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "ref_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "ref_line_suf_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "ref_release_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "lc_type_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field14" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "rcvd_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field15" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "date_seq_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field19" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field8", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "site_ref_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field20" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field9", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "qty_ordered_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field22" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field10", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "qty_received_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field27" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field11", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "rcvd_amt_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field28" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field12", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "unit_cost_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field29" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field13", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "vch_amt_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field30" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field14", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "vend_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field31" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field15", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "voucher_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field32" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field16", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "vouchered_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field33" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "clientid_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "ref_type_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "ref_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "ref_line_suf_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "ref_release_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "lc_type_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "rcvd_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "date_seq_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field8", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "site_ref_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field9", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "qty_ordered_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field16" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field10", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "qty_received_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field17" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field11", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "rcvd_amt_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field18" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field12", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "unit_cost_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field21" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field13", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "vch_amt_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field23" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field14", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "vend_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field24" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field15", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "voucher_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field25" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field16", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "vouchered_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field26" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field8", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field9", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field10", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field11", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field12", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field13", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field14", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field15", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field16", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 17,
"height", 3 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar( "print_pages", new XVar( "tag", "PRINT_PAGES",
"type", 2 ) ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"gridType", 0,
"recsPerRow", 1,
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "print",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"dataGrid", new XVar( "groupFields", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "print",
"type", "print",
"layoutId", "basic",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "print-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "print_pages",
1, "grid_inline_cancel",
2, "inline_add" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "print-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "print-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c4" ) ),
"section", "" ) ),
"cells", new XVar( "c2", new XVar( "model", "c2",
"items", new XVar( 0, "print_header",
1, "print_subheader" ) ),
"c4", new XVar( "model", "c4",
"items", new XVar( 0, "master_info" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_field" ),
1, new XVar( "cell", "headcell_field1" ),
2, new XVar( "cell", "headcell_field2" ),
3, new XVar( "cell", "headcell_field3" ),
4, new XVar( "cell", "headcell_field4" ),
5, new XVar( "cell", "headcell_field5" ),
6, new XVar( "cell", "headcell_field6" ),
7, new XVar( "cell", "headcell_field7" ),
8, new XVar( "cell", "headcell_field8" ),
9, new XVar( "cell", "headcell_field9" ),
10, new XVar( "cell", "headcell_field10" ),
11, new XVar( "cell", "headcell_field11" ),
12, new XVar( "cell", "headcell_field12" ),
13, new XVar( "cell", "headcell_field13" ),
14, new XVar( "cell", "headcell_field14" ),
15, new XVar( "cell", "headcell_field15" ),
16, new XVar( "cell", "headcell_field16" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_field" ),
1, new XVar( "cell", "cell_field1" ),
2, new XVar( "cell", "cell_field2" ),
3, new XVar( "cell", "cell_field3" ),
4, new XVar( "cell", "cell_field4" ),
5, new XVar( "cell", "cell_field5" ),
6, new XVar( "cell", "cell_field6" ),
7, new XVar( "cell", "cell_field7" ),
8, new XVar( "cell", "cell_field8" ),
9, new XVar( "cell", "cell_field9" ),
10, new XVar( "cell", "cell_field10" ),
11, new XVar( "cell", "cell_field11" ),
12, new XVar( "cell", "cell_field12" ),
13, new XVar( "cell", "cell_field13" ),
14, new XVar( "cell", "cell_field14" ),
15, new XVar( "cell", "cell_field15" ),
16, new XVar( "cell", "cell_field16" ) ) ),
2, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_field" ),
1, new XVar( "cell", "footcell_field1" ),
2, new XVar( "cell", "footcell_field2" ),
3, new XVar( "cell", "footcell_field3" ),
4, new XVar( "cell", "footcell_field4" ),
5, new XVar( "cell", "footcell_field5" ),
6, new XVar( "cell", "footcell_field6" ),
7, new XVar( "cell", "footcell_field7" ),
8, new XVar( "cell", "footcell_field8" ),
9, new XVar( "cell", "footcell_field9" ),
10, new XVar( "cell", "footcell_field10" ),
11, new XVar( "cell", "footcell_field11" ),
12, new XVar( "cell", "footcell_field12" ),
13, new XVar( "cell", "footcell_field13" ),
14, new XVar( "cell", "footcell_field14" ),
15, new XVar( "cell", "footcell_field15" ),
16, new XVar( "cell", "footcell_field16" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "clientid",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "clientid",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "ref_type",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "ref_type",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "ref_num",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "ref_num",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "ref_line_suf",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "ref_line_suf",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "ref_release",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "ref_release",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field14" ),
"field", "lc_type",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "lc_type",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field15" ),
"field", "rcvd_date",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "rcvd_date",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field19" ),
"field", "date_seq",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "date_seq",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field8", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field20" ),
"field", "site_ref",
"columnName", "field" ),
"cell_field8", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "site_ref",
"columnName", "field" ),
"footcell_field8", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field9", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field22" ),
"field", "qty_ordered",
"columnName", "field" ),
"cell_field9", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field16" ),
"field", "qty_ordered",
"columnName", "field" ),
"footcell_field9", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field10", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field27" ),
"field", "qty_received",
"columnName", "field" ),
"cell_field10", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field17" ),
"field", "qty_received",
"columnName", "field" ),
"footcell_field10", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field11", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field28" ),
"field", "rcvd_amt",
"columnName", "field" ),
"cell_field11", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field18" ),
"field", "rcvd_amt",
"columnName", "field" ),
"footcell_field11", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field12", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field29" ),
"field", "unit_cost",
"columnName", "field" ),
"cell_field12", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field21" ),
"field", "unit_cost",
"columnName", "field" ),
"footcell_field12", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field13", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field30" ),
"field", "vch_amt",
"columnName", "field" ),
"cell_field13", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field23" ),
"field", "vch_amt",
"columnName", "field" ),
"footcell_field13", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field14", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field31" ),
"field", "vend_num",
"columnName", "field" ),
"cell_field14", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field24" ),
"field", "vend_num",
"columnName", "field" ),
"footcell_field14", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field15", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field32" ),
"field", "voucher",
"columnName", "field" ),
"cell_field15", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field25" ),
"field", "voucher",
"columnName", "field" ),
"footcell_field15", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field16", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field33" ),
"field", "vouchered",
"columnName", "field" ),
"cell_field16", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field26" ),
"field", "vouchered",
"columnName", "field" ),
"footcell_field16", new XVar( "model", "footcell_field",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "print_header", new XVar( "type", "print_header" ),
"print_subheader", new XVar( "type", "print_subheader" ),
"print_pages", new XVar( "type", "print_pages" ),
"master_info", new XVar( "type", "master_info",
"tables", new XVar( "dbo.tp_po", "true" ) ),
"simple_grid_field", new XVar( "field", "clientid",
"type", "grid_field" ),
"simple_grid_field1", new XVar( "type", "grid_field_label",
"field", "clientid" ),
"simple_grid_field2", new XVar( "field", "ref_type",
"type", "grid_field" ),
"simple_grid_field10", new XVar( "type", "grid_field_label",
"field", "ref_type" ),
"simple_grid_field3", new XVar( "field", "ref_num",
"type", "grid_field" ),
"simple_grid_field11", new XVar( "type", "grid_field_label",
"field", "ref_num" ),
"simple_grid_field4", new XVar( "field", "ref_line_suf",
"type", "grid_field" ),
"simple_grid_field12", new XVar( "type", "grid_field_label",
"field", "ref_line_suf" ),
"simple_grid_field5", new XVar( "field", "ref_release",
"type", "grid_field" ),
"simple_grid_field13", new XVar( "type", "grid_field_label",
"field", "ref_release" ),
"simple_grid_field6", new XVar( "field", "lc_type",
"type", "grid_field" ),
"simple_grid_field14", new XVar( "type", "grid_field_label",
"field", "lc_type" ),
"simple_grid_field7", new XVar( "field", "rcvd_date",
"type", "grid_field" ),
"simple_grid_field15", new XVar( "type", "grid_field_label",
"field", "rcvd_date" ),
"simple_grid_field8", new XVar( "field", "date_seq",
"type", "grid_field" ),
"simple_grid_field19", new XVar( "type", "grid_field_label",
"field", "date_seq" ),
"simple_grid_field9", new XVar( "field", "site_ref",
"type", "grid_field" ),
"simple_grid_field20", new XVar( "type", "grid_field_label",
"field", "site_ref" ),
"simple_grid_field16", new XVar( "field", "qty_ordered",
"type", "grid_field" ),
"simple_grid_field22", new XVar( "type", "grid_field_label",
"field", "qty_ordered" ),
"simple_grid_field17", new XVar( "field", "qty_received",
"type", "grid_field" ),
"simple_grid_field27", new XVar( "type", "grid_field_label",
"field", "qty_received" ),
"simple_grid_field18", new XVar( "field", "rcvd_amt",
"type", "grid_field" ),
"simple_grid_field28", new XVar( "type", "grid_field_label",
"field", "rcvd_amt" ),
"simple_grid_field21", new XVar( "field", "unit_cost",
"type", "grid_field" ),
"simple_grid_field29", new XVar( "type", "grid_field_label",
"field", "unit_cost" ),
"simple_grid_field23", new XVar( "field", "vch_amt",
"type", "grid_field" ),
"simple_grid_field30", new XVar( "type", "grid_field_label",
"field", "vch_amt" ),
"simple_grid_field24", new XVar( "field", "vend_num",
"type", "grid_field" ),
"simple_grid_field31", new XVar( "type", "grid_field_label",
"field", "vend_num" ),
"simple_grid_field25", new XVar( "field", "voucher",
"type", "grid_field" ),
"simple_grid_field32", new XVar( "type", "grid_field_label",
"field", "voucher" ),
"simple_grid_field26", new XVar( "field", "vouchered",
"type", "grid_field" ),
"simple_grid_field33", new XVar( "type", "grid_field_label",
"field", "vouchered" ),
"inline_add", new XVar( "type", "inline_add",
"detailsOnly", true ),
"grid_inline_cancel", new XVar( "type", "grid_inline_cancel" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}