
		// dbo.csi_lc_rcpt_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_csi_lc_rcpt_mst_export
			{
				static public XVar options()
				{
					return new XVar( "totals", new XVar( "clientid", new XVar( "totalsType", "" ),
"VariationNumber", new XVar( "totalsType", "" ),
"ref_type", new XVar( "totalsType", "" ),
"ref_num", new XVar( "totalsType", "" ),
"ref_line_suf", new XVar( "totalsType", "" ),
"ref_release", new XVar( "totalsType", "" ),
"lc_type", new XVar( "totalsType", "" ),
"rcvd_date", new XVar( "totalsType", "" ),
"date_seq", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"CreateDate", new XVar( "totalsType", "" ),
"CreatedBy", new XVar( "totalsType", "" ),
"exch_rate", new XVar( "totalsType", "" ),
"grn_num", new XVar( "totalsType", "" ),
"InWorkflow", new XVar( "totalsType", "" ),
"NoteExistsFlag", new XVar( "totalsType", "" ),
"qty_ordered", new XVar( "totalsType", "" ),
"qty_received", new XVar( "totalsType", "" ),
"rcvd_amt", new XVar( "totalsType", "" ),
"RecordDate", new XVar( "totalsType", "" ),
"RowPointer", new XVar( "totalsType", "" ),
"unit_cost", new XVar( "totalsType", "" ),
"UpdatedBy", new XVar( "totalsType", "" ),
"vch_amt", new XVar( "totalsType", "" ),
"vend_num", new XVar( "totalsType", "" ),
"voucher", new XVar( "totalsType", "" ),
"vouchered", new XVar( "totalsType", "" ),
"DLDeleteIndicator", new XVar( "totalsType", "" ),
"uf_uet1", new XVar( "totalsType", "" ),
"uf_uet2", new XVar( "totalsType", "" ),
"uf_uet3", new XVar( "totalsType", "" ),
"uf_uet4", new XVar( "totalsType", "" ),
"uf_uet5", new XVar( "totalsType", "" ),
"uf_uet6", new XVar( "totalsType", "" ),
"uf_uet7", new XVar( "totalsType", "" ),
"uf_uet8", new XVar( "totalsType", "" ),
"uf_uet9", new XVar( "totalsType", "" ),
"uf_uet10", new XVar( "totalsType", "" ),
"tp_id", new XVar( "totalsType", "" ),
"tp_posted", new XVar( "totalsType", "" ),
"sc_id", new XVar( "totalsType", "" ),
"sf_id", new XVar( "totalsType", "" ),
"mg_id", new XVar( "totalsType", "" ),
"mg_posted", new XVar( "totalsType", "" ),
"sf_posted", new XVar( "totalsType", "" ),
"sc_posted", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "clientid",
1, "ref_type",
2, "ref_num",
3, "ref_line_suf",
4, "ref_release",
5, "lc_type",
6, "rcvd_date",
7, "date_seq",
8, "site_ref",
9, "qty_ordered",
10, "qty_received",
11, "rcvd_amt",
12, "unit_cost",
13, "vch_amt",
14, "vend_num",
15, "voucher",
16, "vouchered" ),
"exportFields", new XVar( 0, "clientid",
1, "ref_type",
2, "ref_num",
3, "ref_line_suf",
4, "ref_release",
5, "lc_type",
6, "rcvd_date",
7, "date_seq",
8, "site_ref",
9, "qty_ordered",
10, "qty_received",
11, "rcvd_amt",
12, "unit_cost",
13, "vch_amt",
14, "vend_num",
15, "voucher",
16, "vouchered" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "clientid", new XVar( 0, "export_field" ),
"ref_type", new XVar( 0, "export_field2" ),
"ref_num", new XVar( 0, "export_field3" ),
"ref_line_suf", new XVar( 0, "export_field4" ),
"ref_release", new XVar( 0, "export_field5" ),
"lc_type", new XVar( 0, "export_field6" ),
"rcvd_date", new XVar( 0, "export_field7" ),
"date_seq", new XVar( 0, "export_field8" ),
"site_ref", new XVar( 0, "export_field9" ),
"qty_ordered", new XVar( 0, "export_field16" ),
"qty_received", new XVar( 0, "export_field17" ),
"rcvd_amt", new XVar( 0, "export_field18" ),
"unit_cost", new XVar( 0, "export_field21" ),
"vch_amt", new XVar( 0, "export_field23" ),
"vend_num", new XVar( 0, "export_field24" ),
"voucher", new XVar( 0, "export_field25" ),
"vouchered", new XVar( 0, "export_field26" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "export_header" ),
"grid", new XVar( 0, "export_field",
1, "export_field2",
2, "export_field3",
3, "export_field4",
4, "export_field5",
5, "export_field6",
6, "export_field7",
7, "export_field8",
8, "export_field9",
9, "export_field16",
10, "export_field17",
11, "export_field18",
12, "export_field21",
13, "export_field23",
14, "export_field24",
15, "export_field25",
16, "export_field26" ),
"footer", new XVar( 0, "export_export",
1, "export_cancel" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "export_header", "top",
"export_field", "grid",
"export_field2", "grid",
"export_field3", "grid",
"export_field4", "grid",
"export_field5", "grid",
"export_field6", "grid",
"export_field7", "grid",
"export_field8", "grid",
"export_field9", "grid",
"export_field16", "grid",
"export_field17", "grid",
"export_field18", "grid",
"export_field21", "grid",
"export_field23", "grid",
"export_field24", "grid",
"export_field25", "grid",
"export_field26", "grid",
"export_export", "footer",
"export_cancel", "footer" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "export_header", new XVar( 0, "export_header" ),
"export_export", new XVar( 0, "export_export" ),
"export_cancel", new XVar( 0, "export_cancel" ),
"export_field", new XVar( 0, "export_field",
1, "export_field2",
2, "export_field3",
3, "export_field4",
4, "export_field5",
5, "export_field6",
6, "export_field7",
7, "export_field8",
8, "export_field9",
9, "export_field16",
10, "export_field17",
11, "export_field18",
12, "export_field21",
13, "export_field23",
14, "export_field24",
15, "export_field25",
16, "export_field26" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"export", new XVar( "format", 2,
"selectFields", false,
"delimiter", ",",
"selectDelimiter", false,
"exportFileTypes", new XVar( "excel", true,
"word", true,
"csv", true,
"xml", false ) ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "export",
"type", "export",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "export-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "export-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_field",
1, "export_field2",
2, "export_field3",
3, "export_field4",
4, "export_field5",
5, "export_field6",
6, "export_field7",
7, "export_field8",
8, "export_field9",
9, "export_field16",
10, "export_field17",
11, "export_field18",
12, "export_field21",
13, "export_field23",
14, "export_field24",
15, "export_field25",
16, "export_field26" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"footer", new XVar( "modelId", "export-footer",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "export_export",
1, "export_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "export_header", new XVar( "type", "export_header" ),
"export_export", new XVar( "type", "export_export" ),
"export_cancel", new XVar( "type", "export_cancel" ),
"export_field", new XVar( "field", "clientid",
"type", "export_field" ),
"export_field2", new XVar( "field", "ref_type",
"type", "export_field" ),
"export_field3", new XVar( "field", "ref_num",
"type", "export_field" ),
"export_field4", new XVar( "field", "ref_line_suf",
"type", "export_field" ),
"export_field5", new XVar( "field", "ref_release",
"type", "export_field" ),
"export_field6", new XVar( "field", "lc_type",
"type", "export_field" ),
"export_field7", new XVar( "field", "rcvd_date",
"type", "export_field" ),
"export_field8", new XVar( "field", "date_seq",
"type", "export_field" ),
"export_field9", new XVar( "field", "site_ref",
"type", "export_field" ),
"export_field16", new XVar( "field", "qty_ordered",
"type", "export_field" ),
"export_field17", new XVar( "field", "qty_received",
"type", "export_field" ),
"export_field18", new XVar( "field", "rcvd_amt",
"type", "export_field" ),
"export_field21", new XVar( "field", "unit_cost",
"type", "export_field" ),
"export_field23", new XVar( "field", "vch_amt",
"type", "export_field" ),
"export_field24", new XVar( "field", "vend_num",
"type", "export_field" ),
"export_field25", new XVar( "field", "voucher",
"type", "export_field" ),
"export_field26", new XVar( "field", "vouchered",
"type", "export_field" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1,
"exportFormat", 2,
"exportDelimiter", ",",
"exportSelectDelimiter", false,
"exportSelectFields", false );
				}
			}
		}