
		// dbo.csi_site_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_csi_site_mst_import
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "clientid",
1, "site_ref",
2, "tp_payer_entity_name",
3, "tp_bankcode",
4, "sf_entity_name",
5, "site_prefix",
6, "mg_whse",
7, "mg_quest_vend_num",
8, "sc_entity_name",
9, "tp_active",
10, "tp_vend_stat_pre",
11, "tp_vend_stat_post",
12, "tp_vend_post_to_sl",
13, "exp_entity_name",
14, "exp_journal",
15, "tp_lc_active" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "clientid", new XVar( 0, "import_field" ),
"site_ref", new XVar( 0, "import_field1" ),
"tp_payer_entity_name", new XVar( 0, "import_field2" ),
"tp_bankcode", new XVar( 0, "import_field3" ),
"sf_entity_name", new XVar( 0, "import_field4" ),
"site_prefix", new XVar( 0, "import_field5" ),
"mg_whse", new XVar( 0, "import_field6" ),
"mg_quest_vend_num", new XVar( 0, "import_field7" ),
"sc_entity_name", new XVar( 0, "import_field8" ),
"tp_active", new XVar( 0, "import_field9" ),
"tp_vend_stat_pre", new XVar( 0, "import_field10" ),
"tp_vend_stat_post", new XVar( 0, "import_field11" ),
"tp_vend_post_to_sl", new XVar( 0, "import_field12" ),
"exp_entity_name", new XVar( 0, "import_field13" ),
"exp_journal", new XVar( 0, "import_field14" ),
"tp_lc_active", new XVar( 0, "import_field15" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "import_header" ),
"grid", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "import_header", "top",
"import_field", "grid",
"import_field1", "grid",
"import_field2", "grid",
"import_field3", "grid",
"import_field4", "grid",
"import_field5", "grid",
"import_field6", "grid",
"import_field7", "grid",
"import_field8", "grid",
"import_field9", "grid",
"import_field10", "grid",
"import_field11", "grid",
"import_field12", "grid",
"import_field13", "grid",
"import_field14", "grid",
"import_field15", "grid" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "import_header", new XVar( 0, "import_header" ),
"import_field", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "import",
"type", "import",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "import-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "import-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "import_header", new XVar( "type", "import_header" ),
"import_field", new XVar( "field", "clientid",
"type", "import_field" ),
"import_field1", new XVar( "field", "site_ref",
"type", "import_field" ),
"import_field2", new XVar( "field", "tp_payer_entity_name",
"type", "import_field" ),
"import_field3", new XVar( "field", "tp_bankcode",
"type", "import_field" ),
"import_field4", new XVar( "field", "sf_entity_name",
"type", "import_field" ),
"import_field5", new XVar( "field", "site_prefix",
"type", "import_field" ),
"import_field6", new XVar( "field", "mg_whse",
"type", "import_field" ),
"import_field7", new XVar( "field", "mg_quest_vend_num",
"type", "import_field" ),
"import_field8", new XVar( "field", "sc_entity_name",
"type", "import_field" ),
"import_field9", new XVar( "field", "tp_active",
"type", "import_field" ),
"import_field10", new XVar( "field", "tp_vend_stat_pre",
"type", "import_field" ),
"import_field11", new XVar( "field", "tp_vend_stat_post",
"type", "import_field" ),
"import_field12", new XVar( "field", "tp_vend_post_to_sl",
"type", "import_field" ),
"import_field13", new XVar( "field", "exp_entity_name",
"type", "import_field" ),
"import_field14", new XVar( "field", "exp_journal",
"type", "import_field" ),
"import_field15", new XVar( "field", "tp_lc_active",
"type", "import_field" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}