
		// dbo.csi_terms_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_csi_terms_mst_export
			{
				static public XVar options()
				{
					return new XVar( "totals", new XVar( "clientid", new XVar( "totalsType", "" ),
"terms_code", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"advanced", new XVar( "totalsType", "" ),
"cash_only", new XVar( "totalsType", "" ),
"CreateDate", new XVar( "totalsType", "" ),
"CreatedBy", new XVar( "totalsType", "" ),
"cutoff_day", new XVar( "totalsType", "" ),
"description", new XVar( "totalsType", "" ),
"disc_days", new XVar( "totalsType", "" ),
"disc_pct", new XVar( "totalsType", "" ),
"due_days", new XVar( "totalsType", "" ),
"holiday_offset_method", new XVar( "totalsType", "" ),
"InWorkflow", new XVar( "totalsType", "" ),
"NoteExistsFlag", new XVar( "totalsType", "" ),
"prox_code", new XVar( "totalsType", "" ),
"prox_day", new XVar( "totalsType", "" ),
"prox_disc_day", new XVar( "totalsType", "" ),
"prox_disc_month_to_forward", new XVar( "totalsType", "" ),
"prox_month_to_forward", new XVar( "totalsType", "" ),
"RecordDate", new XVar( "totalsType", "" ),
"RowPointer", new XVar( "totalsType", "" ),
"tax_disc", new XVar( "totalsType", "" ),
"UpdatedBy", new XVar( "totalsType", "" ),
"use_multi_due_dates", new XVar( "totalsType", "" ),
"DLDeleteIndicator", new XVar( "totalsType", "" ),
"VariationNumber", new XVar( "totalsType", "" ),
"salesforceid", new XVar( "totalsType", "" ),
"tp_id", new XVar( "totalsType", "" ),
"tp_posted", new XVar( "totalsType", "" ),
"sc_id", new XVar( "totalsType", "" ),
"sc_posted", new XVar( "totalsType", "" ),
"sf_id", new XVar( "totalsType", "" ),
"sf_posted", new XVar( "totalsType", "" ),
"mg_id", new XVar( "totalsType", "" ),
"mg_posted", new XVar( "totalsType", "" ),
"uf_uet1", new XVar( "totalsType", "" ),
"uf_uet2", new XVar( "totalsType", "" ),
"uf_uet3", new XVar( "totalsType", "" ),
"uf_uet4", new XVar( "totalsType", "" ),
"uf_uet5", new XVar( "totalsType", "" ),
"uf_uet6", new XVar( "totalsType", "" ),
"uf_uet7", new XVar( "totalsType", "" ),
"uf_uet8", new XVar( "totalsType", "" ),
"uf_uet9", new XVar( "totalsType", "" ),
"uf_uet10", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "clientid",
1, "terms_code",
2, "site_ref",
3, "description",
4, "tp_posted",
5, "uf_uet7",
6, "uf_uet8",
7, "uf_uet9",
8, "uf_uet10" ),
"exportFields", new XVar( 0, "clientid",
1, "terms_code",
2, "site_ref",
3, "description",
4, "tp_posted",
5, "uf_uet7",
6, "uf_uet8",
7, "uf_uet9",
8, "uf_uet10" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "clientid", new XVar( 0, "export_field" ),
"terms_code", new XVar( 0, "export_field1" ),
"site_ref", new XVar( 0, "export_field2" ),
"description", new XVar( 0, "export_field8" ),
"tp_posted", new XVar( 0, "export_field29" ),
"uf_uet7", new XVar( 0, "export_field42" ),
"uf_uet8", new XVar( 0, "export_field43" ),
"uf_uet9", new XVar( 0, "export_field44" ),
"uf_uet10", new XVar( 0, "export_field45" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "export_header" ),
"grid", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field8",
4, "export_field29",
5, "export_field42",
6, "export_field43",
7, "export_field44",
8, "export_field45" ),
"footer", new XVar( 0, "export_export",
1, "export_cancel" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "export_header", "top",
"export_field", "grid",
"export_field1", "grid",
"export_field2", "grid",
"export_field8", "grid",
"export_field29", "grid",
"export_field42", "grid",
"export_field43", "grid",
"export_field44", "grid",
"export_field45", "grid",
"export_export", "footer",
"export_cancel", "footer" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "export_header", new XVar( 0, "export_header" ),
"export_export", new XVar( 0, "export_export" ),
"export_cancel", new XVar( 0, "export_cancel" ),
"export_field", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field8",
4, "export_field29",
5, "export_field42",
6, "export_field43",
7, "export_field44",
8, "export_field45" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"export", new XVar( "format", 2,
"selectFields", false,
"delimiter", ",",
"selectDelimiter", false,
"exportFileTypes", new XVar( "excel", true,
"word", true,
"csv", true,
"xml", false ) ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "export",
"type", "export",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "export-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "export-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field8",
4, "export_field29",
5, "export_field42",
6, "export_field43",
7, "export_field44",
8, "export_field45" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"footer", new XVar( "modelId", "export-footer",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "export_export",
1, "export_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "export_header", new XVar( "type", "export_header" ),
"export_export", new XVar( "type", "export_export" ),
"export_cancel", new XVar( "type", "export_cancel" ),
"export_field", new XVar( "field", "clientid",
"type", "export_field" ),
"export_field1", new XVar( "field", "terms_code",
"type", "export_field" ),
"export_field2", new XVar( "field", "site_ref",
"type", "export_field" ),
"export_field8", new XVar( "field", "description",
"type", "export_field" ),
"export_field29", new XVar( "field", "tp_posted",
"type", "export_field" ),
"export_field42", new XVar( "field", "uf_uet7",
"type", "export_field" ),
"export_field43", new XVar( "field", "uf_uet8",
"type", "export_field" ),
"export_field44", new XVar( "field", "uf_uet9",
"type", "export_field" ),
"export_field45", new XVar( "field", "uf_uet10",
"type", "export_field" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1,
"exportFormat", 2,
"exportDelimiter", ",",
"exportSelectDelimiter", false,
"exportSelectFields", false );
				}
			}
		}