
		// dbo.mg_order_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_mg_order_mst_import
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "clientid",
1, "site_ref",
2, "base_currency_code",
3, "base_discount_amount",
4, "base_discount_invoiced",
5, "base_grand_total",
6, "base_discount_tax_compensation_amount",
7, "base_discount_tax_compensation_invoiced",
8, "base_shipping_amount",
9, "base_shipping_discount_amount",
10, "base_shipping_discount_tax_compensation_amnt",
11, "base_shipping_incl_tax",
12, "base_shipping_invoiced",
13, "base_shipping_tax_amount",
14, "base_subtotal",
15, "base_subtotal_incl_tax",
16, "base_subtotal_invoiced",
17, "base_tax_amount",
18, "base_tax_invoiced",
19, "base_total_due",
20, "base_total_invoiced",
21, "base_total_invoiced_cost",
22, "base_total_paid",
23, "base_to_global_rate",
24, "base_to_order_rate",
25, "billing_address_id",
26, "created_at",
27, "customer_email",
28, "customer_firstname",
29, "customer_is_guest",
30, "customer_lastname",
31, "customer_note_notify",
32, "discount_amount",
33, "discount_invoiced",
34, "email_sent",
35, "entity_id",
36, "global_currency_code",
37, "grand_total",
38, "discount_tax_compensation_amount",
39, "discount_tax_compensation_invoiced",
40, "increment_id",
41, "is_virtual",
42, "order_currency_code",
43, "protect_code",
44, "quote_id",
45, "remote_ip",
46, "shipping_amount",
47, "shipping_description",
48, "shipping_discount_amount",
49, "shipping_discount_tax_compensation_amount",
50, "shipping_incl_tax",
51, "shipping_invoiced",
52, "shipping_tax_amount",
53, "state",
54, "status",
55, "store_currency_code",
56, "store_id",
57, "store_name",
58, "store_to_base_rate",
59, "store_to_order_rate",
60, "subtotal",
61, "subtotal_incl_tax",
62, "subtotal_invoiced",
63, "tax_amount",
64, "tax_invoiced",
65, "total_due",
66, "total_invoiced",
67, "total_item_count",
68, "total_paid",
69, "total_qty_ordered",
70, "updated_at",
71, "customer_id",
72, "co_num",
73, "json_data",
74, "line",
75, "posted",
76, "cust_num",
77, "cust_seq" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "clientid", new XVar( 0, "import_field" ),
"site_ref", new XVar( 0, "import_field1" ),
"base_currency_code", new XVar( 0, "import_field2" ),
"base_discount_amount", new XVar( 0, "import_field3" ),
"base_discount_invoiced", new XVar( 0, "import_field4" ),
"base_grand_total", new XVar( 0, "import_field5" ),
"base_discount_tax_compensation_amount", new XVar( 0, "import_field6" ),
"base_discount_tax_compensation_invoiced", new XVar( 0, "import_field7" ),
"base_shipping_amount", new XVar( 0, "import_field8" ),
"base_shipping_discount_amount", new XVar( 0, "import_field9" ),
"base_shipping_discount_tax_compensation_amnt", new XVar( 0, "import_field10" ),
"base_shipping_incl_tax", new XVar( 0, "import_field11" ),
"base_shipping_invoiced", new XVar( 0, "import_field12" ),
"base_shipping_tax_amount", new XVar( 0, "import_field13" ),
"base_subtotal", new XVar( 0, "import_field14" ),
"base_subtotal_incl_tax", new XVar( 0, "import_field15" ),
"base_subtotal_invoiced", new XVar( 0, "import_field16" ),
"base_tax_amount", new XVar( 0, "import_field17" ),
"base_tax_invoiced", new XVar( 0, "import_field18" ),
"base_total_due", new XVar( 0, "import_field19" ),
"base_total_invoiced", new XVar( 0, "import_field20" ),
"base_total_invoiced_cost", new XVar( 0, "import_field21" ),
"base_total_paid", new XVar( 0, "import_field22" ),
"base_to_global_rate", new XVar( 0, "import_field23" ),
"base_to_order_rate", new XVar( 0, "import_field24" ),
"billing_address_id", new XVar( 0, "import_field25" ),
"created_at", new XVar( 0, "import_field26" ),
"customer_email", new XVar( 0, "import_field27" ),
"customer_firstname", new XVar( 0, "import_field28" ),
"customer_is_guest", new XVar( 0, "import_field29" ),
"customer_lastname", new XVar( 0, "import_field30" ),
"customer_note_notify", new XVar( 0, "import_field31" ),
"discount_amount", new XVar( 0, "import_field32" ),
"discount_invoiced", new XVar( 0, "import_field33" ),
"email_sent", new XVar( 0, "import_field34" ),
"entity_id", new XVar( 0, "import_field35" ),
"global_currency_code", new XVar( 0, "import_field36" ),
"grand_total", new XVar( 0, "import_field37" ),
"discount_tax_compensation_amount", new XVar( 0, "import_field38" ),
"discount_tax_compensation_invoiced", new XVar( 0, "import_field39" ),
"increment_id", new XVar( 0, "import_field40" ),
"is_virtual", new XVar( 0, "import_field41" ),
"order_currency_code", new XVar( 0, "import_field42" ),
"protect_code", new XVar( 0, "import_field43" ),
"quote_id", new XVar( 0, "import_field44" ),
"remote_ip", new XVar( 0, "import_field45" ),
"shipping_amount", new XVar( 0, "import_field46" ),
"shipping_description", new XVar( 0, "import_field47" ),
"shipping_discount_amount", new XVar( 0, "import_field48" ),
"shipping_discount_tax_compensation_amount", new XVar( 0, "import_field49" ),
"shipping_incl_tax", new XVar( 0, "import_field50" ),
"shipping_invoiced", new XVar( 0, "import_field51" ),
"shipping_tax_amount", new XVar( 0, "import_field52" ),
"state", new XVar( 0, "import_field53" ),
"status", new XVar( 0, "import_field54" ),
"store_currency_code", new XVar( 0, "import_field55" ),
"store_id", new XVar( 0, "import_field56" ),
"store_name", new XVar( 0, "import_field57" ),
"store_to_base_rate", new XVar( 0, "import_field58" ),
"store_to_order_rate", new XVar( 0, "import_field59" ),
"subtotal", new XVar( 0, "import_field60" ),
"subtotal_incl_tax", new XVar( 0, "import_field61" ),
"subtotal_invoiced", new XVar( 0, "import_field62" ),
"tax_amount", new XVar( 0, "import_field63" ),
"tax_invoiced", new XVar( 0, "import_field64" ),
"total_due", new XVar( 0, "import_field65" ),
"total_invoiced", new XVar( 0, "import_field66" ),
"total_item_count", new XVar( 0, "import_field67" ),
"total_paid", new XVar( 0, "import_field68" ),
"total_qty_ordered", new XVar( 0, "import_field69" ),
"updated_at", new XVar( 0, "import_field70" ),
"customer_id", new XVar( 0, "import_field71" ),
"co_num", new XVar( 0, "import_field72" ),
"json_data", new XVar( 0, "import_field73" ),
"line", new XVar( 0, "import_field74" ),
"posted", new XVar( 0, "import_field75" ),
"cust_num", new XVar( 0, "import_field76" ),
"cust_seq", new XVar( 0, "import_field77" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "import_header" ),
"grid", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16",
17, "import_field17",
18, "import_field18",
19, "import_field19",
20, "import_field20",
21, "import_field21",
22, "import_field22",
23, "import_field23",
24, "import_field24",
25, "import_field25",
26, "import_field26",
27, "import_field27",
28, "import_field28",
29, "import_field29",
30, "import_field30",
31, "import_field31",
32, "import_field32",
33, "import_field33",
34, "import_field34",
35, "import_field35",
36, "import_field36",
37, "import_field37",
38, "import_field38",
39, "import_field39",
40, "import_field40",
41, "import_field41",
42, "import_field42",
43, "import_field43",
44, "import_field44",
45, "import_field45",
46, "import_field46",
47, "import_field47",
48, "import_field48",
49, "import_field49",
50, "import_field50",
51, "import_field51",
52, "import_field52",
53, "import_field53",
54, "import_field54",
55, "import_field55",
56, "import_field56",
57, "import_field57",
58, "import_field58",
59, "import_field59",
60, "import_field60",
61, "import_field61",
62, "import_field62",
63, "import_field63",
64, "import_field64",
65, "import_field65",
66, "import_field66",
67, "import_field67",
68, "import_field68",
69, "import_field69",
70, "import_field70",
71, "import_field71",
72, "import_field72",
73, "import_field73",
74, "import_field74",
75, "import_field75",
76, "import_field76",
77, "import_field77" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "import_header", "top",
"import_field", "grid",
"import_field1", "grid",
"import_field2", "grid",
"import_field3", "grid",
"import_field4", "grid",
"import_field5", "grid",
"import_field6", "grid",
"import_field7", "grid",
"import_field8", "grid",
"import_field9", "grid",
"import_field10", "grid",
"import_field11", "grid",
"import_field12", "grid",
"import_field13", "grid",
"import_field14", "grid",
"import_field15", "grid",
"import_field16", "grid",
"import_field17", "grid",
"import_field18", "grid",
"import_field19", "grid",
"import_field20", "grid",
"import_field21", "grid",
"import_field22", "grid",
"import_field23", "grid",
"import_field24", "grid",
"import_field25", "grid",
"import_field26", "grid",
"import_field27", "grid",
"import_field28", "grid",
"import_field29", "grid",
"import_field30", "grid",
"import_field31", "grid",
"import_field32", "grid",
"import_field33", "grid",
"import_field34", "grid",
"import_field35", "grid",
"import_field36", "grid",
"import_field37", "grid",
"import_field38", "grid",
"import_field39", "grid",
"import_field40", "grid",
"import_field41", "grid",
"import_field42", "grid",
"import_field43", "grid",
"import_field44", "grid",
"import_field45", "grid",
"import_field46", "grid",
"import_field47", "grid",
"import_field48", "grid",
"import_field49", "grid",
"import_field50", "grid",
"import_field51", "grid",
"import_field52", "grid",
"import_field53", "grid",
"import_field54", "grid",
"import_field55", "grid",
"import_field56", "grid",
"import_field57", "grid",
"import_field58", "grid",
"import_field59", "grid",
"import_field60", "grid",
"import_field61", "grid",
"import_field62", "grid",
"import_field63", "grid",
"import_field64", "grid",
"import_field65", "grid",
"import_field66", "grid",
"import_field67", "grid",
"import_field68", "grid",
"import_field69", "grid",
"import_field70", "grid",
"import_field71", "grid",
"import_field72", "grid",
"import_field73", "grid",
"import_field74", "grid",
"import_field75", "grid",
"import_field76", "grid",
"import_field77", "grid" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "import_header", new XVar( 0, "import_header" ),
"import_field", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16",
17, "import_field17",
18, "import_field18",
19, "import_field19",
20, "import_field20",
21, "import_field21",
22, "import_field22",
23, "import_field23",
24, "import_field24",
25, "import_field25",
26, "import_field26",
27, "import_field27",
28, "import_field28",
29, "import_field29",
30, "import_field30",
31, "import_field31",
32, "import_field32",
33, "import_field33",
34, "import_field34",
35, "import_field35",
36, "import_field36",
37, "import_field37",
38, "import_field38",
39, "import_field39",
40, "import_field40",
41, "import_field41",
42, "import_field42",
43, "import_field43",
44, "import_field44",
45, "import_field45",
46, "import_field46",
47, "import_field47",
48, "import_field48",
49, "import_field49",
50, "import_field50",
51, "import_field51",
52, "import_field52",
53, "import_field53",
54, "import_field54",
55, "import_field55",
56, "import_field56",
57, "import_field57",
58, "import_field58",
59, "import_field59",
60, "import_field60",
61, "import_field61",
62, "import_field62",
63, "import_field63",
64, "import_field64",
65, "import_field65",
66, "import_field66",
67, "import_field67",
68, "import_field68",
69, "import_field69",
70, "import_field70",
71, "import_field71",
72, "import_field72",
73, "import_field73",
74, "import_field74",
75, "import_field75",
76, "import_field76",
77, "import_field77" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "import",
"type", "import",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "import-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "import-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16",
17, "import_field17",
18, "import_field18",
19, "import_field19",
20, "import_field20",
21, "import_field21",
22, "import_field22",
23, "import_field23",
24, "import_field24",
25, "import_field25",
26, "import_field26",
27, "import_field27",
28, "import_field28",
29, "import_field29",
30, "import_field30",
31, "import_field31",
32, "import_field32",
33, "import_field33",
34, "import_field34",
35, "import_field35",
36, "import_field36",
37, "import_field37",
38, "import_field38",
39, "import_field39",
40, "import_field40",
41, "import_field41",
42, "import_field42",
43, "import_field43",
44, "import_field44",
45, "import_field45",
46, "import_field46",
47, "import_field47",
48, "import_field48",
49, "import_field49",
50, "import_field50",
51, "import_field51",
52, "import_field52",
53, "import_field53",
54, "import_field54",
55, "import_field55",
56, "import_field56",
57, "import_field57",
58, "import_field58",
59, "import_field59",
60, "import_field60",
61, "import_field61",
62, "import_field62",
63, "import_field63",
64, "import_field64",
65, "import_field65",
66, "import_field66",
67, "import_field67",
68, "import_field68",
69, "import_field69",
70, "import_field70",
71, "import_field71",
72, "import_field72",
73, "import_field73",
74, "import_field74",
75, "import_field75",
76, "import_field76",
77, "import_field77" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "import_header", new XVar( "type", "import_header" ),
"import_field", new XVar( "field", "clientid",
"type", "import_field" ),
"import_field1", new XVar( "field", "site_ref",
"type", "import_field" ),
"import_field2", new XVar( "field", "base_currency_code",
"type", "import_field" ),
"import_field3", new XVar( "field", "base_discount_amount",
"type", "import_field" ),
"import_field4", new XVar( "field", "base_discount_invoiced",
"type", "import_field" ),
"import_field5", new XVar( "field", "base_grand_total",
"type", "import_field" ),
"import_field6", new XVar( "field", "base_discount_tax_compensation_amount",
"type", "import_field" ),
"import_field7", new XVar( "field", "base_discount_tax_compensation_invoiced",
"type", "import_field" ),
"import_field8", new XVar( "field", "base_shipping_amount",
"type", "import_field" ),
"import_field9", new XVar( "field", "base_shipping_discount_amount",
"type", "import_field" ),
"import_field10", new XVar( "field", "base_shipping_discount_tax_compensation_amnt",
"type", "import_field" ),
"import_field11", new XVar( "field", "base_shipping_incl_tax",
"type", "import_field" ),
"import_field12", new XVar( "field", "base_shipping_invoiced",
"type", "import_field" ),
"import_field13", new XVar( "field", "base_shipping_tax_amount",
"type", "import_field" ),
"import_field14", new XVar( "field", "base_subtotal",
"type", "import_field" ),
"import_field15", new XVar( "field", "base_subtotal_incl_tax",
"type", "import_field" ),
"import_field16", new XVar( "field", "base_subtotal_invoiced",
"type", "import_field" ),
"import_field17", new XVar( "field", "base_tax_amount",
"type", "import_field" ),
"import_field18", new XVar( "field", "base_tax_invoiced",
"type", "import_field" ),
"import_field19", new XVar( "field", "base_total_due",
"type", "import_field" ),
"import_field20", new XVar( "field", "base_total_invoiced",
"type", "import_field" ),
"import_field21", new XVar( "field", "base_total_invoiced_cost",
"type", "import_field" ),
"import_field22", new XVar( "field", "base_total_paid",
"type", "import_field" ),
"import_field23", new XVar( "field", "base_to_global_rate",
"type", "import_field" ),
"import_field24", new XVar( "field", "base_to_order_rate",
"type", "import_field" ),
"import_field25", new XVar( "field", "billing_address_id",
"type", "import_field" ),
"import_field26", new XVar( "field", "created_at",
"type", "import_field" ),
"import_field27", new XVar( "field", "customer_email",
"type", "import_field" ),
"import_field28", new XVar( "field", "customer_firstname",
"type", "import_field" ),
"import_field29", new XVar( "field", "customer_is_guest",
"type", "import_field" ),
"import_field30", new XVar( "field", "customer_lastname",
"type", "import_field" ),
"import_field31", new XVar( "field", "customer_note_notify",
"type", "import_field" ),
"import_field32", new XVar( "field", "discount_amount",
"type", "import_field" ),
"import_field33", new XVar( "field", "discount_invoiced",
"type", "import_field" ),
"import_field34", new XVar( "field", "email_sent",
"type", "import_field" ),
"import_field35", new XVar( "field", "entity_id",
"type", "import_field" ),
"import_field36", new XVar( "field", "global_currency_code",
"type", "import_field" ),
"import_field37", new XVar( "field", "grand_total",
"type", "import_field" ),
"import_field38", new XVar( "field", "discount_tax_compensation_amount",
"type", "import_field" ),
"import_field39", new XVar( "field", "discount_tax_compensation_invoiced",
"type", "import_field" ),
"import_field40", new XVar( "field", "increment_id",
"type", "import_field" ),
"import_field41", new XVar( "field", "is_virtual",
"type", "import_field" ),
"import_field42", new XVar( "field", "order_currency_code",
"type", "import_field" ),
"import_field43", new XVar( "field", "protect_code",
"type", "import_field" ),
"import_field44", new XVar( "field", "quote_id",
"type", "import_field" ),
"import_field45", new XVar( "field", "remote_ip",
"type", "import_field" ),
"import_field46", new XVar( "field", "shipping_amount",
"type", "import_field" ),
"import_field47", new XVar( "field", "shipping_description",
"type", "import_field" ),
"import_field48", new XVar( "field", "shipping_discount_amount",
"type", "import_field" ),
"import_field49", new XVar( "field", "shipping_discount_tax_compensation_amount",
"type", "import_field" ),
"import_field50", new XVar( "field", "shipping_incl_tax",
"type", "import_field" ),
"import_field51", new XVar( "field", "shipping_invoiced",
"type", "import_field" ),
"import_field52", new XVar( "field", "shipping_tax_amount",
"type", "import_field" ),
"import_field53", new XVar( "field", "state",
"type", "import_field" ),
"import_field54", new XVar( "field", "status",
"type", "import_field" ),
"import_field55", new XVar( "field", "store_currency_code",
"type", "import_field" ),
"import_field56", new XVar( "field", "store_id",
"type", "import_field" ),
"import_field57", new XVar( "field", "store_name",
"type", "import_field" ),
"import_field58", new XVar( "field", "store_to_base_rate",
"type", "import_field" ),
"import_field59", new XVar( "field", "store_to_order_rate",
"type", "import_field" ),
"import_field60", new XVar( "field", "subtotal",
"type", "import_field" ),
"import_field61", new XVar( "field", "subtotal_incl_tax",
"type", "import_field" ),
"import_field62", new XVar( "field", "subtotal_invoiced",
"type", "import_field" ),
"import_field63", new XVar( "field", "tax_amount",
"type", "import_field" ),
"import_field64", new XVar( "field", "tax_invoiced",
"type", "import_field" ),
"import_field65", new XVar( "field", "total_due",
"type", "import_field" ),
"import_field66", new XVar( "field", "total_invoiced",
"type", "import_field" ),
"import_field67", new XVar( "field", "total_item_count",
"type", "import_field" ),
"import_field68", new XVar( "field", "total_paid",
"type", "import_field" ),
"import_field69", new XVar( "field", "total_qty_ordered",
"type", "import_field" ),
"import_field70", new XVar( "field", "updated_at",
"type", "import_field" ),
"import_field71", new XVar( "field", "customer_id",
"type", "import_field" ),
"import_field72", new XVar( "field", "co_num",
"type", "import_field" ),
"import_field73", new XVar( "field", "json_data",
"type", "import_field" ),
"import_field74", new XVar( "field", "line",
"type", "import_field" ),
"import_field75", new XVar( "field", "posted",
"type", "import_field" ),
"import_field76", new XVar( "field", "cust_num",
"type", "import_field" ),
"import_field77", new XVar( "field", "cust_seq",
"type", "import_field" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}