
		// dbo.mg_order_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_mg_order_mst_view
			{
				static public XVar options()
				{
					return new XVar( "pdf", new XVar( "pdfView", false ),
"details", new XVar( "dbo.mg_order_line_mst", new XVar( "displayPreview", 2,
"previewPageId", "" ),
"dbo.mg_order_lines_mst", new XVar( "displayPreview", 1 ) ),
"fields", new XVar( "gridFields", new XVar( 0, "clientid",
1, "site_ref",
2, "co_num",
3, "base_currency_code",
4, "base_discount_amount",
5, "base_discount_invoiced",
6, "base_grand_total",
7, "base_discount_tax_compensation_amount",
8, "base_discount_tax_compensation_invoiced",
9, "base_shipping_amount",
10, "base_shipping_discount_amount",
11, "base_shipping_discount_tax_compensation_amnt",
12, "base_shipping_incl_tax",
13, "base_shipping_invoiced",
14, "base_shipping_tax_amount",
15, "base_subtotal",
16, "base_subtotal_incl_tax",
17, "base_subtotal_invoiced",
18, "base_tax_amount",
19, "base_tax_invoiced",
20, "base_total_due",
21, "base_total_invoiced",
22, "base_total_invoiced_cost",
23, "base_total_paid",
24, "base_to_global_rate",
25, "base_to_order_rate",
26, "billing_address_id",
27, "created_at",
28, "customer_email",
29, "customer_firstname",
30, "customer_is_guest",
31, "customer_lastname",
32, "customer_note_notify",
33, "discount_amount",
34, "discount_invoiced",
35, "email_sent",
36, "entity_id",
37, "global_currency_code",
38, "grand_total",
39, "discount_tax_compensation_amount",
40, "increment_id",
41, "is_virtual",
42, "order_currency_code",
43, "protect_code",
44, "quote_id",
45, "remote_ip",
46, "shipping_amount",
47, "shipping_description",
48, "shipping_discount_amount",
49, "shipping_discount_tax_compensation_amount",
50, "shipping_incl_tax",
51, "shipping_invoiced",
52, "shipping_tax_amount",
53, "state",
54, "status",
55, "store_currency_code",
56, "store_id",
57, "store_name",
58, "store_to_base_rate",
59, "store_to_order_rate",
60, "subtotal",
61, "subtotal_incl_tax",
62, "subtotal_invoiced",
63, "tax_amount",
64, "tax_invoiced",
65, "total_due",
66, "total_invoiced",
67, "total_item_count",
68, "total_paid",
69, "total_qty_ordered",
70, "updated_at",
71, "customer_id",
72, "json_data",
73, "line",
74, "posted",
75, "cust_num",
76, "cust_seq" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "clientid", new XVar( 0, "integrated_edit_field" ),
"site_ref", new XVar( 0, "integrated_edit_field1" ),
"co_num", new XVar( 0, "integrated_edit_field2" ),
"base_currency_code", new XVar( 0, "integrated_edit_field3" ),
"base_discount_amount", new XVar( 0, "integrated_edit_field4" ),
"base_discount_invoiced", new XVar( 0, "integrated_edit_field5" ),
"base_grand_total", new XVar( 0, "integrated_edit_field6" ),
"base_discount_tax_compensation_amount", new XVar( 0, "integrated_edit_field7" ),
"base_discount_tax_compensation_invoiced", new XVar( 0, "integrated_edit_field8" ),
"base_shipping_amount", new XVar( 0, "integrated_edit_field9" ),
"base_shipping_discount_amount", new XVar( 0, "integrated_edit_field10" ),
"base_shipping_discount_tax_compensation_amnt", new XVar( 0, "integrated_edit_field11" ),
"base_shipping_incl_tax", new XVar( 0, "integrated_edit_field12" ),
"base_shipping_invoiced", new XVar( 0, "integrated_edit_field13" ),
"base_shipping_tax_amount", new XVar( 0, "integrated_edit_field14" ),
"base_subtotal", new XVar( 0, "integrated_edit_field15" ),
"base_subtotal_incl_tax", new XVar( 0, "integrated_edit_field16" ),
"base_subtotal_invoiced", new XVar( 0, "integrated_edit_field17" ),
"base_tax_amount", new XVar( 0, "integrated_edit_field18" ),
"base_tax_invoiced", new XVar( 0, "integrated_edit_field19" ),
"base_total_due", new XVar( 0, "integrated_edit_field20" ),
"base_total_invoiced", new XVar( 0, "integrated_edit_field21" ),
"base_total_invoiced_cost", new XVar( 0, "integrated_edit_field22" ),
"base_total_paid", new XVar( 0, "integrated_edit_field23" ),
"base_to_global_rate", new XVar( 0, "integrated_edit_field24" ),
"base_to_order_rate", new XVar( 0, "integrated_edit_field25" ),
"billing_address_id", new XVar( 0, "integrated_edit_field26" ),
"created_at", new XVar( 0, "integrated_edit_field27" ),
"customer_email", new XVar( 0, "integrated_edit_field28" ),
"customer_firstname", new XVar( 0, "integrated_edit_field29" ),
"customer_is_guest", new XVar( 0, "integrated_edit_field30" ),
"customer_lastname", new XVar( 0, "integrated_edit_field31" ),
"customer_note_notify", new XVar( 0, "integrated_edit_field32" ),
"discount_amount", new XVar( 0, "integrated_edit_field33" ),
"discount_invoiced", new XVar( 0, "integrated_edit_field34" ),
"email_sent", new XVar( 0, "integrated_edit_field35" ),
"entity_id", new XVar( 0, "integrated_edit_field36" ),
"global_currency_code", new XVar( 0, "integrated_edit_field37" ),
"grand_total", new XVar( 0, "integrated_edit_field38" ),
"discount_tax_compensation_amount", new XVar( 0, "integrated_edit_field39" ),
"increment_id", new XVar( 0, "integrated_edit_field41" ),
"is_virtual", new XVar( 0, "integrated_edit_field42" ),
"order_currency_code", new XVar( 0, "integrated_edit_field43" ),
"protect_code", new XVar( 0, "integrated_edit_field44" ),
"quote_id", new XVar( 0, "integrated_edit_field45" ),
"remote_ip", new XVar( 0, "integrated_edit_field46" ),
"shipping_amount", new XVar( 0, "integrated_edit_field47" ),
"shipping_description", new XVar( 0, "integrated_edit_field48" ),
"shipping_discount_amount", new XVar( 0, "integrated_edit_field49" ),
"shipping_discount_tax_compensation_amount", new XVar( 0, "integrated_edit_field50" ),
"shipping_incl_tax", new XVar( 0, "integrated_edit_field51" ),
"shipping_invoiced", new XVar( 0, "integrated_edit_field52" ),
"shipping_tax_amount", new XVar( 0, "integrated_edit_field53" ),
"state", new XVar( 0, "integrated_edit_field54" ),
"status", new XVar( 0, "integrated_edit_field55" ),
"store_currency_code", new XVar( 0, "integrated_edit_field56" ),
"store_id", new XVar( 0, "integrated_edit_field57" ),
"store_name", new XVar( 0, "integrated_edit_field58" ),
"store_to_base_rate", new XVar( 0, "integrated_edit_field59" ),
"store_to_order_rate", new XVar( 0, "integrated_edit_field60" ),
"subtotal", new XVar( 0, "integrated_edit_field61" ),
"subtotal_incl_tax", new XVar( 0, "integrated_edit_field62" ),
"subtotal_invoiced", new XVar( 0, "integrated_edit_field63" ),
"tax_amount", new XVar( 0, "integrated_edit_field64" ),
"tax_invoiced", new XVar( 0, "integrated_edit_field65" ),
"total_due", new XVar( 0, "integrated_edit_field66" ),
"total_invoiced", new XVar( 0, "integrated_edit_field67" ),
"total_item_count", new XVar( 0, "integrated_edit_field68" ),
"total_paid", new XVar( 0, "integrated_edit_field69" ),
"total_qty_ordered", new XVar( 0, "integrated_edit_field70" ),
"updated_at", new XVar( 0, "integrated_edit_field71" ),
"customer_id", new XVar( 0, "integrated_edit_field72" ),
"json_data", new XVar( 0, "integrated_edit_field73" ),
"line", new XVar( 0, "integrated_edit_field74" ),
"posted", new XVar( 0, "integrated_edit_field75" ),
"cust_num", new XVar( 0, "integrated_edit_field40" ),
"cust_seq", new XVar( 0, "integrated_edit_field76" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "view_back_list",
1, "view_close" ),
"top", new XVar( 0, "view_header" ),
"grid", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field41",
41, "integrated_edit_field42",
42, "integrated_edit_field43",
43, "integrated_edit_field44",
44, "integrated_edit_field45",
45, "integrated_edit_field46",
46, "integrated_edit_field47",
47, "integrated_edit_field48",
48, "integrated_edit_field49",
49, "integrated_edit_field50",
50, "integrated_edit_field51",
51, "integrated_edit_field52",
52, "integrated_edit_field53",
53, "integrated_edit_field54",
54, "integrated_edit_field55",
55, "integrated_edit_field56",
56, "integrated_edit_field57",
57, "integrated_edit_field58",
58, "integrated_edit_field59",
59, "integrated_edit_field60",
60, "integrated_edit_field61",
61, "integrated_edit_field62",
62, "integrated_edit_field63",
63, "integrated_edit_field64",
64, "integrated_edit_field65",
65, "integrated_edit_field66",
66, "integrated_edit_field67",
67, "integrated_edit_field68",
68, "integrated_edit_field69",
69, "integrated_edit_field70",
70, "integrated_edit_field71",
71, "integrated_edit_field72",
72, "integrated_edit_field73",
73, "integrated_edit_field74",
74, "details_preview",
75, "integrated_edit_field75",
76, "integrated_edit_field40",
77, "integrated_edit_field76" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "back_button",
1, "close_button" ) ),
"itemForms", new XVar( "view_back_list", "below-grid",
"view_close", "below-grid",
"view_header", "top",
"integrated_edit_field", "grid",
"integrated_edit_field1", "grid",
"integrated_edit_field2", "grid",
"integrated_edit_field3", "grid",
"integrated_edit_field4", "grid",
"integrated_edit_field5", "grid",
"integrated_edit_field6", "grid",
"integrated_edit_field7", "grid",
"integrated_edit_field8", "grid",
"integrated_edit_field9", "grid",
"integrated_edit_field10", "grid",
"integrated_edit_field11", "grid",
"integrated_edit_field12", "grid",
"integrated_edit_field13", "grid",
"integrated_edit_field14", "grid",
"integrated_edit_field15", "grid",
"integrated_edit_field16", "grid",
"integrated_edit_field17", "grid",
"integrated_edit_field18", "grid",
"integrated_edit_field19", "grid",
"integrated_edit_field20", "grid",
"integrated_edit_field21", "grid",
"integrated_edit_field22", "grid",
"integrated_edit_field23", "grid",
"integrated_edit_field24", "grid",
"integrated_edit_field25", "grid",
"integrated_edit_field26", "grid",
"integrated_edit_field27", "grid",
"integrated_edit_field28", "grid",
"integrated_edit_field29", "grid",
"integrated_edit_field30", "grid",
"integrated_edit_field31", "grid",
"integrated_edit_field32", "grid",
"integrated_edit_field33", "grid",
"integrated_edit_field34", "grid",
"integrated_edit_field35", "grid",
"integrated_edit_field36", "grid",
"integrated_edit_field37", "grid",
"integrated_edit_field38", "grid",
"integrated_edit_field39", "grid",
"integrated_edit_field41", "grid",
"integrated_edit_field42", "grid",
"integrated_edit_field43", "grid",
"integrated_edit_field44", "grid",
"integrated_edit_field45", "grid",
"integrated_edit_field46", "grid",
"integrated_edit_field47", "grid",
"integrated_edit_field48", "grid",
"integrated_edit_field49", "grid",
"integrated_edit_field50", "grid",
"integrated_edit_field51", "grid",
"integrated_edit_field52", "grid",
"integrated_edit_field53", "grid",
"integrated_edit_field54", "grid",
"integrated_edit_field55", "grid",
"integrated_edit_field56", "grid",
"integrated_edit_field57", "grid",
"integrated_edit_field58", "grid",
"integrated_edit_field59", "grid",
"integrated_edit_field60", "grid",
"integrated_edit_field61", "grid",
"integrated_edit_field62", "grid",
"integrated_edit_field63", "grid",
"integrated_edit_field64", "grid",
"integrated_edit_field65", "grid",
"integrated_edit_field66", "grid",
"integrated_edit_field67", "grid",
"integrated_edit_field68", "grid",
"integrated_edit_field69", "grid",
"integrated_edit_field70", "grid",
"integrated_edit_field71", "grid",
"integrated_edit_field72", "grid",
"integrated_edit_field73", "grid",
"integrated_edit_field74", "grid",
"details_preview", "grid",
"integrated_edit_field75", "grid",
"integrated_edit_field40", "grid",
"integrated_edit_field76", "grid" ),
"itemLocations", new XVar( "integrated_edit_field", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field1", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field2", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field3", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field4", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field5", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field6", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field7", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field8", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field9", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field10", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field11", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field12", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field13", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field14", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field15", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field16", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field17", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field18", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field19", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field20", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field21", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field22", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field23", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field24", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field25", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field26", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field27", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field28", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field29", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field30", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field31", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field32", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field33", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field34", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field35", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field36", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field37", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field38", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field39", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field41", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field42", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field43", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field44", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field45", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field46", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field47", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field48", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field49", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field50", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field51", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field52", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field53", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field54", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field55", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field56", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field57", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field58", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field59", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field60", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field61", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field62", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field63", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field64", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field65", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field66", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field67", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field68", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field69", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field70", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field71", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field72", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field73", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field74", new XVar( "location", "grid",
"cellId", "c3" ),
"details_preview", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field75", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field40", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field76", new XVar( "location", "grid",
"cellId", "c3" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "view_header", new XVar( 0, "view_header" ),
"view_back_list", new XVar( 0, "view_back_list" ),
"view_close", new XVar( 0, "view_close" ),
"integrated_edit_field", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field41",
41, "integrated_edit_field42",
42, "integrated_edit_field43",
43, "integrated_edit_field44",
44, "integrated_edit_field45",
45, "integrated_edit_field46",
46, "integrated_edit_field47",
47, "integrated_edit_field48",
48, "integrated_edit_field49",
49, "integrated_edit_field50",
50, "integrated_edit_field51",
51, "integrated_edit_field52",
52, "integrated_edit_field53",
53, "integrated_edit_field54",
54, "integrated_edit_field55",
55, "integrated_edit_field56",
56, "integrated_edit_field57",
57, "integrated_edit_field58",
58, "integrated_edit_field59",
59, "integrated_edit_field60",
60, "integrated_edit_field61",
61, "integrated_edit_field62",
62, "integrated_edit_field63",
63, "integrated_edit_field64",
64, "integrated_edit_field65",
65, "integrated_edit_field66",
66, "integrated_edit_field67",
67, "integrated_edit_field68",
68, "integrated_edit_field69",
69, "integrated_edit_field70",
70, "integrated_edit_field71",
71, "integrated_edit_field72",
72, "integrated_edit_field73",
73, "integrated_edit_field74",
74, "integrated_edit_field75",
75, "integrated_edit_field40",
76, "integrated_edit_field76" ),
"details_preview", new XVar( 0, "details_preview" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field41",
41, "integrated_edit_field42",
42, "integrated_edit_field43",
43, "integrated_edit_field44",
44, "integrated_edit_field45",
45, "integrated_edit_field46",
46, "integrated_edit_field47",
47, "integrated_edit_field48",
48, "integrated_edit_field49",
49, "integrated_edit_field50",
50, "integrated_edit_field51",
51, "integrated_edit_field52",
52, "integrated_edit_field53",
53, "integrated_edit_field54",
54, "integrated_edit_field55",
55, "integrated_edit_field56",
56, "integrated_edit_field57",
57, "integrated_edit_field58",
58, "integrated_edit_field59",
59, "integrated_edit_field60",
60, "integrated_edit_field61",
61, "integrated_edit_field62",
62, "integrated_edit_field63",
63, "integrated_edit_field64",
64, "integrated_edit_field65",
65, "integrated_edit_field66",
66, "integrated_edit_field67",
67, "integrated_edit_field68",
68, "integrated_edit_field69",
69, "integrated_edit_field70",
70, "integrated_edit_field71",
71, "integrated_edit_field72",
72, "integrated_edit_field73",
73, "integrated_edit_field74",
74, "details_preview",
75, "integrated_edit_field75",
76, "integrated_edit_field40",
77, "integrated_edit_field76" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "view",
"breadcrumb", false,
"nextPrev", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "view",
"type", "view",
"layoutId", "nomenu",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "view-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1",
"colspan", 2 ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "view-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_back_list",
1, "view_close" ) ),
"c2", new XVar( "model", "c2",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "view-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ) ),
"section", "" ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field41",
41, "integrated_edit_field42",
42, "integrated_edit_field43",
43, "integrated_edit_field44",
44, "integrated_edit_field45",
45, "integrated_edit_field46",
46, "integrated_edit_field47",
47, "integrated_edit_field48",
48, "integrated_edit_field49",
49, "integrated_edit_field50",
50, "integrated_edit_field51",
51, "integrated_edit_field52",
52, "integrated_edit_field53",
53, "integrated_edit_field54",
54, "integrated_edit_field55",
55, "integrated_edit_field56",
56, "integrated_edit_field57",
57, "integrated_edit_field58",
58, "integrated_edit_field59",
59, "integrated_edit_field60",
60, "integrated_edit_field61",
61, "integrated_edit_field62",
62, "integrated_edit_field63",
63, "integrated_edit_field64",
64, "integrated_edit_field65",
65, "integrated_edit_field66",
66, "integrated_edit_field67",
67, "integrated_edit_field68",
68, "integrated_edit_field69",
69, "integrated_edit_field70",
70, "integrated_edit_field71",
71, "integrated_edit_field72",
72, "integrated_edit_field73",
73, "integrated_edit_field74",
74, "details_preview",
75, "integrated_edit_field75",
76, "integrated_edit_field40",
77, "integrated_edit_field76" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ) ),
"items", new XVar( "view_header", new XVar( "type", "view_header" ),
"view_back_list", new XVar( "type", "view_back_list" ),
"view_close", new XVar( "type", "view_close" ),
"integrated_edit_field", new XVar( "field", "clientid",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field1", new XVar( "field", "site_ref",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field2", new XVar( "field", "co_num",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field3", new XVar( "field", "base_currency_code",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field4", new XVar( "field", "base_discount_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field5", new XVar( "field", "base_discount_invoiced",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field6", new XVar( "field", "base_grand_total",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field7", new XVar( "field", "base_discount_tax_compensation_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field8", new XVar( "field", "base_discount_tax_compensation_invoiced",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field9", new XVar( "field", "base_shipping_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field10", new XVar( "field", "base_shipping_discount_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field11", new XVar( "field", "base_shipping_discount_tax_compensation_amnt",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field12", new XVar( "field", "base_shipping_incl_tax",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field13", new XVar( "field", "base_shipping_invoiced",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field14", new XVar( "field", "base_shipping_tax_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field15", new XVar( "field", "base_subtotal",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field16", new XVar( "field", "base_subtotal_incl_tax",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field17", new XVar( "field", "base_subtotal_invoiced",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field18", new XVar( "field", "base_tax_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field19", new XVar( "field", "base_tax_invoiced",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field20", new XVar( "field", "base_total_due",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field21", new XVar( "field", "base_total_invoiced",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field22", new XVar( "field", "base_total_invoiced_cost",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field23", new XVar( "field", "base_total_paid",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field24", new XVar( "field", "base_to_global_rate",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field25", new XVar( "field", "base_to_order_rate",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field26", new XVar( "field", "billing_address_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field27", new XVar( "field", "created_at",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field28", new XVar( "field", "customer_email",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field29", new XVar( "field", "customer_firstname",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field30", new XVar( "field", "customer_is_guest",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field31", new XVar( "field", "customer_lastname",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field32", new XVar( "field", "customer_note_notify",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field33", new XVar( "field", "discount_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field34", new XVar( "field", "discount_invoiced",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field35", new XVar( "field", "email_sent",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field36", new XVar( "field", "entity_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field37", new XVar( "field", "global_currency_code",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field38", new XVar( "field", "grand_total",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field39", new XVar( "field", "discount_tax_compensation_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field41", new XVar( "field", "increment_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field42", new XVar( "field", "is_virtual",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field43", new XVar( "field", "order_currency_code",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field44", new XVar( "field", "protect_code",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field45", new XVar( "field", "quote_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field46", new XVar( "field", "remote_ip",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field47", new XVar( "field", "shipping_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field48", new XVar( "field", "shipping_description",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field49", new XVar( "field", "shipping_discount_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field50", new XVar( "field", "shipping_discount_tax_compensation_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field51", new XVar( "field", "shipping_incl_tax",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field52", new XVar( "field", "shipping_invoiced",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field53", new XVar( "field", "shipping_tax_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field54", new XVar( "field", "state",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field55", new XVar( "field", "status",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field56", new XVar( "field", "store_currency_code",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field57", new XVar( "field", "store_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field58", new XVar( "field", "store_name",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field59", new XVar( "field", "store_to_base_rate",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field60", new XVar( "field", "store_to_order_rate",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field61", new XVar( "field", "subtotal",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field62", new XVar( "field", "subtotal_incl_tax",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field63", new XVar( "field", "subtotal_invoiced",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field64", new XVar( "field", "tax_amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field65", new XVar( "field", "tax_invoiced",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field66", new XVar( "field", "total_due",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field67", new XVar( "field", "total_invoiced",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field68", new XVar( "field", "total_item_count",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field69", new XVar( "field", "total_paid",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field70", new XVar( "field", "total_qty_ordered",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field71", new XVar( "field", "updated_at",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field72", new XVar( "field", "customer_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field73", new XVar( "field", "json_data",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field74", new XVar( "field", "line",
"type", "integrated_edit_field",
"orientation", 0 ),
"details_preview", new XVar( "type", "details_preview",
"table", "dbo.mg_order_lines_mst",
"items", XVar.Array(),
"popup", false ),
"integrated_edit_field75", new XVar( "field", "posted",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field40", new XVar( "field", "cust_num",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field76", new XVar( "field", "cust_seq",
"type", "integrated_edit_field",
"orientation", 0 ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}