
		// dbo.mg_order_line_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_mg_order_line_mst_export
			{
				static public XVar options()
				{
					return new XVar( "totals", new XVar( "clientid", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"increment_id", new XVar( "totalsType", "" ),
"store_id", new XVar( "totalsType", "" ),
"item_id", new XVar( "totalsType", "" ),
"sku", new XVar( "totalsType", "" ),
"qty_ordered", new XVar( "totalsType", "" ),
"row_total", new XVar( "totalsType", "" ),
"discount_amount", new XVar( "totalsType", "" ),
"price", new XVar( "totalsType", "" ),
"original_price", new XVar( "totalsType", "" ),
"qty_shipped", new XVar( "totalsType", "" ),
"qty_canceled", new XVar( "totalsType", "" ),
"product_option", new XVar( "totalsType", "" ),
"name", new XVar( "totalsType", "" ),
"product_type", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "clientid",
1, "site_ref",
2, "increment_id",
3, "store_id",
4, "item_id",
5, "sku",
6, "qty_ordered",
7, "row_total",
8, "discount_amount",
9, "price",
10, "original_price",
11, "qty_shipped",
12, "qty_canceled",
13, "product_option",
14, "name",
15, "product_type" ),
"exportFields", new XVar( 0, "clientid",
1, "site_ref",
2, "increment_id",
3, "store_id",
4, "item_id",
5, "sku",
6, "qty_ordered",
7, "row_total",
8, "discount_amount",
9, "price",
10, "original_price",
11, "qty_shipped",
12, "qty_canceled",
13, "product_option",
14, "name",
15, "product_type" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "clientid", new XVar( 0, "export_field" ),
"site_ref", new XVar( 0, "export_field1" ),
"increment_id", new XVar( 0, "export_field2" ),
"store_id", new XVar( 0, "export_field3" ),
"item_id", new XVar( 0, "export_field4" ),
"sku", new XVar( 0, "export_field5" ),
"qty_ordered", new XVar( 0, "export_field6" ),
"row_total", new XVar( 0, "export_field7" ),
"discount_amount", new XVar( 0, "export_field8" ),
"price", new XVar( 0, "export_field9" ),
"original_price", new XVar( 0, "export_field10" ),
"qty_shipped", new XVar( 0, "export_field11" ),
"qty_canceled", new XVar( 0, "export_field12" ),
"product_option", new XVar( 0, "export_field13" ),
"name", new XVar( 0, "export_field14" ),
"product_type", new XVar( 0, "export_field15" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "export_header" ),
"grid", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field3",
4, "export_field4",
5, "export_field5",
6, "export_field6",
7, "export_field7",
8, "export_field8",
9, "export_field9",
10, "export_field10",
11, "export_field11",
12, "export_field12",
13, "export_field13",
14, "export_field14",
15, "export_field15" ),
"footer", new XVar( 0, "export_export",
1, "export_cancel" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "export_header", "top",
"export_field", "grid",
"export_field1", "grid",
"export_field2", "grid",
"export_field3", "grid",
"export_field4", "grid",
"export_field5", "grid",
"export_field6", "grid",
"export_field7", "grid",
"export_field8", "grid",
"export_field9", "grid",
"export_field10", "grid",
"export_field11", "grid",
"export_field12", "grid",
"export_field13", "grid",
"export_field14", "grid",
"export_field15", "grid",
"export_export", "footer",
"export_cancel", "footer" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "export_header", new XVar( 0, "export_header" ),
"export_export", new XVar( 0, "export_export" ),
"export_cancel", new XVar( 0, "export_cancel" ),
"export_field", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field3",
4, "export_field4",
5, "export_field5",
6, "export_field6",
7, "export_field7",
8, "export_field8",
9, "export_field9",
10, "export_field10",
11, "export_field11",
12, "export_field12",
13, "export_field13",
14, "export_field14",
15, "export_field15" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"export", new XVar( "format", 2,
"selectFields", false,
"delimiter", ",",
"selectDelimiter", false,
"exportFileTypes", new XVar( "excel", true,
"word", true,
"csv", true,
"xml", false ) ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "export",
"type", "export",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "export-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "export-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field3",
4, "export_field4",
5, "export_field5",
6, "export_field6",
7, "export_field7",
8, "export_field8",
9, "export_field9",
10, "export_field10",
11, "export_field11",
12, "export_field12",
13, "export_field13",
14, "export_field14",
15, "export_field15" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"footer", new XVar( "modelId", "export-footer",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "export_export",
1, "export_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "export_header", new XVar( "type", "export_header" ),
"export_export", new XVar( "type", "export_export" ),
"export_cancel", new XVar( "type", "export_cancel" ),
"export_field", new XVar( "field", "clientid",
"type", "export_field" ),
"export_field1", new XVar( "field", "site_ref",
"type", "export_field" ),
"export_field2", new XVar( "field", "increment_id",
"type", "export_field" ),
"export_field3", new XVar( "field", "store_id",
"type", "export_field" ),
"export_field4", new XVar( "field", "item_id",
"type", "export_field" ),
"export_field5", new XVar( "field", "sku",
"type", "export_field" ),
"export_field6", new XVar( "field", "qty_ordered",
"type", "export_field" ),
"export_field7", new XVar( "field", "row_total",
"type", "export_field" ),
"export_field8", new XVar( "field", "discount_amount",
"type", "export_field" ),
"export_field9", new XVar( "field", "price",
"type", "export_field" ),
"export_field10", new XVar( "field", "original_price",
"type", "export_field" ),
"export_field11", new XVar( "field", "qty_shipped",
"type", "export_field" ),
"export_field12", new XVar( "field", "qty_canceled",
"type", "export_field" ),
"export_field13", new XVar( "field", "product_option",
"type", "export_field" ),
"export_field14", new XVar( "field", "name",
"type", "export_field" ),
"export_field15", new XVar( "field", "product_type",
"type", "export_field" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1,
"exportFormat", 2,
"exportDelimiter", ",",
"exportSelectDelimiter", false,
"exportSelectFields", false );
				}
			}
		}