
		// dbo.mg_orderline_count Report
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_mg_orderline_count_report_rprint
			{
				static public XVar options()
				{
					return new XVar( "pdf", new XVar( "pdfView", false ),
"fields", new XVar( "gridFields", new XVar( 0, "cnt" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "cnt", new XVar( 0, "report_grid_field1" ),
"yy", new XVar( 0, "report_group_field" ),
"mm", new XVar( 0, "report_group_field1" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "print_pages" ),
"below-grid", XVar.Array(),
"top", new XVar( 0, "print_header",
1, "print_subheader" ),
"grid", new XVar( 0, "report_group_field",
1, "report_group_field1",
2, "report_grid_field1" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "print_pages" ),
"below-grid", XVar.Array() ),
"itemForms", new XVar( "print_pages", "above-grid",
"print_header", "top",
"print_subheader", "top",
"report_group_field", "grid",
"report_group_field1", "grid",
"report_grid_field1", "grid" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "print_header", new XVar( 0, "print_header" ),
"print_subheader", new XVar( 0, "print_subheader" ),
"print_pages", new XVar( 0, "print_pages" ),
"report_grid_field", new XVar( 0, "report_grid_field1" ),
"report_group_field", new XVar( 0, "report_group_field",
1, "report_group_field1" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar( "print_pages", new XVar( "tag", "PRINT_PAGES",
"type", 2 ) ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "rprint",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"newreport", new XVar( "reportInfo", new XVar( "groupFields", new XVar( 0, new XVar( "interval", 0,
"summary", false,
"field", "yy",
"color", new XVar( "header", "7aca7a",
"summary", "90ee90" ),
"axis", 1 ),
1, new XVar( "interval", 0,
"summary", false,
"field", "mm",
"color", new XVar( "header", "93b8c4",
"summary", "add8e6" ),
"axis", 0 ) ),
"fields", new XVar( 0, new XVar( "field", "cnt",
"grid", true,
"avg", false,
"max", false,
"min", false,
"sum", true ) ),
"showData", true,
"pageSummary", false,
"globalSummary", false,
"crosstab", true,
"colors", XVar.Array(),
"horizSummary", true,
"layout", "plain",
"vertSummary", true ) ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "rprint",
"type", "rprint",
"layoutId", "basic",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "print-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "print_pages" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "print-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "print-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c2", new XVar( "model", "c2",
"items", new XVar( 0, "print_header",
1, "print_subheader" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "report-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "report_group_field",
1, "report_group_field1" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "report_grid_field1" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1,
"reportInfo", new XVar( "groupFields", new XVar( 0, new XVar( "interval", 0,
"summary", false,
"field", "yy",
"color", new XVar( "header", "7aca7a",
"summary", "90ee90" ),
"axis", 1 ),
1, new XVar( "interval", 0,
"summary", false,
"field", "mm",
"color", new XVar( "header", "93b8c4",
"summary", "add8e6" ),
"axis", 0 ) ),
"fields", new XVar( 0, new XVar( "field", "cnt",
"grid", true,
"avg", false,
"max", false,
"min", false,
"sum", true ) ),
"showData", true,
"pageSummary", false,
"globalSummary", false,
"crosstab", true,
"colors", XVar.Array(),
"horizSummary", true,
"layout", "plain",
"vertSummary", true ) ) ),
"items", new XVar( "print_header", new XVar( "type", "print_header" ),
"print_subheader", new XVar( "type", "print_subheader" ),
"print_pages", new XVar( "type", "print_pages" ),
"report_grid_field1", new XVar( "field", "cnt",
"type", "report_grid_field",
"reportAvg", false,
"reportMin", false,
"reportMax", false,
"reportSum", true ),
"report_group_field", new XVar( "field", "yy",
"type", "report_group_field",
"summary", false,
"axis", 1,
"interval", 0 ),
"report_group_field1", new XVar( "field", "mm",
"type", "report_group_field",
"summary", false,
"axis", 0,
"interval", 0 ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}