
		// dbo.sc_aptran_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_sc_aptran_mst_masterlist
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "site_ref",
1, "trans_num",
2, "type",
3, "vend_num",
4, "invoice_id",
5, "material",
6, "tax_amt",
7, "dist_date",
8, "vend_inv",
9, "inv_date",
10, "due_date",
11, "currency",
12, "num_lines",
13, "is_prepay",
14, "rowpointer",
15, "createdate",
16, "posted",
17, "postdate",
18, "err_msg",
19, "bill_url",
20, "terms_code",
21, "json_data",
22, "jresult",
23, "clientid",
24, "payer_entity_name",
25, "invoice_status",
26, "description",
27, "inv_internal_notes",
28, "po_num",
29, "approval_date",
30, "income_type",
31, "amt_due",
32, "freight",
33, "misc",
34, "total" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "site_ref", new XVar( 0, "simple_grid_field",
1, "simple_grid_field35" ),
"trans_num", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field36" ),
"type", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field37" ),
"vend_num", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field38" ),
"invoice_id", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field39" ),
"material", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field40" ),
"tax_amt", new XVar( 0, "simple_grid_field6",
1, "simple_grid_field41" ),
"dist_date", new XVar( 0, "simple_grid_field7",
1, "simple_grid_field42" ),
"vend_inv", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field43" ),
"inv_date", new XVar( 0, "simple_grid_field9",
1, "simple_grid_field44" ),
"due_date", new XVar( 0, "simple_grid_field10",
1, "simple_grid_field45" ),
"currency", new XVar( 0, "simple_grid_field11",
1, "simple_grid_field46" ),
"num_lines", new XVar( 0, "simple_grid_field12",
1, "simple_grid_field47" ),
"is_prepay", new XVar( 0, "simple_grid_field13",
1, "simple_grid_field48" ),
"rowpointer", new XVar( 0, "simple_grid_field14",
1, "simple_grid_field49" ),
"createdate", new XVar( 0, "simple_grid_field15",
1, "simple_grid_field50" ),
"posted", new XVar( 0, "simple_grid_field16",
1, "simple_grid_field51" ),
"postdate", new XVar( 0, "simple_grid_field17",
1, "simple_grid_field52" ),
"err_msg", new XVar( 0, "simple_grid_field18",
1, "simple_grid_field53" ),
"bill_url", new XVar( 0, "simple_grid_field19",
1, "simple_grid_field54" ),
"terms_code", new XVar( 0, "simple_grid_field20",
1, "simple_grid_field55" ),
"json_data", new XVar( 0, "simple_grid_field21",
1, "simple_grid_field56" ),
"jresult", new XVar( 0, "simple_grid_field22",
1, "simple_grid_field57" ),
"clientid", new XVar( 0, "simple_grid_field23",
1, "simple_grid_field58" ),
"payer_entity_name", new XVar( 0, "simple_grid_field24",
1, "simple_grid_field59" ),
"invoice_status", new XVar( 0, "simple_grid_field25",
1, "simple_grid_field60" ),
"description", new XVar( 0, "simple_grid_field26",
1, "simple_grid_field61" ),
"inv_internal_notes", new XVar( 0, "simple_grid_field27",
1, "simple_grid_field62" ),
"po_num", new XVar( 0, "simple_grid_field28",
1, "simple_grid_field63" ),
"approval_date", new XVar( 0, "simple_grid_field29",
1, "simple_grid_field64" ),
"income_type", new XVar( 0, "simple_grid_field30",
1, "simple_grid_field65" ),
"amt_due", new XVar( 0, "simple_grid_field31",
1, "simple_grid_field66" ),
"freight", new XVar( 0, "simple_grid_field32",
1, "simple_grid_field67" ),
"misc", new XVar( 0, "simple_grid_field33",
1, "simple_grid_field68" ),
"total", new XVar( 0, "simple_grid_field34",
1, "simple_grid_field69" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "inline_add" ),
"below-grid", XVar.Array(),
"top", new XVar( 0, "back_master",
1, "masterlist_header" ),
"grid", new XVar( 0, "simple_grid_field35",
1, "simple_grid_field",
2, "simple_grid_field36",
3, "simple_grid_field1",
4, "simple_grid_field37",
5, "simple_grid_field2",
6, "simple_grid_field38",
7, "simple_grid_field3",
8, "simple_grid_field39",
9, "simple_grid_field4",
10, "simple_grid_field40",
11, "simple_grid_field5",
12, "simple_grid_field41",
13, "simple_grid_field6",
14, "simple_grid_field42",
15, "simple_grid_field7",
16, "simple_grid_field43",
17, "simple_grid_field8",
18, "simple_grid_field44",
19, "simple_grid_field9",
20, "simple_grid_field45",
21, "simple_grid_field10",
22, "simple_grid_field46",
23, "simple_grid_field11",
24, "simple_grid_field47",
25, "simple_grid_field12",
26, "simple_grid_field48",
27, "simple_grid_field13",
28, "simple_grid_field49",
29, "simple_grid_field14",
30, "simple_grid_field50",
31, "simple_grid_field15",
32, "simple_grid_field51",
33, "simple_grid_field16",
34, "simple_grid_field52",
35, "simple_grid_field17",
36, "simple_grid_field53",
37, "simple_grid_field18",
38, "simple_grid_field54",
39, "simple_grid_field19",
40, "simple_grid_field55",
41, "simple_grid_field20",
42, "simple_grid_field56",
43, "simple_grid_field21",
44, "simple_grid_field57",
45, "simple_grid_field22",
46, "simple_grid_field58",
47, "simple_grid_field23",
48, "simple_grid_field59",
49, "simple_grid_field24",
50, "simple_grid_field60",
51, "simple_grid_field25",
52, "simple_grid_field61",
53, "simple_grid_field26",
54, "simple_grid_field62",
55, "simple_grid_field27",
56, "simple_grid_field63",
57, "simple_grid_field28",
58, "simple_grid_field64",
59, "simple_grid_field29",
60, "simple_grid_field65",
61, "simple_grid_field30",
62, "simple_grid_field66",
63, "simple_grid_field31",
64, "simple_grid_field67",
65, "simple_grid_field32",
66, "simple_grid_field68",
67, "simple_grid_field33",
68, "simple_grid_field69",
69, "simple_grid_field34",
70, "grid_inline_cancel" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "inlineadd_link" ),
"below-grid", XVar.Array() ),
"itemForms", new XVar( "inline_add", "above-grid",
"back_master", "top",
"masterlist_header", "top",
"simple_grid_field35", "grid",
"simple_grid_field", "grid",
"simple_grid_field36", "grid",
"simple_grid_field1", "grid",
"simple_grid_field37", "grid",
"simple_grid_field2", "grid",
"simple_grid_field38", "grid",
"simple_grid_field3", "grid",
"simple_grid_field39", "grid",
"simple_grid_field4", "grid",
"simple_grid_field40", "grid",
"simple_grid_field5", "grid",
"simple_grid_field41", "grid",
"simple_grid_field6", "grid",
"simple_grid_field42", "grid",
"simple_grid_field7", "grid",
"simple_grid_field43", "grid",
"simple_grid_field8", "grid",
"simple_grid_field44", "grid",
"simple_grid_field9", "grid",
"simple_grid_field45", "grid",
"simple_grid_field10", "grid",
"simple_grid_field46", "grid",
"simple_grid_field11", "grid",
"simple_grid_field47", "grid",
"simple_grid_field12", "grid",
"simple_grid_field48", "grid",
"simple_grid_field13", "grid",
"simple_grid_field49", "grid",
"simple_grid_field14", "grid",
"simple_grid_field50", "grid",
"simple_grid_field15", "grid",
"simple_grid_field51", "grid",
"simple_grid_field16", "grid",
"simple_grid_field52", "grid",
"simple_grid_field17", "grid",
"simple_grid_field53", "grid",
"simple_grid_field18", "grid",
"simple_grid_field54", "grid",
"simple_grid_field19", "grid",
"simple_grid_field55", "grid",
"simple_grid_field20", "grid",
"simple_grid_field56", "grid",
"simple_grid_field21", "grid",
"simple_grid_field57", "grid",
"simple_grid_field22", "grid",
"simple_grid_field58", "grid",
"simple_grid_field23", "grid",
"simple_grid_field59", "grid",
"simple_grid_field24", "grid",
"simple_grid_field60", "grid",
"simple_grid_field25", "grid",
"simple_grid_field61", "grid",
"simple_grid_field26", "grid",
"simple_grid_field62", "grid",
"simple_grid_field27", "grid",
"simple_grid_field63", "grid",
"simple_grid_field28", "grid",
"simple_grid_field64", "grid",
"simple_grid_field29", "grid",
"simple_grid_field65", "grid",
"simple_grid_field30", "grid",
"simple_grid_field66", "grid",
"simple_grid_field31", "grid",
"simple_grid_field67", "grid",
"simple_grid_field32", "grid",
"simple_grid_field68", "grid",
"simple_grid_field33", "grid",
"simple_grid_field69", "grid",
"simple_grid_field34", "grid",
"grid_inline_cancel", "grid" ),
"itemLocations", new XVar( "simple_grid_field35", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field36", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field37", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field38", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field39", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field40", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field41", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field42", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"simple_grid_field43", new XVar( "location", "grid",
"cellId", "headcell_field8" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "cell_field8" ),
"simple_grid_field44", new XVar( "location", "grid",
"cellId", "headcell_field9" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "cell_field9" ),
"simple_grid_field45", new XVar( "location", "grid",
"cellId", "headcell_field10" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "cell_field10" ),
"simple_grid_field46", new XVar( "location", "grid",
"cellId", "headcell_field11" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "cell_field11" ),
"simple_grid_field47", new XVar( "location", "grid",
"cellId", "headcell_field12" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "cell_field12" ),
"simple_grid_field48", new XVar( "location", "grid",
"cellId", "headcell_field13" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "cell_field13" ),
"simple_grid_field49", new XVar( "location", "grid",
"cellId", "headcell_field14" ),
"simple_grid_field14", new XVar( "location", "grid",
"cellId", "cell_field14" ),
"simple_grid_field50", new XVar( "location", "grid",
"cellId", "headcell_field15" ),
"simple_grid_field15", new XVar( "location", "grid",
"cellId", "cell_field15" ),
"simple_grid_field51", new XVar( "location", "grid",
"cellId", "headcell_field16" ),
"simple_grid_field16", new XVar( "location", "grid",
"cellId", "cell_field16" ),
"simple_grid_field52", new XVar( "location", "grid",
"cellId", "headcell_field17" ),
"simple_grid_field17", new XVar( "location", "grid",
"cellId", "cell_field17" ),
"simple_grid_field53", new XVar( "location", "grid",
"cellId", "headcell_field18" ),
"simple_grid_field18", new XVar( "location", "grid",
"cellId", "cell_field18" ),
"simple_grid_field54", new XVar( "location", "grid",
"cellId", "headcell_field19" ),
"simple_grid_field19", new XVar( "location", "grid",
"cellId", "cell_field19" ),
"simple_grid_field55", new XVar( "location", "grid",
"cellId", "headcell_field20" ),
"simple_grid_field20", new XVar( "location", "grid",
"cellId", "cell_field20" ),
"simple_grid_field56", new XVar( "location", "grid",
"cellId", "headcell_field21" ),
"simple_grid_field21", new XVar( "location", "grid",
"cellId", "cell_field21" ),
"simple_grid_field57", new XVar( "location", "grid",
"cellId", "headcell_field22" ),
"simple_grid_field22", new XVar( "location", "grid",
"cellId", "cell_field22" ),
"simple_grid_field58", new XVar( "location", "grid",
"cellId", "headcell_field23" ),
"simple_grid_field23", new XVar( "location", "grid",
"cellId", "cell_field23" ),
"simple_grid_field59", new XVar( "location", "grid",
"cellId", "headcell_field24" ),
"simple_grid_field24", new XVar( "location", "grid",
"cellId", "cell_field24" ),
"simple_grid_field60", new XVar( "location", "grid",
"cellId", "headcell_field25" ),
"simple_grid_field25", new XVar( "location", "grid",
"cellId", "cell_field25" ),
"simple_grid_field61", new XVar( "location", "grid",
"cellId", "headcell_field26" ),
"simple_grid_field26", new XVar( "location", "grid",
"cellId", "cell_field26" ),
"simple_grid_field62", new XVar( "location", "grid",
"cellId", "headcell_field27" ),
"simple_grid_field27", new XVar( "location", "grid",
"cellId", "cell_field27" ),
"simple_grid_field63", new XVar( "location", "grid",
"cellId", "headcell_field28" ),
"simple_grid_field28", new XVar( "location", "grid",
"cellId", "cell_field28" ),
"simple_grid_field64", new XVar( "location", "grid",
"cellId", "headcell_field29" ),
"simple_grid_field29", new XVar( "location", "grid",
"cellId", "cell_field29" ),
"simple_grid_field65", new XVar( "location", "grid",
"cellId", "headcell_field30" ),
"simple_grid_field30", new XVar( "location", "grid",
"cellId", "cell_field30" ),
"simple_grid_field66", new XVar( "location", "grid",
"cellId", "headcell_field31" ),
"simple_grid_field31", new XVar( "location", "grid",
"cellId", "cell_field31" ),
"simple_grid_field67", new XVar( "location", "grid",
"cellId", "headcell_field32" ),
"simple_grid_field32", new XVar( "location", "grid",
"cellId", "cell_field32" ),
"simple_grid_field68", new XVar( "location", "grid",
"cellId", "headcell_field33" ),
"simple_grid_field33", new XVar( "location", "grid",
"cellId", "cell_field33" ),
"simple_grid_field69", new XVar( "location", "grid",
"cellId", "headcell_field34" ),
"simple_grid_field34", new XVar( "location", "grid",
"cellId", "cell_field34" ),
"grid_inline_cancel", new XVar( "location", "grid",
"cellId", "cell_icons" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "masterlist_header", new XVar( 0, "masterlist_header" ),
"back_master", new XVar( 0, "back_master" ),
"grid_field", new XVar( 0, "simple_grid_field",
1, "simple_grid_field1",
2, "simple_grid_field2",
3, "simple_grid_field3",
4, "simple_grid_field4",
5, "simple_grid_field5",
6, "simple_grid_field6",
7, "simple_grid_field7",
8, "simple_grid_field8",
9, "simple_grid_field9",
10, "simple_grid_field10",
11, "simple_grid_field11",
12, "simple_grid_field12",
13, "simple_grid_field13",
14, "simple_grid_field14",
15, "simple_grid_field15",
16, "simple_grid_field16",
17, "simple_grid_field17",
18, "simple_grid_field18",
19, "simple_grid_field19",
20, "simple_grid_field20",
21, "simple_grid_field21",
22, "simple_grid_field22",
23, "simple_grid_field23",
24, "simple_grid_field24",
25, "simple_grid_field25",
26, "simple_grid_field26",
27, "simple_grid_field27",
28, "simple_grid_field28",
29, "simple_grid_field29",
30, "simple_grid_field30",
31, "simple_grid_field31",
32, "simple_grid_field32",
33, "simple_grid_field33",
34, "simple_grid_field34" ),
"grid_field_label", new XVar( 0, "simple_grid_field35",
1, "simple_grid_field36",
2, "simple_grid_field37",
3, "simple_grid_field38",
4, "simple_grid_field39",
5, "simple_grid_field40",
6, "simple_grid_field41",
7, "simple_grid_field42",
8, "simple_grid_field43",
9, "simple_grid_field44",
10, "simple_grid_field45",
11, "simple_grid_field46",
12, "simple_grid_field47",
13, "simple_grid_field48",
14, "simple_grid_field49",
15, "simple_grid_field50",
16, "simple_grid_field51",
17, "simple_grid_field52",
18, "simple_grid_field53",
19, "simple_grid_field54",
20, "simple_grid_field55",
21, "simple_grid_field56",
22, "simple_grid_field57",
23, "simple_grid_field58",
24, "simple_grid_field59",
25, "simple_grid_field60",
26, "simple_grid_field61",
27, "simple_grid_field62",
28, "simple_grid_field63",
29, "simple_grid_field64",
30, "simple_grid_field65",
31, "simple_grid_field66",
32, "simple_grid_field67",
33, "simple_grid_field68",
34, "simple_grid_field69" ),
"inline_add", new XVar( 0, "inline_add" ),
"grid_inline_cancel", new XVar( 0, "grid_inline_cancel" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "site_ref_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field35" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "trans_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field36" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "type_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field37" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "vend_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field38" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "invoice_id_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field39" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "material_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field40" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tax_amt_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field41" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "dist_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field42" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field8", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "vend_inv_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field43" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field9", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "inv_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field44" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field10", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "due_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field45" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field11", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "currency_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field46" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field12", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "num_lines_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field47" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field13", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "is_prepay_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field48" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field14", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "rowpointer_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field49" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field15", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "createdate_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field50" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field16", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "posted_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field51" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field17", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "postdate_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field52" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field18", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "err_msg_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field53" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field19", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "bill_url_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field54" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field20", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "terms_code_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field55" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field21", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "json_data_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field56" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field22", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "jresult_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field57" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field23", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "clientid_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field58" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field24", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "payer_entity_name_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field59" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field25", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "invoice_status_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field60" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field26", new XVar( "cols", new XVar( 0, 27 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "description_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field61" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field27", new XVar( "cols", new XVar( 0, 28 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "inv_internal_notes_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field62" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field28", new XVar( "cols", new XVar( 0, 29 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "po_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field63" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field29", new XVar( "cols", new XVar( 0, 30 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "approval_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field64" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field30", new XVar( "cols", new XVar( 0, 31 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "income_type_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field65" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field31", new XVar( "cols", new XVar( 0, 32 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "amt_due_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field66" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field32", new XVar( "cols", new XVar( 0, 33 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "freight_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field67" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field33", new XVar( "cols", new XVar( 0, 34 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "misc_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field68" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field34", new XVar( "cols", new XVar( 0, 35 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "total_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field69" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "inline_cancel" ),
"items", new XVar( 0, "grid_inline_cancel" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "site_ref_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "trans_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "type_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "vend_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "invoice_id_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "material_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tax_amt_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "dist_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field8", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "vend_inv_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field9", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "inv_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field10", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "due_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field11", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "currency_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field12", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "num_lines_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field13", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "is_prepay_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field14", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "rowpointer_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field14" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field15", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "createdate_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field15" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field16", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "posted_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field16" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field17", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "postdate_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field17" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field18", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "err_msg_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field18" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field19", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "bill_url_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field19" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field20", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "terms_code_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field20" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field21", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "json_data_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field21" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field22", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "jresult_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field22" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field23", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "clientid_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field23" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field24", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "payer_entity_name_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field24" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field25", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "invoice_status_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field25" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field26", new XVar( "cols", new XVar( 0, 27 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "description_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field26" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field27", new XVar( "cols", new XVar( 0, 28 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "inv_internal_notes_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field27" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field28", new XVar( "cols", new XVar( 0, 29 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "po_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field28" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field29", new XVar( "cols", new XVar( 0, 30 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "approval_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field29" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field30", new XVar( "cols", new XVar( 0, 31 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "income_type_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field30" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field31", new XVar( "cols", new XVar( 0, 32 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "amt_due_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field31" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field32", new XVar( "cols", new XVar( 0, 33 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "freight_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field32" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field33", new XVar( "cols", new XVar( 0, 34 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "misc_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field33" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field34", new XVar( "cols", new XVar( 0, 35 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "total_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field34" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field8", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field9", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field10", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field11", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field12", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field13", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field14", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field15", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field16", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field17", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field18", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field19", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field20", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field21", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field22", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field23", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field24", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field25", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field26", new XVar( "cols", new XVar( 0, 27 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field27", new XVar( "cols", new XVar( 0, 28 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field28", new XVar( "cols", new XVar( 0, 29 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field29", new XVar( "cols", new XVar( 0, 30 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field30", new XVar( "cols", new XVar( 0, 31 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field31", new XVar( "cols", new XVar( 0, 32 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field32", new XVar( "cols", new XVar( 0, 33 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field33", new XVar( "cols", new XVar( 0, 34 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field34", new XVar( "cols", new XVar( 0, 35 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 36,
"height", 3 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"gridType", 0,
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "masterlist",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "masterlist",
"type", "masterlist",
"layoutId", "masterlist",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "empty-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "inline_add" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "empty-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "masterlist-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "back_master",
1, "masterlist_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_icons" ),
1, new XVar( "cell", "headcell_field" ),
2, new XVar( "cell", "headcell_field1" ),
3, new XVar( "cell", "headcell_field2" ),
4, new XVar( "cell", "headcell_field3" ),
5, new XVar( "cell", "headcell_field4" ),
6, new XVar( "cell", "headcell_field5" ),
7, new XVar( "cell", "headcell_field6" ),
8, new XVar( "cell", "headcell_field7" ),
9, new XVar( "cell", "headcell_field8" ),
10, new XVar( "cell", "headcell_field9" ),
11, new XVar( "cell", "headcell_field10" ),
12, new XVar( "cell", "headcell_field11" ),
13, new XVar( "cell", "headcell_field12" ),
14, new XVar( "cell", "headcell_field13" ),
15, new XVar( "cell", "headcell_field14" ),
16, new XVar( "cell", "headcell_field15" ),
17, new XVar( "cell", "headcell_field16" ),
18, new XVar( "cell", "headcell_field17" ),
19, new XVar( "cell", "headcell_field18" ),
20, new XVar( "cell", "headcell_field19" ),
21, new XVar( "cell", "headcell_field20" ),
22, new XVar( "cell", "headcell_field21" ),
23, new XVar( "cell", "headcell_field22" ),
24, new XVar( "cell", "headcell_field23" ),
25, new XVar( "cell", "headcell_field24" ),
26, new XVar( "cell", "headcell_field25" ),
27, new XVar( "cell", "headcell_field26" ),
28, new XVar( "cell", "headcell_field27" ),
29, new XVar( "cell", "headcell_field28" ),
30, new XVar( "cell", "headcell_field29" ),
31, new XVar( "cell", "headcell_field30" ),
32, new XVar( "cell", "headcell_field31" ),
33, new XVar( "cell", "headcell_field32" ),
34, new XVar( "cell", "headcell_field33" ),
35, new XVar( "cell", "headcell_field34" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_icons" ),
1, new XVar( "cell", "cell_field" ),
2, new XVar( "cell", "cell_field1" ),
3, new XVar( "cell", "cell_field2" ),
4, new XVar( "cell", "cell_field3" ),
5, new XVar( "cell", "cell_field4" ),
6, new XVar( "cell", "cell_field5" ),
7, new XVar( "cell", "cell_field6" ),
8, new XVar( "cell", "cell_field7" ),
9, new XVar( "cell", "cell_field8" ),
10, new XVar( "cell", "cell_field9" ),
11, new XVar( "cell", "cell_field10" ),
12, new XVar( "cell", "cell_field11" ),
13, new XVar( "cell", "cell_field12" ),
14, new XVar( "cell", "cell_field13" ),
15, new XVar( "cell", "cell_field14" ),
16, new XVar( "cell", "cell_field15" ),
17, new XVar( "cell", "cell_field16" ),
18, new XVar( "cell", "cell_field17" ),
19, new XVar( "cell", "cell_field18" ),
20, new XVar( "cell", "cell_field19" ),
21, new XVar( "cell", "cell_field20" ),
22, new XVar( "cell", "cell_field21" ),
23, new XVar( "cell", "cell_field22" ),
24, new XVar( "cell", "cell_field23" ),
25, new XVar( "cell", "cell_field24" ),
26, new XVar( "cell", "cell_field25" ),
27, new XVar( "cell", "cell_field26" ),
28, new XVar( "cell", "cell_field27" ),
29, new XVar( "cell", "cell_field28" ),
30, new XVar( "cell", "cell_field29" ),
31, new XVar( "cell", "cell_field30" ),
32, new XVar( "cell", "cell_field31" ),
33, new XVar( "cell", "cell_field32" ),
34, new XVar( "cell", "cell_field33" ),
35, new XVar( "cell", "cell_field34" ) ) ),
2, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_icons" ),
1, new XVar( "cell", "footcell_field" ),
2, new XVar( "cell", "footcell_field1" ),
3, new XVar( "cell", "footcell_field2" ),
4, new XVar( "cell", "footcell_field3" ),
5, new XVar( "cell", "footcell_field4" ),
6, new XVar( "cell", "footcell_field5" ),
7, new XVar( "cell", "footcell_field6" ),
8, new XVar( "cell", "footcell_field7" ),
9, new XVar( "cell", "footcell_field8" ),
10, new XVar( "cell", "footcell_field9" ),
11, new XVar( "cell", "footcell_field10" ),
12, new XVar( "cell", "footcell_field11" ),
13, new XVar( "cell", "footcell_field12" ),
14, new XVar( "cell", "footcell_field13" ),
15, new XVar( "cell", "footcell_field14" ),
16, new XVar( "cell", "footcell_field15" ),
17, new XVar( "cell", "footcell_field16" ),
18, new XVar( "cell", "footcell_field17" ),
19, new XVar( "cell", "footcell_field18" ),
20, new XVar( "cell", "footcell_field19" ),
21, new XVar( "cell", "footcell_field20" ),
22, new XVar( "cell", "footcell_field21" ),
23, new XVar( "cell", "footcell_field22" ),
24, new XVar( "cell", "footcell_field23" ),
25, new XVar( "cell", "footcell_field24" ),
26, new XVar( "cell", "footcell_field25" ),
27, new XVar( "cell", "footcell_field26" ),
28, new XVar( "cell", "footcell_field27" ),
29, new XVar( "cell", "footcell_field28" ),
30, new XVar( "cell", "footcell_field29" ),
31, new XVar( "cell", "footcell_field30" ),
32, new XVar( "cell", "footcell_field31" ),
33, new XVar( "cell", "footcell_field32" ),
34, new XVar( "cell", "footcell_field33" ),
35, new XVar( "cell", "footcell_field34" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field35" ),
"field", "site_ref",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "site_ref",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field36" ),
"field", "trans_num",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "trans_num",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field37" ),
"field", "type",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "type",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field38" ),
"field", "vend_num",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "vend_num",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field39" ),
"field", "invoice_id",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "invoice_id",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field40" ),
"field", "material",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "material",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field41" ),
"field", "tax_amt",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "tax_amt",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field42" ),
"field", "dist_date",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "dist_date",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field8", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field43" ),
"field", "vend_inv",
"columnName", "field" ),
"cell_field8", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "vend_inv",
"columnName", "field" ),
"footcell_field8", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field9", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field44" ),
"field", "inv_date",
"columnName", "field" ),
"cell_field9", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "inv_date",
"columnName", "field" ),
"footcell_field9", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field10", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field45" ),
"field", "due_date",
"columnName", "field" ),
"cell_field10", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "due_date",
"columnName", "field" ),
"footcell_field10", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field11", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field46" ),
"field", "currency",
"columnName", "field" ),
"cell_field11", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "currency",
"columnName", "field" ),
"footcell_field11", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field12", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field47" ),
"field", "num_lines",
"columnName", "field" ),
"cell_field12", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "num_lines",
"columnName", "field" ),
"footcell_field12", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field13", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field48" ),
"field", "is_prepay",
"columnName", "field" ),
"cell_field13", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "is_prepay",
"columnName", "field" ),
"footcell_field13", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field14", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field49" ),
"field", "rowpointer",
"columnName", "field" ),
"cell_field14", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field14" ),
"field", "rowpointer",
"columnName", "field" ),
"footcell_field14", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field15", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field50" ),
"field", "createdate",
"columnName", "field" ),
"cell_field15", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field15" ),
"field", "createdate",
"columnName", "field" ),
"footcell_field15", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field16", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field51" ),
"field", "posted",
"columnName", "field" ),
"cell_field16", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field16" ),
"field", "posted",
"columnName", "field" ),
"footcell_field16", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field17", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field52" ),
"field", "postdate",
"columnName", "field" ),
"cell_field17", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field17" ),
"field", "postdate",
"columnName", "field" ),
"footcell_field17", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field18", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field53" ),
"field", "err_msg",
"columnName", "field" ),
"cell_field18", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field18" ),
"field", "err_msg",
"columnName", "field" ),
"footcell_field18", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field19", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field54" ),
"field", "bill_url",
"columnName", "field" ),
"cell_field19", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field19" ),
"field", "bill_url",
"columnName", "field" ),
"footcell_field19", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field20", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field55" ),
"field", "terms_code",
"columnName", "field" ),
"cell_field20", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field20" ),
"field", "terms_code",
"columnName", "field" ),
"footcell_field20", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field21", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field56" ),
"field", "json_data",
"columnName", "field" ),
"cell_field21", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field21" ),
"field", "json_data",
"columnName", "field" ),
"footcell_field21", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field22", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field57" ),
"field", "jresult",
"columnName", "field" ),
"cell_field22", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field22" ),
"field", "jresult",
"columnName", "field" ),
"footcell_field22", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field23", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field58" ),
"field", "clientid",
"columnName", "field" ),
"cell_field23", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field23" ),
"field", "clientid",
"columnName", "field" ),
"footcell_field23", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field24", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field59" ),
"field", "payer_entity_name",
"columnName", "field" ),
"cell_field24", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field24" ),
"field", "payer_entity_name",
"columnName", "field" ),
"footcell_field24", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field25", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field60" ),
"field", "invoice_status",
"columnName", "field" ),
"cell_field25", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field25" ),
"field", "invoice_status",
"columnName", "field" ),
"footcell_field25", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field26", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field61" ),
"field", "description",
"columnName", "field" ),
"cell_field26", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field26" ),
"field", "description",
"columnName", "field" ),
"footcell_field26", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field27", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field62" ),
"field", "inv_internal_notes",
"columnName", "field" ),
"cell_field27", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field27" ),
"field", "inv_internal_notes",
"columnName", "field" ),
"footcell_field27", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field28", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field63" ),
"field", "po_num",
"columnName", "field" ),
"cell_field28", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field28" ),
"field", "po_num",
"columnName", "field" ),
"footcell_field28", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field29", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field64" ),
"field", "approval_date",
"columnName", "field" ),
"cell_field29", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field29" ),
"field", "approval_date",
"columnName", "field" ),
"footcell_field29", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field30", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field65" ),
"field", "income_type",
"columnName", "field" ),
"cell_field30", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field30" ),
"field", "income_type",
"columnName", "field" ),
"footcell_field30", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field31", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field66" ),
"field", "amt_due",
"columnName", "field" ),
"cell_field31", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field31" ),
"field", "amt_due",
"columnName", "field" ),
"footcell_field31", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field32", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field67" ),
"field", "freight",
"columnName", "field" ),
"cell_field32", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field32" ),
"field", "freight",
"columnName", "field" ),
"footcell_field32", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field33", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field68" ),
"field", "misc",
"columnName", "field" ),
"cell_field33", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field33" ),
"field", "misc",
"columnName", "field" ),
"footcell_field33", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field34", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field69" ),
"field", "total",
"columnName", "field" ),
"cell_field34", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field34" ),
"field", "total",
"columnName", "field" ),
"footcell_field34", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_icons", new XVar( "model", "headcell_icons",
"items", XVar.Array() ),
"cell_icons", new XVar( "model", "cell_icons",
"items", new XVar( 0, "grid_inline_cancel" ) ),
"footcell_icons", new XVar( "model", "footcell_icons",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "masterlist_header", new XVar( "type", "masterlist_header" ),
"back_master", new XVar( "type", "back_master" ),
"simple_grid_field", new XVar( "field", "site_ref",
"type", "grid_field" ),
"simple_grid_field35", new XVar( "type", "grid_field_label",
"field", "site_ref" ),
"simple_grid_field1", new XVar( "field", "trans_num",
"type", "grid_field" ),
"simple_grid_field36", new XVar( "type", "grid_field_label",
"field", "trans_num" ),
"simple_grid_field2", new XVar( "field", "type",
"type", "grid_field" ),
"simple_grid_field37", new XVar( "type", "grid_field_label",
"field", "type" ),
"simple_grid_field3", new XVar( "field", "vend_num",
"type", "grid_field" ),
"simple_grid_field38", new XVar( "type", "grid_field_label",
"field", "vend_num" ),
"simple_grid_field4", new XVar( "field", "invoice_id",
"type", "grid_field" ),
"simple_grid_field39", new XVar( "type", "grid_field_label",
"field", "invoice_id" ),
"simple_grid_field5", new XVar( "field", "material",
"type", "grid_field" ),
"simple_grid_field40", new XVar( "type", "grid_field_label",
"field", "material" ),
"simple_grid_field6", new XVar( "field", "tax_amt",
"type", "grid_field" ),
"simple_grid_field41", new XVar( "type", "grid_field_label",
"field", "tax_amt" ),
"simple_grid_field7", new XVar( "field", "dist_date",
"type", "grid_field" ),
"simple_grid_field42", new XVar( "type", "grid_field_label",
"field", "dist_date" ),
"simple_grid_field8", new XVar( "field", "vend_inv",
"type", "grid_field" ),
"simple_grid_field43", new XVar( "type", "grid_field_label",
"field", "vend_inv" ),
"simple_grid_field9", new XVar( "field", "inv_date",
"type", "grid_field" ),
"simple_grid_field44", new XVar( "type", "grid_field_label",
"field", "inv_date" ),
"simple_grid_field10", new XVar( "field", "due_date",
"type", "grid_field" ),
"simple_grid_field45", new XVar( "type", "grid_field_label",
"field", "due_date" ),
"simple_grid_field11", new XVar( "field", "currency",
"type", "grid_field" ),
"simple_grid_field46", new XVar( "type", "grid_field_label",
"field", "currency" ),
"simple_grid_field12", new XVar( "field", "num_lines",
"type", "grid_field" ),
"simple_grid_field47", new XVar( "type", "grid_field_label",
"field", "num_lines" ),
"simple_grid_field13", new XVar( "field", "is_prepay",
"type", "grid_field" ),
"simple_grid_field48", new XVar( "type", "grid_field_label",
"field", "is_prepay" ),
"simple_grid_field14", new XVar( "field", "rowpointer",
"type", "grid_field" ),
"simple_grid_field49", new XVar( "type", "grid_field_label",
"field", "rowpointer" ),
"simple_grid_field15", new XVar( "field", "createdate",
"type", "grid_field" ),
"simple_grid_field50", new XVar( "type", "grid_field_label",
"field", "createdate" ),
"simple_grid_field16", new XVar( "field", "posted",
"type", "grid_field" ),
"simple_grid_field51", new XVar( "type", "grid_field_label",
"field", "posted" ),
"simple_grid_field17", new XVar( "field", "postdate",
"type", "grid_field" ),
"simple_grid_field52", new XVar( "type", "grid_field_label",
"field", "postdate" ),
"simple_grid_field18", new XVar( "field", "err_msg",
"type", "grid_field" ),
"simple_grid_field53", new XVar( "type", "grid_field_label",
"field", "err_msg" ),
"simple_grid_field19", new XVar( "field", "bill_url",
"type", "grid_field" ),
"simple_grid_field54", new XVar( "type", "grid_field_label",
"field", "bill_url" ),
"simple_grid_field20", new XVar( "field", "terms_code",
"type", "grid_field" ),
"simple_grid_field55", new XVar( "type", "grid_field_label",
"field", "terms_code" ),
"simple_grid_field21", new XVar( "field", "json_data",
"type", "grid_field" ),
"simple_grid_field56", new XVar( "type", "grid_field_label",
"field", "json_data" ),
"simple_grid_field22", new XVar( "field", "jresult",
"type", "grid_field" ),
"simple_grid_field57", new XVar( "type", "grid_field_label",
"field", "jresult" ),
"simple_grid_field23", new XVar( "field", "clientid",
"type", "grid_field" ),
"simple_grid_field58", new XVar( "type", "grid_field_label",
"field", "clientid" ),
"simple_grid_field24", new XVar( "field", "payer_entity_name",
"type", "grid_field" ),
"simple_grid_field59", new XVar( "type", "grid_field_label",
"field", "payer_entity_name" ),
"simple_grid_field25", new XVar( "field", "invoice_status",
"type", "grid_field" ),
"simple_grid_field60", new XVar( "type", "grid_field_label",
"field", "invoice_status" ),
"simple_grid_field26", new XVar( "field", "description",
"type", "grid_field" ),
"simple_grid_field61", new XVar( "type", "grid_field_label",
"field", "description" ),
"simple_grid_field27", new XVar( "field", "inv_internal_notes",
"type", "grid_field" ),
"simple_grid_field62", new XVar( "type", "grid_field_label",
"field", "inv_internal_notes" ),
"simple_grid_field28", new XVar( "field", "po_num",
"type", "grid_field" ),
"simple_grid_field63", new XVar( "type", "grid_field_label",
"field", "po_num" ),
"simple_grid_field29", new XVar( "field", "approval_date",
"type", "grid_field" ),
"simple_grid_field64", new XVar( "type", "grid_field_label",
"field", "approval_date" ),
"simple_grid_field30", new XVar( "field", "income_type",
"type", "grid_field" ),
"simple_grid_field65", new XVar( "type", "grid_field_label",
"field", "income_type" ),
"simple_grid_field31", new XVar( "field", "amt_due",
"type", "grid_field" ),
"simple_grid_field66", new XVar( "type", "grid_field_label",
"field", "amt_due" ),
"simple_grid_field32", new XVar( "field", "freight",
"type", "grid_field" ),
"simple_grid_field67", new XVar( "type", "grid_field_label",
"field", "freight" ),
"simple_grid_field33", new XVar( "field", "misc",
"type", "grid_field" ),
"simple_grid_field68", new XVar( "type", "grid_field_label",
"field", "misc" ),
"simple_grid_field34", new XVar( "field", "total",
"type", "grid_field" ),
"simple_grid_field69", new XVar( "type", "grid_field_label",
"field", "total" ),
"inline_add", new XVar( "type", "inline_add",
"detailsOnly", true ),
"grid_inline_cancel", new XVar( "type", "grid_inline_cancel" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}