
		// dbo.sc_expensereport_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_sc_expensereport_mst_import
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "site_ref",
1, "report_id",
2, "uri",
3, "name",
4, "total",
5, "curr_code",
6, "clientid",
7, "createdate",
8, "submitdate",
9, "ownerloginid",
10, "ownername",
11, "country",
12, "reportdate",
13, "concuruserid",
14, "vend_num",
15, "trans_num",
16, "posted" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "site_ref", new XVar( 0, "import_field" ),
"report_id", new XVar( 0, "import_field1" ),
"uri", new XVar( 0, "import_field2" ),
"name", new XVar( 0, "import_field3" ),
"total", new XVar( 0, "import_field4" ),
"curr_code", new XVar( 0, "import_field5" ),
"clientid", new XVar( 0, "import_field6" ),
"createdate", new XVar( 0, "import_field7" ),
"submitdate", new XVar( 0, "import_field8" ),
"ownerloginid", new XVar( 0, "import_field9" ),
"ownername", new XVar( 0, "import_field10" ),
"country", new XVar( 0, "import_field11" ),
"reportdate", new XVar( 0, "import_field12" ),
"concuruserid", new XVar( 0, "import_field13" ),
"vend_num", new XVar( 0, "import_field14" ),
"trans_num", new XVar( 0, "import_field15" ),
"posted", new XVar( 0, "import_field16" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "import_header" ),
"grid", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "import_header", "top",
"import_field", "grid",
"import_field1", "grid",
"import_field2", "grid",
"import_field3", "grid",
"import_field4", "grid",
"import_field5", "grid",
"import_field6", "grid",
"import_field7", "grid",
"import_field8", "grid",
"import_field9", "grid",
"import_field10", "grid",
"import_field11", "grid",
"import_field12", "grid",
"import_field13", "grid",
"import_field14", "grid",
"import_field15", "grid",
"import_field16", "grid" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "import_header", new XVar( 0, "import_header" ),
"import_field", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "import",
"type", "import",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "import-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "import-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "import_header", new XVar( "type", "import_header" ),
"import_field", new XVar( "field", "site_ref",
"type", "import_field" ),
"import_field1", new XVar( "field", "report_id",
"type", "import_field" ),
"import_field2", new XVar( "field", "uri",
"type", "import_field" ),
"import_field3", new XVar( "field", "name",
"type", "import_field" ),
"import_field4", new XVar( "field", "total",
"type", "import_field" ),
"import_field5", new XVar( "field", "curr_code",
"type", "import_field" ),
"import_field6", new XVar( "field", "clientid",
"type", "import_field" ),
"import_field7", new XVar( "field", "createdate",
"type", "import_field" ),
"import_field8", new XVar( "field", "submitdate",
"type", "import_field" ),
"import_field9", new XVar( "field", "ownerloginid",
"type", "import_field" ),
"import_field10", new XVar( "field", "ownername",
"type", "import_field" ),
"import_field11", new XVar( "field", "country",
"type", "import_field" ),
"import_field12", new XVar( "field", "reportdate",
"type", "import_field" ),
"import_field13", new XVar( "field", "concuruserid",
"type", "import_field" ),
"import_field14", new XVar( "field", "vend_num",
"type", "import_field" ),
"import_field15", new XVar( "field", "trans_num",
"type", "import_field" ),
"import_field16", new XVar( "field", "posted",
"type", "import_field" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}