
		// dbo.sc_invoice_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_sc_invoice_mst_import
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "site_ref",
1, "trans_num",
2, "type",
3, "vend_num",
4, "invoice_id",
5, "material",
6, "tax_amt",
7, "dist_date",
8, "vend_inv",
9, "inv_date",
10, "due_date",
11, "currency",
12, "num_lines",
13, "is_prepay",
14, "rowpointer",
15, "createdate",
16, "posted",
17, "postdate",
18, "err_msg",
19, "bill_url",
20, "terms_code",
21, "json_data",
22, "jresult",
23, "clientid",
24, "payer_entity_name",
25, "invoice_status",
26, "description",
27, "inv_internal_notes",
28, "po_num",
29, "approval_date",
30, "income_type",
31, "amt_due",
32, "freight",
33, "misc",
34, "total",
35, "vendorcode",
36, "vendorname",
37, "inv_num",
38, "Billable",
39, "SRO",
40, "line",
41, "transaction",
42, "lastmodifieddate" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "site_ref", new XVar( 0, "import_field" ),
"trans_num", new XVar( 0, "import_field1" ),
"type", new XVar( 0, "import_field2" ),
"vend_num", new XVar( 0, "import_field3" ),
"invoice_id", new XVar( 0, "import_field4" ),
"material", new XVar( 0, "import_field5" ),
"tax_amt", new XVar( 0, "import_field6" ),
"dist_date", new XVar( 0, "import_field7" ),
"vend_inv", new XVar( 0, "import_field8" ),
"inv_date", new XVar( 0, "import_field9" ),
"due_date", new XVar( 0, "import_field10" ),
"currency", new XVar( 0, "import_field11" ),
"num_lines", new XVar( 0, "import_field12" ),
"is_prepay", new XVar( 0, "import_field13" ),
"rowpointer", new XVar( 0, "import_field14" ),
"createdate", new XVar( 0, "import_field15" ),
"posted", new XVar( 0, "import_field16" ),
"postdate", new XVar( 0, "import_field17" ),
"err_msg", new XVar( 0, "import_field18" ),
"bill_url", new XVar( 0, "import_field19" ),
"terms_code", new XVar( 0, "import_field20" ),
"json_data", new XVar( 0, "import_field21" ),
"jresult", new XVar( 0, "import_field22" ),
"clientid", new XVar( 0, "import_field23" ),
"payer_entity_name", new XVar( 0, "import_field24" ),
"invoice_status", new XVar( 0, "import_field25" ),
"description", new XVar( 0, "import_field26" ),
"inv_internal_notes", new XVar( 0, "import_field27" ),
"po_num", new XVar( 0, "import_field28" ),
"approval_date", new XVar( 0, "import_field29" ),
"income_type", new XVar( 0, "import_field30" ),
"amt_due", new XVar( 0, "import_field31" ),
"freight", new XVar( 0, "import_field32" ),
"misc", new XVar( 0, "import_field33" ),
"total", new XVar( 0, "import_field34" ),
"vendorcode", new XVar( 0, "import_field35" ),
"vendorname", new XVar( 0, "import_field36" ),
"inv_num", new XVar( 0, "import_field37" ),
"Billable", new XVar( 0, "import_field38" ),
"SRO", new XVar( 0, "import_field39" ),
"line", new XVar( 0, "import_field40" ),
"transaction", new XVar( 0, "import_field41" ),
"lastmodifieddate", new XVar( 0, "import_field42" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "import_header" ),
"grid", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16",
17, "import_field17",
18, "import_field18",
19, "import_field19",
20, "import_field20",
21, "import_field21",
22, "import_field22",
23, "import_field23",
24, "import_field24",
25, "import_field25",
26, "import_field26",
27, "import_field27",
28, "import_field28",
29, "import_field29",
30, "import_field30",
31, "import_field31",
32, "import_field32",
33, "import_field33",
34, "import_field34",
35, "import_field35",
36, "import_field36",
37, "import_field37",
38, "import_field38",
39, "import_field39",
40, "import_field40",
41, "import_field41",
42, "import_field42" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "import_header", "top",
"import_field", "grid",
"import_field1", "grid",
"import_field2", "grid",
"import_field3", "grid",
"import_field4", "grid",
"import_field5", "grid",
"import_field6", "grid",
"import_field7", "grid",
"import_field8", "grid",
"import_field9", "grid",
"import_field10", "grid",
"import_field11", "grid",
"import_field12", "grid",
"import_field13", "grid",
"import_field14", "grid",
"import_field15", "grid",
"import_field16", "grid",
"import_field17", "grid",
"import_field18", "grid",
"import_field19", "grid",
"import_field20", "grid",
"import_field21", "grid",
"import_field22", "grid",
"import_field23", "grid",
"import_field24", "grid",
"import_field25", "grid",
"import_field26", "grid",
"import_field27", "grid",
"import_field28", "grid",
"import_field29", "grid",
"import_field30", "grid",
"import_field31", "grid",
"import_field32", "grid",
"import_field33", "grid",
"import_field34", "grid",
"import_field35", "grid",
"import_field36", "grid",
"import_field37", "grid",
"import_field38", "grid",
"import_field39", "grid",
"import_field40", "grid",
"import_field41", "grid",
"import_field42", "grid" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "import_header", new XVar( 0, "import_header" ),
"import_field", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16",
17, "import_field17",
18, "import_field18",
19, "import_field19",
20, "import_field20",
21, "import_field21",
22, "import_field22",
23, "import_field23",
24, "import_field24",
25, "import_field25",
26, "import_field26",
27, "import_field27",
28, "import_field28",
29, "import_field29",
30, "import_field30",
31, "import_field31",
32, "import_field32",
33, "import_field33",
34, "import_field34",
35, "import_field35",
36, "import_field36",
37, "import_field37",
38, "import_field38",
39, "import_field39",
40, "import_field40",
41, "import_field41",
42, "import_field42" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "import",
"type", "import",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "import-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "import-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16",
17, "import_field17",
18, "import_field18",
19, "import_field19",
20, "import_field20",
21, "import_field21",
22, "import_field22",
23, "import_field23",
24, "import_field24",
25, "import_field25",
26, "import_field26",
27, "import_field27",
28, "import_field28",
29, "import_field29",
30, "import_field30",
31, "import_field31",
32, "import_field32",
33, "import_field33",
34, "import_field34",
35, "import_field35",
36, "import_field36",
37, "import_field37",
38, "import_field38",
39, "import_field39",
40, "import_field40",
41, "import_field41",
42, "import_field42" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "import_header", new XVar( "type", "import_header" ),
"import_field", new XVar( "field", "site_ref",
"type", "import_field" ),
"import_field1", new XVar( "field", "trans_num",
"type", "import_field" ),
"import_field2", new XVar( "field", "type",
"type", "import_field" ),
"import_field3", new XVar( "field", "vend_num",
"type", "import_field" ),
"import_field4", new XVar( "field", "invoice_id",
"type", "import_field" ),
"import_field5", new XVar( "field", "material",
"type", "import_field" ),
"import_field6", new XVar( "field", "tax_amt",
"type", "import_field" ),
"import_field7", new XVar( "field", "dist_date",
"type", "import_field" ),
"import_field8", new XVar( "field", "vend_inv",
"type", "import_field" ),
"import_field9", new XVar( "field", "inv_date",
"type", "import_field" ),
"import_field10", new XVar( "field", "due_date",
"type", "import_field" ),
"import_field11", new XVar( "field", "currency",
"type", "import_field" ),
"import_field12", new XVar( "field", "num_lines",
"type", "import_field" ),
"import_field13", new XVar( "field", "is_prepay",
"type", "import_field" ),
"import_field14", new XVar( "field", "rowpointer",
"type", "import_field" ),
"import_field15", new XVar( "field", "createdate",
"type", "import_field" ),
"import_field16", new XVar( "field", "posted",
"type", "import_field" ),
"import_field17", new XVar( "field", "postdate",
"type", "import_field" ),
"import_field18", new XVar( "field", "err_msg",
"type", "import_field" ),
"import_field19", new XVar( "field", "bill_url",
"type", "import_field" ),
"import_field20", new XVar( "field", "terms_code",
"type", "import_field" ),
"import_field21", new XVar( "field", "json_data",
"type", "import_field" ),
"import_field22", new XVar( "field", "jresult",
"type", "import_field" ),
"import_field23", new XVar( "field", "clientid",
"type", "import_field" ),
"import_field24", new XVar( "field", "payer_entity_name",
"type", "import_field" ),
"import_field25", new XVar( "field", "invoice_status",
"type", "import_field" ),
"import_field26", new XVar( "field", "description",
"type", "import_field" ),
"import_field27", new XVar( "field", "inv_internal_notes",
"type", "import_field" ),
"import_field28", new XVar( "field", "po_num",
"type", "import_field" ),
"import_field29", new XVar( "field", "approval_date",
"type", "import_field" ),
"import_field30", new XVar( "field", "income_type",
"type", "import_field" ),
"import_field31", new XVar( "field", "amt_due",
"type", "import_field" ),
"import_field32", new XVar( "field", "freight",
"type", "import_field" ),
"import_field33", new XVar( "field", "misc",
"type", "import_field" ),
"import_field34", new XVar( "field", "total",
"type", "import_field" ),
"import_field35", new XVar( "field", "vendorcode",
"type", "import_field" ),
"import_field36", new XVar( "field", "vendorname",
"type", "import_field" ),
"import_field37", new XVar( "field", "inv_num",
"type", "import_field" ),
"import_field38", new XVar( "field", "Billable",
"type", "import_field" ),
"import_field39", new XVar( "field", "SRO",
"type", "import_field" ),
"import_field40", new XVar( "field", "line",
"type", "import_field" ),
"import_field41", new XVar( "field", "transaction",
"type", "import_field" ),
"import_field42", new XVar( "field", "lastmodifieddate",
"type", "import_field" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}