
		// dbo.sc_sro_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_sc_sro_mst_print
			{
				static public XVar options()
				{
					return new XVar( "pdf", new XVar( "pdfView", false ),
"totals", new XVar( "trans_num", new XVar( "totalsType", "" ),
"emp_num", new XVar( "totalsType", "" ),
"trans_date", new XVar( "totalsType", "" ),
"sro_num", new XVar( "totalsType", "" ),
"line", new XVar( "totalsType", "" ),
"oper_num", new XVar( "totalsType", "" ),
"misc_code", new XVar( "totalsType", "" ),
"qty", new XVar( "totalsType", "" ),
"pay_type", new XVar( "totalsType", "" ),
"cost", new XVar( "totalsType", "" ),
"price", new XVar( "totalsType", "" ),
"curr_code", new XVar( "totalsType", "" ),
"report_id", new XVar( "totalsType", "" ),
"posted", new XVar( "totalsType", "" ),
"batchid", new XVar( "totalsType", "" ),
"clientid", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"rowpointer", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "trans_num",
1, "emp_num",
2, "trans_date",
3, "sro_num",
4, "line",
5, "oper_num",
6, "misc_code",
7, "qty",
8, "pay_type",
9, "cost",
10, "price",
11, "curr_code",
12, "report_id",
13, "posted",
14, "batchid",
15, "clientid",
16, "site_ref",
17, "rowpointer" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "trans_num", new XVar( 0, "simple_grid_field",
1, "simple_grid_field18" ),
"emp_num", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field19" ),
"trans_date", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field20" ),
"sro_num", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field21" ),
"line", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field22" ),
"oper_num", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field23" ),
"misc_code", new XVar( 0, "simple_grid_field6",
1, "simple_grid_field24" ),
"qty", new XVar( 0, "simple_grid_field7",
1, "simple_grid_field25" ),
"pay_type", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field26" ),
"cost", new XVar( 0, "simple_grid_field9",
1, "simple_grid_field27" ),
"price", new XVar( 0, "simple_grid_field10",
1, "simple_grid_field28" ),
"curr_code", new XVar( 0, "simple_grid_field11",
1, "simple_grid_field29" ),
"report_id", new XVar( 0, "simple_grid_field12",
1, "simple_grid_field30" ),
"posted", new XVar( 0, "simple_grid_field13",
1, "simple_grid_field31" ),
"batchid", new XVar( 0, "simple_grid_field14",
1, "simple_grid_field32" ),
"clientid", new XVar( 0, "simple_grid_field15",
1, "simple_grid_field33" ),
"site_ref", new XVar( 0, "simple_grid_field16",
1, "simple_grid_field34" ),
"rowpointer", new XVar( 0, "simple_grid_field17",
1, "simple_grid_field35" ) ),
"hideEmptyFields", XVar.Array() ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "print_pages" ),
"below-grid", XVar.Array(),
"top", new XVar( 0, "print_header",
1, "print_subheader" ),
"grid", new XVar( 0, "simple_grid_field18",
1, "simple_grid_field",
2, "simple_grid_field19",
3, "simple_grid_field1",
4, "simple_grid_field20",
5, "simple_grid_field2",
6, "simple_grid_field21",
7, "simple_grid_field3",
8, "simple_grid_field22",
9, "simple_grid_field4",
10, "simple_grid_field23",
11, "simple_grid_field5",
12, "simple_grid_field24",
13, "simple_grid_field6",
14, "simple_grid_field25",
15, "simple_grid_field7",
16, "simple_grid_field26",
17, "simple_grid_field8",
18, "simple_grid_field27",
19, "simple_grid_field9",
20, "simple_grid_field28",
21, "simple_grid_field10",
22, "simple_grid_field29",
23, "simple_grid_field11",
24, "simple_grid_field30",
25, "simple_grid_field12",
26, "simple_grid_field31",
27, "simple_grid_field13",
28, "simple_grid_field32",
29, "simple_grid_field14",
30, "simple_grid_field33",
31, "simple_grid_field15",
32, "simple_grid_field34",
33, "simple_grid_field16",
34, "simple_grid_field35",
35, "simple_grid_field17" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "print_pages" ),
"below-grid", XVar.Array() ),
"itemForms", new XVar( "print_pages", "above-grid",
"print_header", "top",
"print_subheader", "top",
"simple_grid_field18", "grid",
"simple_grid_field", "grid",
"simple_grid_field19", "grid",
"simple_grid_field1", "grid",
"simple_grid_field20", "grid",
"simple_grid_field2", "grid",
"simple_grid_field21", "grid",
"simple_grid_field3", "grid",
"simple_grid_field22", "grid",
"simple_grid_field4", "grid",
"simple_grid_field23", "grid",
"simple_grid_field5", "grid",
"simple_grid_field24", "grid",
"simple_grid_field6", "grid",
"simple_grid_field25", "grid",
"simple_grid_field7", "grid",
"simple_grid_field26", "grid",
"simple_grid_field8", "grid",
"simple_grid_field27", "grid",
"simple_grid_field9", "grid",
"simple_grid_field28", "grid",
"simple_grid_field10", "grid",
"simple_grid_field29", "grid",
"simple_grid_field11", "grid",
"simple_grid_field30", "grid",
"simple_grid_field12", "grid",
"simple_grid_field31", "grid",
"simple_grid_field13", "grid",
"simple_grid_field32", "grid",
"simple_grid_field14", "grid",
"simple_grid_field33", "grid",
"simple_grid_field15", "grid",
"simple_grid_field34", "grid",
"simple_grid_field16", "grid",
"simple_grid_field35", "grid",
"simple_grid_field17", "grid" ),
"itemLocations", new XVar( "simple_grid_field18", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field19", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field20", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field21", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field22", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field23", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field24", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field25", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"simple_grid_field26", new XVar( "location", "grid",
"cellId", "headcell_field8" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "cell_field8" ),
"simple_grid_field27", new XVar( "location", "grid",
"cellId", "headcell_field9" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "cell_field9" ),
"simple_grid_field28", new XVar( "location", "grid",
"cellId", "headcell_field10" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "cell_field10" ),
"simple_grid_field29", new XVar( "location", "grid",
"cellId", "headcell_field11" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "cell_field11" ),
"simple_grid_field30", new XVar( "location", "grid",
"cellId", "headcell_field12" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "cell_field12" ),
"simple_grid_field31", new XVar( "location", "grid",
"cellId", "headcell_field13" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "cell_field13" ),
"simple_grid_field32", new XVar( "location", "grid",
"cellId", "headcell_field14" ),
"simple_grid_field14", new XVar( "location", "grid",
"cellId", "cell_field14" ),
"simple_grid_field33", new XVar( "location", "grid",
"cellId", "headcell_field15" ),
"simple_grid_field15", new XVar( "location", "grid",
"cellId", "cell_field15" ),
"simple_grid_field34", new XVar( "location", "grid",
"cellId", "headcell_field16" ),
"simple_grid_field16", new XVar( "location", "grid",
"cellId", "cell_field16" ),
"simple_grid_field35", new XVar( "location", "grid",
"cellId", "headcell_field17" ),
"simple_grid_field17", new XVar( "location", "grid",
"cellId", "cell_field17" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "print_header", new XVar( 0, "print_header" ),
"print_subheader", new XVar( 0, "print_subheader" ),
"print_pages", new XVar( 0, "print_pages" ),
"grid_field", new XVar( 0, "simple_grid_field",
1, "simple_grid_field1",
2, "simple_grid_field2",
3, "simple_grid_field3",
4, "simple_grid_field4",
5, "simple_grid_field5",
6, "simple_grid_field6",
7, "simple_grid_field7",
8, "simple_grid_field8",
9, "simple_grid_field9",
10, "simple_grid_field10",
11, "simple_grid_field11",
12, "simple_grid_field12",
13, "simple_grid_field13",
14, "simple_grid_field14",
15, "simple_grid_field15",
16, "simple_grid_field16",
17, "simple_grid_field17" ),
"grid_field_label", new XVar( 0, "simple_grid_field18",
1, "simple_grid_field19",
2, "simple_grid_field20",
3, "simple_grid_field21",
4, "simple_grid_field22",
5, "simple_grid_field23",
6, "simple_grid_field24",
7, "simple_grid_field25",
8, "simple_grid_field26",
9, "simple_grid_field27",
10, "simple_grid_field28",
11, "simple_grid_field29",
12, "simple_grid_field30",
13, "simple_grid_field31",
14, "simple_grid_field32",
15, "simple_grid_field33",
16, "simple_grid_field34",
17, "simple_grid_field35" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_field", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "trans_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field18" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "emp_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field19" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "trans_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field20" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "sro_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field21" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "line_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field22" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "oper_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field23" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "misc_code_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field24" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "qty_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field25" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field8", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "pay_type_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field26" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field9", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "cost_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field27" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field10", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "price_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field28" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field11", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "curr_code_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field29" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field12", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "report_id_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field30" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field13", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "posted_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field31" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field14", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "batchid_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field32" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field15", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "clientid_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field33" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field16", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "site_ref_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field34" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field17", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "rowpointer_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field35" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "trans_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "emp_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "trans_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "sro_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "line_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "oper_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "misc_code_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "qty_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field8", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "pay_type_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field9", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "cost_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field10", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "price_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field11", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "curr_code_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field12", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "report_id_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field13", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "posted_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field14", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "batchid_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field14" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field15", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "clientid_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field15" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field16", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "site_ref_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field16" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field17", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "rowpointer_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field17" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field8", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field9", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field10", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field11", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field12", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field13", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field14", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field15", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field16", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field17", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 18,
"height", 3 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar( "print_pages", new XVar( "tag", "PRINT_PAGES",
"type", 2 ) ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"gridType", 0,
"recsPerRow", 1,
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "print",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"dataGrid", new XVar( "groupFields", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "print",
"type", "print",
"layoutId", "basic",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "print-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "print_pages" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "print-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "print-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c2", new XVar( "model", "c2",
"items", new XVar( 0, "print_header",
1, "print_subheader" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_field" ),
1, new XVar( "cell", "headcell_field1" ),
2, new XVar( "cell", "headcell_field2" ),
3, new XVar( "cell", "headcell_field3" ),
4, new XVar( "cell", "headcell_field4" ),
5, new XVar( "cell", "headcell_field5" ),
6, new XVar( "cell", "headcell_field6" ),
7, new XVar( "cell", "headcell_field7" ),
8, new XVar( "cell", "headcell_field8" ),
9, new XVar( "cell", "headcell_field9" ),
10, new XVar( "cell", "headcell_field10" ),
11, new XVar( "cell", "headcell_field11" ),
12, new XVar( "cell", "headcell_field12" ),
13, new XVar( "cell", "headcell_field13" ),
14, new XVar( "cell", "headcell_field14" ),
15, new XVar( "cell", "headcell_field15" ),
16, new XVar( "cell", "headcell_field16" ),
17, new XVar( "cell", "headcell_field17" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_field" ),
1, new XVar( "cell", "cell_field1" ),
2, new XVar( "cell", "cell_field2" ),
3, new XVar( "cell", "cell_field3" ),
4, new XVar( "cell", "cell_field4" ),
5, new XVar( "cell", "cell_field5" ),
6, new XVar( "cell", "cell_field6" ),
7, new XVar( "cell", "cell_field7" ),
8, new XVar( "cell", "cell_field8" ),
9, new XVar( "cell", "cell_field9" ),
10, new XVar( "cell", "cell_field10" ),
11, new XVar( "cell", "cell_field11" ),
12, new XVar( "cell", "cell_field12" ),
13, new XVar( "cell", "cell_field13" ),
14, new XVar( "cell", "cell_field14" ),
15, new XVar( "cell", "cell_field15" ),
16, new XVar( "cell", "cell_field16" ),
17, new XVar( "cell", "cell_field17" ) ) ),
2, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_field" ),
1, new XVar( "cell", "footcell_field1" ),
2, new XVar( "cell", "footcell_field2" ),
3, new XVar( "cell", "footcell_field3" ),
4, new XVar( "cell", "footcell_field4" ),
5, new XVar( "cell", "footcell_field5" ),
6, new XVar( "cell", "footcell_field6" ),
7, new XVar( "cell", "footcell_field7" ),
8, new XVar( "cell", "footcell_field8" ),
9, new XVar( "cell", "footcell_field9" ),
10, new XVar( "cell", "footcell_field10" ),
11, new XVar( "cell", "footcell_field11" ),
12, new XVar( "cell", "footcell_field12" ),
13, new XVar( "cell", "footcell_field13" ),
14, new XVar( "cell", "footcell_field14" ),
15, new XVar( "cell", "footcell_field15" ),
16, new XVar( "cell", "footcell_field16" ),
17, new XVar( "cell", "footcell_field17" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field18" ),
"field", "trans_num",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "trans_num",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field19" ),
"field", "emp_num",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "emp_num",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field20" ),
"field", "trans_date",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "trans_date",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field21" ),
"field", "sro_num",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "sro_num",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field22" ),
"field", "line",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "line",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field23" ),
"field", "oper_num",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "oper_num",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field24" ),
"field", "misc_code",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "misc_code",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field25" ),
"field", "qty",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "qty",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field8", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field26" ),
"field", "pay_type",
"columnName", "field" ),
"cell_field8", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "pay_type",
"columnName", "field" ),
"footcell_field8", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field9", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field27" ),
"field", "cost",
"columnName", "field" ),
"cell_field9", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "cost",
"columnName", "field" ),
"footcell_field9", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field10", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field28" ),
"field", "price",
"columnName", "field" ),
"cell_field10", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "price",
"columnName", "field" ),
"footcell_field10", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field11", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field29" ),
"field", "curr_code",
"columnName", "field" ),
"cell_field11", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "curr_code",
"columnName", "field" ),
"footcell_field11", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field12", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field30" ),
"field", "report_id",
"columnName", "field" ),
"cell_field12", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "report_id",
"columnName", "field" ),
"footcell_field12", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field13", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field31" ),
"field", "posted",
"columnName", "field" ),
"cell_field13", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "posted",
"columnName", "field" ),
"footcell_field13", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field14", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field32" ),
"field", "batchid",
"columnName", "field" ),
"cell_field14", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field14" ),
"field", "batchid",
"columnName", "field" ),
"footcell_field14", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field15", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field33" ),
"field", "clientid",
"columnName", "field" ),
"cell_field15", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field15" ),
"field", "clientid",
"columnName", "field" ),
"footcell_field15", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field16", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field34" ),
"field", "site_ref",
"columnName", "field" ),
"cell_field16", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field16" ),
"field", "site_ref",
"columnName", "field" ),
"footcell_field16", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field17", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field35" ),
"field", "rowpointer",
"columnName", "field" ),
"cell_field17", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field17" ),
"field", "rowpointer",
"columnName", "field" ),
"footcell_field17", new XVar( "model", "footcell_field",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "print_header", new XVar( "type", "print_header" ),
"print_subheader", new XVar( "type", "print_subheader" ),
"print_pages", new XVar( "type", "print_pages" ),
"simple_grid_field", new XVar( "field", "trans_num",
"type", "grid_field" ),
"simple_grid_field18", new XVar( "type", "grid_field_label",
"field", "trans_num" ),
"simple_grid_field1", new XVar( "field", "emp_num",
"type", "grid_field" ),
"simple_grid_field19", new XVar( "type", "grid_field_label",
"field", "emp_num" ),
"simple_grid_field2", new XVar( "field", "trans_date",
"type", "grid_field" ),
"simple_grid_field20", new XVar( "type", "grid_field_label",
"field", "trans_date" ),
"simple_grid_field3", new XVar( "field", "sro_num",
"type", "grid_field" ),
"simple_grid_field21", new XVar( "type", "grid_field_label",
"field", "sro_num" ),
"simple_grid_field4", new XVar( "field", "line",
"type", "grid_field" ),
"simple_grid_field22", new XVar( "type", "grid_field_label",
"field", "line" ),
"simple_grid_field5", new XVar( "field", "oper_num",
"type", "grid_field" ),
"simple_grid_field23", new XVar( "type", "grid_field_label",
"field", "oper_num" ),
"simple_grid_field6", new XVar( "field", "misc_code",
"type", "grid_field" ),
"simple_grid_field24", new XVar( "type", "grid_field_label",
"field", "misc_code" ),
"simple_grid_field7", new XVar( "field", "qty",
"type", "grid_field" ),
"simple_grid_field25", new XVar( "type", "grid_field_label",
"field", "qty" ),
"simple_grid_field8", new XVar( "field", "pay_type",
"type", "grid_field" ),
"simple_grid_field26", new XVar( "type", "grid_field_label",
"field", "pay_type" ),
"simple_grid_field9", new XVar( "field", "cost",
"type", "grid_field" ),
"simple_grid_field27", new XVar( "type", "grid_field_label",
"field", "cost" ),
"simple_grid_field10", new XVar( "field", "price",
"type", "grid_field" ),
"simple_grid_field28", new XVar( "type", "grid_field_label",
"field", "price" ),
"simple_grid_field11", new XVar( "field", "curr_code",
"type", "grid_field" ),
"simple_grid_field29", new XVar( "type", "grid_field_label",
"field", "curr_code" ),
"simple_grid_field12", new XVar( "field", "report_id",
"type", "grid_field" ),
"simple_grid_field30", new XVar( "type", "grid_field_label",
"field", "report_id" ),
"simple_grid_field13", new XVar( "field", "posted",
"type", "grid_field" ),
"simple_grid_field31", new XVar( "type", "grid_field_label",
"field", "posted" ),
"simple_grid_field14", new XVar( "field", "batchid",
"type", "grid_field" ),
"simple_grid_field32", new XVar( "type", "grid_field_label",
"field", "batchid" ),
"simple_grid_field15", new XVar( "field", "clientid",
"type", "grid_field" ),
"simple_grid_field33", new XVar( "type", "grid_field_label",
"field", "clientid" ),
"simple_grid_field16", new XVar( "field", "site_ref",
"type", "grid_field" ),
"simple_grid_field34", new XVar( "type", "grid_field_label",
"field", "site_ref" ),
"simple_grid_field17", new XVar( "field", "rowpointer",
"type", "grid_field" ),
"simple_grid_field35", new XVar( "type", "grid_field_label",
"field", "rowpointer" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}