
		// dbo.sc_sro_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_sc_sro_mst_list
			{
				static public XVar options()
				{
					return new XVar( "list", new XVar( "inlineAdd", false,
"detailsAdd", false,
"inlineEdit", false,
"spreadsheetMode", false,
"addToBottom", false,
"delete", false,
"updateSelected", false,
"addInPopup", null,
"editInPopup", null,
"viewInPopup", null,
"clickSort", true,
"sortDropdown", false,
"showHideFields", false,
"reorderFields", false,
"fieldFilter", false,
"hideNumberOfRecords", false ),
"listSearch", new XVar( "alwaysOnPanelFields", XVar.Array(),
"searchPanel", true,
"fixedSearchPanel", false,
"simpleSearchOptions", false,
"searchSaving", false ),
"totals", new XVar( "trans_num", new XVar( "totalsType", "" ),
"emp_num", new XVar( "totalsType", "" ),
"trans_date", new XVar( "totalsType", "" ),
"sro_num", new XVar( "totalsType", "" ),
"line", new XVar( "totalsType", "" ),
"oper_num", new XVar( "totalsType", "" ),
"misc_code", new XVar( "totalsType", "" ),
"qty", new XVar( "totalsType", "" ),
"pay_type", new XVar( "totalsType", "" ),
"cost", new XVar( "totalsType", "" ),
"price", new XVar( "totalsType", "" ),
"curr_code", new XVar( "totalsType", "" ),
"report_id", new XVar( "totalsType", "" ),
"posted", new XVar( "totalsType", "" ),
"batchid", new XVar( "totalsType", "" ),
"clientid", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"rowpointer", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "trans_num",
1, "clientid",
2, "site_ref",
3, "trans_date",
4, "emp_num",
5, "sro_num",
6, "line",
7, "oper_num",
8, "misc_code",
9, "qty",
10, "pay_type",
11, "cost",
12, "price",
13, "curr_code",
14, "report_id",
15, "posted",
16, "rowpointer" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", new XVar( 0, "batchid",
1, "rowpointer",
2, "trans_num",
3, "trans_date",
4, "sro_num",
5, "site_ref",
6, "report_id",
7, "qty",
8, "price",
9, "posted",
10, "pay_type",
11, "oper_num",
12, "misc_code",
13, "line",
14, "emp_num",
15, "curr_code",
16, "cost",
17, "clientid" ),
"filterFields", XVar.Array(),
"inlineAddFields", new XVar( 0, "rowpointer" ),
"inlineEditFields", new XVar( 0, "rowpointer" ),
"fieldItems", new XVar( "trans_num", new XVar( 0, "simple_grid_field",
1, "simple_grid_field17" ),
"clientid", new XVar( 0, "simple_grid_field15",
1, "simple_grid_field18" ),
"site_ref", new XVar( 0, "simple_grid_field16",
1, "simple_grid_field19" ),
"trans_date", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field20" ),
"emp_num", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field21" ),
"sro_num", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field22" ),
"line", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field23" ),
"oper_num", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field24" ),
"misc_code", new XVar( 0, "simple_grid_field6",
1, "simple_grid_field25" ),
"qty", new XVar( 0, "simple_grid_field7",
1, "simple_grid_field26" ),
"pay_type", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field27" ),
"cost", new XVar( 0, "simple_grid_field9",
1, "simple_grid_field28" ),
"price", new XVar( 0, "simple_grid_field10",
1, "simple_grid_field29" ),
"curr_code", new XVar( 0, "simple_grid_field11",
1, "simple_grid_field30" ),
"report_id", new XVar( 0, "simple_grid_field12",
1, "simple_grid_field31" ),
"posted", new XVar( 0, "simple_grid_field13",
1, "simple_grid_field32" ),
"rowpointer", new XVar( 0, "simple_grid_field14",
1, "simple_grid_field33" ) ),
"hideEmptyFields", XVar.Array(),
"fieldFilterFields", XVar.Array() ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", true ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "details_found",
1, "page_size",
2, "print_panel" ),
"below-grid", new XVar( 0, "pagination" ),
"left", new XVar( 0, "logo",
1, "expand_button",
2, "menu",
3, "search_panel" ),
"supertop", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb",
3, "simple_search",
4, "list_options",
5, "loginform_login",
6, "username_button" ),
"top", XVar.Array(),
"grid", new XVar( 0, "simple_grid_field17",
1, "simple_grid_field",
2, "simple_grid_field18",
3, "simple_grid_field15",
4, "simple_grid_field19",
5, "simple_grid_field16",
6, "simple_grid_field20",
7, "simple_grid_field2",
8, "simple_grid_field21",
9, "simple_grid_field1",
10, "simple_grid_field22",
11, "simple_grid_field3",
12, "simple_grid_field23",
13, "simple_grid_field4",
14, "simple_grid_field24",
15, "simple_grid_field5",
16, "simple_grid_field25",
17, "simple_grid_field6",
18, "simple_grid_field26",
19, "simple_grid_field7",
20, "simple_grid_field27",
21, "simple_grid_field8",
22, "simple_grid_field28",
23, "simple_grid_field9",
24, "simple_grid_field29",
25, "simple_grid_field10",
26, "simple_grid_field30",
27, "simple_grid_field11",
28, "simple_grid_field31",
29, "simple_grid_field12",
30, "simple_grid_field32",
31, "simple_grid_field13",
32, "simple_grid_field33",
33, "simple_grid_field14",
34, "grid_checkbox_head",
35, "grid_checkbox" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "details_found",
1, "recsPerPage",
2, "print_friendly" ),
"below-grid", new XVar( 0, "pagination" ),
"top", XVar.Array() ),
"itemForms", new XVar( "details_found", "above-grid",
"page_size", "above-grid",
"print_panel", "above-grid",
"pagination", "below-grid",
"logo", "left",
"expand_button", "left",
"menu", "left",
"search_panel", "left",
"expand_menu_button", "supertop",
"collapse_button", "supertop",
"breadcrumb", "supertop",
"simple_search", "supertop",
"list_options", "supertop",
"loginform_login", "supertop",
"username_button", "supertop",
"simple_grid_field17", "grid",
"simple_grid_field", "grid",
"simple_grid_field18", "grid",
"simple_grid_field15", "grid",
"simple_grid_field19", "grid",
"simple_grid_field16", "grid",
"simple_grid_field20", "grid",
"simple_grid_field2", "grid",
"simple_grid_field21", "grid",
"simple_grid_field1", "grid",
"simple_grid_field22", "grid",
"simple_grid_field3", "grid",
"simple_grid_field23", "grid",
"simple_grid_field4", "grid",
"simple_grid_field24", "grid",
"simple_grid_field5", "grid",
"simple_grid_field25", "grid",
"simple_grid_field6", "grid",
"simple_grid_field26", "grid",
"simple_grid_field7", "grid",
"simple_grid_field27", "grid",
"simple_grid_field8", "grid",
"simple_grid_field28", "grid",
"simple_grid_field9", "grid",
"simple_grid_field29", "grid",
"simple_grid_field10", "grid",
"simple_grid_field30", "grid",
"simple_grid_field11", "grid",
"simple_grid_field31", "grid",
"simple_grid_field12", "grid",
"simple_grid_field32", "grid",
"simple_grid_field13", "grid",
"simple_grid_field33", "grid",
"simple_grid_field14", "grid",
"grid_checkbox_head", "grid",
"grid_checkbox", "grid" ),
"itemLocations", new XVar( "simple_grid_field17", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field18", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field15", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field19", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field16", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field20", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field21", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field22", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field23", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field24", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"simple_grid_field25", new XVar( "location", "grid",
"cellId", "headcell_field8" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "cell_field8" ),
"simple_grid_field26", new XVar( "location", "grid",
"cellId", "headcell_field9" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "cell_field9" ),
"simple_grid_field27", new XVar( "location", "grid",
"cellId", "headcell_field10" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "cell_field10" ),
"simple_grid_field28", new XVar( "location", "grid",
"cellId", "headcell_field11" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "cell_field11" ),
"simple_grid_field29", new XVar( "location", "grid",
"cellId", "headcell_field12" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "cell_field12" ),
"simple_grid_field30", new XVar( "location", "grid",
"cellId", "headcell_field13" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "cell_field13" ),
"simple_grid_field31", new XVar( "location", "grid",
"cellId", "headcell_field14" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "cell_field14" ),
"simple_grid_field32", new XVar( "location", "grid",
"cellId", "headcell_field15" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "cell_field15" ),
"simple_grid_field33", new XVar( "location", "grid",
"cellId", "headcell_field16" ),
"simple_grid_field14", new XVar( "location", "grid",
"cellId", "cell_field16" ),
"grid_checkbox_head", new XVar( "location", "grid",
"cellId", "headcell_checkbox" ),
"grid_checkbox", new XVar( "location", "grid",
"cellId", "cell_checkbox" ) ),
"itemVisiblity", new XVar( "breadcrumb", 5,
"expand_menu_button", 2,
"print_panel", 5,
"expand_button", 5 ) ),
"itemsByType", new XVar( "page_size", new XVar( 0, "page_size" ),
"breadcrumb", new XVar( 0, "breadcrumb" ),
"logo", new XVar( 0, "logo" ),
"menu", new XVar( 0, "menu" ),
"simple_search", new XVar( 0, "simple_search" ),
"pagination", new XVar( 0, "pagination" ),
"details_found", new XVar( 0, "details_found" ),
"search_panel", new XVar( 0, "search_panel" ),
"list_options", new XVar( 0, "list_options" ),
"show_search_panel", new XVar( 0, "show_search_panel" ),
"hide_search_panel", new XVar( 0, "hide_search_panel" ),
"search_panel_field", new XVar( 0, "search_panel_field",
1, "search_panel_field1",
2, "search_panel_field2",
3, "search_panel_field3",
4, "search_panel_field4",
5, "search_panel_field5",
6, "search_panel_field6",
7, "search_panel_field7",
8, "search_panel_field8",
9, "search_panel_field9",
10, "search_panel_field10",
11, "search_panel_field11",
12, "search_panel_field12",
13, "search_panel_field13",
14, "search_panel_field14",
15, "search_panel_field15",
16, "search_panel_field16",
17, "search_panel_field17" ),
"username_button", new XVar( 0, "username_button" ),
"loginform_login", new XVar( 0, "loginform_login" ),
"userinfo_link", new XVar( 0, "userinfo_link" ),
"logout_link", new XVar( 0, "logout_link" ),
"adminarea_link", new XVar( 0, "adminarea_link" ),
"changepassword_link", new XVar( 0, "changepassword_link" ),
"expand_menu_button", new XVar( 0, "expand_menu_button" ),
"collapse_button", new XVar( 0, "collapse_button" ),
"print_panel", new XVar( 0, "print_panel" ),
"print_scope", new XVar( 0, "print_scope" ),
"print_button", new XVar( 0, "print_button" ),
"print_records", new XVar( 0, "print_records" ),
"export", new XVar( 0, "export" ),
"-", new XVar( 0, "-",
1, "-1",
2, "-2" ),
"advsearch_link", new XVar( 0, "advsearch_link" ),
"grid_field", new XVar( 0, "simple_grid_field",
1, "simple_grid_field15",
2, "simple_grid_field16",
3, "simple_grid_field2",
4, "simple_grid_field1",
5, "simple_grid_field3",
6, "simple_grid_field4",
7, "simple_grid_field5",
8, "simple_grid_field6",
9, "simple_grid_field7",
10, "simple_grid_field8",
11, "simple_grid_field9",
12, "simple_grid_field10",
13, "simple_grid_field11",
14, "simple_grid_field12",
15, "simple_grid_field13",
16, "simple_grid_field14" ),
"grid_field_label", new XVar( 0, "simple_grid_field17",
1, "simple_grid_field18",
2, "simple_grid_field19",
3, "simple_grid_field20",
4, "simple_grid_field21",
5, "simple_grid_field22",
6, "simple_grid_field23",
7, "simple_grid_field24",
8, "simple_grid_field25",
9, "simple_grid_field26",
10, "simple_grid_field27",
11, "simple_grid_field28",
12, "simple_grid_field29",
13, "simple_grid_field30",
14, "simple_grid_field31",
15, "simple_grid_field32",
16, "simple_grid_field33" ),
"grid_checkbox", new XVar( 0, "grid_checkbox" ),
"grid_checkbox_head", new XVar( 0, "grid_checkbox_head" ),
"expand_button", new XVar( 0, "expand_button" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_checkbox", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox_head" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "trans_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field17" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "clientid_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field18" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "site_ref_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field19" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "trans_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field20" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "emp_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field21" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "sro_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field22" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "line_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field23" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "oper_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field24" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field8", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "misc_code_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field25" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field9", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "qty_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field26" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field10", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "pay_type_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field27" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field11", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "cost_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field28" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field12", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "price_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field29" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field13", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "curr_code_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field30" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field14", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "report_id_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field31" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field15", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "posted_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field32" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field16", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "rowpointer_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field33" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_checkbox", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "trans_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "clientid_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field15" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "site_ref_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field16" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "trans_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "emp_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "sro_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "line_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "oper_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field8", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "misc_code_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field9", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "qty_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field10", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "pay_type_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field11", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "cost_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field12", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "price_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field13", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "curr_code_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field14", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "report_id_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field15", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "posted_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field16", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "rowpointer_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field14" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_checkbox", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field8", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field9", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field10", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field11", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field12", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field13", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field14", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field15", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field16", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 18,
"height", 3 ) ) ),
"loginForm", new XVar( "loginForm", 0 ),
"page", new XVar( "verticalBar", true,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar( "details_found", new XVar( "tag", "DISPLAYING",
"type", 2 ) ) ),
"gridType", 0,
"recsPerRow", 1,
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", new XVar( 0, new XVar( "id", "main",
"horizontal", false ) ),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "list",
"breadcrumb", true ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"dataGrid", new XVar( "groupFields", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "list",
"type", "list",
"layoutId", "leftbar",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "list-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "details_found",
1, "page_size",
2, "print_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "list-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "pagination" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"left", new XVar( "modelId", "leftbar-menu",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c0" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c0", new XVar( "model", "c0",
"items", new XVar( 0, "logo",
1, "expand_button" ) ),
"c1", new XVar( "model", "c1",
"items", new XVar( 0, "menu",
1, "search_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"supertop", new XVar( "modelId", "leftbar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "simple_search",
1, "list_options",
2, "loginform_login",
3, "username_button" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "list-sidebar-top",
"grid", XVar.Array(),
"cells", new XVar(  ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_checkbox" ),
1, new XVar( "cell", "headcell_field" ),
2, new XVar( "cell", "headcell_field1" ),
3, new XVar( "cell", "headcell_field2" ),
4, new XVar( "cell", "headcell_field3" ),
5, new XVar( "cell", "headcell_field4" ),
6, new XVar( "cell", "headcell_field5" ),
7, new XVar( "cell", "headcell_field6" ),
8, new XVar( "cell", "headcell_field7" ),
9, new XVar( "cell", "headcell_field8" ),
10, new XVar( "cell", "headcell_field9" ),
11, new XVar( "cell", "headcell_field10" ),
12, new XVar( "cell", "headcell_field11" ),
13, new XVar( "cell", "headcell_field12" ),
14, new XVar( "cell", "headcell_field13" ),
15, new XVar( "cell", "headcell_field14" ),
16, new XVar( "cell", "headcell_field15" ),
17, new XVar( "cell", "headcell_field16" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_checkbox" ),
1, new XVar( "cell", "cell_field" ),
2, new XVar( "cell", "cell_field1" ),
3, new XVar( "cell", "cell_field2" ),
4, new XVar( "cell", "cell_field3" ),
5, new XVar( "cell", "cell_field4" ),
6, new XVar( "cell", "cell_field5" ),
7, new XVar( "cell", "cell_field6" ),
8, new XVar( "cell", "cell_field7" ),
9, new XVar( "cell", "cell_field8" ),
10, new XVar( "cell", "cell_field9" ),
11, new XVar( "cell", "cell_field10" ),
12, new XVar( "cell", "cell_field11" ),
13, new XVar( "cell", "cell_field12" ),
14, new XVar( "cell", "cell_field13" ),
15, new XVar( "cell", "cell_field14" ),
16, new XVar( "cell", "cell_field15" ),
17, new XVar( "cell", "cell_field16" ) ) ),
2, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_checkbox" ),
1, new XVar( "cell", "footcell_field" ),
2, new XVar( "cell", "footcell_field1" ),
3, new XVar( "cell", "footcell_field2" ),
4, new XVar( "cell", "footcell_field3" ),
5, new XVar( "cell", "footcell_field4" ),
6, new XVar( "cell", "footcell_field5" ),
7, new XVar( "cell", "footcell_field6" ),
8, new XVar( "cell", "footcell_field7" ),
9, new XVar( "cell", "footcell_field8" ),
10, new XVar( "cell", "footcell_field9" ),
11, new XVar( "cell", "footcell_field10" ),
12, new XVar( "cell", "footcell_field11" ),
13, new XVar( "cell", "footcell_field12" ),
14, new XVar( "cell", "footcell_field13" ),
15, new XVar( "cell", "footcell_field14" ),
16, new XVar( "cell", "footcell_field15" ),
17, new XVar( "cell", "footcell_field16" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field17" ),
"field", "trans_num",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "trans_num",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field18" ),
"field", "clientid",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field15" ),
"field", "clientid",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field19" ),
"field", "site_ref",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field16" ),
"field", "site_ref",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field20" ),
"field", "trans_date",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "trans_date",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field21" ),
"field", "emp_num",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "emp_num",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field22" ),
"field", "sro_num",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "sro_num",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field23" ),
"field", "line",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "line",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field24" ),
"field", "oper_num",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "oper_num",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field8", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field25" ),
"field", "misc_code",
"columnName", "field" ),
"cell_field8", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "misc_code",
"columnName", "field" ),
"footcell_field8", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field9", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field26" ),
"field", "qty",
"columnName", "field" ),
"cell_field9", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "qty",
"columnName", "field" ),
"footcell_field9", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field10", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field27" ),
"field", "pay_type",
"columnName", "field" ),
"cell_field10", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "pay_type",
"columnName", "field" ),
"footcell_field10", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field11", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field28" ),
"field", "cost",
"columnName", "field" ),
"cell_field11", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "cost",
"columnName", "field" ),
"footcell_field11", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field12", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field29" ),
"field", "price",
"columnName", "field" ),
"cell_field12", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "price",
"columnName", "field" ),
"footcell_field12", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field13", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field30" ),
"field", "curr_code",
"columnName", "field" ),
"cell_field13", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "curr_code",
"columnName", "field" ),
"footcell_field13", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field14", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field31" ),
"field", "report_id",
"columnName", "field" ),
"cell_field14", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "report_id",
"columnName", "field" ),
"footcell_field14", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field15", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field32" ),
"field", "posted",
"columnName", "field" ),
"cell_field15", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "posted",
"columnName", "field" ),
"footcell_field15", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field16", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field33" ),
"field", "rowpointer",
"columnName", "field" ),
"cell_field16", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field14" ),
"field", "rowpointer",
"columnName", "field" ),
"footcell_field16", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_checkbox", new XVar( "model", "headcell_checkbox",
"items", new XVar( 0, "grid_checkbox_head" ) ),
"cell_checkbox", new XVar( "model", "cell_checkbox",
"items", new XVar( 0, "grid_checkbox" ) ),
"footcell_checkbox", new XVar( "model", "footcell_checkbox",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "page_size", new XVar( "type", "page_size" ),
"breadcrumb", new XVar( "type", "breadcrumb" ),
"logo", new XVar( "type", "logo" ),
"menu", new XVar( "type", "menu" ),
"simple_search", new XVar( "type", "simple_search" ),
"pagination", new XVar( "type", "pagination" ),
"details_found", new XVar( "type", "details_found" ),
"search_panel", new XVar( "type", "search_panel",
"items", new XVar( 0, "search_panel_field",
1, "search_panel_field17",
2, "search_panel_field16",
3, "search_panel_field15",
4, "search_panel_field14",
5, "search_panel_field13",
6, "search_panel_field12",
7, "search_panel_field11",
8, "search_panel_field10",
9, "search_panel_field9",
10, "search_panel_field8",
11, "search_panel_field7",
12, "search_panel_field6",
13, "search_panel_field5",
14, "search_panel_field4",
15, "search_panel_field3",
16, "search_panel_field2",
17, "search_panel_field1" ) ),
"list_options", new XVar( "type", "list_options",
"items", new XVar( 0, "advsearch_link",
1, "show_search_panel",
2, "hide_search_panel",
3, "-2",
4, "export" ) ),
"show_search_panel", new XVar( "type", "show_search_panel" ),
"hide_search_panel", new XVar( "type", "hide_search_panel" ),
"search_panel_field", new XVar( "field", "batchid",
"type", "search_panel_field",
"required", false ),
"search_panel_field1", new XVar( "field", "clientid",
"type", "search_panel_field",
"required", false ),
"search_panel_field2", new XVar( "field", "cost",
"type", "search_panel_field",
"required", false ),
"search_panel_field3", new XVar( "field", "curr_code",
"type", "search_panel_field",
"required", false ),
"search_panel_field4", new XVar( "field", "emp_num",
"type", "search_panel_field",
"required", false ),
"search_panel_field5", new XVar( "field", "line",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field6", new XVar( "field", "misc_code",
"type", "search_panel_field",
"required", false ),
"search_panel_field7", new XVar( "field", "oper_num",
"type", "search_panel_field",
"required", false ),
"search_panel_field8", new XVar( "field", "pay_type",
"type", "search_panel_field",
"required", false ),
"search_panel_field9", new XVar( "field", "posted",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field10", new XVar( "field", "price",
"type", "search_panel_field",
"required", false ),
"search_panel_field11", new XVar( "field", "qty",
"type", "search_panel_field",
"required", false ),
"search_panel_field12", new XVar( "field", "report_id",
"type", "search_panel_field",
"required", false ),
"search_panel_field13", new XVar( "field", "site_ref",
"type", "search_panel_field",
"required", false ),
"search_panel_field14", new XVar( "field", "sro_num",
"type", "search_panel_field",
"required", false ),
"search_panel_field15", new XVar( "field", "trans_date",
"type", "search_panel_field",
"required", false ),
"search_panel_field16", new XVar( "field", "trans_num",
"type", "search_panel_field",
"required", false ),
"username_button", new XVar( "type", "username_button",
"items", new XVar( 0, "userinfo_link",
1, "logout_link",
2, "adminarea_link",
3, "changepassword_link" ) ),
"loginform_login", new XVar( "type", "loginform_login",
"popup", false ),
"userinfo_link", new XVar( "type", "userinfo_link" ),
"logout_link", new XVar( "type", "logout_link" ),
"adminarea_link", new XVar( "type", "adminarea_link" ),
"changepassword_link", new XVar( "type", "changepassword_link" ),
"expand_menu_button", new XVar( "type", "expand_menu_button" ),
"collapse_button", new XVar( "type", "collapse_button" ),
"print_panel", new XVar( "type", "print_panel",
"items", new XVar( 0, "print_scope",
1, "print_records",
2, "print_button" ) ),
"print_scope", new XVar( "type", "print_scope" ),
"print_button", new XVar( "type", "print_button" ),
"print_records", new XVar( "type", "print_records" ),
"export", new XVar( "type", "export" ),
"-", new XVar( "type", "-" ),
"-1", new XVar( "type", "-" ),
"advsearch_link", new XVar( "type", "advsearch_link" ),
"-2", new XVar( "type", "-" ),
"search_panel_field17", new XVar( "field", "rowpointer",
"type", "search_panel_field",
"required", false ),
"simple_grid_field", new XVar( "field", "trans_num",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field17", new XVar( "type", "grid_field_label",
"field", "trans_num" ),
"simple_grid_field15", new XVar( "field", "clientid",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field18", new XVar( "type", "grid_field_label",
"field", "clientid" ),
"simple_grid_field16", new XVar( "field", "site_ref",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field19", new XVar( "type", "grid_field_label",
"field", "site_ref" ),
"simple_grid_field2", new XVar( "field", "trans_date",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field20", new XVar( "type", "grid_field_label",
"field", "trans_date" ),
"simple_grid_field1", new XVar( "field", "emp_num",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field21", new XVar( "type", "grid_field_label",
"field", "emp_num" ),
"simple_grid_field3", new XVar( "field", "sro_num",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field22", new XVar( "type", "grid_field_label",
"field", "sro_num" ),
"simple_grid_field4", new XVar( "field", "line",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field23", new XVar( "type", "grid_field_label",
"field", "line" ),
"simple_grid_field5", new XVar( "field", "oper_num",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field24", new XVar( "type", "grid_field_label",
"field", "oper_num" ),
"simple_grid_field6", new XVar( "field", "misc_code",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field25", new XVar( "type", "grid_field_label",
"field", "misc_code" ),
"simple_grid_field7", new XVar( "field", "qty",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field26", new XVar( "type", "grid_field_label",
"field", "qty" ),
"simple_grid_field8", new XVar( "field", "pay_type",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field27", new XVar( "type", "grid_field_label",
"field", "pay_type" ),
"simple_grid_field9", new XVar( "field", "cost",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field28", new XVar( "type", "grid_field_label",
"field", "cost" ),
"simple_grid_field10", new XVar( "field", "price",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field29", new XVar( "type", "grid_field_label",
"field", "price" ),
"simple_grid_field11", new XVar( "field", "curr_code",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field30", new XVar( "type", "grid_field_label",
"field", "curr_code" ),
"simple_grid_field12", new XVar( "field", "report_id",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field31", new XVar( "type", "grid_field_label",
"field", "report_id" ),
"simple_grid_field13", new XVar( "field", "posted",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field32", new XVar( "type", "grid_field_label",
"field", "posted" ),
"simple_grid_field14", new XVar( "field", "rowpointer",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field33", new XVar( "type", "grid_field_label",
"field", "rowpointer" ),
"grid_checkbox", new XVar( "type", "grid_checkbox" ),
"grid_checkbox_head", new XVar( "type", "grid_checkbox_head" ),
"expand_button", new XVar( "type", "expand_button" ) ),
"dbProps", new XVar(  ),
"spreadsheetGrid", false,
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}