
		// dbo.sf_customer_master
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_sf_customer_master_list
			{
				static public XVar options()
				{
					return new XVar( "list", new XVar( "inlineAdd", false,
"detailsAdd", false,
"inlineEdit", false,
"spreadsheetMode", false,
"reorderRows", false,
"addToBottom", false,
"delete", false,
"updateSelected", false,
"addInPopup", null,
"editInPopup", null,
"clickSort", true,
"sortDropdown", false,
"showHideFields", false,
"reorderFields", false,
"fieldFilter", false,
"hideNumberOfRecords", false ),
"listSearch", new XVar( "alwaysOnPanelFields", XVar.Array(),
"searchPanel", true,
"fixedSearchPanel", false,
"simpleSearchOptions", false,
"searchSaving", false ),
"totals", new XVar( "clientid", new XVar( "totalsType", "" ),
"sf_posted", new XVar( "totalsType", "" ),
"mg_posted", new XVar( "totalsType", "" ),
"cust_num", new XVar( "totalsType", "" ),
"cust_seq", new XVar( "totalsType", "" ),
"name", new XVar( "totalsType", "" ),
"city", new XVar( "totalsType", "" ),
"state", new XVar( "totalsType", "" ),
"zip", new XVar( "totalsType", "" ),
"country", new XVar( "totalsType", "" ),
"county", new XVar( "totalsType", "" ),
"address", new XVar( "totalsType", "" ),
"contact1", new XVar( "totalsType", "" ),
"phone1", new XVar( "totalsType", "" ),
"contact2", new XVar( "totalsType", "" ),
"phone2", new XVar( "totalsType", "" ),
"contact3", new XVar( "totalsType", "" ),
"phone3", new XVar( "totalsType", "" ),
"credit_limit", new XVar( "totalsType", "" ),
"terms_code", new XVar( "totalsType", "" ),
"curr_code", new XVar( "totalsType", "" ),
"ship_to_email", new XVar( "totalsType", "" ),
"bill_to_email", new XVar( "totalsType", "" ),
"internet_url", new XVar( "totalsType", "" ),
"internal_email_addr", new XVar( "totalsType", "" ),
"external_email_addr", new XVar( "totalsType", "" ),
"RowPointer", new XVar( "totalsType", "" ),
"sf_id", new XVar( "totalsType", "" ),
"accountnumber", new XVar( "totalsType", "" ),
"parentaccount", new XVar( "totalsType", "" ),
"uf_uet1", new XVar( "totalsType", "" ),
"uf_uet2", new XVar( "totalsType", "" ),
"uf_uet3", new XVar( "totalsType", "" ),
"uf_uet4", new XVar( "totalsType", "" ),
"uf_uet5", new XVar( "totalsType", "" ),
"uf_uet6", new XVar( "totalsType", "" ),
"uf_uet7", new XVar( "totalsType", "" ),
"uf_uet8", new XVar( "totalsType", "" ),
"uf_uet9", new XVar( "totalsType", "" ),
"uf_uet10", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"SalesForceID_Uf", new XVar( "totalsType", "" ),
"err_message", new XVar( "totalsType", "" ),
"order_bal", new XVar( "totalsType", "" ),
"sales_ytd", new XVar( "totalsType", "" ),
"sales_lst_yr", new XVar( "totalsType", "" ),
"posted_bal", new XVar( "totalsType", "" ),
"parent_account", new XVar( "totalsType", "" ),
"slsman", new XVar( "totalsType", "" ),
"cust_type", new XVar( "totalsType", "" ),
"pricecode", new XVar( "totalsType", "" ),
"DLDeleteIndicator", new XVar( "totalsType", "" ),
"VariationNumber", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "clientid",
1, "accountnumber",
2, "parentaccount",
3, "sf_posted",
4, "sf_id",
5, "cust_num",
6, "cust_seq",
7, "name",
8, "city",
9, "state",
10, "zip",
11, "country",
12, "terms_code",
13, "curr_code",
14, "site_ref",
15, "SalesForceID_Uf",
16, "err_message",
17, "order_bal",
18, "sales_ytd",
19, "sales_lst_yr",
20, "posted_bal",
21, "parent_account",
22, "slsman",
23, "cust_type",
24, "pricecode",
25, "DLDeleteIndicator",
26, "VariationNumber" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", new XVar( 0, "RowPointer",
1, "VariationNumber",
2, "DLDeleteIndicator",
3, "pricecode",
4, "cust_type",
5, "slsman",
6, "parent_account",
7, "posted_bal",
8, "sales_lst_yr",
9, "sales_ytd",
10, "order_bal",
11, "err_message",
12, "SalesForceID_Uf",
13, "site_ref",
14, "address",
15, "uf_uet10",
16, "uf_uet9",
17, "uf_uet8",
18, "uf_uet7",
19, "uf_uet6",
20, "uf_uet5",
21, "uf_uet4",
22, "uf_uet3",
23, "uf_uet2",
24, "uf_uet1",
25, "zip",
26, "terms_code",
27, "state",
28, "ship_to_email",
29, "sf_posted",
30, "sf_id",
31, "phone3",
32, "phone2",
33, "phone1",
34, "parentaccount",
35, "name",
36, "internet_url",
37, "internal_email_addr",
38, "external_email_addr",
39, "cust_seq",
40, "cust_num",
41, "curr_code",
42, "credit_limit",
43, "county",
44, "country",
45, "contact3",
46, "contact2",
47, "contact1",
48, "clientid",
49, "city",
50, "bill_to_email",
51, "accountnumber" ),
"filterFields", new XVar( 0, "clientid" ),
"inlineAddFields", new XVar( 0, "site_ref",
1, "SalesForceID_Uf",
2, "err_message",
3, "order_bal",
4, "sales_ytd",
5, "sales_lst_yr",
6, "posted_bal",
7, "parent_account",
8, "slsman",
9, "cust_type",
10, "pricecode",
11, "DLDeleteIndicator",
12, "VariationNumber" ),
"inlineEditFields", new XVar( 0, "site_ref",
1, "SalesForceID_Uf",
2, "err_message",
3, "order_bal",
4, "sales_ytd",
5, "sales_lst_yr",
6, "posted_bal",
7, "parent_account",
8, "slsman",
9, "cust_type",
10, "pricecode",
11, "DLDeleteIndicator",
12, "VariationNumber" ),
"fieldItems", new XVar( "clientid", new XVar( 0, "simple_grid_field",
1, "simple_grid_field24" ),
"accountnumber", new XVar( 0, "simple_grid_field31",
1, "simple_grid_field33" ),
"parentaccount", new XVar( 0, "simple_grid_field32",
1, "simple_grid_field34" ),
"sf_posted", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field25" ),
"sf_id", new XVar( 0, "simple_grid_field30",
1, "simple_grid_field35" ),
"cust_num", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field26" ),
"cust_seq", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field27" ),
"name", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field28" ),
"city", new XVar( 0, "simple_grid_field6",
1, "simple_grid_field29" ),
"state", new XVar( 0, "simple_grid_field7",
1, "simple_grid_field36" ),
"zip", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field37" ),
"country", new XVar( 0, "simple_grid_field9",
1, "simple_grid_field38" ),
"terms_code", new XVar( 0, "simple_grid_field22",
1, "simple_grid_field39" ),
"curr_code", new XVar( 0, "simple_grid_field23",
1, "simple_grid_field40" ),
"site_ref", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field41" ),
"SalesForceID_Uf", new XVar( 0, "simple_grid_field10",
1, "simple_grid_field42" ),
"err_message", new XVar( 0, "simple_grid_field11",
1, "simple_grid_field43" ),
"order_bal", new XVar( 0, "simple_grid_field12",
1, "simple_grid_field44" ),
"sales_ytd", new XVar( 0, "simple_grid_field13",
1, "simple_grid_field45" ),
"sales_lst_yr", new XVar( 0, "simple_grid_field14",
1, "simple_grid_field46" ),
"posted_bal", new XVar( 0, "simple_grid_field15",
1, "simple_grid_field47" ),
"parent_account", new XVar( 0, "simple_grid_field16",
1, "simple_grid_field48" ),
"slsman", new XVar( 0, "simple_grid_field17",
1, "simple_grid_field49" ),
"cust_type", new XVar( 0, "simple_grid_field18",
1, "simple_grid_field50" ),
"pricecode", new XVar( 0, "simple_grid_field19",
1, "simple_grid_field51" ),
"DLDeleteIndicator", new XVar( 0, "simple_grid_field20",
1, "simple_grid_field52" ),
"VariationNumber", new XVar( 0, "simple_grid_field21",
1, "simple_grid_field53" ) ),
"hideEmptyFields", XVar.Array(),
"fieldFilterFields", XVar.Array() ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", true,
"print", true ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "details_found",
1, "page_size",
2, "print_panel" ),
"below-grid", new XVar( 0, "pagination" ),
"left", new XVar( 0, "logo",
1, "expand_button",
2, "menu",
3, "search_panel",
4, "filter_panel" ),
"supertop", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb",
3, "simple_search",
4, "list_options",
5, "loginform_login",
6, "username_button" ),
"top", XVar.Array(),
"grid", new XVar( 0, "simple_grid_field24",
1, "simple_grid_field",
2, "simple_grid_field33",
3, "simple_grid_field31",
4, "simple_grid_field34",
5, "simple_grid_field32",
6, "simple_grid_field25",
7, "simple_grid_field1",
8, "simple_grid_field35",
9, "simple_grid_field30",
10, "simple_grid_field26",
11, "simple_grid_field3",
12, "simple_grid_field27",
13, "simple_grid_field4",
14, "simple_grid_field28",
15, "simple_grid_field5",
16, "simple_grid_field29",
17, "simple_grid_field6",
18, "simple_grid_field36",
19, "simple_grid_field7",
20, "simple_grid_field37",
21, "simple_grid_field8",
22, "simple_grid_field38",
23, "simple_grid_field9",
24, "simple_grid_field39",
25, "simple_grid_field22",
26, "simple_grid_field40",
27, "simple_grid_field23",
28, "simple_grid_field41",
29, "simple_grid_field2",
30, "simple_grid_field42",
31, "simple_grid_field10",
32, "simple_grid_field43",
33, "simple_grid_field11",
34, "simple_grid_field44",
35, "simple_grid_field12",
36, "simple_grid_field45",
37, "simple_grid_field13",
38, "simple_grid_field46",
39, "simple_grid_field14",
40, "simple_grid_field47",
41, "simple_grid_field15",
42, "simple_grid_field48",
43, "simple_grid_field16",
44, "simple_grid_field49",
45, "simple_grid_field17",
46, "simple_grid_field50",
47, "simple_grid_field18",
48, "simple_grid_field51",
49, "simple_grid_field19",
50, "simple_grid_field52",
51, "simple_grid_field20",
52, "simple_grid_field53",
53, "simple_grid_field21",
54, "grid_checkbox_head",
55, "grid_checkbox",
56, "grid_view" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "details_found",
1, "recsPerPage",
2, "print_friendly" ),
"below-grid", new XVar( 0, "pagination" ),
"top", XVar.Array() ),
"itemForms", new XVar( "details_found", "above-grid",
"page_size", "above-grid",
"print_panel", "above-grid",
"pagination", "below-grid",
"logo", "left",
"expand_button", "left",
"menu", "left",
"search_panel", "left",
"filter_panel", "left",
"expand_menu_button", "supertop",
"collapse_button", "supertop",
"breadcrumb", "supertop",
"simple_search", "supertop",
"list_options", "supertop",
"loginform_login", "supertop",
"username_button", "supertop",
"simple_grid_field24", "grid",
"simple_grid_field", "grid",
"simple_grid_field33", "grid",
"simple_grid_field31", "grid",
"simple_grid_field34", "grid",
"simple_grid_field32", "grid",
"simple_grid_field25", "grid",
"simple_grid_field1", "grid",
"simple_grid_field35", "grid",
"simple_grid_field30", "grid",
"simple_grid_field26", "grid",
"simple_grid_field3", "grid",
"simple_grid_field27", "grid",
"simple_grid_field4", "grid",
"simple_grid_field28", "grid",
"simple_grid_field5", "grid",
"simple_grid_field29", "grid",
"simple_grid_field6", "grid",
"simple_grid_field36", "grid",
"simple_grid_field7", "grid",
"simple_grid_field37", "grid",
"simple_grid_field8", "grid",
"simple_grid_field38", "grid",
"simple_grid_field9", "grid",
"simple_grid_field39", "grid",
"simple_grid_field22", "grid",
"simple_grid_field40", "grid",
"simple_grid_field23", "grid",
"simple_grid_field41", "grid",
"simple_grid_field2", "grid",
"simple_grid_field42", "grid",
"simple_grid_field10", "grid",
"simple_grid_field43", "grid",
"simple_grid_field11", "grid",
"simple_grid_field44", "grid",
"simple_grid_field12", "grid",
"simple_grid_field45", "grid",
"simple_grid_field13", "grid",
"simple_grid_field46", "grid",
"simple_grid_field14", "grid",
"simple_grid_field47", "grid",
"simple_grid_field15", "grid",
"simple_grid_field48", "grid",
"simple_grid_field16", "grid",
"simple_grid_field49", "grid",
"simple_grid_field17", "grid",
"simple_grid_field50", "grid",
"simple_grid_field18", "grid",
"simple_grid_field51", "grid",
"simple_grid_field19", "grid",
"simple_grid_field52", "grid",
"simple_grid_field20", "grid",
"simple_grid_field53", "grid",
"simple_grid_field21", "grid",
"grid_checkbox_head", "grid",
"grid_checkbox", "grid",
"grid_view", "grid" ),
"itemLocations", new XVar( "simple_grid_field24", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field33", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field31", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field34", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field32", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field25", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field35", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field30", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field26", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field27", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field28", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"simple_grid_field29", new XVar( "location", "grid",
"cellId", "headcell_field8" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "cell_field8" ),
"simple_grid_field36", new XVar( "location", "grid",
"cellId", "headcell_field9" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "cell_field9" ),
"simple_grid_field37", new XVar( "location", "grid",
"cellId", "headcell_field10" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "cell_field10" ),
"simple_grid_field38", new XVar( "location", "grid",
"cellId", "headcell_field11" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "cell_field11" ),
"simple_grid_field39", new XVar( "location", "grid",
"cellId", "headcell_field12" ),
"simple_grid_field22", new XVar( "location", "grid",
"cellId", "cell_field12" ),
"simple_grid_field40", new XVar( "location", "grid",
"cellId", "headcell_field13" ),
"simple_grid_field23", new XVar( "location", "grid",
"cellId", "cell_field13" ),
"simple_grid_field41", new XVar( "location", "grid",
"cellId", "headcell_field14" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field14" ),
"simple_grid_field42", new XVar( "location", "grid",
"cellId", "headcell_field15" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "cell_field15" ),
"simple_grid_field43", new XVar( "location", "grid",
"cellId", "headcell_field16" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "cell_field16" ),
"simple_grid_field44", new XVar( "location", "grid",
"cellId", "headcell_field17" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "cell_field17" ),
"simple_grid_field45", new XVar( "location", "grid",
"cellId", "headcell_field18" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "cell_field18" ),
"simple_grid_field46", new XVar( "location", "grid",
"cellId", "headcell_field19" ),
"simple_grid_field14", new XVar( "location", "grid",
"cellId", "cell_field19" ),
"simple_grid_field47", new XVar( "location", "grid",
"cellId", "headcell_field20" ),
"simple_grid_field15", new XVar( "location", "grid",
"cellId", "cell_field20" ),
"simple_grid_field48", new XVar( "location", "grid",
"cellId", "headcell_field21" ),
"simple_grid_field16", new XVar( "location", "grid",
"cellId", "cell_field21" ),
"simple_grid_field49", new XVar( "location", "grid",
"cellId", "headcell_field22" ),
"simple_grid_field17", new XVar( "location", "grid",
"cellId", "cell_field22" ),
"simple_grid_field50", new XVar( "location", "grid",
"cellId", "headcell_field23" ),
"simple_grid_field18", new XVar( "location", "grid",
"cellId", "cell_field23" ),
"simple_grid_field51", new XVar( "location", "grid",
"cellId", "headcell_field24" ),
"simple_grid_field19", new XVar( "location", "grid",
"cellId", "cell_field24" ),
"simple_grid_field52", new XVar( "location", "grid",
"cellId", "headcell_field25" ),
"simple_grid_field20", new XVar( "location", "grid",
"cellId", "cell_field25" ),
"simple_grid_field53", new XVar( "location", "grid",
"cellId", "headcell_field26" ),
"simple_grid_field21", new XVar( "location", "grid",
"cellId", "cell_field26" ),
"grid_checkbox_head", new XVar( "location", "grid",
"cellId", "headcell_checkbox" ),
"grid_checkbox", new XVar( "location", "grid",
"cellId", "cell_checkbox" ),
"grid_view", new XVar( "location", "grid",
"cellId", "cell_icons" ) ),
"itemVisiblity", new XVar( "breadcrumb", 5,
"expand_menu_button", 2,
"print_panel", 5,
"expand_button", 5 ) ),
"itemsByType", new XVar( "page_size", new XVar( 0, "page_size" ),
"breadcrumb", new XVar( 0, "breadcrumb" ),
"logo", new XVar( 0, "logo" ),
"menu", new XVar( 0, "menu" ),
"simple_search", new XVar( 0, "simple_search" ),
"pagination", new XVar( 0, "pagination" ),
"details_found", new XVar( 0, "details_found" ),
"search_panel", new XVar( 0, "search_panel" ),
"list_options", new XVar( 0, "list_options" ),
"-", new XVar( 0, "-2",
1, "-",
2, "-1" ),
"advsearch_link", new XVar( 0, "advsearch_link" ),
"username_button", new XVar( 0, "username_button" ),
"loginform_login", new XVar( 0, "loginform_login" ),
"userinfo_link", new XVar( 0, "userinfo_link" ),
"logout_link", new XVar( 0, "logout_link" ),
"adminarea_link", new XVar( 0, "adminarea_link" ),
"expand_menu_button", new XVar( 0, "expand_menu_button" ),
"collapse_button", new XVar( 0, "collapse_button" ),
"print_panel", new XVar( 0, "print_panel" ),
"print_scope", new XVar( 0, "print_scope" ),
"print_button", new XVar( 0, "print_button" ),
"print_records", new XVar( 0, "print_records" ),
"export", new XVar( 0, "export" ),
"import", new XVar( 0, "import" ),
"show_search_panel", new XVar( 0, "show_search_panel" ),
"hide_search_panel", new XVar( 0, "hide_search_panel" ),
"search_panel_field", new XVar( 0, "search_panel_field",
1, "search_panel_field1",
2, "search_panel_field2",
3, "search_panel_field6",
4, "search_panel_field7",
5, "search_panel_field8",
6, "search_panel_field9",
7, "search_panel_field10",
8, "search_panel_field11",
9, "search_panel_field12",
10, "search_panel_field13",
11, "search_panel_field14",
12, "search_panel_field15",
13, "search_panel_field16",
14, "search_panel_field17",
15, "search_panel_field18",
16, "search_panel_field19",
17, "search_panel_field20",
18, "search_panel_field22",
19, "search_panel_field23",
20, "search_panel_field24",
21, "search_panel_field25",
22, "search_panel_field26",
23, "search_panel_field27",
24, "search_panel_field28",
25, "search_panel_field29",
26, "search_panel_field30",
27, "search_panel_field31",
28, "search_panel_field32",
29, "search_panel_field21",
30, "search_panel_field33",
31, "search_panel_field34",
32, "search_panel_field35",
33, "search_panel_field36",
34, "search_panel_field37",
35, "search_panel_field38",
36, "search_panel_field39",
37, "search_panel_field40",
38, "search_panel_field41",
39, "search_panel_field3",
40, "search_panel_field4",
41, "search_panel_field5",
42, "search_panel_field42",
43, "search_panel_field43",
44, "search_panel_field44",
45, "search_panel_field45",
46, "search_panel_field46",
47, "search_panel_field47",
48, "search_panel_field48",
49, "search_panel_field49",
50, "search_panel_field50",
51, "search_panel_field51" ),
"filter_panel", new XVar( 0, "filter_panel" ),
"filter_panel_field", new XVar( 0, "filter_panel_field" ),
"changepassword_link", new XVar( 0, "changepassword_link" ),
"grid_field", new XVar( 0, "simple_grid_field",
1, "simple_grid_field31",
2, "simple_grid_field32",
3, "simple_grid_field1",
4, "simple_grid_field30",
5, "simple_grid_field3",
6, "simple_grid_field4",
7, "simple_grid_field5",
8, "simple_grid_field6",
9, "simple_grid_field7",
10, "simple_grid_field8",
11, "simple_grid_field9",
12, "simple_grid_field22",
13, "simple_grid_field23",
14, "simple_grid_field2",
15, "simple_grid_field10",
16, "simple_grid_field11",
17, "simple_grid_field12",
18, "simple_grid_field13",
19, "simple_grid_field14",
20, "simple_grid_field15",
21, "simple_grid_field16",
22, "simple_grid_field17",
23, "simple_grid_field18",
24, "simple_grid_field19",
25, "simple_grid_field20",
26, "simple_grid_field21" ),
"grid_field_label", new XVar( 0, "simple_grid_field24",
1, "simple_grid_field33",
2, "simple_grid_field34",
3, "simple_grid_field25",
4, "simple_grid_field35",
5, "simple_grid_field26",
6, "simple_grid_field27",
7, "simple_grid_field28",
8, "simple_grid_field29",
9, "simple_grid_field36",
10, "simple_grid_field37",
11, "simple_grid_field38",
12, "simple_grid_field39",
13, "simple_grid_field40",
14, "simple_grid_field41",
15, "simple_grid_field42",
16, "simple_grid_field43",
17, "simple_grid_field44",
18, "simple_grid_field45",
19, "simple_grid_field46",
20, "simple_grid_field47",
21, "simple_grid_field48",
22, "simple_grid_field49",
23, "simple_grid_field50",
24, "simple_grid_field51",
25, "simple_grid_field52",
26, "simple_grid_field53" ),
"grid_checkbox", new XVar( 0, "grid_checkbox" ),
"grid_checkbox_head", new XVar( 0, "grid_checkbox_head" ),
"grid_view", new XVar( 0, "grid_view" ),
"expand_button", new XVar( 0, "expand_button" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox_head" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "clientid_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field24" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "accountnumber_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field33" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "parentaccount_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field34" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "sf_posted_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field25" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "sf_id_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field35" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "cust_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field26" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "cust_seq_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field27" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "name_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field28" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field8", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "city_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field29" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field9", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "state_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field36" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field10", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "zip_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field37" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field11", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "country_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field38" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field12", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "terms_code_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field39" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field13", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "curr_code_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field40" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field14", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "site_ref_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field41" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field15", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "SalesForceID_Uf_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field42" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field16", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "err_message_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field43" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field17", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "order_bal_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field44" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field18", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "sales_ytd_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field45" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field19", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "sales_lst_yr_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field46" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field20", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "posted_bal_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field47" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field21", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "parent_account_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field48" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field22", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "slsman_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field49" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field23", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "cust_type_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field50" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field24", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "pricecode_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field51" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field25", new XVar( "cols", new XVar( 0, 27 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "DLDeleteIndicator_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field52" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field26", new XVar( "cols", new XVar( 0, 28 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "VariationNumber_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field53" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "view_column" ),
"items", new XVar( 0, "grid_view" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "clientid_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "accountnumber_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field31" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "parentaccount_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field32" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "sf_posted_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "sf_id_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field30" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "cust_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "cust_seq_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "name_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field8", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "city_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field9", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "state_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field10", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "zip_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field11", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "country_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field12", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "terms_code_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field22" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field13", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "curr_code_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field23" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field14", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "site_ref_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field15", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "SalesForceID_Uf_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field16", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "err_message_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field17", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "order_bal_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field18", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "sales_ytd_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field19", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "sales_lst_yr_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field14" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field20", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "posted_bal_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field15" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field21", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "parent_account_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field16" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field22", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "slsman_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field17" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field23", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "cust_type_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field18" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field24", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "pricecode_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field19" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field25", new XVar( "cols", new XVar( 0, 27 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "DLDeleteIndicator_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field20" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field26", new XVar( "cols", new XVar( 0, 28 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "VariationNumber_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field21" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field8", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field9", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field10", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field11", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field12", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field13", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field14", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field15", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field16", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field17", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field18", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field19", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field20", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field21", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field22", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field23", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field24", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field25", new XVar( "cols", new XVar( 0, 27 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field26", new XVar( "cols", new XVar( 0, 28 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 29,
"height", 3 ) ) ),
"loginForm", new XVar( "loginForm", 0 ),
"page", new XVar( "verticalBar", true,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar( "details_found", new XVar( "tag", "DISPLAYING",
"type", 2 ) ) ),
"gridType", 0,
"recsPerRow", 1,
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", new XVar( 0, new XVar( "id", "main",
"horizontal", false ) ),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "list",
"breadcrumb", true ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"dataGrid", new XVar( "groupFields", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "list",
"type", "list",
"layoutId", "leftbar",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "list-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "details_found",
1, "page_size",
2, "print_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "list-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "pagination" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"left", new XVar( "modelId", "leftbar-menu",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c0" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c0", new XVar( "model", "c0",
"items", new XVar( 0, "logo",
1, "expand_button" ) ),
"c1", new XVar( "model", "c1",
"items", new XVar( 0, "menu",
1, "search_panel",
2, "filter_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"supertop", new XVar( "modelId", "leftbar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "simple_search",
1, "list_options",
2, "loginform_login",
3, "username_button" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "list-sidebar-top",
"grid", XVar.Array(),
"cells", new XVar(  ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_icons" ),
1, new XVar( "cell", "headcell_checkbox" ),
2, new XVar( "cell", "headcell_field" ),
3, new XVar( "cell", "headcell_field1" ),
4, new XVar( "cell", "headcell_field2" ),
5, new XVar( "cell", "headcell_field3" ),
6, new XVar( "cell", "headcell_field4" ),
7, new XVar( "cell", "headcell_field5" ),
8, new XVar( "cell", "headcell_field6" ),
9, new XVar( "cell", "headcell_field7" ),
10, new XVar( "cell", "headcell_field8" ),
11, new XVar( "cell", "headcell_field9" ),
12, new XVar( "cell", "headcell_field10" ),
13, new XVar( "cell", "headcell_field11" ),
14, new XVar( "cell", "headcell_field12" ),
15, new XVar( "cell", "headcell_field13" ),
16, new XVar( "cell", "headcell_field14" ),
17, new XVar( "cell", "headcell_field15" ),
18, new XVar( "cell", "headcell_field16" ),
19, new XVar( "cell", "headcell_field17" ),
20, new XVar( "cell", "headcell_field18" ),
21, new XVar( "cell", "headcell_field19" ),
22, new XVar( "cell", "headcell_field20" ),
23, new XVar( "cell", "headcell_field21" ),
24, new XVar( "cell", "headcell_field22" ),
25, new XVar( "cell", "headcell_field23" ),
26, new XVar( "cell", "headcell_field24" ),
27, new XVar( "cell", "headcell_field25" ),
28, new XVar( "cell", "headcell_field26" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_icons" ),
1, new XVar( "cell", "cell_checkbox" ),
2, new XVar( "cell", "cell_field" ),
3, new XVar( "cell", "cell_field1" ),
4, new XVar( "cell", "cell_field2" ),
5, new XVar( "cell", "cell_field3" ),
6, new XVar( "cell", "cell_field4" ),
7, new XVar( "cell", "cell_field5" ),
8, new XVar( "cell", "cell_field6" ),
9, new XVar( "cell", "cell_field7" ),
10, new XVar( "cell", "cell_field8" ),
11, new XVar( "cell", "cell_field9" ),
12, new XVar( "cell", "cell_field10" ),
13, new XVar( "cell", "cell_field11" ),
14, new XVar( "cell", "cell_field12" ),
15, new XVar( "cell", "cell_field13" ),
16, new XVar( "cell", "cell_field14" ),
17, new XVar( "cell", "cell_field15" ),
18, new XVar( "cell", "cell_field16" ),
19, new XVar( "cell", "cell_field17" ),
20, new XVar( "cell", "cell_field18" ),
21, new XVar( "cell", "cell_field19" ),
22, new XVar( "cell", "cell_field20" ),
23, new XVar( "cell", "cell_field21" ),
24, new XVar( "cell", "cell_field22" ),
25, new XVar( "cell", "cell_field23" ),
26, new XVar( "cell", "cell_field24" ),
27, new XVar( "cell", "cell_field25" ),
28, new XVar( "cell", "cell_field26" ) ) ),
2, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_icons" ),
1, new XVar( "cell", "footcell_checkbox" ),
2, new XVar( "cell", "footcell_field" ),
3, new XVar( "cell", "footcell_field1" ),
4, new XVar( "cell", "footcell_field2" ),
5, new XVar( "cell", "footcell_field3" ),
6, new XVar( "cell", "footcell_field4" ),
7, new XVar( "cell", "footcell_field5" ),
8, new XVar( "cell", "footcell_field6" ),
9, new XVar( "cell", "footcell_field7" ),
10, new XVar( "cell", "footcell_field8" ),
11, new XVar( "cell", "footcell_field9" ),
12, new XVar( "cell", "footcell_field10" ),
13, new XVar( "cell", "footcell_field11" ),
14, new XVar( "cell", "footcell_field12" ),
15, new XVar( "cell", "footcell_field13" ),
16, new XVar( "cell", "footcell_field14" ),
17, new XVar( "cell", "footcell_field15" ),
18, new XVar( "cell", "footcell_field16" ),
19, new XVar( "cell", "footcell_field17" ),
20, new XVar( "cell", "footcell_field18" ),
21, new XVar( "cell", "footcell_field19" ),
22, new XVar( "cell", "footcell_field20" ),
23, new XVar( "cell", "footcell_field21" ),
24, new XVar( "cell", "footcell_field22" ),
25, new XVar( "cell", "footcell_field23" ),
26, new XVar( "cell", "footcell_field24" ),
27, new XVar( "cell", "footcell_field25" ),
28, new XVar( "cell", "footcell_field26" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field24" ),
"field", "clientid",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "clientid",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field33" ),
"field", "accountnumber",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field31" ),
"field", "accountnumber",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field34" ),
"field", "parentaccount",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field32" ),
"field", "parentaccount",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field25" ),
"field", "sf_posted",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "sf_posted",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field35" ),
"field", "sf_id",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field30" ),
"field", "sf_id",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field26" ),
"field", "cust_num",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "cust_num",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field27" ),
"field", "cust_seq",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "cust_seq",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field28" ),
"field", "name",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "name",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field8", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field29" ),
"field", "city",
"columnName", "field" ),
"cell_field8", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "city",
"columnName", "field" ),
"footcell_field8", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field9", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field36" ),
"field", "state",
"columnName", "field" ),
"cell_field9", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "state",
"columnName", "field" ),
"footcell_field9", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field10", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field37" ),
"field", "zip",
"columnName", "field" ),
"cell_field10", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "zip",
"columnName", "field" ),
"footcell_field10", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field11", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field38" ),
"field", "country",
"columnName", "field" ),
"cell_field11", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "country",
"columnName", "field" ),
"footcell_field11", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field12", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field39" ),
"field", "terms_code",
"columnName", "field" ),
"cell_field12", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field22" ),
"field", "terms_code",
"columnName", "field" ),
"footcell_field12", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field13", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field40" ),
"field", "curr_code",
"columnName", "field" ),
"cell_field13", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field23" ),
"field", "curr_code",
"columnName", "field" ),
"footcell_field13", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field14", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field41" ),
"field", "site_ref",
"columnName", "field" ),
"cell_field14", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "site_ref",
"columnName", "field" ),
"footcell_field14", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field15", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field42" ),
"field", "SalesForceID_Uf",
"columnName", "field" ),
"cell_field15", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "SalesForceID_Uf",
"columnName", "field" ),
"footcell_field15", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field16", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field43" ),
"field", "err_message",
"columnName", "field" ),
"cell_field16", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "err_message",
"columnName", "field" ),
"footcell_field16", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field17", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field44" ),
"field", "order_bal",
"columnName", "field" ),
"cell_field17", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "order_bal",
"columnName", "field" ),
"footcell_field17", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field18", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field45" ),
"field", "sales_ytd",
"columnName", "field" ),
"cell_field18", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "sales_ytd",
"columnName", "field" ),
"footcell_field18", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field19", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field46" ),
"field", "sales_lst_yr",
"columnName", "field" ),
"cell_field19", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field14" ),
"field", "sales_lst_yr",
"columnName", "field" ),
"footcell_field19", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field20", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field47" ),
"field", "posted_bal",
"columnName", "field" ),
"cell_field20", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field15" ),
"field", "posted_bal",
"columnName", "field" ),
"footcell_field20", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field21", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field48" ),
"field", "parent_account",
"columnName", "field" ),
"cell_field21", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field16" ),
"field", "parent_account",
"columnName", "field" ),
"footcell_field21", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field22", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field49" ),
"field", "slsman",
"columnName", "field" ),
"cell_field22", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field17" ),
"field", "slsman",
"columnName", "field" ),
"footcell_field22", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field23", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field50" ),
"field", "cust_type",
"columnName", "field" ),
"cell_field23", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field18" ),
"field", "cust_type",
"columnName", "field" ),
"footcell_field23", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field24", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field51" ),
"field", "pricecode",
"columnName", "field" ),
"cell_field24", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field19" ),
"field", "pricecode",
"columnName", "field" ),
"footcell_field24", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field25", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field52" ),
"field", "DLDeleteIndicator",
"columnName", "field" ),
"cell_field25", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field20" ),
"field", "DLDeleteIndicator",
"columnName", "field" ),
"footcell_field25", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field26", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field53" ),
"field", "VariationNumber",
"columnName", "field" ),
"cell_field26", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field21" ),
"field", "VariationNumber",
"columnName", "field" ),
"footcell_field26", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_checkbox", new XVar( "model", "headcell_checkbox",
"items", new XVar( 0, "grid_checkbox_head" ) ),
"cell_checkbox", new XVar( "model", "cell_checkbox",
"items", new XVar( 0, "grid_checkbox" ) ),
"footcell_checkbox", new XVar( "model", "footcell_checkbox",
"items", XVar.Array() ),
"headcell_icons", new XVar( "model", "headcell_icons",
"items", XVar.Array() ),
"cell_icons", new XVar( "model", "cell_icons",
"items", new XVar( 0, "grid_view" ) ),
"footcell_icons", new XVar( "model", "footcell_icons",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "page_size", new XVar( "type", "page_size" ),
"breadcrumb", new XVar( "type", "breadcrumb" ),
"logo", new XVar( "type", "logo" ),
"menu", new XVar( "type", "menu" ),
"simple_search", new XVar( "type", "simple_search" ),
"pagination", new XVar( "type", "pagination" ),
"details_found", new XVar( "type", "details_found" ),
"search_panel", new XVar( "type", "search_panel",
"items", new XVar( 0, "search_panel_field",
1, "search_panel_field51",
2, "search_panel_field50",
3, "search_panel_field49",
4, "search_panel_field48",
5, "search_panel_field47",
6, "search_panel_field46",
7, "search_panel_field45",
8, "search_panel_field44",
9, "search_panel_field43",
10, "search_panel_field42",
11, "search_panel_field5",
12, "search_panel_field4",
13, "search_panel_field3",
14, "search_panel_field2",
15, "search_panel_field41",
16, "search_panel_field40",
17, "search_panel_field39",
18, "search_panel_field38",
19, "search_panel_field37",
20, "search_panel_field36",
21, "search_panel_field35",
22, "search_panel_field34",
23, "search_panel_field33",
24, "search_panel_field21",
25, "search_panel_field32",
26, "search_panel_field31",
27, "search_panel_field30",
28, "search_panel_field29",
29, "search_panel_field28",
30, "search_panel_field27",
31, "search_panel_field26",
32, "search_panel_field25",
33, "search_panel_field24",
34, "search_panel_field23",
35, "search_panel_field22",
36, "search_panel_field20",
37, "search_panel_field19",
38, "search_panel_field18",
39, "search_panel_field17",
40, "search_panel_field16",
41, "search_panel_field15",
42, "search_panel_field14",
43, "search_panel_field13",
44, "search_panel_field12",
45, "search_panel_field11",
46, "search_panel_field10",
47, "search_panel_field9",
48, "search_panel_field8",
49, "search_panel_field7",
50, "search_panel_field6",
51, "search_panel_field1" ),
"_flexiblePanel", true ),
"list_options", new XVar( "type", "list_options",
"items", new XVar( 0, "advsearch_link",
1, "show_search_panel",
2, "hide_search_panel",
3, "-2",
4, "export",
5, "-1",
6, "import" ) ),
"-2", new XVar( "type", "-" ),
"advsearch_link", new XVar( "type", "advsearch_link" ),
"username_button", new XVar( "type", "username_button",
"items", new XVar( 0, "userinfo_link",
1, "logout_link",
2, "adminarea_link",
3, "changepassword_link" ) ),
"loginform_login", new XVar( "type", "loginform_login",
"popup", false ),
"userinfo_link", new XVar( "type", "userinfo_link" ),
"logout_link", new XVar( "type", "logout_link" ),
"adminarea_link", new XVar( "type", "adminarea_link" ),
"expand_menu_button", new XVar( "type", "expand_menu_button" ),
"collapse_button", new XVar( "type", "collapse_button" ),
"print_panel", new XVar( "type", "print_panel",
"items", new XVar( 0, "print_scope",
1, "print_records",
2, "print_button" ) ),
"print_scope", new XVar( "type", "print_scope" ),
"print_button", new XVar( "type", "print_button" ),
"print_records", new XVar( "type", "print_records" ),
"export", new XVar( "type", "export" ),
"-", new XVar( "type", "-" ),
"import", new XVar( "type", "import" ),
"-1", new XVar( "type", "-" ),
"show_search_panel", new XVar( "type", "show_search_panel" ),
"hide_search_panel", new XVar( "type", "hide_search_panel" ),
"search_panel_field", new XVar( "field", "RowPointer",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field1", new XVar( "field", "accountnumber",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field2", new XVar( "field", "address",
"type", "search_panel_field",
"required", false ),
"search_panel_field6", new XVar( "field", "bill_to_email",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field7", new XVar( "field", "city",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field8", new XVar( "field", "clientid",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field9", new XVar( "field", "contact1",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field10", new XVar( "field", "contact2",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field11", new XVar( "field", "contact3",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field12", new XVar( "field", "country",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field13", new XVar( "field", "county",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field14", new XVar( "field", "credit_limit",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field15", new XVar( "field", "curr_code",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field16", new XVar( "field", "cust_num",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field17", new XVar( "field", "cust_seq",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field18", new XVar( "field", "external_email_addr",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field19", new XVar( "field", "internal_email_addr",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field20", new XVar( "field", "internet_url",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field22", new XVar( "field", "name",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field23", new XVar( "field", "parentaccount",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field24", new XVar( "field", "phone1",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field25", new XVar( "field", "phone2",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field26", new XVar( "field", "phone3",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field27", new XVar( "field", "sf_id",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field28", new XVar( "field", "sf_posted",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field29", new XVar( "field", "ship_to_email",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field30", new XVar( "field", "state",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field31", new XVar( "field", "terms_code",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field32", new XVar( "field", "zip",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"filter_panel", new XVar( "type", "filter_panel",
"items", new XVar( 0, "filter_panel_field" ) ),
"filter_panel_field", new XVar( "field", "clientid",
"type", "filter_panel_field" ),
"search_panel_field21", new XVar( "field", "uf_uet1",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field33", new XVar( "field", "uf_uet2",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field34", new XVar( "field", "uf_uet3",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field35", new XVar( "field", "uf_uet4",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field36", new XVar( "field", "uf_uet5",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field37", new XVar( "field", "uf_uet6",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field38", new XVar( "field", "uf_uet7",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field39", new XVar( "field", "uf_uet8",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field40", new XVar( "field", "uf_uet9",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field41", new XVar( "field", "uf_uet10",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"changepassword_link", new XVar( "type", "changepassword_link" ),
"search_panel_field3", new XVar( "field", "site_ref",
"type", "search_panel_field",
"required", false ),
"search_panel_field4", new XVar( "field", "SalesForceID_Uf",
"type", "search_panel_field",
"required", false ),
"search_panel_field5", new XVar( "field", "err_message",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field42", new XVar( "field", "order_bal",
"type", "search_panel_field",
"required", false ),
"search_panel_field43", new XVar( "field", "sales_ytd",
"type", "search_panel_field",
"required", false ),
"search_panel_field44", new XVar( "field", "sales_lst_yr",
"type", "search_panel_field",
"required", false ),
"search_panel_field45", new XVar( "field", "posted_bal",
"type", "search_panel_field",
"required", false ),
"search_panel_field46", new XVar( "field", "parent_account",
"type", "search_panel_field",
"required", false ),
"search_panel_field47", new XVar( "field", "slsman",
"type", "search_panel_field",
"required", false ),
"search_panel_field48", new XVar( "field", "cust_type",
"type", "search_panel_field",
"required", false ),
"search_panel_field49", new XVar( "field", "pricecode",
"type", "search_panel_field",
"required", false ),
"search_panel_field50", new XVar( "field", "DLDeleteIndicator",
"type", "search_panel_field",
"required", false ),
"search_panel_field51", new XVar( "field", "VariationNumber",
"type", "search_panel_field",
"required", false ),
"simple_grid_field", new XVar( "field", "clientid",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field24", new XVar( "type", "grid_field_label",
"field", "clientid" ),
"simple_grid_field31", new XVar( "field", "accountnumber",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field33", new XVar( "type", "grid_field_label",
"field", "accountnumber" ),
"simple_grid_field32", new XVar( "field", "parentaccount",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field34", new XVar( "type", "grid_field_label",
"field", "parentaccount" ),
"simple_grid_field1", new XVar( "field", "sf_posted",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field25", new XVar( "type", "grid_field_label",
"field", "sf_posted" ),
"simple_grid_field30", new XVar( "field", "sf_id",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field35", new XVar( "type", "grid_field_label",
"field", "sf_id" ),
"simple_grid_field3", new XVar( "field", "cust_num",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field26", new XVar( "type", "grid_field_label",
"field", "cust_num" ),
"simple_grid_field4", new XVar( "field", "cust_seq",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field27", new XVar( "type", "grid_field_label",
"field", "cust_seq" ),
"simple_grid_field5", new XVar( "field", "name",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field28", new XVar( "type", "grid_field_label",
"field", "name" ),
"simple_grid_field6", new XVar( "field", "city",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field29", new XVar( "type", "grid_field_label",
"field", "city" ),
"simple_grid_field7", new XVar( "field", "state",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field36", new XVar( "type", "grid_field_label",
"field", "state" ),
"simple_grid_field8", new XVar( "field", "zip",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field37", new XVar( "type", "grid_field_label",
"field", "zip" ),
"simple_grid_field9", new XVar( "field", "country",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field38", new XVar( "type", "grid_field_label",
"field", "country" ),
"simple_grid_field22", new XVar( "field", "terms_code",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field39", new XVar( "type", "grid_field_label",
"field", "terms_code" ),
"simple_grid_field23", new XVar( "field", "curr_code",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field40", new XVar( "type", "grid_field_label",
"field", "curr_code" ),
"simple_grid_field2", new XVar( "field", "site_ref",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field41", new XVar( "type", "grid_field_label",
"field", "site_ref" ),
"simple_grid_field10", new XVar( "field", "SalesForceID_Uf",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field42", new XVar( "type", "grid_field_label",
"field", "SalesForceID_Uf" ),
"simple_grid_field11", new XVar( "field", "err_message",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field43", new XVar( "type", "grid_field_label",
"field", "err_message" ),
"simple_grid_field12", new XVar( "field", "order_bal",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field44", new XVar( "type", "grid_field_label",
"field", "order_bal" ),
"simple_grid_field13", new XVar( "field", "sales_ytd",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field45", new XVar( "type", "grid_field_label",
"field", "sales_ytd" ),
"simple_grid_field14", new XVar( "field", "sales_lst_yr",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field46", new XVar( "type", "grid_field_label",
"field", "sales_lst_yr" ),
"simple_grid_field15", new XVar( "field", "posted_bal",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field47", new XVar( "type", "grid_field_label",
"field", "posted_bal" ),
"simple_grid_field16", new XVar( "field", "parent_account",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field48", new XVar( "type", "grid_field_label",
"field", "parent_account" ),
"simple_grid_field17", new XVar( "field", "slsman",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field49", new XVar( "type", "grid_field_label",
"field", "slsman" ),
"simple_grid_field18", new XVar( "field", "cust_type",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field50", new XVar( "type", "grid_field_label",
"field", "cust_type" ),
"simple_grid_field19", new XVar( "field", "pricecode",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field51", new XVar( "type", "grid_field_label",
"field", "pricecode" ),
"simple_grid_field20", new XVar( "field", "DLDeleteIndicator",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field52", new XVar( "type", "grid_field_label",
"field", "DLDeleteIndicator" ),
"simple_grid_field21", new XVar( "field", "VariationNumber",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field53", new XVar( "type", "grid_field_label",
"field", "VariationNumber" ),
"grid_checkbox", new XVar( "type", "grid_checkbox" ),
"grid_checkbox_head", new XVar( "type", "grid_checkbox_head" ),
"grid_view", new XVar( "type", "grid_view" ),
"expand_button", new XVar( "type", "expand_button" ) ),
"dbProps", new XVar(  ),
"spreadsheetGrid", false,
"version", 14,
"reorderRows", false,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}