
		// dbo.sf_customer_master
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_sf_customer_master_view
			{
				static public XVar options()
				{
					return new XVar( "pdf", new XVar( "pdfView", false ),
"fields", new XVar( "gridFields", new XVar( 0, "clientid",
1, "sf_posted",
2, "mg_posted",
3, "cust_num",
4, "cust_seq",
5, "name",
6, "city",
7, "state",
8, "zip",
9, "country",
10, "county",
11, "address",
12, "contact1",
13, "phone1",
14, "contact2",
15, "phone2",
16, "contact3",
17, "phone3",
18, "credit_limit",
19, "terms_code",
20, "curr_code",
21, "ship_to_email",
22, "bill_to_email",
23, "internet_url",
24, "internal_email_addr",
25, "external_email_addr",
26, "RowPointer",
27, "sf_id",
28, "accountnumber",
29, "parentaccount",
30, "uf_uet1",
31, "uf_uet2",
32, "uf_uet3",
33, "uf_uet4",
34, "uf_uet5",
35, "uf_uet6",
36, "uf_uet7",
37, "uf_uet8",
38, "uf_uet9",
39, "uf_uet10",
40, "site_ref",
41, "SalesForceID_Uf",
42, "err_message",
43, "order_bal",
44, "sales_ytd",
45, "sales_lst_yr",
46, "posted_bal",
47, "parent_account",
48, "slsman",
49, "cust_type",
50, "pricecode",
51, "DLDeleteIndicator",
52, "VariationNumber" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "clientid", new XVar( 0, "integrated_edit_field" ),
"sf_posted", new XVar( 0, "integrated_edit_field1" ),
"mg_posted", new XVar( 0, "integrated_edit_field2" ),
"cust_num", new XVar( 0, "integrated_edit_field3" ),
"cust_seq", new XVar( 0, "integrated_edit_field4" ),
"name", new XVar( 0, "integrated_edit_field5" ),
"city", new XVar( 0, "integrated_edit_field6" ),
"state", new XVar( 0, "integrated_edit_field7" ),
"zip", new XVar( 0, "integrated_edit_field8" ),
"country", new XVar( 0, "integrated_edit_field9" ),
"county", new XVar( 0, "integrated_edit_field10" ),
"address", new XVar( 0, "integrated_edit_field11" ),
"contact1", new XVar( 0, "integrated_edit_field12" ),
"phone1", new XVar( 0, "integrated_edit_field13" ),
"contact2", new XVar( 0, "integrated_edit_field14" ),
"phone2", new XVar( 0, "integrated_edit_field15" ),
"contact3", new XVar( 0, "integrated_edit_field16" ),
"phone3", new XVar( 0, "integrated_edit_field17" ),
"credit_limit", new XVar( 0, "integrated_edit_field18" ),
"terms_code", new XVar( 0, "integrated_edit_field19" ),
"curr_code", new XVar( 0, "integrated_edit_field20" ),
"ship_to_email", new XVar( 0, "integrated_edit_field21" ),
"bill_to_email", new XVar( 0, "integrated_edit_field22" ),
"internet_url", new XVar( 0, "integrated_edit_field23" ),
"internal_email_addr", new XVar( 0, "integrated_edit_field24" ),
"external_email_addr", new XVar( 0, "integrated_edit_field25" ),
"RowPointer", new XVar( 0, "integrated_edit_field26" ),
"sf_id", new XVar( 0, "integrated_edit_field27" ),
"accountnumber", new XVar( 0, "integrated_edit_field28" ),
"parentaccount", new XVar( 0, "integrated_edit_field29" ),
"uf_uet1", new XVar( 0, "integrated_edit_field30" ),
"uf_uet2", new XVar( 0, "integrated_edit_field31" ),
"uf_uet3", new XVar( 0, "integrated_edit_field32" ),
"uf_uet4", new XVar( 0, "integrated_edit_field33" ),
"uf_uet5", new XVar( 0, "integrated_edit_field34" ),
"uf_uet6", new XVar( 0, "integrated_edit_field35" ),
"uf_uet7", new XVar( 0, "integrated_edit_field36" ),
"uf_uet8", new XVar( 0, "integrated_edit_field37" ),
"uf_uet9", new XVar( 0, "integrated_edit_field38" ),
"uf_uet10", new XVar( 0, "integrated_edit_field39" ),
"site_ref", new XVar( 0, "integrated_edit_field40" ),
"SalesForceID_Uf", new XVar( 0, "integrated_edit_field41" ),
"err_message", new XVar( 0, "integrated_edit_field42" ),
"order_bal", new XVar( 0, "integrated_edit_field43" ),
"sales_ytd", new XVar( 0, "integrated_edit_field44" ),
"sales_lst_yr", new XVar( 0, "integrated_edit_field45" ),
"posted_bal", new XVar( 0, "integrated_edit_field46" ),
"parent_account", new XVar( 0, "integrated_edit_field47" ),
"slsman", new XVar( 0, "integrated_edit_field48" ),
"cust_type", new XVar( 0, "integrated_edit_field49" ),
"pricecode", new XVar( 0, "integrated_edit_field50" ),
"DLDeleteIndicator", new XVar( 0, "integrated_edit_field51" ),
"VariationNumber", new XVar( 0, "integrated_edit_field52" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "view_back_list",
1, "view_close" ),
"top", new XVar( 0, "view_header" ),
"grid", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field40",
41, "integrated_edit_field41",
42, "integrated_edit_field42",
43, "integrated_edit_field43",
44, "integrated_edit_field44",
45, "integrated_edit_field45",
46, "integrated_edit_field46",
47, "integrated_edit_field47",
48, "integrated_edit_field48",
49, "integrated_edit_field49",
50, "integrated_edit_field50",
51, "integrated_edit_field51",
52, "integrated_edit_field52" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "back_button",
1, "close_button" ) ),
"itemForms", new XVar( "view_back_list", "below-grid",
"view_close", "below-grid",
"view_header", "top",
"integrated_edit_field", "grid",
"integrated_edit_field1", "grid",
"integrated_edit_field2", "grid",
"integrated_edit_field3", "grid",
"integrated_edit_field4", "grid",
"integrated_edit_field5", "grid",
"integrated_edit_field6", "grid",
"integrated_edit_field7", "grid",
"integrated_edit_field8", "grid",
"integrated_edit_field9", "grid",
"integrated_edit_field10", "grid",
"integrated_edit_field11", "grid",
"integrated_edit_field12", "grid",
"integrated_edit_field13", "grid",
"integrated_edit_field14", "grid",
"integrated_edit_field15", "grid",
"integrated_edit_field16", "grid",
"integrated_edit_field17", "grid",
"integrated_edit_field18", "grid",
"integrated_edit_field19", "grid",
"integrated_edit_field20", "grid",
"integrated_edit_field21", "grid",
"integrated_edit_field22", "grid",
"integrated_edit_field23", "grid",
"integrated_edit_field24", "grid",
"integrated_edit_field25", "grid",
"integrated_edit_field26", "grid",
"integrated_edit_field27", "grid",
"integrated_edit_field28", "grid",
"integrated_edit_field29", "grid",
"integrated_edit_field30", "grid",
"integrated_edit_field31", "grid",
"integrated_edit_field32", "grid",
"integrated_edit_field33", "grid",
"integrated_edit_field34", "grid",
"integrated_edit_field35", "grid",
"integrated_edit_field36", "grid",
"integrated_edit_field37", "grid",
"integrated_edit_field38", "grid",
"integrated_edit_field39", "grid",
"integrated_edit_field40", "grid",
"integrated_edit_field41", "grid",
"integrated_edit_field42", "grid",
"integrated_edit_field43", "grid",
"integrated_edit_field44", "grid",
"integrated_edit_field45", "grid",
"integrated_edit_field46", "grid",
"integrated_edit_field47", "grid",
"integrated_edit_field48", "grid",
"integrated_edit_field49", "grid",
"integrated_edit_field50", "grid",
"integrated_edit_field51", "grid",
"integrated_edit_field52", "grid" ),
"itemLocations", new XVar( "integrated_edit_field", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field1", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field2", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field3", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field4", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field5", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field6", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field7", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field8", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field9", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field10", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field11", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field12", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field13", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field14", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field15", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field16", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field17", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field18", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field19", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field20", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field21", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field22", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field23", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field24", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field25", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field26", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field27", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field28", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field29", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field30", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field31", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field32", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field33", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field34", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field35", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field36", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field37", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field38", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field39", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field40", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field41", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field42", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field43", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field44", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field45", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field46", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field47", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field48", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field49", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field50", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field51", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field52", new XVar( "location", "grid",
"cellId", "c3" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "view_header", new XVar( 0, "view_header" ),
"view_back_list", new XVar( 0, "view_back_list" ),
"view_close", new XVar( 0, "view_close" ),
"integrated_edit_field", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field40",
41, "integrated_edit_field41",
42, "integrated_edit_field42",
43, "integrated_edit_field43",
44, "integrated_edit_field44",
45, "integrated_edit_field45",
46, "integrated_edit_field46",
47, "integrated_edit_field47",
48, "integrated_edit_field48",
49, "integrated_edit_field49",
50, "integrated_edit_field50",
51, "integrated_edit_field51",
52, "integrated_edit_field52" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field40",
41, "integrated_edit_field41",
42, "integrated_edit_field42",
43, "integrated_edit_field43",
44, "integrated_edit_field44",
45, "integrated_edit_field45",
46, "integrated_edit_field46",
47, "integrated_edit_field47",
48, "integrated_edit_field48",
49, "integrated_edit_field49",
50, "integrated_edit_field50",
51, "integrated_edit_field51",
52, "integrated_edit_field52" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "view",
"breadcrumb", false,
"nextPrev", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "view",
"type", "view",
"layoutId", "nomenu",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "view-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1",
"colspan", 2 ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "view-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_back_list",
1, "view_close" ) ),
"c2", new XVar( "model", "c2",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "view-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ) ),
"section", "" ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field40",
41, "integrated_edit_field41",
42, "integrated_edit_field42",
43, "integrated_edit_field43",
44, "integrated_edit_field44",
45, "integrated_edit_field45",
46, "integrated_edit_field46",
47, "integrated_edit_field47",
48, "integrated_edit_field48",
49, "integrated_edit_field49",
50, "integrated_edit_field50",
51, "integrated_edit_field51",
52, "integrated_edit_field52" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ) ),
"items", new XVar( "view_header", new XVar( "type", "view_header" ),
"view_back_list", new XVar( "type", "view_back_list" ),
"view_close", new XVar( "type", "view_close" ),
"integrated_edit_field", new XVar( "field", "clientid",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field1", new XVar( "field", "sf_posted",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field2", new XVar( "field", "mg_posted",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field3", new XVar( "field", "cust_num",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field4", new XVar( "field", "cust_seq",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field5", new XVar( "field", "name",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field6", new XVar( "field", "city",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field7", new XVar( "field", "state",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field8", new XVar( "field", "zip",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field9", new XVar( "field", "country",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field10", new XVar( "field", "county",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field11", new XVar( "field", "address",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field12", new XVar( "field", "contact1",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field13", new XVar( "field", "phone1",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field14", new XVar( "field", "contact2",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field15", new XVar( "field", "phone2",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field16", new XVar( "field", "contact3",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field17", new XVar( "field", "phone3",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field18", new XVar( "field", "credit_limit",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field19", new XVar( "field", "terms_code",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field20", new XVar( "field", "curr_code",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field21", new XVar( "field", "ship_to_email",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field22", new XVar( "field", "bill_to_email",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field23", new XVar( "field", "internet_url",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field24", new XVar( "field", "internal_email_addr",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field25", new XVar( "field", "external_email_addr",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field26", new XVar( "field", "RowPointer",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field27", new XVar( "field", "sf_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field28", new XVar( "field", "accountnumber",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field29", new XVar( "field", "parentaccount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field30", new XVar( "field", "uf_uet1",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field31", new XVar( "field", "uf_uet2",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field32", new XVar( "field", "uf_uet3",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field33", new XVar( "field", "uf_uet4",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field34", new XVar( "field", "uf_uet5",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field35", new XVar( "field", "uf_uet6",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field36", new XVar( "field", "uf_uet7",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field37", new XVar( "field", "uf_uet8",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field38", new XVar( "field", "uf_uet9",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field39", new XVar( "field", "uf_uet10",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field40", new XVar( "field", "site_ref",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field41", new XVar( "field", "SalesForceID_Uf",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field42", new XVar( "field", "err_message",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field43", new XVar( "field", "order_bal",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field44", new XVar( "field", "sales_ytd",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field45", new XVar( "field", "sales_lst_yr",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field46", new XVar( "field", "posted_bal",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field47", new XVar( "field", "parent_account",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field48", new XVar( "field", "slsman",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field49", new XVar( "field", "cust_type",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field50", new XVar( "field", "pricecode",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field51", new XVar( "field", "DLDeleteIndicator",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field52", new XVar( "field", "VariationNumber",
"type", "integrated_edit_field",
"orientation", 0 ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}