
		// dbo.sh_fulfillment_orders_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_sh_fulfillment_orders_mst_export
			{
				static public XVar options()
				{
					return new XVar( "totals", new XVar( "in_dex", new XVar( "totalsType", "" ),
"clientid", new XVar( "totalsType", "" ),
"order_id", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"co_num", new XVar( "totalsType", "" ),
"fulfill_id", new XVar( "totalsType", "" ),
"fulfillment_status", new XVar( "totalsType", "" ),
"fulfill_line_id", new XVar( "totalsType", "" ),
"Quantity", new XVar( "totalsType", "" ),
"tags", new XVar( "totalsType", "" ),
"co_line", new XVar( "totalsType", "" ),
"deliveryMethod", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "in_dex",
1, "clientid",
2, "order_id",
3, "site_ref",
4, "co_num",
5, "fulfill_id",
6, "fulfillment_status",
7, "fulfill_line_id",
8, "Quantity",
9, "tags",
10, "co_line",
11, "deliveryMethod" ),
"exportFields", new XVar( 0, "in_dex",
1, "clientid",
2, "order_id",
3, "site_ref",
4, "co_num",
5, "fulfill_id",
6, "fulfillment_status",
7, "fulfill_line_id",
8, "Quantity",
9, "tags",
10, "co_line",
11, "deliveryMethod" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "in_dex", new XVar( 0, "export_field" ),
"clientid", new XVar( 0, "export_field1" ),
"order_id", new XVar( 0, "export_field2" ),
"site_ref", new XVar( 0, "export_field3" ),
"co_num", new XVar( 0, "export_field4" ),
"fulfill_id", new XVar( 0, "export_field5" ),
"fulfillment_status", new XVar( 0, "export_field6" ),
"fulfill_line_id", new XVar( 0, "export_field7" ),
"Quantity", new XVar( 0, "export_field8" ),
"tags", new XVar( 0, "export_field9" ),
"co_line", new XVar( 0, "export_field10" ),
"deliveryMethod", new XVar( 0, "export_field11" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "export_header" ),
"grid", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field3",
4, "export_field4",
5, "export_field5",
6, "export_field6",
7, "export_field7",
8, "export_field8",
9, "export_field9",
10, "export_field10",
11, "export_field11" ),
"footer", new XVar( 0, "export_export",
1, "export_cancel" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "export_header", "top",
"export_field", "grid",
"export_field1", "grid",
"export_field2", "grid",
"export_field3", "grid",
"export_field4", "grid",
"export_field5", "grid",
"export_field6", "grid",
"export_field7", "grid",
"export_field8", "grid",
"export_field9", "grid",
"export_field10", "grid",
"export_field11", "grid",
"export_export", "footer",
"export_cancel", "footer" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "export_header", new XVar( 0, "export_header" ),
"export_export", new XVar( 0, "export_export" ),
"export_cancel", new XVar( 0, "export_cancel" ),
"export_field", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field3",
4, "export_field4",
5, "export_field5",
6, "export_field6",
7, "export_field7",
8, "export_field8",
9, "export_field9",
10, "export_field10",
11, "export_field11" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"export", new XVar( "format", 2,
"selectFields", false,
"delimiter", ",",
"selectDelimiter", false,
"exportFileTypes", new XVar( "excel", true,
"word", true,
"csv", true,
"xml", false ) ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "export",
"type", "export",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "export-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "export-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field3",
4, "export_field4",
5, "export_field5",
6, "export_field6",
7, "export_field7",
8, "export_field8",
9, "export_field9",
10, "export_field10",
11, "export_field11" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"footer", new XVar( "modelId", "export-footer",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "export_export",
1, "export_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "export_header", new XVar( "type", "export_header" ),
"export_export", new XVar( "type", "export_export" ),
"export_cancel", new XVar( "type", "export_cancel" ),
"export_field", new XVar( "field", "in_dex",
"type", "export_field" ),
"export_field1", new XVar( "field", "clientid",
"type", "export_field" ),
"export_field2", new XVar( "field", "order_id",
"type", "export_field" ),
"export_field3", new XVar( "field", "site_ref",
"type", "export_field" ),
"export_field4", new XVar( "field", "co_num",
"type", "export_field" ),
"export_field5", new XVar( "field", "fulfill_id",
"type", "export_field" ),
"export_field6", new XVar( "field", "fulfillment_status",
"type", "export_field" ),
"export_field7", new XVar( "field", "fulfill_line_id",
"type", "export_field" ),
"export_field8", new XVar( "field", "Quantity",
"type", "export_field" ),
"export_field9", new XVar( "field", "tags",
"type", "export_field" ),
"export_field10", new XVar( "field", "co_line",
"type", "export_field" ),
"export_field11", new XVar( "field", "deliveryMethod",
"type", "export_field" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1,
"exportFormat", 2,
"exportDelimiter", ",",
"exportSelectDelimiter", false,
"exportSelectFields", false );
				}
			}
		}