
		// dbo.sh_get_order_lines_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_sh_get_order_lines_mst_view
			{
				static public XVar options()
				{
					return new XVar( "pdf", new XVar( "pdfView", false ),
"fields", new XVar( "gridFields", new XVar( 0, "in_dex",
1, "clientid",
2, "VariationNumber",
3, "Name",
4, "Quantity",
5, "Sku",
6, "site_ref",
7, "co_num",
8, "co_line",
9, "Vendor",
10, "VariantTitle",
11, "Amount",
12, "tp_id",
13, "tp_posted",
14, "sc_id",
15, "sc_posted",
16, "sf_id",
17, "sf_posted",
18, "mg_id",
19, "uf_uet1",
20, "uf_uet2",
21, "uf_uet3",
22, "uf_uet4",
23, "uf_uet5",
24, "uf_uet6",
25, "uf_uet7",
26, "uf_uet8",
27, "uf_uet9",
28, "uf_uet10",
29, "L_id",
30, "mg_posted",
31, "item_id",
32, "OriginalTotal",
33, "TotalDiscount",
34, "CurrencyCode",
35, "tax_code1",
36, "fulfill_id",
37, "Fulfill_status",
38, "fulfill_line_id",
39, "Total_Quantity",
40, "sh_posted",
41, "u_m" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "in_dex", new XVar( 0, "integrated_edit_field" ),
"clientid", new XVar( 0, "integrated_edit_field1" ),
"VariationNumber", new XVar( 0, "integrated_edit_field2" ),
"Name", new XVar( 0, "integrated_edit_field3" ),
"Quantity", new XVar( 0, "integrated_edit_field4" ),
"Sku", new XVar( 0, "integrated_edit_field5" ),
"site_ref", new XVar( 0, "integrated_edit_field6" ),
"co_num", new XVar( 0, "integrated_edit_field7" ),
"co_line", new XVar( 0, "integrated_edit_field8" ),
"Vendor", new XVar( 0, "integrated_edit_field9" ),
"VariantTitle", new XVar( 0, "integrated_edit_field10" ),
"Amount", new XVar( 0, "integrated_edit_field11" ),
"tp_id", new XVar( 0, "integrated_edit_field12" ),
"tp_posted", new XVar( 0, "integrated_edit_field13" ),
"sc_id", new XVar( 0, "integrated_edit_field14" ),
"sc_posted", new XVar( 0, "integrated_edit_field15" ),
"sf_id", new XVar( 0, "integrated_edit_field16" ),
"sf_posted", new XVar( 0, "integrated_edit_field17" ),
"mg_id", new XVar( 0, "integrated_edit_field18" ),
"uf_uet1", new XVar( 0, "integrated_edit_field19" ),
"uf_uet2", new XVar( 0, "integrated_edit_field20" ),
"uf_uet3", new XVar( 0, "integrated_edit_field21" ),
"uf_uet4", new XVar( 0, "integrated_edit_field22" ),
"uf_uet5", new XVar( 0, "integrated_edit_field23" ),
"uf_uet6", new XVar( 0, "integrated_edit_field24" ),
"uf_uet7", new XVar( 0, "integrated_edit_field25" ),
"uf_uet8", new XVar( 0, "integrated_edit_field26" ),
"uf_uet9", new XVar( 0, "integrated_edit_field27" ),
"uf_uet10", new XVar( 0, "integrated_edit_field28" ),
"L_id", new XVar( 0, "integrated_edit_field29" ),
"mg_posted", new XVar( 0, "integrated_edit_field30" ),
"item_id", new XVar( 0, "integrated_edit_field31" ),
"OriginalTotal", new XVar( 0, "integrated_edit_field32" ),
"TotalDiscount", new XVar( 0, "integrated_edit_field33" ),
"CurrencyCode", new XVar( 0, "integrated_edit_field34" ),
"tax_code1", new XVar( 0, "integrated_edit_field35" ),
"fulfill_id", new XVar( 0, "integrated_edit_field36" ),
"Fulfill_status", new XVar( 0, "integrated_edit_field37" ),
"fulfill_line_id", new XVar( 0, "integrated_edit_field38" ),
"Total_Quantity", new XVar( 0, "integrated_edit_field39" ),
"sh_posted", new XVar( 0, "integrated_edit_field40" ),
"u_m", new XVar( 0, "integrated_edit_field41" ) ) ),
"pageLinks", new XVar( "edit", true,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "view_back_list",
1, "view_close",
2, "hamburger" ),
"top", new XVar( 0, "view_header" ),
"grid", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field40",
41, "integrated_edit_field41" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array() ),
"itemForms", new XVar( "view_back_list", "below-grid",
"view_close", "below-grid",
"hamburger", "below-grid",
"view_header", "top",
"integrated_edit_field", "grid",
"integrated_edit_field1", "grid",
"integrated_edit_field2", "grid",
"integrated_edit_field3", "grid",
"integrated_edit_field4", "grid",
"integrated_edit_field5", "grid",
"integrated_edit_field6", "grid",
"integrated_edit_field7", "grid",
"integrated_edit_field8", "grid",
"integrated_edit_field9", "grid",
"integrated_edit_field10", "grid",
"integrated_edit_field11", "grid",
"integrated_edit_field12", "grid",
"integrated_edit_field13", "grid",
"integrated_edit_field14", "grid",
"integrated_edit_field15", "grid",
"integrated_edit_field16", "grid",
"integrated_edit_field17", "grid",
"integrated_edit_field18", "grid",
"integrated_edit_field19", "grid",
"integrated_edit_field20", "grid",
"integrated_edit_field21", "grid",
"integrated_edit_field22", "grid",
"integrated_edit_field23", "grid",
"integrated_edit_field24", "grid",
"integrated_edit_field25", "grid",
"integrated_edit_field26", "grid",
"integrated_edit_field27", "grid",
"integrated_edit_field28", "grid",
"integrated_edit_field29", "grid",
"integrated_edit_field30", "grid",
"integrated_edit_field31", "grid",
"integrated_edit_field32", "grid",
"integrated_edit_field33", "grid",
"integrated_edit_field34", "grid",
"integrated_edit_field35", "grid",
"integrated_edit_field36", "grid",
"integrated_edit_field37", "grid",
"integrated_edit_field38", "grid",
"integrated_edit_field39", "grid",
"integrated_edit_field40", "grid",
"integrated_edit_field41", "grid" ),
"itemLocations", new XVar( "integrated_edit_field", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field1", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field2", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field3", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field4", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field5", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field6", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field7", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field8", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field9", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field10", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field11", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field12", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field13", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field14", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field15", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field16", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field17", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field18", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field19", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field20", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field21", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field22", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field23", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field24", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field25", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field26", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field27", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field28", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field29", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field30", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field31", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field32", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field33", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field34", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field35", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field36", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field37", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field38", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field39", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field40", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field41", new XVar( "location", "grid",
"cellId", "c3" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "view_header", new XVar( 0, "view_header" ),
"view_back_list", new XVar( 0, "view_back_list" ),
"view_close", new XVar( 0, "view_close" ),
"hamburger", new XVar( 0, "hamburger" ),
"view_edit", new XVar( 0, "view_edit" ),
"integrated_edit_field", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field40",
41, "integrated_edit_field41" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field40",
41, "integrated_edit_field41" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "view",
"breadcrumb", false,
"nextPrev", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "view",
"type", "view",
"layoutId", "nomenu",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "view-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1",
"colspan", 2 ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "view-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_back_list",
1, "view_close" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "hamburger" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "view-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ) ),
"section", "" ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2",
3, "integrated_edit_field3",
4, "integrated_edit_field4",
5, "integrated_edit_field5",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field40",
41, "integrated_edit_field41" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ) ),
"items", new XVar( "view_header", new XVar( "type", "view_header" ),
"view_back_list", new XVar( "type", "view_back_list" ),
"view_close", new XVar( "type", "view_close" ),
"hamburger", new XVar( "type", "hamburger",
"items", new XVar( 0, "view_edit" ) ),
"view_edit", new XVar( "type", "view_edit" ),
"integrated_edit_field", new XVar( "field", "in_dex",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field1", new XVar( "field", "clientid",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field2", new XVar( "field", "VariationNumber",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field3", new XVar( "field", "Name",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field4", new XVar( "field", "Quantity",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field5", new XVar( "field", "Sku",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field6", new XVar( "field", "site_ref",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field7", new XVar( "field", "co_num",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field8", new XVar( "field", "co_line",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field9", new XVar( "field", "Vendor",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field10", new XVar( "field", "VariantTitle",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field11", new XVar( "field", "Amount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field12", new XVar( "field", "tp_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field13", new XVar( "field", "tp_posted",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field14", new XVar( "field", "sc_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field15", new XVar( "field", "sc_posted",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field16", new XVar( "field", "sf_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field17", new XVar( "field", "sf_posted",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field18", new XVar( "field", "mg_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field19", new XVar( "field", "uf_uet1",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field20", new XVar( "field", "uf_uet2",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field21", new XVar( "field", "uf_uet3",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field22", new XVar( "field", "uf_uet4",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field23", new XVar( "field", "uf_uet5",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field24", new XVar( "field", "uf_uet6",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field25", new XVar( "field", "uf_uet7",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field26", new XVar( "field", "uf_uet8",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field27", new XVar( "field", "uf_uet9",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field28", new XVar( "field", "uf_uet10",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field29", new XVar( "field", "L_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field30", new XVar( "field", "mg_posted",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field31", new XVar( "field", "item_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field32", new XVar( "field", "OriginalTotal",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field33", new XVar( "field", "TotalDiscount",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field34", new XVar( "field", "CurrencyCode",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field35", new XVar( "field", "tax_code1",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field36", new XVar( "field", "fulfill_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field37", new XVar( "field", "Fulfill_status",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field38", new XVar( "field", "fulfill_line_id",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field39", new XVar( "field", "Total_Quantity",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field40", new XVar( "field", "sh_posted",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field41", new XVar( "field", "u_m",
"type", "integrated_edit_field",
"orientation", 0 ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}