
		// dbo.tp_po
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_tp_po_list
			{
				static public XVar options()
				{
					return new XVar( "list", new XVar( "inlineAdd", false,
"detailsAdd", true,
"inlineEdit", false,
"spreadsheetMode", false,
"addToBottom", false,
"delete", false,
"updateSelected", true,
"addInPopup", null,
"viewInPopup", null,
"clickSort", true,
"sortDropdown", false,
"showHideFields", false,
"reorderFields", false,
"fieldFilter", false,
"hideNumberOfRecords", false ),
"allDetails", new XVar( "linkType", 0 ),
"details", new XVar( "dbo.tp_poitem", new XVar( "displayPreview", 1,
"previewPageId", "list",
"showCount", true,
"hideEmptyChild", false,
"hideEmptyPreview", false,
"showProceedLink", true,
"printDetails", true ),
"dbo.tp_invoicedetails", new XVar( "displayPreview", 1,
"previewPageId", "list",
"showCount", true,
"hideEmptyChild", false,
"hideEmptyPreview", false,
"showProceedLink", true,
"printDetails", true ),
"dbo.tp_po_audit", new XVar( "displayPreview", 1,
"previewPageId", "list",
"showCount", true,
"hideEmptyChild", false,
"hideEmptyPreview", false,
"showProceedLink", true,
"printDetails", true ),
"dbo.tp_po_mst", new XVar( "displayPreview", 1,
"previewPageId", "list",
"showCount", true,
"hideEmptyChild", false,
"hideEmptyPreview", false,
"showProceedLink", true,
"printDetails", true ),
"dbo.tp_po_rcpt_mst", new XVar( "displayPreview", 1,
"previewPageId", "list",
"showCount", true,
"hideEmptyChild", false,
"hideEmptyPreview", false,
"showProceedLink", true,
"printDetails", true ),
"dbo.fieldaudit", new XVar( "displayPreview", 1,
"previewPageId", "list",
"showCount", true,
"hideEmptyChild", false,
"hideEmptyPreview", false,
"showProceedLink", true,
"printDetails", true ),
"dbo.csi_lc_rcpt_mst", new XVar( "displayPreview", 1,
"showCount", true,
"hideEmptyChild", false,
"hideEmptyPreview", false,
"showProceedLink", true,
"printDetails", true ) ),
"master", new XVar( "dbo.tp_vendor", new XVar( "preview", true ) ),
"listSearch", new XVar( "alwaysOnPanelFields", new XVar( 0, "po_num",
1, "name" ),
"searchPanel", true,
"fixedSearchPanel", true,
"simpleSearchOptions", false,
"searchSaving", false ),
"totals", new XVar( "clientid", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"po_num", new XVar( "totalsType", "" ),
"stat", new XVar( "totalsType", "" ),
"vend_num", new XVar( "totalsType", "" ),
"name", new XVar( "totalsType", "" ),
"order_date", new XVar( "totalsType", "" ),
"vend_order", new XVar( "totalsType", "" ),
"whse", new XVar( "totalsType", "" ),
"po_cost", new XVar( "totalsType", "" ),
"tp_posted", new XVar( "totalsType", "" ),
"inv_num", new XVar( "totalsType", "" ),
"inv_date", new XVar( "totalsType", "" ),
"curr_code", new XVar( "totalsType", "" ),
"dist_date", new XVar( "totalsType", "" ),
"exch_rate", new XVar( "totalsType", "" ),
"received", new XVar( "totalsType", "" ),
"PendInv", new XVar( "totalsType", "" ),
"CreateDate", new XVar( "totalsType", "" ),
"RecordDate", new XVar( "totalsType", "" ),
"tp_posted_date", new XVar( "totalsType", "" ),
"tp_rev", new XVar( "totalsType", "" ),
"firstrcvd", new XVar( "totalsType", "" ),
"lastrcvd", new XVar( "totalsType", "" ),
"tp_closed", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "tp_posted",
1, "received",
2, "PendInv",
3, "clientid",
4, "site_ref",
5, "po_num",
6, "stat",
7, "vend_num",
8, "name",
9, "order_date",
10, "vend_order",
11, "whse",
12, "po_cost",
13, "inv_num",
14, "inv_date",
15, "curr_code",
16, "dist_date",
17, "exch_rate",
18, "CreateDate",
19, "tp_posted_date",
20, "tp_rev",
21, "firstrcvd",
22, "lastrcvd",
23, "tp_closed" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", new XVar( 0, "po_num",
1, "tp_closed",
2, "lastrcvd",
3, "firstrcvd",
4, "tp_rev",
5, "tp_posted_date",
6, "CreateDate",
7, "PendInv",
8, "name" ),
"filterFields", new XVar( 0, "clientid",
1, "curr_code",
2, "received",
3, "tp_posted",
4, "PendInv" ),
"inlineAddFields", XVar.Array(),
"inlineEditFields", XVar.Array(),
"fieldItems", new XVar( "clientid", new XVar( 0, "simple_grid_field",
1, "simple_grid_field19" ),
"site_ref", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field20" ),
"po_num", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field21" ),
"stat", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field22" ),
"vend_num", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field23" ),
"name", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field24" ),
"order_date", new XVar( 0, "simple_grid_field6",
1, "simple_grid_field25" ),
"vend_order", new XVar( 0, "simple_grid_field7",
1, "simple_grid_field26" ),
"whse", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field27" ),
"po_cost", new XVar( 0, "simple_grid_field9",
1, "simple_grid_field28" ),
"tp_posted", new XVar( 0, "simple_grid_field10",
1, "simple_grid_field17" ),
"inv_num", new XVar( 0, "simple_grid_field11",
1, "simple_grid_field29" ),
"inv_date", new XVar( 0, "simple_grid_field12",
1, "simple_grid_field30" ),
"curr_code", new XVar( 0, "simple_grid_field13",
1, "simple_grid_field31" ),
"dist_date", new XVar( 0, "simple_grid_field14",
1, "simple_grid_field32" ),
"exch_rate", new XVar( 0, "simple_grid_field15",
1, "simple_grid_field33" ),
"received", new XVar( 0, "simple_grid_field16",
1, "simple_grid_field18" ),
"PendInv", new XVar( 0, "grid_field",
1, "grid_field1" ),
"CreateDate", new XVar( 0, "grid_field2",
1, "grid_field_label" ),
"tp_posted_date", new XVar( 0, "grid_field3",
1, "grid_field_label1" ),
"tp_rev", new XVar( 0, "grid_field4",
1, "grid_field_label2" ),
"firstrcvd", new XVar( 0, "grid_field5",
1, "grid_field_label3" ),
"lastrcvd", new XVar( 0, "grid_field6",
1, "grid_field_label4" ),
"tp_closed", new XVar( 0, "grid_field7",
1, "grid_field_label5" ) ),
"hideEmptyFields", XVar.Array(),
"fieldFilterFields", XVar.Array() ),
"pageLinks", new XVar( "edit", true,
"add", false,
"view", false,
"print", true ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "inline_add",
1, "update_selected",
2, "details_found",
3, "page_size",
4, "print_panel" ),
"below-grid", new XVar( 0, "pagination" ),
"left", new XVar( 0, "logo",
1, "expand_button",
2, "menu",
3, "search_panel",
4, "filter_panel" ),
"supertop", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb",
3, "simple_search",
4, "list_options",
5, "loginform_login",
6, "username_button" ),
"grid", new XVar( 0, "custom_button",
1, "simple_grid_field18",
2, "simple_grid_field16",
3, "grid_field1",
4, "grid_field",
5, "simple_grid_field19",
6, "simple_grid_field",
7, "simple_grid_field20",
8, "simple_grid_field1",
9, "simple_grid_field21",
10, "simple_grid_field2",
11, "simple_grid_field22",
12, "simple_grid_field3",
13, "simple_grid_field23",
14, "simple_grid_field4",
15, "simple_grid_field24",
16, "simple_grid_field5",
17, "simple_grid_field25",
18, "simple_grid_field6",
19, "simple_grid_field26",
20, "simple_grid_field7",
21, "simple_grid_field27",
22, "simple_grid_field8",
23, "simple_grid_field28",
24, "simple_grid_field9",
25, "simple_grid_field29",
26, "simple_grid_field11",
27, "simple_grid_field30",
28, "simple_grid_field12",
29, "simple_grid_field31",
30, "simple_grid_field13",
31, "simple_grid_field32",
32, "simple_grid_field14",
33, "simple_grid_field33",
34, "simple_grid_field15",
35, "details_preview",
36, "details_preview1",
37, "details_preview2",
38, "details_preview3",
39, "details_preview4",
40, "details_preview5",
41, "details_preview6",
42, "grid_checkbox_head",
43, "grid_checkbox",
44, "grid_alldetails_link",
45, "grid_details_link",
46, "grid_details_link1",
47, "grid_details_link2",
48, "grid_details_link3",
49, "grid_details_link4",
50, "grid_details_link5",
51, "grid_details_link6",
52, "simple_grid_field17",
53, "simple_grid_field10",
54, "grid_field_label",
55, "grid_field2",
56, "grid_field_label1",
57, "grid_field3",
58, "grid_field_label2",
59, "grid_field4",
60, "custom_button1",
61, "grid_field_label3",
62, "grid_field5",
63, "grid_field_label4",
64, "grid_field6",
65, "grid_field_label5",
66, "grid_field7",
67, "grid_edit",
68, "grid_inline_cancel" ),
"top", new XVar( 0, "master_info" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "inlineadd_link",
1, "updateselected_link",
2, "details_found",
3, "recsPerPage",
4, "print_friendly" ),
"below-grid", new XVar( 0, "pagination" ),
"top", new XVar( 0, "mastertable_block" ) ),
"itemForms", new XVar( "inline_add", "above-grid",
"update_selected", "above-grid",
"details_found", "above-grid",
"page_size", "above-grid",
"print_panel", "above-grid",
"pagination", "below-grid",
"logo", "left",
"expand_button", "left",
"menu", "left",
"search_panel", "left",
"filter_panel", "left",
"expand_menu_button", "supertop",
"collapse_button", "supertop",
"breadcrumb", "supertop",
"simple_search", "supertop",
"list_options", "supertop",
"loginform_login", "supertop",
"username_button", "supertop",
"custom_button", "grid",
"simple_grid_field18", "grid",
"simple_grid_field16", "grid",
"grid_field1", "grid",
"grid_field", "grid",
"simple_grid_field19", "grid",
"simple_grid_field", "grid",
"simple_grid_field20", "grid",
"simple_grid_field1", "grid",
"simple_grid_field21", "grid",
"simple_grid_field2", "grid",
"simple_grid_field22", "grid",
"simple_grid_field3", "grid",
"simple_grid_field23", "grid",
"simple_grid_field4", "grid",
"simple_grid_field24", "grid",
"simple_grid_field5", "grid",
"simple_grid_field25", "grid",
"simple_grid_field6", "grid",
"simple_grid_field26", "grid",
"simple_grid_field7", "grid",
"simple_grid_field27", "grid",
"simple_grid_field8", "grid",
"simple_grid_field28", "grid",
"simple_grid_field9", "grid",
"simple_grid_field29", "grid",
"simple_grid_field11", "grid",
"simple_grid_field30", "grid",
"simple_grid_field12", "grid",
"simple_grid_field31", "grid",
"simple_grid_field13", "grid",
"simple_grid_field32", "grid",
"simple_grid_field14", "grid",
"simple_grid_field33", "grid",
"simple_grid_field15", "grid",
"details_preview", "grid",
"details_preview1", "grid",
"details_preview2", "grid",
"details_preview3", "grid",
"details_preview4", "grid",
"details_preview5", "grid",
"details_preview6", "grid",
"grid_checkbox_head", "grid",
"grid_checkbox", "grid",
"grid_alldetails_link", "grid",
"grid_details_link", "grid",
"grid_details_link1", "grid",
"grid_details_link2", "grid",
"grid_details_link3", "grid",
"grid_details_link4", "grid",
"grid_details_link5", "grid",
"grid_details_link6", "grid",
"simple_grid_field17", "grid",
"simple_grid_field10", "grid",
"grid_field_label", "grid",
"grid_field2", "grid",
"grid_field_label1", "grid",
"grid_field3", "grid",
"grid_field_label2", "grid",
"grid_field4", "grid",
"custom_button1", "grid",
"grid_field_label3", "grid",
"grid_field5", "grid",
"grid_field_label4", "grid",
"grid_field6", "grid",
"grid_field_label5", "grid",
"grid_field7", "grid",
"grid_edit", "grid",
"grid_inline_cancel", "grid",
"master_info", "top" ),
"itemLocations", new XVar( "custom_button", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field18", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field16", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"grid_field1", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"grid_field", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field19", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field20", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field21", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field22", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field23", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"simple_grid_field24", new XVar( "location", "grid",
"cellId", "headcell_field8" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field8" ),
"simple_grid_field25", new XVar( "location", "grid",
"cellId", "headcell_field9" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "cell_field9" ),
"simple_grid_field26", new XVar( "location", "grid",
"cellId", "headcell_field10" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "cell_field10" ),
"simple_grid_field27", new XVar( "location", "grid",
"cellId", "headcell_field11" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "cell_field11" ),
"simple_grid_field28", new XVar( "location", "grid",
"cellId", "headcell_field12" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "cell_field12" ),
"simple_grid_field29", new XVar( "location", "grid",
"cellId", "headcell_field13" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "cell_field13" ),
"simple_grid_field30", new XVar( "location", "grid",
"cellId", "headcell_field14" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "cell_field14" ),
"simple_grid_field31", new XVar( "location", "grid",
"cellId", "headcell_field15" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "cell_field15" ),
"simple_grid_field32", new XVar( "location", "grid",
"cellId", "headcell_field16" ),
"simple_grid_field14", new XVar( "location", "grid",
"cellId", "cell_field16" ),
"simple_grid_field33", new XVar( "location", "grid",
"cellId", "headcell_field17" ),
"simple_grid_field15", new XVar( "location", "grid",
"cellId", "cell_field17" ),
"details_preview", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview1", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview2", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview3", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview4", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview5", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview6", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"grid_checkbox_head", new XVar( "location", "grid",
"cellId", "headcell_checkbox" ),
"grid_checkbox", new XVar( "location", "grid",
"cellId", "cell_checkbox" ),
"grid_alldetails_link", new XVar( "location", "grid",
"cellId", "cell_details" ),
"grid_details_link", new XVar( "location", "grid",
"cellId", "cell_details" ),
"grid_details_link1", new XVar( "location", "grid",
"cellId", "cell_details" ),
"grid_details_link2", new XVar( "location", "grid",
"cellId", "cell_details" ),
"grid_details_link3", new XVar( "location", "grid",
"cellId", "cell_details" ),
"grid_details_link4", new XVar( "location", "grid",
"cellId", "cell_details" ),
"grid_details_link5", new XVar( "location", "grid",
"cellId", "cell_details" ),
"grid_details_link6", new XVar( "location", "grid",
"cellId", "cell_details" ),
"simple_grid_field17", new XVar( "location", "grid",
"cellId", "headcell_field18" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "cell_field18" ),
"grid_field_label", new XVar( "location", "grid",
"cellId", "headcell_field19" ),
"grid_field2", new XVar( "location", "grid",
"cellId", "cell_field19" ),
"grid_field_label1", new XVar( "location", "grid",
"cellId", "headcell_field20" ),
"grid_field3", new XVar( "location", "grid",
"cellId", "cell_field20" ),
"grid_field_label2", new XVar( "location", "grid",
"cellId", "headcell_field21" ),
"grid_field4", new XVar( "location", "grid",
"cellId", "cell_field21" ),
"custom_button1", new XVar( "location", "grid",
"cellId", "cell_field22" ),
"grid_field_label3", new XVar( "location", "grid",
"cellId", "headcell_field23" ),
"grid_field5", new XVar( "location", "grid",
"cellId", "cell_field23" ),
"grid_field_label4", new XVar( "location", "grid",
"cellId", "headcell_field24" ),
"grid_field6", new XVar( "location", "grid",
"cellId", "cell_field24" ),
"grid_field_label5", new XVar( "location", "grid",
"cellId", "headcell_field25" ),
"grid_field7", new XVar( "location", "grid",
"cellId", "cell_field25" ),
"grid_edit", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_inline_cancel", new XVar( "location", "grid",
"cellId", "cell_icons" ) ),
"itemVisiblity", new XVar( "breadcrumb", 5,
"expand_menu_button", 2,
"print_panel", 5,
"expand_button", 5 ) ),
"itemsByType", new XVar( "page_size", new XVar( 0, "page_size" ),
"breadcrumb", new XVar( 0, "breadcrumb" ),
"logo", new XVar( 0, "logo" ),
"menu", new XVar( 0, "menu" ),
"simple_search", new XVar( 0, "simple_search" ),
"pagination", new XVar( 0, "pagination" ),
"grid_checkbox", new XVar( 0, "grid_checkbox" ),
"grid_checkbox_head", new XVar( 0, "grid_checkbox_head" ),
"details_found", new XVar( 0, "details_found" ),
"search_panel", new XVar( 0, "search_panel" ),
"list_options", new XVar( 0, "list_options" ),
"show_search_panel", new XVar( 0, "show_search_panel" ),
"hide_search_panel", new XVar( 0, "hide_search_panel" ),
"search_panel_field", new XVar( 0, "search_panel_field4",
1, "search_panel_field7",
2, "search_panel_field",
3, "search_panel_field1",
4, "search_panel_field2",
5, "search_panel_field3",
6, "search_panel_field5",
7, "search_panel_field6",
8, "search_panel_field8" ),
"username_button", new XVar( 0, "username_button" ),
"loginform_login", new XVar( 0, "loginform_login" ),
"userinfo_link", new XVar( 0, "userinfo_link" ),
"logout_link", new XVar( 0, "logout_link" ),
"adminarea_link", new XVar( 0, "adminarea_link" ),
"changepassword_link", new XVar( 0, "changepassword_link" ),
"expand_menu_button", new XVar( 0, "expand_menu_button" ),
"collapse_button", new XVar( 0, "collapse_button" ),
"print_panel", new XVar( 0, "print_panel" ),
"print_scope", new XVar( 0, "print_scope" ),
"print_button", new XVar( 0, "print_button" ),
"print_records", new XVar( 0, "print_records" ),
"export", new XVar( 0, "export" ),
"-", new XVar( 0, "-",
1, "-1",
2, "-2",
3, "-3" ),
"import", new XVar( 0, "import" ),
"advsearch_link", new XVar( 0, "advsearch_link" ),
"grid_field", new XVar( 0, "simple_grid_field",
1, "simple_grid_field1",
2, "simple_grid_field2",
3, "simple_grid_field3",
4, "simple_grid_field4",
5, "simple_grid_field5",
6, "simple_grid_field6",
7, "simple_grid_field7",
8, "simple_grid_field8",
9, "simple_grid_field9",
10, "simple_grid_field10",
11, "simple_grid_field11",
12, "simple_grid_field12",
13, "simple_grid_field13",
14, "simple_grid_field14",
15, "simple_grid_field15",
16, "simple_grid_field16",
17, "grid_field",
18, "grid_field2",
19, "grid_field3",
20, "grid_field4",
21, "grid_field5",
22, "grid_field6",
23, "grid_field7" ),
"print_details", new XVar( 0, "print_details" ),
"details_preview", new XVar( 0, "details_preview",
1, "details_preview1",
2, "details_preview2",
3, "details_preview3",
4, "details_preview4",
5, "details_preview5",
6, "details_preview6" ),
"grid_alldetails_link", new XVar( 0, "grid_alldetails_link" ),
"grid_details_link", new XVar( 0, "grid_details_link",
1, "grid_details_link1",
2, "grid_details_link2",
3, "grid_details_link3",
4, "grid_details_link4",
5, "grid_details_link5",
6, "grid_details_link6" ),
"filter_panel", new XVar( 0, "filter_panel" ),
"filter_panel_field", new XVar( 0, "filter_panel_field",
1, "filter_panel_field1",
2, "filter_panel_field2",
3, "filter_panel_field3",
4, "filter_panel_field4" ),
"master_info", new XVar( 0, "master_info" ),
"custom_button", new XVar( 0, "custom_button",
1, "custom_button1" ),
"grid_field_label", new XVar( 0, "simple_grid_field17",
1, "simple_grid_field18",
2, "simple_grid_field19",
3, "simple_grid_field20",
4, "simple_grid_field21",
5, "simple_grid_field22",
6, "simple_grid_field23",
7, "simple_grid_field24",
8, "simple_grid_field25",
9, "simple_grid_field26",
10, "simple_grid_field27",
11, "simple_grid_field28",
12, "simple_grid_field29",
13, "simple_grid_field30",
14, "simple_grid_field31",
15, "simple_grid_field32",
16, "simple_grid_field33",
17, "grid_field1",
18, "grid_field_label",
19, "grid_field_label1",
20, "grid_field_label2",
21, "grid_field_label3",
22, "grid_field_label4",
23, "grid_field_label5" ),
"grid_edit", new XVar( 0, "grid_edit" ),
"update_selected", new XVar( 0, "update_selected" ),
"expand_button", new XVar( 0, "expand_button" ),
"inline_add", new XVar( 0, "inline_add" ),
"grid_inline_cancel", new XVar( 0, "grid_inline_cancel" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox_head" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_details", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field18", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_posted_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field17" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field27", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "received_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field18" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "PendInv_fieldheadercolumn" ),
"items", new XVar( 0, "grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "clientid_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field19" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "site_ref_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field20" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "po_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field21" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "stat_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field22" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "vend_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field23" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field8", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "name_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field24" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field9", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "order_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field25" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field10", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "vend_order_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field26" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field11", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "whse_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field27" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field12", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "po_cost_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field28" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field13", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "inv_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field29" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field14", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "inv_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field30" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field15", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "curr_code_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field31" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field16", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "dist_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field32" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field17", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "exch_rate_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field33" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field19", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "CreateDate_fieldheadercolumn" ),
"items", new XVar( 0, "grid_field_label" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field20", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_posted_date_fieldheadercolumn" ),
"items", new XVar( 0, "grid_field_label1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field21", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_rev_fieldheadercolumn" ),
"items", new XVar( 0, "grid_field_label2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field22", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field23", new XVar( "cols", new XVar( 0, 27 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "firstrcvd_fieldheadercolumn" ),
"items", new XVar( 0, "grid_field_label3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field24", new XVar( "cols", new XVar( 0, 28 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "lastrcvd_fieldheadercolumn" ),
"items", new XVar( 0, "grid_field_label4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field25", new XVar( "cols", new XVar( 0, 29 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_closed_fieldheadercolumn" ),
"items", new XVar( 0, "grid_field_label5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "edit_column",
1, "inline_cancel" ),
"items", new XVar( 0, "grid_edit",
1, "grid_inline_cancel" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_details", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "grid_alldetails_link",
1, "grid_details_link",
2, "grid_details_link1",
3, "grid_details_link2",
4, "grid_details_link3",
5, "grid_details_link4",
6, "grid_details_link5",
7, "grid_details_link6" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", true,
"fixedAtClient", true ),
"cell_field18", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_posted_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field27", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "received_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field16" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "PendInv_fieldcolumn" ),
"items", new XVar( 0, "grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "clientid_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "site_ref_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "po_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "stat_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "vend_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field8", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "name_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field9", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "order_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field10", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "vend_order_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field11", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "whse_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field12", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "po_cost_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field13", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "inv_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field14", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "inv_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field15", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "curr_code_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field16", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "dist_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field14" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field17", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "exch_rate_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field15" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field19", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "CreateDate_fieldcolumn" ),
"items", new XVar( 0, "grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field20", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_posted_date_fieldcolumn" ),
"items", new XVar( 0, "grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field21", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_rev_fieldcolumn" ),
"items", new XVar( 0, "grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field22", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", true,
"fixedAtClient", true ),
"cell_field23", new XVar( "cols", new XVar( 0, 27 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "firstrcvd_fieldcolumn" ),
"items", new XVar( 0, "grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field24", new XVar( "cols", new XVar( 0, 28 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "lastrcvd_fieldcolumn" ),
"items", new XVar( 0, "grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field25", new XVar( "cols", new XVar( 0, 29 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_closed_fieldcolumn" ),
"items", new XVar( 0, "grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_dpreview", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5,
6, 6,
7, 7,
8, 8,
9, 9,
10, 10,
11, 11,
12, 12,
13, 13,
14, 14,
15, 15,
16, 16,
17, 17,
18, 18,
19, 19,
20, 20,
21, 21,
22, 22,
23, 23,
24, 24,
25, 25,
26, 26,
27, 27,
28, 28,
29, 29 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "details_preview",
1, "details_preview1",
2, "details_preview2",
3, "details_preview3",
4, "details_preview4",
5, "details_preview5",
6, "details_preview6" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"footcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_details", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 3,
1, 4,
2, 5 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field8", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field9", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field10", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field11", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field12", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field13", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field14", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field15", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field16", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field17", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field18", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field19", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field20", new XVar( "cols", new XVar( 0, 25,
1, 26 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field21", new XVar( "cols", new XVar( 0, 27 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field22", new XVar( "cols", new XVar( 0, 28 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field23", new XVar( "cols", new XVar( 0, 29 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 30,
"height", 4 ) ) ),
"loginForm", new XVar( "loginForm", 0 ),
"page", new XVar( "verticalBar", true,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar( "details_found", new XVar( "tag", "DISPLAYING",
"type", 2 ) ) ),
"gridType", 0,
"recsPerRow", 1,
"hasCustomButtons", true,
"customButtons", new XVar( 0, "New_Button4",
1, "New_Button7" ),
"hasNotifications", false,
"menus", new XVar( 0, new XVar( "id", "main",
"horizontal", false ) ),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "list",
"breadcrumb", true ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", new XVar( 0, "New_Button4",
1, "New_Button7" ) ),
"dataGrid", new XVar( "groupFields", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "list",
"type", "list",
"layoutId", "leftbar",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "list-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ),
1, new XVar( "cell", "c4" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "inline_add",
1, "update_selected" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "details_found",
1, "page_size",
2, "print_panel" ) ),
"c3", new XVar( "model", "c3",
"items", XVar.Array() ),
"c4", new XVar( "model", "c4",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "list-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "pagination" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"left", new XVar( "modelId", "leftbar-menu",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c0" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c0", new XVar( "model", "c0",
"items", new XVar( 0, "logo",
1, "expand_button" ) ),
"c1", new XVar( "model", "c1",
"items", new XVar( 0, "menu",
1, "search_panel",
2, "filter_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"supertop", new XVar( "modelId", "leftbar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "simple_search",
1, "list_options",
2, "loginform_login",
3, "username_button" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_icons" ),
1, new XVar( "cell", "headcell_checkbox" ),
2, new XVar( "cell", "headcell_details" ),
3, new XVar( "cell", "headcell_field" ),
4, new XVar( "cell", "headcell_field18" ),
5, new XVar( "cell", "headcell_field27" ),
6, new XVar( "cell", "headcell_field1" ),
7, new XVar( "cell", "headcell_field2" ),
8, new XVar( "cell", "headcell_field3" ),
9, new XVar( "cell", "headcell_field4" ),
10, new XVar( "cell", "headcell_field5" ),
11, new XVar( "cell", "headcell_field6" ),
12, new XVar( "cell", "headcell_field7" ),
13, new XVar( "cell", "headcell_field8" ),
14, new XVar( "cell", "headcell_field9" ),
15, new XVar( "cell", "headcell_field10" ),
16, new XVar( "cell", "headcell_field11" ),
17, new XVar( "cell", "headcell_field12" ),
18, new XVar( "cell", "headcell_field13" ),
19, new XVar( "cell", "headcell_field14" ),
20, new XVar( "cell", "headcell_field15" ),
21, new XVar( "cell", "headcell_field16" ),
22, new XVar( "cell", "headcell_field17" ),
23, new XVar( "cell", "headcell_field19" ),
24, new XVar( "cell", "headcell_field20" ),
25, new XVar( "cell", "headcell_field21" ),
26, new XVar( "cell", "headcell_field22" ),
27, new XVar( "cell", "headcell_field23" ),
28, new XVar( "cell", "headcell_field24" ),
29, new XVar( "cell", "headcell_field25" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_icons" ),
1, new XVar( "cell", "cell_checkbox" ),
2, new XVar( "cell", "cell_details" ),
3, new XVar( "cell", "cell_field" ),
4, new XVar( "cell", "cell_field18" ),
5, new XVar( "cell", "cell_field27" ),
6, new XVar( "cell", "cell_field1" ),
7, new XVar( "cell", "cell_field2" ),
8, new XVar( "cell", "cell_field3" ),
9, new XVar( "cell", "cell_field4" ),
10, new XVar( "cell", "cell_field5" ),
11, new XVar( "cell", "cell_field6" ),
12, new XVar( "cell", "cell_field7" ),
13, new XVar( "cell", "cell_field8" ),
14, new XVar( "cell", "cell_field9" ),
15, new XVar( "cell", "cell_field10" ),
16, new XVar( "cell", "cell_field11" ),
17, new XVar( "cell", "cell_field12" ),
18, new XVar( "cell", "cell_field13" ),
19, new XVar( "cell", "cell_field14" ),
20, new XVar( "cell", "cell_field15" ),
21, new XVar( "cell", "cell_field16" ),
22, new XVar( "cell", "cell_field17" ),
23, new XVar( "cell", "cell_field19" ),
24, new XVar( "cell", "cell_field20" ),
25, new XVar( "cell", "cell_field21" ),
26, new XVar( "cell", "cell_field22" ),
27, new XVar( "cell", "cell_field23" ),
28, new XVar( "cell", "cell_field24" ),
29, new XVar( "cell", "cell_field25" ) ) ),
2, new XVar( "cells", new XVar( 0, new XVar( "cell", "cell_dpreview",
"colspan", 30 ) ),
"section", "body" ),
3, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_icons" ),
1, new XVar( "cell", "footcell_checkbox" ),
2, new XVar( "cell", "footcell_details" ),
3, new XVar( "cell", "footcell_field",
"colspan", 3 ),
4, new XVar( "cell", "footcell_field1" ),
5, new XVar( "cell", "footcell_field2" ),
6, new XVar( "cell", "footcell_field3" ),
7, new XVar( "cell", "footcell_field4" ),
8, new XVar( "cell", "footcell_field5" ),
9, new XVar( "cell", "footcell_field6" ),
10, new XVar( "cell", "footcell_field7" ),
11, new XVar( "cell", "footcell_field8" ),
12, new XVar( "cell", "footcell_field9" ),
13, new XVar( "cell", "footcell_field10" ),
14, new XVar( "cell", "footcell_field11" ),
15, new XVar( "cell", "footcell_field12" ),
16, new XVar( "cell", "footcell_field13" ),
17, new XVar( "cell", "footcell_field14" ),
18, new XVar( "cell", "footcell_field15" ),
19, new XVar( "cell", "footcell_field16" ),
20, new XVar( "cell", "footcell_field17" ),
21, new XVar( "cell", "footcell_field18" ),
22, new XVar( "cell", "footcell_field19" ),
23, new XVar( "cell", "footcell_field20",
"colspan", 2 ),
24, new XVar( "cell", "footcell_field21" ),
25, new XVar( "cell", "footcell_field22" ),
26, new XVar( "cell", "footcell_field23" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", XVar.Array() ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "custom_button" ) ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field18" ),
"field", "received",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field16" ),
"field", "received",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "grid_field1" ),
"field", "PendInv",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "grid_field" ),
"field", "PendInv",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field19" ),
"field", "clientid",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "clientid",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field20" ),
"field", "site_ref",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "site_ref",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field21" ),
"field", "po_num",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "po_num",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field22" ),
"field", "stat",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "stat",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field23" ),
"field", "vend_num",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "vend_num",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field8", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field24" ),
"field", "name",
"columnName", "field" ),
"cell_field8", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "name",
"columnName", "field" ),
"footcell_field8", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field9", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field25" ),
"field", "order_date",
"columnName", "field" ),
"cell_field9", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "order_date",
"columnName", "field" ),
"footcell_field9", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field10", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field26" ),
"field", "vend_order",
"columnName", "field" ),
"cell_field10", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "vend_order",
"columnName", "field" ),
"footcell_field10", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field11", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field27" ),
"field", "whse",
"columnName", "field" ),
"cell_field11", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "whse",
"columnName", "field" ),
"footcell_field11", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field12", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field28" ),
"field", "po_cost",
"columnName", "field" ),
"cell_field12", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "po_cost",
"columnName", "field" ),
"footcell_field12", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field13", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field29" ),
"field", "inv_num",
"columnName", "field" ),
"cell_field13", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "inv_num",
"columnName", "field" ),
"footcell_field13", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field14", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field30" ),
"field", "inv_date",
"columnName", "field" ),
"cell_field14", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "inv_date",
"columnName", "field" ),
"footcell_field14", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field15", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field31" ),
"field", "curr_code",
"columnName", "field" ),
"cell_field15", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "curr_code",
"columnName", "field" ),
"footcell_field15", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field16", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field32" ),
"field", "dist_date",
"columnName", "field" ),
"cell_field16", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field14" ),
"field", "dist_date",
"columnName", "field" ),
"footcell_field16", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field17", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field33" ),
"field", "exch_rate",
"columnName", "field" ),
"cell_field17", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field15" ),
"field", "exch_rate",
"columnName", "field" ),
"footcell_field17", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"cell_dpreview", new XVar( "model", "cell_dpreview",
"items", new XVar( 0, "details_preview",
1, "details_preview1",
2, "details_preview2",
3, "details_preview3",
4, "details_preview4",
5, "details_preview5",
6, "details_preview6" ) ),
"headcell_checkbox", new XVar( "model", "headcell_checkbox",
"items", new XVar( 0, "grid_checkbox_head" ) ),
"cell_checkbox", new XVar( "model", "cell_checkbox",
"items", new XVar( 0, "grid_checkbox" ) ),
"footcell_checkbox", new XVar( "model", "footcell_checkbox",
"items", XVar.Array() ),
"headcell_details", new XVar( "model", "headcell_details",
"items", XVar.Array() ),
"cell_details", new XVar( "model", "cell_details",
"items", new XVar( 0, "grid_alldetails_link",
1, "grid_details_link",
2, "grid_details_link1",
3, "grid_details_link2",
4, "grid_details_link3",
5, "grid_details_link4",
6, "grid_details_link5",
7, "grid_details_link6" ) ),
"footcell_details", new XVar( "model", "footcell_details",
"items", XVar.Array() ),
"headcell_field18", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field17" ),
"field", "tp_posted",
"columnName", "field" ),
"cell_field18", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "tp_posted",
"columnName", "field" ),
"headcell_field19", new XVar( "model", "headcell_field",
"items", new XVar( 0, "grid_field_label" ),
"field", "CreateDate",
"columnName", "field" ),
"cell_field19", new XVar( "model", "cell_field",
"items", new XVar( 0, "grid_field2" ),
"field", "CreateDate",
"columnName", "field" ),
"footcell_field18", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field20", new XVar( "model", "headcell_field",
"items", new XVar( 0, "grid_field_label1" ),
"field", "tp_posted_date",
"columnName", "field" ),
"cell_field20", new XVar( "model", "cell_field",
"items", new XVar( 0, "grid_field3" ),
"field", "tp_posted_date",
"columnName", "field" ),
"footcell_field19", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field21", new XVar( "model", "headcell_field",
"items", new XVar( 0, "grid_field_label2" ),
"field", "tp_rev",
"columnName", "field" ),
"cell_field21", new XVar( "model", "cell_field",
"items", new XVar( 0, "grid_field4" ),
"field", "tp_rev",
"columnName", "field" ),
"footcell_field20", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field22", new XVar( "model", "headcell_field",
"items", XVar.Array() ),
"cell_field22", new XVar( "model", "cell_field",
"items", new XVar( 0, "custom_button1" ) ),
"headcell_field23", new XVar( "model", "headcell_field",
"items", new XVar( 0, "grid_field_label3" ),
"field", "firstrcvd",
"columnName", "field" ),
"cell_field23", new XVar( "model", "cell_field",
"items", new XVar( 0, "grid_field5" ),
"field", "firstrcvd",
"columnName", "field" ),
"footcell_field21", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field24", new XVar( "model", "headcell_field",
"items", new XVar( 0, "grid_field_label4" ),
"field", "lastrcvd",
"columnName", "field" ),
"cell_field24", new XVar( "model", "cell_field",
"items", new XVar( 0, "grid_field6" ),
"field", "lastrcvd",
"columnName", "field" ),
"footcell_field22", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field25", new XVar( "model", "headcell_field",
"items", new XVar( 0, "grid_field_label5" ),
"field", "tp_closed",
"columnName", "field" ),
"cell_field25", new XVar( "model", "cell_field",
"items", new XVar( 0, "grid_field7" ),
"field", "tp_closed",
"columnName", "field" ),
"footcell_field23", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_icons", new XVar( "model", "headcell_icons",
"items", XVar.Array() ),
"cell_icons", new XVar( "model", "cell_icons",
"items", new XVar( 0, "grid_edit",
1, "grid_inline_cancel" ) ),
"footcell_icons", new XVar( "model", "footcell_icons",
"items", XVar.Array() ),
"headcell_field27", new XVar( "model", "headcell_field",
"items", XVar.Array() ),
"cell_field27", new XVar( "model", "cell_field",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "list-sidebar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c2", new XVar( "model", "c2",
"items", new XVar( 0, "master_info" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "page_size", new XVar( "type", "page_size" ),
"breadcrumb", new XVar( "type", "breadcrumb" ),
"logo", new XVar( "type", "logo" ),
"menu", new XVar( "type", "menu" ),
"simple_search", new XVar( "type", "simple_search" ),
"pagination", new XVar( "type", "pagination" ),
"grid_checkbox", new XVar( "type", "grid_checkbox" ),
"grid_checkbox_head", new XVar( "type", "grid_checkbox_head" ),
"details_found", new XVar( "type", "details_found" ),
"search_panel", new XVar( "type", "search_panel",
"items", new XVar( 0, "search_panel_field7",
1, "search_panel_field8",
2, "search_panel_field6",
3, "search_panel_field5",
4, "search_panel_field3",
5, "search_panel_field2",
6, "search_panel_field1",
7, "search_panel_field",
8, "search_panel_field4" ),
"_flexiblePanel", false ),
"list_options", new XVar( "type", "list_options",
"items", new XVar( 0, "advsearch_link",
1, "show_search_panel",
2, "hide_search_panel",
3, "-2",
4, "export",
5, "-1",
6, "import" ) ),
"show_search_panel", new XVar( "type", "show_search_panel" ),
"hide_search_panel", new XVar( "type", "hide_search_panel" ),
"search_panel_field4", new XVar( "field", "name",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", true ),
"search_panel_field7", new XVar( "field", "po_num",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", true ),
"username_button", new XVar( "type", "username_button",
"items", new XVar( 0, "userinfo_link",
1, "logout_link",
2, "adminarea_link",
3, "changepassword_link" ) ),
"loginform_login", new XVar( "type", "loginform_login",
"popup", false ),
"userinfo_link", new XVar( "type", "userinfo_link" ),
"logout_link", new XVar( "type", "logout_link" ),
"adminarea_link", new XVar( "type", "adminarea_link" ),
"changepassword_link", new XVar( "type", "changepassword_link" ),
"expand_menu_button", new XVar( "type", "expand_menu_button" ),
"collapse_button", new XVar( "type", "collapse_button" ),
"print_panel", new XVar( "type", "print_panel",
"items", new XVar( 0, "print_scope",
1, "print_details",
2, "print_records",
3, "print_button" ) ),
"print_scope", new XVar( "type", "print_scope" ),
"print_button", new XVar( "type", "print_button" ),
"print_records", new XVar( "type", "print_records" ),
"export", new XVar( "type", "export" ),
"-", new XVar( "type", "-" ),
"import", new XVar( "type", "import" ),
"-1", new XVar( "type", "-" ),
"advsearch_link", new XVar( "type", "advsearch_link" ),
"-2", new XVar( "type", "-" ),
"simple_grid_field", new XVar( "field", "clientid",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field1", new XVar( "field", "site_ref",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field2", new XVar( "field", "po_num",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field3", new XVar( "field", "stat",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field4", new XVar( "field", "vend_num",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field5", new XVar( "field", "name",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field6", new XVar( "field", "order_date",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field7", new XVar( "field", "vend_order",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field8", new XVar( "field", "whse",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field9", new XVar( "field", "po_cost",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field10", new XVar( "field", "tp_posted",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field11", new XVar( "field", "inv_num",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field12", new XVar( "field", "inv_date",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field13", new XVar( "field", "curr_code",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"print_details", new XVar( "type", "print_details",
"tables", new XVar( "dbo.tp_poitem", true,
"dbo.tp_invoicedetails", true,
"dbo.tp_po_audit", true,
"dbo.tp_po_mst", true,
"dbo.tp_po_rcpt_mst", true,
"dbo.fieldaudit", true,
"dbo.csi_lc_rcpt_mst", true ) ),
"details_preview", new XVar( "type", "details_preview",
"table", "dbo.tp_poitem",
"items", XVar.Array(),
"popup", false,
"hideEmptyPreview", false,
"proceedLink", true,
"pageId", "list" ),
"grid_alldetails_link", new XVar( "type", "grid_alldetails_link" ),
"grid_details_link", new XVar( "type", "grid_details_link",
"table", "dbo.tp_poitem",
"badge", true,
"hideIfNone", false,
"showCount", true ),
"details_preview1", new XVar( "type", "details_preview",
"table", "dbo.tp_invoicedetails",
"items", XVar.Array(),
"popup", false,
"hideEmptyPreview", false,
"proceedLink", true,
"pageId", "list" ),
"grid_details_link1", new XVar( "type", "grid_details_link",
"table", "dbo.tp_invoicedetails",
"badge", true,
"showCount", true,
"hideIfNone", false ),
"simple_grid_field14", new XVar( "field", "dist_date",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field15", new XVar( "field", "exch_rate",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field16", new XVar( "field", "received",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"filter_panel", new XVar( "type", "filter_panel",
"items", new XVar( 0, "filter_panel_field",
1, "filter_panel_field4",
2, "filter_panel_field3",
3, "filter_panel_field2",
4, "filter_panel_field1" ) ),
"filter_panel_field", new XVar( "field", "clientid",
"type", "filter_panel_field" ),
"filter_panel_field1", new XVar( "field", "curr_code",
"type", "filter_panel_field" ),
"filter_panel_field2", new XVar( "field", "received",
"type", "filter_panel_field" ),
"master_info", new XVar( "type", "master_info",
"tables", new XVar( "dbo.tp_vendor", "true" ) ),
"custom_button", new XVar( "eventId", "New_Button4",
"label", new XVar( "text", "Post",
"type", 0 ),
"type", "custom_button",
"buttonSize", "small",
"buttonStyle", "primary" ),
"simple_grid_field17", new XVar( "type", "grid_field_label",
"field", "tp_posted" ),
"simple_grid_field18", new XVar( "type", "grid_field_label",
"field", "received" ),
"simple_grid_field19", new XVar( "type", "grid_field_label",
"field", "clientid" ),
"simple_grid_field20", new XVar( "type", "grid_field_label",
"field", "site_ref" ),
"simple_grid_field21", new XVar( "type", "grid_field_label",
"field", "po_num" ),
"simple_grid_field22", new XVar( "type", "grid_field_label",
"field", "stat" ),
"simple_grid_field23", new XVar( "type", "grid_field_label",
"field", "vend_num" ),
"simple_grid_field24", new XVar( "type", "grid_field_label",
"field", "name" ),
"simple_grid_field25", new XVar( "type", "grid_field_label",
"field", "order_date" ),
"simple_grid_field26", new XVar( "type", "grid_field_label",
"field", "vend_order" ),
"simple_grid_field27", new XVar( "type", "grid_field_label",
"field", "whse" ),
"simple_grid_field28", new XVar( "type", "grid_field_label",
"field", "po_cost" ),
"simple_grid_field29", new XVar( "type", "grid_field_label",
"field", "inv_num" ),
"simple_grid_field30", new XVar( "type", "grid_field_label",
"field", "inv_date" ),
"simple_grid_field31", new XVar( "type", "grid_field_label",
"field", "curr_code" ),
"simple_grid_field32", new XVar( "type", "grid_field_label",
"field", "dist_date" ),
"simple_grid_field33", new XVar( "type", "grid_field_label",
"field", "exch_rate" ),
"filter_panel_field3", new XVar( "field", "tp_posted",
"type", "filter_panel_field" ),
"grid_field", new XVar( "field", "PendInv",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"search_panel_field", new XVar( "field", "PendInv",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"filter_panel_field4", new XVar( "field", "PendInv",
"type", "filter_panel_field" ),
"grid_field1", new XVar( "type", "grid_field_label",
"field", "PendInv" ),
"grid_field2", new XVar( "field", "CreateDate",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"grid_field_label", new XVar( "type", "grid_field_label",
"field", "CreateDate" ),
"search_panel_field1", new XVar( "field", "CreateDate",
"type", "search_panel_field",
"required", false ),
"grid_field3", new XVar( "field", "tp_posted_date",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"grid_field_label1", new XVar( "type", "grid_field_label",
"field", "tp_posted_date" ),
"search_panel_field2", new XVar( "field", "tp_posted_date",
"type", "search_panel_field",
"required", false ),
"grid_field4", new XVar( "field", "tp_rev",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"grid_field_label2", new XVar( "type", "grid_field_label",
"field", "tp_rev" ),
"search_panel_field3", new XVar( "field", "tp_rev",
"type", "search_panel_field",
"required", false ),
"custom_button1", new XVar( "eventId", "New_Button7",
"label", new XVar( "text", "Post Rev",
"type", 0 ),
"type", "custom_button",
"buttonSize", "small" ),
"details_preview2", new XVar( "type", "details_preview",
"table", "dbo.tp_po_audit",
"items", XVar.Array(),
"popup", false,
"hideEmptyPreview", false,
"proceedLink", true,
"pageId", "list" ),
"grid_details_link2", new XVar( "type", "grid_details_link",
"table", "dbo.tp_po_audit",
"badge", true,
"showCount", true,
"hideIfNone", false ),
"details_preview3", new XVar( "type", "details_preview",
"table", "dbo.tp_po_mst",
"items", XVar.Array(),
"popup", false,
"hideEmptyPreview", false,
"proceedLink", true,
"pageId", "list" ),
"grid_details_link3", new XVar( "type", "grid_details_link",
"table", "dbo.tp_po_mst",
"badge", true,
"showCount", true,
"hideIfNone", false ),
"details_preview4", new XVar( "type", "details_preview",
"table", "dbo.tp_po_rcpt_mst",
"items", XVar.Array(),
"popup", false,
"hideEmptyPreview", false,
"proceedLink", true,
"pageId", "list" ),
"grid_details_link4", new XVar( "type", "grid_details_link",
"table", "dbo.tp_po_rcpt_mst",
"badge", true,
"showCount", true,
"hideIfNone", false ),
"grid_field5", new XVar( "field", "firstrcvd",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"grid_field_label3", new XVar( "type", "grid_field_label",
"field", "firstrcvd" ),
"search_panel_field5", new XVar( "field", "firstrcvd",
"type", "search_panel_field",
"required", false ),
"grid_field6", new XVar( "field", "lastrcvd",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"grid_field_label4", new XVar( "type", "grid_field_label",
"field", "lastrcvd" ),
"search_panel_field6", new XVar( "field", "lastrcvd",
"type", "search_panel_field",
"required", false ),
"details_preview5", new XVar( "type", "details_preview",
"table", "dbo.fieldaudit",
"items", XVar.Array(),
"popup", false,
"hideEmptyPreview", false,
"proceedLink", true,
"pageId", "list" ),
"grid_details_link5", new XVar( "type", "grid_details_link",
"table", "dbo.fieldaudit",
"badge", true,
"showCount", true,
"hideIfNone", false ),
"grid_field7", new XVar( "field", "tp_closed",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"grid_field_label5", new XVar( "type", "grid_field_label",
"field", "tp_closed" ),
"search_panel_field8", new XVar( "field", "tp_closed",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"-3", new XVar( "type", "-" ),
"grid_edit", new XVar( "type", "grid_edit" ),
"update_selected", new XVar( "type", "update_selected" ),
"details_preview6", new XVar( "type", "details_preview",
"table", "dbo.csi_lc_rcpt_mst",
"items", XVar.Array(),
"popup", false,
"hideEmptyPreview", false,
"proceedLink", true ),
"grid_details_link6", new XVar( "type", "grid_details_link",
"table", "dbo.csi_lc_rcpt_mst",
"badge", true,
"showCount", true,
"hideIfNone", false ),
"expand_button", new XVar( "type", "expand_button" ),
"inline_add", new XVar( "type", "inline_add",
"detailsOnly", true ),
"grid_inline_cancel", new XVar( "type", "grid_inline_cancel" ) ),
"dbProps", new XVar(  ),
"spreadsheetGrid", false,
"version", 14,
"pageWidth", "full",
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}