
		// dbo.tp_poitem
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_tp_poitem_masterprint
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "po_line",
1, "po_release",
2, "description",
3, "item",
4, "item_cost",
5, "item_cost_conv",
6, "non_inv_acct_unit4",
7, "plan_cost",
8, "plan_cost_conv",
9, "qty_ordered",
10, "qty_ordered_conv",
11, "qty_received",
12, "qty_voucher",
13, "rcvd_date",
14, "stat",
15, "u_m",
16, "unit_mat_cost",
17, "unit_mat_cost_conv",
18, "whse",
19, "CreateDate",
20, "tp_item_cost" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "po_line", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field4" ),
"po_release", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field6" ),
"description", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field10" ),
"item", new XVar( 0, "simple_grid_field7",
1, "simple_grid_field11" ),
"item_cost", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field12" ),
"item_cost_conv", new XVar( 0, "simple_grid_field9",
1, "simple_grid_field13" ),
"non_inv_acct_unit4", new XVar( 0, "simple_grid_field14",
1, "simple_grid_field22" ),
"plan_cost", new XVar( 0, "simple_grid_field15",
1, "simple_grid_field23" ),
"plan_cost_conv", new XVar( 0, "simple_grid_field16",
1, "simple_grid_field28" ),
"qty_ordered", new XVar( 0, "simple_grid_field17",
1, "simple_grid_field29" ),
"qty_ordered_conv", new XVar( 0, "simple_grid_field18",
1, "simple_grid_field31" ),
"qty_received", new XVar( 0, "simple_grid_field19",
1, "simple_grid_field32" ),
"qty_voucher", new XVar( 0, "simple_grid_field20",
1, "simple_grid_field33" ),
"rcvd_date", new XVar( 0, "simple_grid_field21",
1, "simple_grid_field34" ),
"stat", new XVar( 0, "simple_grid_field24",
1, "simple_grid_field35" ),
"u_m", new XVar( 0, "simple_grid_field25",
1, "simple_grid_field36" ),
"unit_mat_cost", new XVar( 0, "simple_grid_field26",
1, "simple_grid_field37" ),
"unit_mat_cost_conv", new XVar( 0, "simple_grid_field27",
1, "simple_grid_field38" ),
"whse", new XVar( 0, "simple_grid_field30",
1, "simple_grid_field39" ),
"CreateDate", new XVar( 0, "simple_grid_field",
1, "simple_grid_field40" ),
"tp_item_cost", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field41" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "inline_add" ),
"below-grid", XVar.Array(),
"top", new XVar( 0, "masterprint_header" ),
"grid", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field2",
2, "simple_grid_field6",
3, "simple_grid_field3",
4, "simple_grid_field10",
5, "simple_grid_field5",
6, "simple_grid_field11",
7, "simple_grid_field7",
8, "simple_grid_field12",
9, "simple_grid_field8",
10, "simple_grid_field13",
11, "simple_grid_field9",
12, "simple_grid_field22",
13, "simple_grid_field14",
14, "simple_grid_field23",
15, "simple_grid_field15",
16, "simple_grid_field28",
17, "simple_grid_field16",
18, "simple_grid_field29",
19, "simple_grid_field17",
20, "simple_grid_field31",
21, "simple_grid_field18",
22, "simple_grid_field32",
23, "simple_grid_field19",
24, "simple_grid_field33",
25, "simple_grid_field20",
26, "simple_grid_field34",
27, "simple_grid_field21",
28, "simple_grid_field35",
29, "simple_grid_field24",
30, "simple_grid_field36",
31, "simple_grid_field25",
32, "simple_grid_field37",
33, "simple_grid_field26",
34, "simple_grid_field38",
35, "simple_grid_field27",
36, "simple_grid_field39",
37, "simple_grid_field30",
38, "simple_grid_field40",
39, "simple_grid_field",
40, "simple_grid_field41",
41, "simple_grid_field1",
42, "grid_inline_cancel" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "inlineadd_link" ),
"below-grid", XVar.Array() ),
"itemForms", new XVar( "inline_add", "above-grid",
"masterprint_header", "top",
"simple_grid_field4", "grid",
"simple_grid_field2", "grid",
"simple_grid_field6", "grid",
"simple_grid_field3", "grid",
"simple_grid_field10", "grid",
"simple_grid_field5", "grid",
"simple_grid_field11", "grid",
"simple_grid_field7", "grid",
"simple_grid_field12", "grid",
"simple_grid_field8", "grid",
"simple_grid_field13", "grid",
"simple_grid_field9", "grid",
"simple_grid_field22", "grid",
"simple_grid_field14", "grid",
"simple_grid_field23", "grid",
"simple_grid_field15", "grid",
"simple_grid_field28", "grid",
"simple_grid_field16", "grid",
"simple_grid_field29", "grid",
"simple_grid_field17", "grid",
"simple_grid_field31", "grid",
"simple_grid_field18", "grid",
"simple_grid_field32", "grid",
"simple_grid_field19", "grid",
"simple_grid_field33", "grid",
"simple_grid_field20", "grid",
"simple_grid_field34", "grid",
"simple_grid_field21", "grid",
"simple_grid_field35", "grid",
"simple_grid_field24", "grid",
"simple_grid_field36", "grid",
"simple_grid_field25", "grid",
"simple_grid_field37", "grid",
"simple_grid_field26", "grid",
"simple_grid_field38", "grid",
"simple_grid_field27", "grid",
"simple_grid_field39", "grid",
"simple_grid_field30", "grid",
"simple_grid_field40", "grid",
"simple_grid_field", "grid",
"simple_grid_field41", "grid",
"simple_grid_field1", "grid",
"grid_inline_cancel", "grid" ),
"itemLocations", new XVar( "simple_grid_field4", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field22", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field14", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field23", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field15", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"simple_grid_field28", new XVar( "location", "grid",
"cellId", "headcell_field8" ),
"simple_grid_field16", new XVar( "location", "grid",
"cellId", "cell_field8" ),
"simple_grid_field29", new XVar( "location", "grid",
"cellId", "headcell_field9" ),
"simple_grid_field17", new XVar( "location", "grid",
"cellId", "cell_field9" ),
"simple_grid_field31", new XVar( "location", "grid",
"cellId", "headcell_field10" ),
"simple_grid_field18", new XVar( "location", "grid",
"cellId", "cell_field10" ),
"simple_grid_field32", new XVar( "location", "grid",
"cellId", "headcell_field11" ),
"simple_grid_field19", new XVar( "location", "grid",
"cellId", "cell_field11" ),
"simple_grid_field33", new XVar( "location", "grid",
"cellId", "headcell_field12" ),
"simple_grid_field20", new XVar( "location", "grid",
"cellId", "cell_field12" ),
"simple_grid_field34", new XVar( "location", "grid",
"cellId", "headcell_field13" ),
"simple_grid_field21", new XVar( "location", "grid",
"cellId", "cell_field13" ),
"simple_grid_field35", new XVar( "location", "grid",
"cellId", "headcell_field14" ),
"simple_grid_field24", new XVar( "location", "grid",
"cellId", "cell_field14" ),
"simple_grid_field36", new XVar( "location", "grid",
"cellId", "headcell_field15" ),
"simple_grid_field25", new XVar( "location", "grid",
"cellId", "cell_field15" ),
"simple_grid_field37", new XVar( "location", "grid",
"cellId", "headcell_field16" ),
"simple_grid_field26", new XVar( "location", "grid",
"cellId", "cell_field16" ),
"simple_grid_field38", new XVar( "location", "grid",
"cellId", "headcell_field17" ),
"simple_grid_field27", new XVar( "location", "grid",
"cellId", "cell_field17" ),
"simple_grid_field39", new XVar( "location", "grid",
"cellId", "headcell_field18" ),
"simple_grid_field30", new XVar( "location", "grid",
"cellId", "cell_field18" ),
"simple_grid_field40", new XVar( "location", "grid",
"cellId", "headcell_field19" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field19" ),
"simple_grid_field41", new XVar( "location", "grid",
"cellId", "headcell_field20" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field20" ),
"grid_inline_cancel", new XVar( "location", "grid",
"cellId", "cell_icons" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "masterprint_header", new XVar( 0, "masterprint_header" ),
"grid_field", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field3",
2, "simple_grid_field5",
3, "simple_grid_field7",
4, "simple_grid_field8",
5, "simple_grid_field9",
6, "simple_grid_field14",
7, "simple_grid_field15",
8, "simple_grid_field16",
9, "simple_grid_field17",
10, "simple_grid_field18",
11, "simple_grid_field19",
12, "simple_grid_field20",
13, "simple_grid_field21",
14, "simple_grid_field24",
15, "simple_grid_field25",
16, "simple_grid_field26",
17, "simple_grid_field27",
18, "simple_grid_field30",
19, "simple_grid_field",
20, "simple_grid_field1" ),
"grid_field_label", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field6",
2, "simple_grid_field10",
3, "simple_grid_field11",
4, "simple_grid_field12",
5, "simple_grid_field13",
6, "simple_grid_field22",
7, "simple_grid_field23",
8, "simple_grid_field28",
9, "simple_grid_field29",
10, "simple_grid_field31",
11, "simple_grid_field32",
12, "simple_grid_field33",
13, "simple_grid_field34",
14, "simple_grid_field35",
15, "simple_grid_field36",
16, "simple_grid_field37",
17, "simple_grid_field38",
18, "simple_grid_field39",
19, "simple_grid_field40",
20, "simple_grid_field41" ),
"inline_add", new XVar( 0, "inline_add" ),
"grid_inline_cancel", new XVar( 0, "grid_inline_cancel" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "po_line_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "po_release_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "description_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "item_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "item_cost_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "item_cost_conv_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "non_inv_acct_unit4_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field22" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "plan_cost_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field23" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field8", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "plan_cost_conv_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field28" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field9", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "qty_ordered_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field29" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field10", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "qty_ordered_conv_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field31" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field11", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "qty_received_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field32" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field12", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "qty_voucher_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field33" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field13", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "rcvd_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field34" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field14", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "stat_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field35" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field15", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "u_m_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field36" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field16", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "unit_mat_cost_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field37" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field17", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "unit_mat_cost_conv_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field38" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field18", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "whse_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field39" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field19", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "CreateDate_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field40" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field20", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_item_cost_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field41" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "inline_cancel" ),
"items", new XVar( 0, "grid_inline_cancel" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "po_line_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "po_release_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "description_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "item_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "item_cost_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "item_cost_conv_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "non_inv_acct_unit4_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field14" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "plan_cost_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field15" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field8", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "plan_cost_conv_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field16" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field9", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "qty_ordered_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field17" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field10", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "qty_ordered_conv_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field18" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field11", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "qty_received_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field19" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field12", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "qty_voucher_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field20" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field13", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "rcvd_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field21" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field14", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "stat_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field24" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field15", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "u_m_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field25" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field16", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "unit_mat_cost_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field26" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field17", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "unit_mat_cost_conv_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field27" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field18", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "whse_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field30" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field19", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "CreateDate_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field20", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_item_cost_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field8", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field9", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field10", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field11", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field12", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field13", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field14", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field15", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field16", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field17", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field18", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field19", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field20", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 22,
"height", 3 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"gridType", 0,
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "masterprint",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "masterprint",
"type", "masterprint",
"layoutId", "masterprint",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "empty-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "inline_add" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "empty-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "masterlist-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "masterprint_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_icons" ),
1, new XVar( "cell", "headcell_field" ),
2, new XVar( "cell", "headcell_field1" ),
3, new XVar( "cell", "headcell_field2" ),
4, new XVar( "cell", "headcell_field3" ),
5, new XVar( "cell", "headcell_field4" ),
6, new XVar( "cell", "headcell_field5" ),
7, new XVar( "cell", "headcell_field6" ),
8, new XVar( "cell", "headcell_field7" ),
9, new XVar( "cell", "headcell_field8" ),
10, new XVar( "cell", "headcell_field9" ),
11, new XVar( "cell", "headcell_field10" ),
12, new XVar( "cell", "headcell_field11" ),
13, new XVar( "cell", "headcell_field12" ),
14, new XVar( "cell", "headcell_field13" ),
15, new XVar( "cell", "headcell_field14" ),
16, new XVar( "cell", "headcell_field15" ),
17, new XVar( "cell", "headcell_field16" ),
18, new XVar( "cell", "headcell_field17" ),
19, new XVar( "cell", "headcell_field18" ),
20, new XVar( "cell", "headcell_field19" ),
21, new XVar( "cell", "headcell_field20" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_icons" ),
1, new XVar( "cell", "cell_field" ),
2, new XVar( "cell", "cell_field1" ),
3, new XVar( "cell", "cell_field2" ),
4, new XVar( "cell", "cell_field3" ),
5, new XVar( "cell", "cell_field4" ),
6, new XVar( "cell", "cell_field5" ),
7, new XVar( "cell", "cell_field6" ),
8, new XVar( "cell", "cell_field7" ),
9, new XVar( "cell", "cell_field8" ),
10, new XVar( "cell", "cell_field9" ),
11, new XVar( "cell", "cell_field10" ),
12, new XVar( "cell", "cell_field11" ),
13, new XVar( "cell", "cell_field12" ),
14, new XVar( "cell", "cell_field13" ),
15, new XVar( "cell", "cell_field14" ),
16, new XVar( "cell", "cell_field15" ),
17, new XVar( "cell", "cell_field16" ),
18, new XVar( "cell", "cell_field17" ),
19, new XVar( "cell", "cell_field18" ),
20, new XVar( "cell", "cell_field19" ),
21, new XVar( "cell", "cell_field20" ) ) ),
2, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_icons" ),
1, new XVar( "cell", "footcell_field" ),
2, new XVar( "cell", "footcell_field1" ),
3, new XVar( "cell", "footcell_field2" ),
4, new XVar( "cell", "footcell_field3" ),
5, new XVar( "cell", "footcell_field4" ),
6, new XVar( "cell", "footcell_field5" ),
7, new XVar( "cell", "footcell_field6" ),
8, new XVar( "cell", "footcell_field7" ),
9, new XVar( "cell", "footcell_field8" ),
10, new XVar( "cell", "footcell_field9" ),
11, new XVar( "cell", "footcell_field10" ),
12, new XVar( "cell", "footcell_field11" ),
13, new XVar( "cell", "footcell_field12" ),
14, new XVar( "cell", "footcell_field13" ),
15, new XVar( "cell", "footcell_field14" ),
16, new XVar( "cell", "footcell_field15" ),
17, new XVar( "cell", "footcell_field16" ),
18, new XVar( "cell", "footcell_field17" ),
19, new XVar( "cell", "footcell_field18" ),
20, new XVar( "cell", "footcell_field19" ),
21, new XVar( "cell", "footcell_field20" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "po_line",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "po_line",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "po_release",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "po_release",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "description",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "description",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "item",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "item",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "item_cost",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "item_cost",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "item_cost_conv",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "item_cost_conv",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field22" ),
"field", "non_inv_acct_unit4",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field14" ),
"field", "non_inv_acct_unit4",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field23" ),
"field", "plan_cost",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field15" ),
"field", "plan_cost",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field8", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field28" ),
"field", "plan_cost_conv",
"columnName", "field" ),
"cell_field8", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field16" ),
"field", "plan_cost_conv",
"columnName", "field" ),
"footcell_field8", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field9", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field29" ),
"field", "qty_ordered",
"columnName", "field" ),
"cell_field9", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field17" ),
"field", "qty_ordered",
"columnName", "field" ),
"footcell_field9", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field10", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field31" ),
"field", "qty_ordered_conv",
"columnName", "field" ),
"cell_field10", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field18" ),
"field", "qty_ordered_conv",
"columnName", "field" ),
"footcell_field10", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field11", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field32" ),
"field", "qty_received",
"columnName", "field" ),
"cell_field11", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field19" ),
"field", "qty_received",
"columnName", "field" ),
"footcell_field11", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field12", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field33" ),
"field", "qty_voucher",
"columnName", "field" ),
"cell_field12", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field20" ),
"field", "qty_voucher",
"columnName", "field" ),
"footcell_field12", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field13", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field34" ),
"field", "rcvd_date",
"columnName", "field" ),
"cell_field13", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field21" ),
"field", "rcvd_date",
"columnName", "field" ),
"footcell_field13", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field14", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field35" ),
"field", "stat",
"columnName", "field" ),
"cell_field14", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field24" ),
"field", "stat",
"columnName", "field" ),
"footcell_field14", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field15", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field36" ),
"field", "u_m",
"columnName", "field" ),
"cell_field15", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field25" ),
"field", "u_m",
"columnName", "field" ),
"footcell_field15", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field16", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field37" ),
"field", "unit_mat_cost",
"columnName", "field" ),
"cell_field16", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field26" ),
"field", "unit_mat_cost",
"columnName", "field" ),
"footcell_field16", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field17", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field38" ),
"field", "unit_mat_cost_conv",
"columnName", "field" ),
"cell_field17", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field27" ),
"field", "unit_mat_cost_conv",
"columnName", "field" ),
"footcell_field17", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field18", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field39" ),
"field", "whse",
"columnName", "field" ),
"cell_field18", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field30" ),
"field", "whse",
"columnName", "field" ),
"footcell_field18", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field19", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field40" ),
"field", "CreateDate",
"columnName", "field" ),
"cell_field19", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "CreateDate",
"columnName", "field" ),
"footcell_field19", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field20", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field41" ),
"field", "tp_item_cost",
"columnName", "field" ),
"cell_field20", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "tp_item_cost",
"columnName", "field" ),
"footcell_field20", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_icons", new XVar( "model", "headcell_icons",
"items", XVar.Array() ),
"cell_icons", new XVar( "model", "cell_icons",
"items", new XVar( 0, "grid_inline_cancel" ) ),
"footcell_icons", new XVar( "model", "footcell_icons",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "masterprint_header", new XVar( "type", "masterprint_header" ),
"simple_grid_field2", new XVar( "field", "po_line",
"type", "grid_field" ),
"simple_grid_field4", new XVar( "type", "grid_field_label",
"field", "po_line" ),
"simple_grid_field3", new XVar( "field", "po_release",
"type", "grid_field" ),
"simple_grid_field6", new XVar( "type", "grid_field_label",
"field", "po_release" ),
"simple_grid_field5", new XVar( "field", "description",
"type", "grid_field" ),
"simple_grid_field10", new XVar( "type", "grid_field_label",
"field", "description" ),
"simple_grid_field7", new XVar( "field", "item",
"type", "grid_field" ),
"simple_grid_field11", new XVar( "type", "grid_field_label",
"field", "item" ),
"simple_grid_field8", new XVar( "field", "item_cost",
"type", "grid_field" ),
"simple_grid_field12", new XVar( "type", "grid_field_label",
"field", "item_cost" ),
"simple_grid_field9", new XVar( "field", "item_cost_conv",
"type", "grid_field" ),
"simple_grid_field13", new XVar( "type", "grid_field_label",
"field", "item_cost_conv" ),
"simple_grid_field14", new XVar( "field", "non_inv_acct_unit4",
"type", "grid_field" ),
"simple_grid_field22", new XVar( "type", "grid_field_label",
"field", "non_inv_acct_unit4" ),
"simple_grid_field15", new XVar( "field", "plan_cost",
"type", "grid_field" ),
"simple_grid_field23", new XVar( "type", "grid_field_label",
"field", "plan_cost" ),
"simple_grid_field16", new XVar( "field", "plan_cost_conv",
"type", "grid_field" ),
"simple_grid_field28", new XVar( "type", "grid_field_label",
"field", "plan_cost_conv" ),
"simple_grid_field17", new XVar( "field", "qty_ordered",
"type", "grid_field" ),
"simple_grid_field29", new XVar( "type", "grid_field_label",
"field", "qty_ordered" ),
"simple_grid_field18", new XVar( "field", "qty_ordered_conv",
"type", "grid_field" ),
"simple_grid_field31", new XVar( "type", "grid_field_label",
"field", "qty_ordered_conv" ),
"simple_grid_field19", new XVar( "field", "qty_received",
"type", "grid_field" ),
"simple_grid_field32", new XVar( "type", "grid_field_label",
"field", "qty_received" ),
"simple_grid_field20", new XVar( "field", "qty_voucher",
"type", "grid_field" ),
"simple_grid_field33", new XVar( "type", "grid_field_label",
"field", "qty_voucher" ),
"simple_grid_field21", new XVar( "field", "rcvd_date",
"type", "grid_field" ),
"simple_grid_field34", new XVar( "type", "grid_field_label",
"field", "rcvd_date" ),
"simple_grid_field24", new XVar( "field", "stat",
"type", "grid_field" ),
"simple_grid_field35", new XVar( "type", "grid_field_label",
"field", "stat" ),
"simple_grid_field25", new XVar( "field", "u_m",
"type", "grid_field" ),
"simple_grid_field36", new XVar( "type", "grid_field_label",
"field", "u_m" ),
"simple_grid_field26", new XVar( "field", "unit_mat_cost",
"type", "grid_field" ),
"simple_grid_field37", new XVar( "type", "grid_field_label",
"field", "unit_mat_cost" ),
"simple_grid_field27", new XVar( "field", "unit_mat_cost_conv",
"type", "grid_field" ),
"simple_grid_field38", new XVar( "type", "grid_field_label",
"field", "unit_mat_cost_conv" ),
"simple_grid_field30", new XVar( "field", "whse",
"type", "grid_field" ),
"simple_grid_field39", new XVar( "type", "grid_field_label",
"field", "whse" ),
"simple_grid_field", new XVar( "field", "CreateDate",
"type", "grid_field" ),
"simple_grid_field40", new XVar( "type", "grid_field_label",
"field", "CreateDate" ),
"simple_grid_field1", new XVar( "field", "tp_item_cost",
"type", "grid_field" ),
"simple_grid_field41", new XVar( "type", "grid_field_label",
"field", "tp_item_cost" ),
"inline_add", new XVar( "type", "inline_add",
"detailsOnly", true ),
"grid_inline_cancel", new XVar( "type", "grid_inline_cancel" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}