
		// dbo.tp_po
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_tp_po_print
			{
				static public XVar options()
				{
					return new XVar( "pdf", new XVar( "pdfView", false ),
"details", new XVar( "dbo.tp_poitem", new XVar( "displayPreview", 1 ),
"dbo.tp_invoicedetails", new XVar( "displayPreview", 1 ),
"dbo.tp_po_audit", new XVar( "displayPreview", 1 ),
"dbo.tp_po_mst", new XVar( "displayPreview", 1 ),
"dbo.tp_po_rcpt_mst", new XVar( "displayPreview", 1 ),
"dbo.fieldaudit", new XVar( "displayPreview", 1 ),
"dbo.csi_lc_rcpt_mst", new XVar( "displayPreview", 1 ) ),
"master", new XVar( "dbo.tp_vendor", new XVar( "preview", true ) ),
"totals", new XVar( "clientid", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"po_num", new XVar( "totalsType", "" ),
"stat", new XVar( "totalsType", "" ),
"vend_num", new XVar( "totalsType", "" ),
"name", new XVar( "totalsType", "" ),
"order_date", new XVar( "totalsType", "" ),
"vend_order", new XVar( "totalsType", "" ),
"whse", new XVar( "totalsType", "" ),
"po_cost", new XVar( "totalsType", "" ),
"tp_posted", new XVar( "totalsType", "" ),
"inv_num", new XVar( "totalsType", "" ),
"inv_date", new XVar( "totalsType", "" ),
"curr_code", new XVar( "totalsType", "" ),
"dist_date", new XVar( "totalsType", "" ),
"exch_rate", new XVar( "totalsType", "" ),
"received", new XVar( "totalsType", "" ),
"PendInv", new XVar( "totalsType", "" ),
"CreateDate", new XVar( "totalsType", "" ),
"RecordDate", new XVar( "totalsType", "" ),
"tp_posted_date", new XVar( "totalsType", "" ),
"tp_rev", new XVar( "totalsType", "" ),
"firstrcvd", new XVar( "totalsType", "" ),
"lastrcvd", new XVar( "totalsType", "" ),
"tp_closed", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "clientid",
1, "site_ref",
2, "po_num",
3, "stat",
4, "vend_num",
5, "name",
6, "order_date",
7, "vend_order",
8, "whse",
9, "po_cost",
10, "tp_posted",
11, "inv_num",
12, "inv_date",
13, "curr_code",
14, "dist_date",
15, "exch_rate",
16, "received",
17, "PendInv",
18, "CreateDate",
19, "tp_posted_date",
20, "tp_rev",
21, "firstrcvd",
22, "lastrcvd",
23, "tp_closed" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "clientid", new XVar( 0, "simple_grid_field",
1, "simple_grid_field24" ),
"site_ref", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field25" ),
"po_num", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field26" ),
"stat", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field27" ),
"vend_num", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field28" ),
"name", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field29" ),
"order_date", new XVar( 0, "simple_grid_field6",
1, "simple_grid_field30" ),
"vend_order", new XVar( 0, "simple_grid_field7",
1, "simple_grid_field31" ),
"whse", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field32" ),
"po_cost", new XVar( 0, "simple_grid_field9",
1, "simple_grid_field33" ),
"tp_posted", new XVar( 0, "simple_grid_field10",
1, "simple_grid_field34" ),
"inv_num", new XVar( 0, "simple_grid_field11",
1, "simple_grid_field35" ),
"inv_date", new XVar( 0, "simple_grid_field12",
1, "simple_grid_field36" ),
"curr_code", new XVar( 0, "simple_grid_field13",
1, "simple_grid_field37" ),
"dist_date", new XVar( 0, "simple_grid_field14",
1, "simple_grid_field38" ),
"exch_rate", new XVar( 0, "simple_grid_field15",
1, "simple_grid_field39" ),
"received", new XVar( 0, "simple_grid_field16",
1, "simple_grid_field40" ),
"PendInv", new XVar( 0, "simple_grid_field17",
1, "simple_grid_field41" ),
"CreateDate", new XVar( 0, "simple_grid_field18",
1, "simple_grid_field42" ),
"tp_posted_date", new XVar( 0, "simple_grid_field19",
1, "simple_grid_field43" ),
"tp_rev", new XVar( 0, "simple_grid_field20",
1, "simple_grid_field44" ),
"firstrcvd", new XVar( 0, "simple_grid_field21",
1, "simple_grid_field45" ),
"lastrcvd", new XVar( 0, "simple_grid_field22",
1, "simple_grid_field46" ),
"tp_closed", new XVar( 0, "simple_grid_field23",
1, "simple_grid_field47" ) ),
"hideEmptyFields", XVar.Array() ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "print_pages",
1, "grid_inline_cancel",
2, "inline_add" ),
"below-grid", XVar.Array(),
"top", new XVar( 0, "print_header",
1, "print_subheader",
2, "master_info" ),
"grid", new XVar( 0, "simple_grid_field24",
1, "simple_grid_field",
2, "simple_grid_field25",
3, "simple_grid_field1",
4, "simple_grid_field26",
5, "simple_grid_field2",
6, "simple_grid_field27",
7, "simple_grid_field3",
8, "simple_grid_field28",
9, "simple_grid_field4",
10, "simple_grid_field29",
11, "simple_grid_field5",
12, "simple_grid_field30",
13, "simple_grid_field6",
14, "simple_grid_field31",
15, "simple_grid_field7",
16, "simple_grid_field32",
17, "simple_grid_field8",
18, "simple_grid_field33",
19, "simple_grid_field9",
20, "simple_grid_field34",
21, "simple_grid_field10",
22, "simple_grid_field35",
23, "simple_grid_field11",
24, "simple_grid_field36",
25, "simple_grid_field12",
26, "simple_grid_field37",
27, "simple_grid_field13",
28, "simple_grid_field38",
29, "simple_grid_field14",
30, "simple_grid_field39",
31, "simple_grid_field15",
32, "simple_grid_field40",
33, "simple_grid_field16",
34, "simple_grid_field41",
35, "simple_grid_field17",
36, "simple_grid_field42",
37, "simple_grid_field18",
38, "simple_grid_field43",
39, "simple_grid_field19",
40, "simple_grid_field44",
41, "simple_grid_field20",
42, "simple_grid_field45",
43, "simple_grid_field21",
44, "simple_grid_field46",
45, "simple_grid_field22",
46, "simple_grid_field47",
47, "simple_grid_field23",
48, "details_preview",
49, "details_preview1",
50, "details_preview2",
51, "details_preview3",
52, "details_preview4",
53, "details_preview5",
54, "details_preview6" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "print_pages",
1, "inline_cancel",
2, "inlineadd_link" ),
"below-grid", XVar.Array() ),
"itemForms", new XVar( "print_pages", "above-grid",
"grid_inline_cancel", "above-grid",
"inline_add", "above-grid",
"print_header", "top",
"print_subheader", "top",
"master_info", "top",
"simple_grid_field24", "grid",
"simple_grid_field", "grid",
"simple_grid_field25", "grid",
"simple_grid_field1", "grid",
"simple_grid_field26", "grid",
"simple_grid_field2", "grid",
"simple_grid_field27", "grid",
"simple_grid_field3", "grid",
"simple_grid_field28", "grid",
"simple_grid_field4", "grid",
"simple_grid_field29", "grid",
"simple_grid_field5", "grid",
"simple_grid_field30", "grid",
"simple_grid_field6", "grid",
"simple_grid_field31", "grid",
"simple_grid_field7", "grid",
"simple_grid_field32", "grid",
"simple_grid_field8", "grid",
"simple_grid_field33", "grid",
"simple_grid_field9", "grid",
"simple_grid_field34", "grid",
"simple_grid_field10", "grid",
"simple_grid_field35", "grid",
"simple_grid_field11", "grid",
"simple_grid_field36", "grid",
"simple_grid_field12", "grid",
"simple_grid_field37", "grid",
"simple_grid_field13", "grid",
"simple_grid_field38", "grid",
"simple_grid_field14", "grid",
"simple_grid_field39", "grid",
"simple_grid_field15", "grid",
"simple_grid_field40", "grid",
"simple_grid_field16", "grid",
"simple_grid_field41", "grid",
"simple_grid_field17", "grid",
"simple_grid_field42", "grid",
"simple_grid_field18", "grid",
"simple_grid_field43", "grid",
"simple_grid_field19", "grid",
"simple_grid_field44", "grid",
"simple_grid_field20", "grid",
"simple_grid_field45", "grid",
"simple_grid_field21", "grid",
"simple_grid_field46", "grid",
"simple_grid_field22", "grid",
"simple_grid_field47", "grid",
"simple_grid_field23", "grid",
"details_preview", "grid",
"details_preview1", "grid",
"details_preview2", "grid",
"details_preview3", "grid",
"details_preview4", "grid",
"details_preview5", "grid",
"details_preview6", "grid" ),
"itemLocations", new XVar( "simple_grid_field24", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field25", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field26", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field27", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field28", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field29", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field30", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field31", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"simple_grid_field32", new XVar( "location", "grid",
"cellId", "headcell_field8" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "cell_field8" ),
"simple_grid_field33", new XVar( "location", "grid",
"cellId", "headcell_field9" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "cell_field9" ),
"simple_grid_field34", new XVar( "location", "grid",
"cellId", "headcell_field10" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "cell_field10" ),
"simple_grid_field35", new XVar( "location", "grid",
"cellId", "headcell_field11" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "cell_field11" ),
"simple_grid_field36", new XVar( "location", "grid",
"cellId", "headcell_field12" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "cell_field12" ),
"simple_grid_field37", new XVar( "location", "grid",
"cellId", "headcell_field13" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "cell_field13" ),
"simple_grid_field38", new XVar( "location", "grid",
"cellId", "headcell_field14" ),
"simple_grid_field14", new XVar( "location", "grid",
"cellId", "cell_field14" ),
"simple_grid_field39", new XVar( "location", "grid",
"cellId", "headcell_field15" ),
"simple_grid_field15", new XVar( "location", "grid",
"cellId", "cell_field15" ),
"simple_grid_field40", new XVar( "location", "grid",
"cellId", "headcell_field16" ),
"simple_grid_field16", new XVar( "location", "grid",
"cellId", "cell_field16" ),
"simple_grid_field41", new XVar( "location", "grid",
"cellId", "headcell_field17" ),
"simple_grid_field17", new XVar( "location", "grid",
"cellId", "cell_field17" ),
"simple_grid_field42", new XVar( "location", "grid",
"cellId", "headcell_field18" ),
"simple_grid_field18", new XVar( "location", "grid",
"cellId", "cell_field18" ),
"simple_grid_field43", new XVar( "location", "grid",
"cellId", "headcell_field19" ),
"simple_grid_field19", new XVar( "location", "grid",
"cellId", "cell_field19" ),
"simple_grid_field44", new XVar( "location", "grid",
"cellId", "headcell_field20" ),
"simple_grid_field20", new XVar( "location", "grid",
"cellId", "cell_field20" ),
"simple_grid_field45", new XVar( "location", "grid",
"cellId", "headcell_field21" ),
"simple_grid_field21", new XVar( "location", "grid",
"cellId", "cell_field21" ),
"simple_grid_field46", new XVar( "location", "grid",
"cellId", "headcell_field22" ),
"simple_grid_field22", new XVar( "location", "grid",
"cellId", "cell_field22" ),
"simple_grid_field47", new XVar( "location", "grid",
"cellId", "headcell_field23" ),
"simple_grid_field23", new XVar( "location", "grid",
"cellId", "cell_field23" ),
"details_preview", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview1", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview2", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview3", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview4", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview5", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"details_preview6", new XVar( "location", "grid",
"cellId", "cell_dpreview" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "print_header", new XVar( 0, "print_header" ),
"print_subheader", new XVar( 0, "print_subheader" ),
"print_pages", new XVar( 0, "print_pages" ),
"master_info", new XVar( 0, "master_info" ),
"grid_field", new XVar( 0, "simple_grid_field",
1, "simple_grid_field1",
2, "simple_grid_field2",
3, "simple_grid_field3",
4, "simple_grid_field4",
5, "simple_grid_field5",
6, "simple_grid_field6",
7, "simple_grid_field7",
8, "simple_grid_field8",
9, "simple_grid_field9",
10, "simple_grid_field10",
11, "simple_grid_field11",
12, "simple_grid_field12",
13, "simple_grid_field13",
14, "simple_grid_field14",
15, "simple_grid_field15",
16, "simple_grid_field16",
17, "simple_grid_field17",
18, "simple_grid_field18",
19, "simple_grid_field19",
20, "simple_grid_field20",
21, "simple_grid_field21",
22, "simple_grid_field22",
23, "simple_grid_field23" ),
"grid_field_label", new XVar( 0, "simple_grid_field24",
1, "simple_grid_field25",
2, "simple_grid_field26",
3, "simple_grid_field27",
4, "simple_grid_field28",
5, "simple_grid_field29",
6, "simple_grid_field30",
7, "simple_grid_field31",
8, "simple_grid_field32",
9, "simple_grid_field33",
10, "simple_grid_field34",
11, "simple_grid_field35",
12, "simple_grid_field36",
13, "simple_grid_field37",
14, "simple_grid_field38",
15, "simple_grid_field39",
16, "simple_grid_field40",
17, "simple_grid_field41",
18, "simple_grid_field42",
19, "simple_grid_field43",
20, "simple_grid_field44",
21, "simple_grid_field45",
22, "simple_grid_field46",
23, "simple_grid_field47" ),
"details_preview", new XVar( 0, "details_preview",
1, "details_preview1",
2, "details_preview2",
3, "details_preview3",
4, "details_preview4",
5, "details_preview5",
6, "details_preview6" ),
"inline_add", new XVar( 0, "inline_add" ),
"grid_inline_cancel", new XVar( 0, "grid_inline_cancel" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_field", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "clientid_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field24" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "site_ref_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field25" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "po_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field26" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "stat_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field27" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "vend_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field28" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "name_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field29" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "order_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field30" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "vend_order_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field31" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field8", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "whse_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field32" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field9", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "po_cost_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field33" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field10", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_posted_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field34" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field11", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "inv_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field35" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field12", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "inv_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field36" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field13", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "curr_code_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field37" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field14", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "dist_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field38" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field15", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "exch_rate_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field39" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field16", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "received_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field40" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field17", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "PendInv_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field41" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field18", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "CreateDate_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field42" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field19", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_posted_date_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field43" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field20", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_rev_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field44" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field21", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "firstrcvd_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field45" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field22", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "lastrcvd_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field46" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field23", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_closed_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field47" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "clientid_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "site_ref_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "po_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "stat_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "vend_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "name_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "order_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "vend_order_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field8", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "whse_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field9", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "po_cost_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field10", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_posted_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field11", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "inv_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field12", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "inv_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field13", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "curr_code_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field14", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "dist_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field14" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field15", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "exch_rate_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field15" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field16", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "received_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field16" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field17", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "PendInv_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field17" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field18", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "CreateDate_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field18" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field19", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_posted_date_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field19" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field20", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_rev_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field20" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field21", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "firstrcvd_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field21" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field22", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "lastrcvd_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field22" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field23", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_closed_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field23" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_dpreview", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5,
6, 6,
7, 7,
8, 8,
9, 9,
10, 10,
11, 11,
12, 12,
13, 13,
14, 14,
15, 15,
16, 16,
17, 17,
18, 18,
19, 19,
20, 20,
21, 21,
22, 22,
23, 23 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "details_preview",
1, "details_preview1",
2, "details_preview2",
3, "details_preview3",
4, "details_preview4",
5, "details_preview5",
6, "details_preview6" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field8", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field9", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field10", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field11", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field12", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field13", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field14", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field15", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field16", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field17", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field18", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field19", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field20", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field21", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field22", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field23", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 24,
"height", 4 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar( "print_pages", new XVar( "tag", "PRINT_PAGES",
"type", 2 ) ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"gridType", 0,
"recsPerRow", 1,
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "print",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"dataGrid", new XVar( "groupFields", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "print",
"type", "print",
"layoutId", "basic",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "print-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "print_pages",
1, "grid_inline_cancel",
2, "inline_add" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "print-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "print-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c4" ) ),
"section", "" ) ),
"cells", new XVar( "c2", new XVar( "model", "c2",
"items", new XVar( 0, "print_header",
1, "print_subheader" ) ),
"c4", new XVar( "model", "c4",
"items", new XVar( 0, "master_info" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_field" ),
1, new XVar( "cell", "headcell_field1" ),
2, new XVar( "cell", "headcell_field2" ),
3, new XVar( "cell", "headcell_field3" ),
4, new XVar( "cell", "headcell_field4" ),
5, new XVar( "cell", "headcell_field5" ),
6, new XVar( "cell", "headcell_field6" ),
7, new XVar( "cell", "headcell_field7" ),
8, new XVar( "cell", "headcell_field8" ),
9, new XVar( "cell", "headcell_field9" ),
10, new XVar( "cell", "headcell_field10" ),
11, new XVar( "cell", "headcell_field11" ),
12, new XVar( "cell", "headcell_field12" ),
13, new XVar( "cell", "headcell_field13" ),
14, new XVar( "cell", "headcell_field14" ),
15, new XVar( "cell", "headcell_field15" ),
16, new XVar( "cell", "headcell_field16" ),
17, new XVar( "cell", "headcell_field17" ),
18, new XVar( "cell", "headcell_field18" ),
19, new XVar( "cell", "headcell_field19" ),
20, new XVar( "cell", "headcell_field20" ),
21, new XVar( "cell", "headcell_field21" ),
22, new XVar( "cell", "headcell_field22" ),
23, new XVar( "cell", "headcell_field23" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_field" ),
1, new XVar( "cell", "cell_field1" ),
2, new XVar( "cell", "cell_field2" ),
3, new XVar( "cell", "cell_field3" ),
4, new XVar( "cell", "cell_field4" ),
5, new XVar( "cell", "cell_field5" ),
6, new XVar( "cell", "cell_field6" ),
7, new XVar( "cell", "cell_field7" ),
8, new XVar( "cell", "cell_field8" ),
9, new XVar( "cell", "cell_field9" ),
10, new XVar( "cell", "cell_field10" ),
11, new XVar( "cell", "cell_field11" ),
12, new XVar( "cell", "cell_field12" ),
13, new XVar( "cell", "cell_field13" ),
14, new XVar( "cell", "cell_field14" ),
15, new XVar( "cell", "cell_field15" ),
16, new XVar( "cell", "cell_field16" ),
17, new XVar( "cell", "cell_field17" ),
18, new XVar( "cell", "cell_field18" ),
19, new XVar( "cell", "cell_field19" ),
20, new XVar( "cell", "cell_field20" ),
21, new XVar( "cell", "cell_field21" ),
22, new XVar( "cell", "cell_field22" ),
23, new XVar( "cell", "cell_field23" ) ) ),
2, new XVar( "cells", new XVar( 0, new XVar( "cell", "cell_dpreview",
"colspan", 24 ) ),
"section", "body" ),
3, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_field" ),
1, new XVar( "cell", "footcell_field1" ),
2, new XVar( "cell", "footcell_field2" ),
3, new XVar( "cell", "footcell_field3" ),
4, new XVar( "cell", "footcell_field4" ),
5, new XVar( "cell", "footcell_field5" ),
6, new XVar( "cell", "footcell_field6" ),
7, new XVar( "cell", "footcell_field7" ),
8, new XVar( "cell", "footcell_field8" ),
9, new XVar( "cell", "footcell_field9" ),
10, new XVar( "cell", "footcell_field10" ),
11, new XVar( "cell", "footcell_field11" ),
12, new XVar( "cell", "footcell_field12" ),
13, new XVar( "cell", "footcell_field13" ),
14, new XVar( "cell", "footcell_field14" ),
15, new XVar( "cell", "footcell_field15" ),
16, new XVar( "cell", "footcell_field16" ),
17, new XVar( "cell", "footcell_field17" ),
18, new XVar( "cell", "footcell_field18" ),
19, new XVar( "cell", "footcell_field19" ),
20, new XVar( "cell", "footcell_field20" ),
21, new XVar( "cell", "footcell_field21" ),
22, new XVar( "cell", "footcell_field22" ),
23, new XVar( "cell", "footcell_field23" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field24" ),
"field", "clientid",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "clientid",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field25" ),
"field", "site_ref",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "site_ref",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field26" ),
"field", "po_num",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "po_num",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field27" ),
"field", "stat",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "stat",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field28" ),
"field", "vend_num",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "vend_num",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field29" ),
"field", "name",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "name",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field30" ),
"field", "order_date",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "order_date",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field31" ),
"field", "vend_order",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "vend_order",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field8", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field32" ),
"field", "whse",
"columnName", "field" ),
"cell_field8", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "whse",
"columnName", "field" ),
"footcell_field8", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field9", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field33" ),
"field", "po_cost",
"columnName", "field" ),
"cell_field9", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "po_cost",
"columnName", "field" ),
"footcell_field9", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field10", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field34" ),
"field", "tp_posted",
"columnName", "field" ),
"cell_field10", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "tp_posted",
"columnName", "field" ),
"footcell_field10", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field11", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field35" ),
"field", "inv_num",
"columnName", "field" ),
"cell_field11", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "inv_num",
"columnName", "field" ),
"footcell_field11", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field12", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field36" ),
"field", "inv_date",
"columnName", "field" ),
"cell_field12", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "inv_date",
"columnName", "field" ),
"footcell_field12", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field13", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field37" ),
"field", "curr_code",
"columnName", "field" ),
"cell_field13", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "curr_code",
"columnName", "field" ),
"footcell_field13", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field14", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field38" ),
"field", "dist_date",
"columnName", "field" ),
"cell_field14", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field14" ),
"field", "dist_date",
"columnName", "field" ),
"footcell_field14", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field15", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field39" ),
"field", "exch_rate",
"columnName", "field" ),
"cell_field15", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field15" ),
"field", "exch_rate",
"columnName", "field" ),
"footcell_field15", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field16", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field40" ),
"field", "received",
"columnName", "field" ),
"cell_field16", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field16" ),
"field", "received",
"columnName", "field" ),
"footcell_field16", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field17", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field41" ),
"field", "PendInv",
"columnName", "field" ),
"cell_field17", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field17" ),
"field", "PendInv",
"columnName", "field" ),
"footcell_field17", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field18", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field42" ),
"field", "CreateDate",
"columnName", "field" ),
"cell_field18", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field18" ),
"field", "CreateDate",
"columnName", "field" ),
"footcell_field18", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field19", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field43" ),
"field", "tp_posted_date",
"columnName", "field" ),
"cell_field19", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field19" ),
"field", "tp_posted_date",
"columnName", "field" ),
"footcell_field19", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field20", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field44" ),
"field", "tp_rev",
"columnName", "field" ),
"cell_field20", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field20" ),
"field", "tp_rev",
"columnName", "field" ),
"footcell_field20", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field21", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field45" ),
"field", "firstrcvd",
"columnName", "field" ),
"cell_field21", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field21" ),
"field", "firstrcvd",
"columnName", "field" ),
"footcell_field21", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field22", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field46" ),
"field", "lastrcvd",
"columnName", "field" ),
"cell_field22", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field22" ),
"field", "lastrcvd",
"columnName", "field" ),
"footcell_field22", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field23", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field47" ),
"field", "tp_closed",
"columnName", "field" ),
"cell_field23", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field23" ),
"field", "tp_closed",
"columnName", "field" ),
"footcell_field23", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"cell_dpreview", new XVar( "model", "cell_dpreview",
"items", new XVar( 0, "details_preview",
1, "details_preview1",
2, "details_preview2",
3, "details_preview3",
4, "details_preview4",
5, "details_preview5",
6, "details_preview6" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "print_header", new XVar( "type", "print_header" ),
"print_subheader", new XVar( "type", "print_subheader" ),
"print_pages", new XVar( "type", "print_pages" ),
"master_info", new XVar( "type", "master_info",
"tables", new XVar( "dbo.tp_vendor", "true" ) ),
"simple_grid_field", new XVar( "field", "clientid",
"type", "grid_field" ),
"simple_grid_field24", new XVar( "type", "grid_field_label",
"field", "clientid" ),
"simple_grid_field1", new XVar( "field", "site_ref",
"type", "grid_field" ),
"simple_grid_field25", new XVar( "type", "grid_field_label",
"field", "site_ref" ),
"simple_grid_field2", new XVar( "field", "po_num",
"type", "grid_field" ),
"simple_grid_field26", new XVar( "type", "grid_field_label",
"field", "po_num" ),
"simple_grid_field3", new XVar( "field", "stat",
"type", "grid_field" ),
"simple_grid_field27", new XVar( "type", "grid_field_label",
"field", "stat" ),
"simple_grid_field4", new XVar( "field", "vend_num",
"type", "grid_field" ),
"simple_grid_field28", new XVar( "type", "grid_field_label",
"field", "vend_num" ),
"simple_grid_field5", new XVar( "field", "name",
"type", "grid_field" ),
"simple_grid_field29", new XVar( "type", "grid_field_label",
"field", "name" ),
"simple_grid_field6", new XVar( "field", "order_date",
"type", "grid_field" ),
"simple_grid_field30", new XVar( "type", "grid_field_label",
"field", "order_date" ),
"simple_grid_field7", new XVar( "field", "vend_order",
"type", "grid_field" ),
"simple_grid_field31", new XVar( "type", "grid_field_label",
"field", "vend_order" ),
"simple_grid_field8", new XVar( "field", "whse",
"type", "grid_field" ),
"simple_grid_field32", new XVar( "type", "grid_field_label",
"field", "whse" ),
"simple_grid_field9", new XVar( "field", "po_cost",
"type", "grid_field" ),
"simple_grid_field33", new XVar( "type", "grid_field_label",
"field", "po_cost" ),
"simple_grid_field10", new XVar( "field", "tp_posted",
"type", "grid_field" ),
"simple_grid_field34", new XVar( "type", "grid_field_label",
"field", "tp_posted" ),
"simple_grid_field11", new XVar( "field", "inv_num",
"type", "grid_field" ),
"simple_grid_field35", new XVar( "type", "grid_field_label",
"field", "inv_num" ),
"simple_grid_field12", new XVar( "field", "inv_date",
"type", "grid_field" ),
"simple_grid_field36", new XVar( "type", "grid_field_label",
"field", "inv_date" ),
"simple_grid_field13", new XVar( "field", "curr_code",
"type", "grid_field" ),
"simple_grid_field37", new XVar( "type", "grid_field_label",
"field", "curr_code" ),
"simple_grid_field14", new XVar( "field", "dist_date",
"type", "grid_field" ),
"simple_grid_field38", new XVar( "type", "grid_field_label",
"field", "dist_date" ),
"simple_grid_field15", new XVar( "field", "exch_rate",
"type", "grid_field" ),
"simple_grid_field39", new XVar( "type", "grid_field_label",
"field", "exch_rate" ),
"simple_grid_field16", new XVar( "field", "received",
"type", "grid_field" ),
"simple_grid_field40", new XVar( "type", "grid_field_label",
"field", "received" ),
"simple_grid_field17", new XVar( "field", "PendInv",
"type", "grid_field" ),
"simple_grid_field41", new XVar( "type", "grid_field_label",
"field", "PendInv" ),
"simple_grid_field18", new XVar( "field", "CreateDate",
"type", "grid_field" ),
"simple_grid_field42", new XVar( "type", "grid_field_label",
"field", "CreateDate" ),
"simple_grid_field19", new XVar( "field", "tp_posted_date",
"type", "grid_field" ),
"simple_grid_field43", new XVar( "type", "grid_field_label",
"field", "tp_posted_date" ),
"simple_grid_field20", new XVar( "field", "tp_rev",
"type", "grid_field" ),
"simple_grid_field44", new XVar( "type", "grid_field_label",
"field", "tp_rev" ),
"simple_grid_field21", new XVar( "field", "firstrcvd",
"type", "grid_field" ),
"simple_grid_field45", new XVar( "type", "grid_field_label",
"field", "firstrcvd" ),
"simple_grid_field22", new XVar( "field", "lastrcvd",
"type", "grid_field" ),
"simple_grid_field46", new XVar( "type", "grid_field_label",
"field", "lastrcvd" ),
"simple_grid_field23", new XVar( "field", "tp_closed",
"type", "grid_field" ),
"simple_grid_field47", new XVar( "type", "grid_field_label",
"field", "tp_closed" ),
"details_preview", new XVar( "type", "details_preview",
"table", "dbo.tp_poitem",
"items", XVar.Array(),
"popup", false ),
"details_preview1", new XVar( "type", "details_preview",
"table", "dbo.tp_invoicedetails",
"items", XVar.Array(),
"popup", false ),
"details_preview2", new XVar( "type", "details_preview",
"table", "dbo.tp_po_audit",
"items", XVar.Array(),
"popup", false ),
"details_preview3", new XVar( "type", "details_preview",
"table", "dbo.tp_po_mst",
"items", XVar.Array(),
"popup", false ),
"details_preview4", new XVar( "type", "details_preview",
"table", "dbo.tp_po_rcpt_mst",
"items", XVar.Array(),
"popup", false ),
"details_preview5", new XVar( "type", "details_preview",
"table", "dbo.fieldaudit",
"items", XVar.Array(),
"popup", false ),
"details_preview6", new XVar( "type", "details_preview",
"table", "dbo.csi_lc_rcpt_mst",
"items", XVar.Array(),
"popup", false ),
"inline_add", new XVar( "type", "inline_add",
"detailsOnly", true ),
"grid_inline_cancel", new XVar( "type", "grid_inline_cancel" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}