
		// dbo.tp_payments_hdr_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_tp_payments_hdr_mst_print
			{
				static public XVar options()
				{
					return new XVar( "pdf", new XVar( "pdfView", false ),
"details", new XVar( "dbo.tp_payments_lines_mst", new XVar( "displayPreview", 1 ) ),
"master", new XVar( "dbo.tp_vendor", new XVar( "preview", true ) ),
"totals", new XVar( "id", new XVar( "totalsType", "" ),
"SequenceRefCode", new XVar( "totalsType", "" ),
"submissionDate", new XVar( "totalsType", "" ),
"AmountSubmitted", new XVar( "totalsType", "" ),
"AmountSubmittedCur", new XVar( "totalsType", "" ),
"PaymentMethod", new XVar( "totalsType", "" ),
"Status", new XVar( "totalsType", "" ),
"PayerFees", new XVar( "totalsType", "" ),
"PayeeFxfees", new XVar( "totalsType", "" ),
"PayerFxfees", new XVar( "totalsType", "" ),
"withdrawCurr", new XVar( "totalsType", "" ),
"withdrawAmt", new XVar( "totalsType", "" ),
"NetAmountCurr", new XVar( "totalsType", "" ),
"NetAmount", new XVar( "totalsType", "" ),
"Message", new XVar( "totalsType", "" ),
"BankingMessage", new XVar( "totalsType", "" ),
"EmailSubject", new XVar( "totalsType", "" ),
"TxnReference", new XVar( "totalsType", "" ),
"paymentcurr", new XVar( "totalsType", "" ),
"PayerEntityName", new XVar( "totalsType", "" ),
"PayerEntityCountryISO", new XVar( "totalsType", "" ),
"Provider", new XVar( "totalsType", "" ),
"AccountIdentifier", new XVar( "totalsType", "" ),
"PayerExchangeRate", new XVar( "totalsType", "" ),
"PaymentAmountInWithdrawCurrency", new XVar( "totalsType", "" ),
"vendor", new XVar( "totalsType", "" ),
"TxnDate", new XVar( "totalsType", "" ),
"posted", new XVar( "totalsType", "" ),
"clientid", new XVar( "totalsType", "" ),
"trans_num", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"rowpointer", new XVar( "totalsType", "" ),
"RelatedBills", new XVar( "totalsType", "" ),
"err_msg", new XVar( "totalsType", "" ),
"json_data", new XVar( "totalsType", "" ),
"jresult", new XVar( "totalsType", "" ),
"postdate", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "id",
1, "SequenceRefCode",
2, "submissionDate",
3, "AmountSubmitted",
4, "AmountSubmittedCur",
5, "PaymentMethod",
6, "Status",
7, "PayerFees",
8, "PayeeFxfees",
9, "PayerFxfees",
10, "withdrawCurr",
11, "withdrawAmt",
12, "NetAmountCurr",
13, "NetAmount",
14, "Message",
15, "BankingMessage",
16, "EmailSubject",
17, "TxnReference",
18, "paymentcurr",
19, "PayerEntityName",
20, "PayerEntityCountryISO",
21, "Provider",
22, "AccountIdentifier",
23, "PayerExchangeRate",
24, "PaymentAmountInWithdrawCurrency",
25, "vendor",
26, "TxnDate",
27, "posted",
28, "clientid",
29, "trans_num",
30, "site_ref",
31, "rowpointer",
32, "RelatedBills",
33, "err_msg",
34, "json_data",
35, "jresult",
36, "postdate" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "id", new XVar( 0, "simple_grid_field",
1, "simple_grid_field37" ),
"SequenceRefCode", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field38" ),
"submissionDate", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field39" ),
"AmountSubmitted", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field40" ),
"AmountSubmittedCur", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field41" ),
"PaymentMethod", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field42" ),
"Status", new XVar( 0, "simple_grid_field6",
1, "simple_grid_field43" ),
"PayerFees", new XVar( 0, "simple_grid_field7",
1, "simple_grid_field44" ),
"PayeeFxfees", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field45" ),
"PayerFxfees", new XVar( 0, "simple_grid_field9",
1, "simple_grid_field46" ),
"withdrawCurr", new XVar( 0, "simple_grid_field10",
1, "simple_grid_field47" ),
"withdrawAmt", new XVar( 0, "simple_grid_field11",
1, "simple_grid_field48" ),
"NetAmountCurr", new XVar( 0, "simple_grid_field12",
1, "simple_grid_field49" ),
"NetAmount", new XVar( 0, "simple_grid_field13",
1, "simple_grid_field50" ),
"Message", new XVar( 0, "simple_grid_field14",
1, "simple_grid_field51" ),
"BankingMessage", new XVar( 0, "simple_grid_field15",
1, "simple_grid_field52" ),
"EmailSubject", new XVar( 0, "simple_grid_field16",
1, "simple_grid_field53" ),
"TxnReference", new XVar( 0, "simple_grid_field17",
1, "simple_grid_field54" ),
"paymentcurr", new XVar( 0, "simple_grid_field18",
1, "simple_grid_field55" ),
"PayerEntityName", new XVar( 0, "simple_grid_field19",
1, "simple_grid_field56" ),
"PayerEntityCountryISO", new XVar( 0, "simple_grid_field20",
1, "simple_grid_field57" ),
"Provider", new XVar( 0, "simple_grid_field21",
1, "simple_grid_field58" ),
"AccountIdentifier", new XVar( 0, "simple_grid_field22",
1, "simple_grid_field59" ),
"PayerExchangeRate", new XVar( 0, "simple_grid_field23",
1, "simple_grid_field60" ),
"PaymentAmountInWithdrawCurrency", new XVar( 0, "simple_grid_field24",
1, "simple_grid_field61" ),
"vendor", new XVar( 0, "simple_grid_field25",
1, "simple_grid_field62" ),
"TxnDate", new XVar( 0, "simple_grid_field26",
1, "simple_grid_field63" ),
"posted", new XVar( 0, "simple_grid_field27",
1, "simple_grid_field64" ),
"clientid", new XVar( 0, "simple_grid_field28",
1, "simple_grid_field65" ),
"trans_num", new XVar( 0, "simple_grid_field29",
1, "simple_grid_field66" ),
"site_ref", new XVar( 0, "simple_grid_field30",
1, "simple_grid_field67" ),
"rowpointer", new XVar( 0, "simple_grid_field31",
1, "simple_grid_field68" ),
"RelatedBills", new XVar( 0, "simple_grid_field32",
1, "simple_grid_field69" ),
"err_msg", new XVar( 0, "simple_grid_field33",
1, "simple_grid_field70" ),
"json_data", new XVar( 0, "simple_grid_field34",
1, "simple_grid_field71" ),
"jresult", new XVar( 0, "simple_grid_field35",
1, "simple_grid_field72" ),
"postdate", new XVar( 0, "simple_grid_field36",
1, "simple_grid_field73" ) ),
"hideEmptyFields", XVar.Array() ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "print_pages",
1, "grid_inline_cancel",
2, "inline_add" ),
"below-grid", XVar.Array(),
"top", new XVar( 0, "print_header",
1, "print_subheader",
2, "master_info" ),
"grid", new XVar( 0, "simple_grid_field37",
1, "simple_grid_field",
2, "simple_grid_field38",
3, "simple_grid_field1",
4, "simple_grid_field39",
5, "simple_grid_field2",
6, "simple_grid_field40",
7, "simple_grid_field3",
8, "simple_grid_field41",
9, "simple_grid_field4",
10, "simple_grid_field42",
11, "simple_grid_field5",
12, "simple_grid_field43",
13, "simple_grid_field6",
14, "simple_grid_field44",
15, "simple_grid_field7",
16, "simple_grid_field45",
17, "simple_grid_field8",
18, "simple_grid_field46",
19, "simple_grid_field9",
20, "simple_grid_field47",
21, "simple_grid_field10",
22, "simple_grid_field48",
23, "simple_grid_field11",
24, "simple_grid_field49",
25, "simple_grid_field12",
26, "simple_grid_field50",
27, "simple_grid_field13",
28, "simple_grid_field51",
29, "simple_grid_field14",
30, "simple_grid_field52",
31, "simple_grid_field15",
32, "simple_grid_field53",
33, "simple_grid_field16",
34, "simple_grid_field54",
35, "simple_grid_field17",
36, "simple_grid_field55",
37, "simple_grid_field18",
38, "simple_grid_field56",
39, "simple_grid_field19",
40, "simple_grid_field57",
41, "simple_grid_field20",
42, "simple_grid_field58",
43, "simple_grid_field21",
44, "simple_grid_field59",
45, "simple_grid_field22",
46, "simple_grid_field60",
47, "simple_grid_field23",
48, "simple_grid_field61",
49, "simple_grid_field24",
50, "simple_grid_field62",
51, "simple_grid_field25",
52, "simple_grid_field63",
53, "simple_grid_field26",
54, "simple_grid_field64",
55, "simple_grid_field27",
56, "simple_grid_field65",
57, "simple_grid_field28",
58, "simple_grid_field66",
59, "simple_grid_field29",
60, "simple_grid_field67",
61, "simple_grid_field30",
62, "simple_grid_field68",
63, "simple_grid_field31",
64, "simple_grid_field69",
65, "simple_grid_field32",
66, "simple_grid_field70",
67, "simple_grid_field33",
68, "simple_grid_field71",
69, "simple_grid_field34",
70, "simple_grid_field72",
71, "simple_grid_field35",
72, "simple_grid_field73",
73, "simple_grid_field36",
74, "details_preview" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "print_pages",
1, "inline_cancel",
2, "inlineadd_link" ),
"below-grid", XVar.Array() ),
"itemForms", new XVar( "print_pages", "above-grid",
"grid_inline_cancel", "above-grid",
"inline_add", "above-grid",
"print_header", "top",
"print_subheader", "top",
"master_info", "top",
"simple_grid_field37", "grid",
"simple_grid_field", "grid",
"simple_grid_field38", "grid",
"simple_grid_field1", "grid",
"simple_grid_field39", "grid",
"simple_grid_field2", "grid",
"simple_grid_field40", "grid",
"simple_grid_field3", "grid",
"simple_grid_field41", "grid",
"simple_grid_field4", "grid",
"simple_grid_field42", "grid",
"simple_grid_field5", "grid",
"simple_grid_field43", "grid",
"simple_grid_field6", "grid",
"simple_grid_field44", "grid",
"simple_grid_field7", "grid",
"simple_grid_field45", "grid",
"simple_grid_field8", "grid",
"simple_grid_field46", "grid",
"simple_grid_field9", "grid",
"simple_grid_field47", "grid",
"simple_grid_field10", "grid",
"simple_grid_field48", "grid",
"simple_grid_field11", "grid",
"simple_grid_field49", "grid",
"simple_grid_field12", "grid",
"simple_grid_field50", "grid",
"simple_grid_field13", "grid",
"simple_grid_field51", "grid",
"simple_grid_field14", "grid",
"simple_grid_field52", "grid",
"simple_grid_field15", "grid",
"simple_grid_field53", "grid",
"simple_grid_field16", "grid",
"simple_grid_field54", "grid",
"simple_grid_field17", "grid",
"simple_grid_field55", "grid",
"simple_grid_field18", "grid",
"simple_grid_field56", "grid",
"simple_grid_field19", "grid",
"simple_grid_field57", "grid",
"simple_grid_field20", "grid",
"simple_grid_field58", "grid",
"simple_grid_field21", "grid",
"simple_grid_field59", "grid",
"simple_grid_field22", "grid",
"simple_grid_field60", "grid",
"simple_grid_field23", "grid",
"simple_grid_field61", "grid",
"simple_grid_field24", "grid",
"simple_grid_field62", "grid",
"simple_grid_field25", "grid",
"simple_grid_field63", "grid",
"simple_grid_field26", "grid",
"simple_grid_field64", "grid",
"simple_grid_field27", "grid",
"simple_grid_field65", "grid",
"simple_grid_field28", "grid",
"simple_grid_field66", "grid",
"simple_grid_field29", "grid",
"simple_grid_field67", "grid",
"simple_grid_field30", "grid",
"simple_grid_field68", "grid",
"simple_grid_field31", "grid",
"simple_grid_field69", "grid",
"simple_grid_field32", "grid",
"simple_grid_field70", "grid",
"simple_grid_field33", "grid",
"simple_grid_field71", "grid",
"simple_grid_field34", "grid",
"simple_grid_field72", "grid",
"simple_grid_field35", "grid",
"simple_grid_field73", "grid",
"simple_grid_field36", "grid",
"details_preview", "grid" ),
"itemLocations", new XVar( "simple_grid_field37", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field38", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field39", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field40", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field41", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field42", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field43", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field44", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"simple_grid_field45", new XVar( "location", "grid",
"cellId", "headcell_field8" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "cell_field8" ),
"simple_grid_field46", new XVar( "location", "grid",
"cellId", "headcell_field9" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "cell_field9" ),
"simple_grid_field47", new XVar( "location", "grid",
"cellId", "headcell_field10" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "cell_field10" ),
"simple_grid_field48", new XVar( "location", "grid",
"cellId", "headcell_field11" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "cell_field11" ),
"simple_grid_field49", new XVar( "location", "grid",
"cellId", "headcell_field12" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "cell_field12" ),
"simple_grid_field50", new XVar( "location", "grid",
"cellId", "headcell_field13" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "cell_field13" ),
"simple_grid_field51", new XVar( "location", "grid",
"cellId", "headcell_field14" ),
"simple_grid_field14", new XVar( "location", "grid",
"cellId", "cell_field14" ),
"simple_grid_field52", new XVar( "location", "grid",
"cellId", "headcell_field15" ),
"simple_grid_field15", new XVar( "location", "grid",
"cellId", "cell_field15" ),
"simple_grid_field53", new XVar( "location", "grid",
"cellId", "headcell_field16" ),
"simple_grid_field16", new XVar( "location", "grid",
"cellId", "cell_field16" ),
"simple_grid_field54", new XVar( "location", "grid",
"cellId", "headcell_field17" ),
"simple_grid_field17", new XVar( "location", "grid",
"cellId", "cell_field17" ),
"simple_grid_field55", new XVar( "location", "grid",
"cellId", "headcell_field18" ),
"simple_grid_field18", new XVar( "location", "grid",
"cellId", "cell_field18" ),
"simple_grid_field56", new XVar( "location", "grid",
"cellId", "headcell_field19" ),
"simple_grid_field19", new XVar( "location", "grid",
"cellId", "cell_field19" ),
"simple_grid_field57", new XVar( "location", "grid",
"cellId", "headcell_field20" ),
"simple_grid_field20", new XVar( "location", "grid",
"cellId", "cell_field20" ),
"simple_grid_field58", new XVar( "location", "grid",
"cellId", "headcell_field21" ),
"simple_grid_field21", new XVar( "location", "grid",
"cellId", "cell_field21" ),
"simple_grid_field59", new XVar( "location", "grid",
"cellId", "headcell_field22" ),
"simple_grid_field22", new XVar( "location", "grid",
"cellId", "cell_field22" ),
"simple_grid_field60", new XVar( "location", "grid",
"cellId", "headcell_field23" ),
"simple_grid_field23", new XVar( "location", "grid",
"cellId", "cell_field23" ),
"simple_grid_field61", new XVar( "location", "grid",
"cellId", "headcell_field24" ),
"simple_grid_field24", new XVar( "location", "grid",
"cellId", "cell_field24" ),
"simple_grid_field62", new XVar( "location", "grid",
"cellId", "headcell_field25" ),
"simple_grid_field25", new XVar( "location", "grid",
"cellId", "cell_field25" ),
"simple_grid_field63", new XVar( "location", "grid",
"cellId", "headcell_field26" ),
"simple_grid_field26", new XVar( "location", "grid",
"cellId", "cell_field26" ),
"simple_grid_field64", new XVar( "location", "grid",
"cellId", "headcell_field27" ),
"simple_grid_field27", new XVar( "location", "grid",
"cellId", "cell_field27" ),
"simple_grid_field65", new XVar( "location", "grid",
"cellId", "headcell_field28" ),
"simple_grid_field28", new XVar( "location", "grid",
"cellId", "cell_field28" ),
"simple_grid_field66", new XVar( "location", "grid",
"cellId", "headcell_field29" ),
"simple_grid_field29", new XVar( "location", "grid",
"cellId", "cell_field29" ),
"simple_grid_field67", new XVar( "location", "grid",
"cellId", "headcell_field30" ),
"simple_grid_field30", new XVar( "location", "grid",
"cellId", "cell_field30" ),
"simple_grid_field68", new XVar( "location", "grid",
"cellId", "headcell_field31" ),
"simple_grid_field31", new XVar( "location", "grid",
"cellId", "cell_field31" ),
"simple_grid_field69", new XVar( "location", "grid",
"cellId", "headcell_field32" ),
"simple_grid_field32", new XVar( "location", "grid",
"cellId", "cell_field32" ),
"simple_grid_field70", new XVar( "location", "grid",
"cellId", "headcell_field33" ),
"simple_grid_field33", new XVar( "location", "grid",
"cellId", "cell_field33" ),
"simple_grid_field71", new XVar( "location", "grid",
"cellId", "headcell_field34" ),
"simple_grid_field34", new XVar( "location", "grid",
"cellId", "cell_field34" ),
"simple_grid_field72", new XVar( "location", "grid",
"cellId", "headcell_field35" ),
"simple_grid_field35", new XVar( "location", "grid",
"cellId", "cell_field35" ),
"simple_grid_field73", new XVar( "location", "grid",
"cellId", "headcell_field36" ),
"simple_grid_field36", new XVar( "location", "grid",
"cellId", "cell_field36" ),
"details_preview", new XVar( "location", "grid",
"cellId", "cell_dpreview" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "print_header", new XVar( 0, "print_header" ),
"print_subheader", new XVar( 0, "print_subheader" ),
"print_pages", new XVar( 0, "print_pages" ),
"master_info", new XVar( 0, "master_info" ),
"grid_field", new XVar( 0, "simple_grid_field",
1, "simple_grid_field1",
2, "simple_grid_field2",
3, "simple_grid_field3",
4, "simple_grid_field4",
5, "simple_grid_field5",
6, "simple_grid_field6",
7, "simple_grid_field7",
8, "simple_grid_field8",
9, "simple_grid_field9",
10, "simple_grid_field10",
11, "simple_grid_field11",
12, "simple_grid_field12",
13, "simple_grid_field13",
14, "simple_grid_field14",
15, "simple_grid_field15",
16, "simple_grid_field16",
17, "simple_grid_field17",
18, "simple_grid_field18",
19, "simple_grid_field19",
20, "simple_grid_field20",
21, "simple_grid_field21",
22, "simple_grid_field22",
23, "simple_grid_field23",
24, "simple_grid_field24",
25, "simple_grid_field25",
26, "simple_grid_field26",
27, "simple_grid_field27",
28, "simple_grid_field28",
29, "simple_grid_field29",
30, "simple_grid_field30",
31, "simple_grid_field31",
32, "simple_grid_field32",
33, "simple_grid_field33",
34, "simple_grid_field34",
35, "simple_grid_field35",
36, "simple_grid_field36" ),
"grid_field_label", new XVar( 0, "simple_grid_field37",
1, "simple_grid_field38",
2, "simple_grid_field39",
3, "simple_grid_field40",
4, "simple_grid_field41",
5, "simple_grid_field42",
6, "simple_grid_field43",
7, "simple_grid_field44",
8, "simple_grid_field45",
9, "simple_grid_field46",
10, "simple_grid_field47",
11, "simple_grid_field48",
12, "simple_grid_field49",
13, "simple_grid_field50",
14, "simple_grid_field51",
15, "simple_grid_field52",
16, "simple_grid_field53",
17, "simple_grid_field54",
18, "simple_grid_field55",
19, "simple_grid_field56",
20, "simple_grid_field57",
21, "simple_grid_field58",
22, "simple_grid_field59",
23, "simple_grid_field60",
24, "simple_grid_field61",
25, "simple_grid_field62",
26, "simple_grid_field63",
27, "simple_grid_field64",
28, "simple_grid_field65",
29, "simple_grid_field66",
30, "simple_grid_field67",
31, "simple_grid_field68",
32, "simple_grid_field69",
33, "simple_grid_field70",
34, "simple_grid_field71",
35, "simple_grid_field72",
36, "simple_grid_field73" ),
"details_preview", new XVar( 0, "details_preview" ),
"inline_add", new XVar( 0, "inline_add" ),
"grid_inline_cancel", new XVar( 0, "grid_inline_cancel" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_field", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "id_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field37" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "SequenceRefCode_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field38" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "submissionDate_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field39" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "AmountSubmitted_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field40" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "AmountSubmittedCur_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field41" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "PaymentMethod_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field42" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "Status_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field43" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "PayerFees_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field44" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field8", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "PayeeFxfees_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field45" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field9", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "PayerFxfees_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field46" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field10", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "withdrawCurr_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field47" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field11", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "withdrawAmt_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field48" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field12", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "NetAmountCurr_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field49" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field13", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "NetAmount_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field50" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field14", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "Message_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field51" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field15", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "BankingMessage_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field52" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field16", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "EmailSubject_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field53" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field17", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "TxnReference_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field54" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field18", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "paymentcurr_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field55" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field19", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "PayerEntityName_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field56" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field20", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "PayerEntityCountryISO_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field57" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field21", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "Provider_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field58" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field22", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "AccountIdentifier_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field59" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field23", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "PayerExchangeRate_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field60" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field24", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "PaymentAmountInWithdrawCurrency_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field61" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field25", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "vendor_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field62" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field26", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "TxnDate_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field63" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field27", new XVar( "cols", new XVar( 0, 27 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "posted_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field64" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field28", new XVar( "cols", new XVar( 0, 28 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "clientid_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field65" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field29", new XVar( "cols", new XVar( 0, 29 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "trans_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field66" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field30", new XVar( "cols", new XVar( 0, 30 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "site_ref_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field67" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field31", new XVar( "cols", new XVar( 0, 31 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "rowpointer_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field68" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field32", new XVar( "cols", new XVar( 0, 32 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "RelatedBills_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field69" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field33", new XVar( "cols", new XVar( 0, 33 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "err_msg_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field70" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field34", new XVar( "cols", new XVar( 0, 34 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "json_data_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field71" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field35", new XVar( "cols", new XVar( 0, 35 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "jresult_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field72" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field36", new XVar( "cols", new XVar( 0, 36 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "postdate_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field73" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "id_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "SequenceRefCode_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "submissionDate_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "AmountSubmitted_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "AmountSubmittedCur_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "PaymentMethod_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "Status_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "PayerFees_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field8", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "PayeeFxfees_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field9", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "PayerFxfees_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field10", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "withdrawCurr_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field11", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "withdrawAmt_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field12", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "NetAmountCurr_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field13", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "NetAmount_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field14", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "Message_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field14" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field15", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "BankingMessage_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field15" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field16", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "EmailSubject_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field16" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field17", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "TxnReference_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field17" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field18", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "paymentcurr_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field18" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field19", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "PayerEntityName_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field19" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field20", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "PayerEntityCountryISO_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field20" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field21", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "Provider_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field21" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field22", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "AccountIdentifier_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field22" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field23", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "PayerExchangeRate_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field23" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field24", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "PaymentAmountInWithdrawCurrency_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field24" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field25", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "vendor_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field25" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field26", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "TxnDate_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field26" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field27", new XVar( "cols", new XVar( 0, 27 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "posted_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field27" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field28", new XVar( "cols", new XVar( 0, 28 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "clientid_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field28" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field29", new XVar( "cols", new XVar( 0, 29 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "trans_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field29" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field30", new XVar( "cols", new XVar( 0, 30 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "site_ref_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field30" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field31", new XVar( "cols", new XVar( 0, 31 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "rowpointer_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field31" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field32", new XVar( "cols", new XVar( 0, 32 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "RelatedBills_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field32" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field33", new XVar( "cols", new XVar( 0, 33 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "err_msg_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field33" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field34", new XVar( "cols", new XVar( 0, 34 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "json_data_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field34" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field35", new XVar( "cols", new XVar( 0, 35 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "jresult_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field35" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field36", new XVar( "cols", new XVar( 0, 36 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "postdate_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field36" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_dpreview", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5,
6, 6,
7, 7,
8, 8,
9, 9,
10, 10,
11, 11,
12, 12,
13, 13,
14, 14,
15, 15,
16, 16,
17, 17,
18, 18,
19, 19,
20, 20,
21, 21,
22, 22,
23, 23,
24, 24,
25, 25,
26, 26,
27, 27,
28, 28,
29, 29,
30, 30,
31, 31,
32, 32,
33, 33,
34, 34,
35, 35,
36, 36 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "details_preview" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field8", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field9", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field10", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field11", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field12", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field13", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field14", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field15", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field16", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field17", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field18", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field19", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field20", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field21", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field22", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field23", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field24", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field25", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field26", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field27", new XVar( "cols", new XVar( 0, 27 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field28", new XVar( "cols", new XVar( 0, 28 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field29", new XVar( "cols", new XVar( 0, 29 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field30", new XVar( "cols", new XVar( 0, 30 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field31", new XVar( "cols", new XVar( 0, 31 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field32", new XVar( "cols", new XVar( 0, 32 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field33", new XVar( "cols", new XVar( 0, 33 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field34", new XVar( "cols", new XVar( 0, 34 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field35", new XVar( "cols", new XVar( 0, 35 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field36", new XVar( "cols", new XVar( 0, 36 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 37,
"height", 4 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar( "print_pages", new XVar( "tag", "PRINT_PAGES",
"type", 2 ) ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"gridType", 0,
"recsPerRow", 1,
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "print",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"dataGrid", new XVar( "groupFields", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "print",
"type", "print",
"layoutId", "basic",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "print-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "print_pages",
1, "grid_inline_cancel",
2, "inline_add" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "print-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "print-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c4" ) ),
"section", "" ) ),
"cells", new XVar( "c2", new XVar( "model", "c2",
"items", new XVar( 0, "print_header",
1, "print_subheader" ) ),
"c4", new XVar( "model", "c4",
"items", new XVar( 0, "master_info" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_field" ),
1, new XVar( "cell", "headcell_field1" ),
2, new XVar( "cell", "headcell_field2" ),
3, new XVar( "cell", "headcell_field3" ),
4, new XVar( "cell", "headcell_field4" ),
5, new XVar( "cell", "headcell_field5" ),
6, new XVar( "cell", "headcell_field6" ),
7, new XVar( "cell", "headcell_field7" ),
8, new XVar( "cell", "headcell_field8" ),
9, new XVar( "cell", "headcell_field9" ),
10, new XVar( "cell", "headcell_field10" ),
11, new XVar( "cell", "headcell_field11" ),
12, new XVar( "cell", "headcell_field12" ),
13, new XVar( "cell", "headcell_field13" ),
14, new XVar( "cell", "headcell_field14" ),
15, new XVar( "cell", "headcell_field15" ),
16, new XVar( "cell", "headcell_field16" ),
17, new XVar( "cell", "headcell_field17" ),
18, new XVar( "cell", "headcell_field18" ),
19, new XVar( "cell", "headcell_field19" ),
20, new XVar( "cell", "headcell_field20" ),
21, new XVar( "cell", "headcell_field21" ),
22, new XVar( "cell", "headcell_field22" ),
23, new XVar( "cell", "headcell_field23" ),
24, new XVar( "cell", "headcell_field24" ),
25, new XVar( "cell", "headcell_field25" ),
26, new XVar( "cell", "headcell_field26" ),
27, new XVar( "cell", "headcell_field27" ),
28, new XVar( "cell", "headcell_field28" ),
29, new XVar( "cell", "headcell_field29" ),
30, new XVar( "cell", "headcell_field30" ),
31, new XVar( "cell", "headcell_field31" ),
32, new XVar( "cell", "headcell_field32" ),
33, new XVar( "cell", "headcell_field33" ),
34, new XVar( "cell", "headcell_field34" ),
35, new XVar( "cell", "headcell_field35" ),
36, new XVar( "cell", "headcell_field36" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_field" ),
1, new XVar( "cell", "cell_field1" ),
2, new XVar( "cell", "cell_field2" ),
3, new XVar( "cell", "cell_field3" ),
4, new XVar( "cell", "cell_field4" ),
5, new XVar( "cell", "cell_field5" ),
6, new XVar( "cell", "cell_field6" ),
7, new XVar( "cell", "cell_field7" ),
8, new XVar( "cell", "cell_field8" ),
9, new XVar( "cell", "cell_field9" ),
10, new XVar( "cell", "cell_field10" ),
11, new XVar( "cell", "cell_field11" ),
12, new XVar( "cell", "cell_field12" ),
13, new XVar( "cell", "cell_field13" ),
14, new XVar( "cell", "cell_field14" ),
15, new XVar( "cell", "cell_field15" ),
16, new XVar( "cell", "cell_field16" ),
17, new XVar( "cell", "cell_field17" ),
18, new XVar( "cell", "cell_field18" ),
19, new XVar( "cell", "cell_field19" ),
20, new XVar( "cell", "cell_field20" ),
21, new XVar( "cell", "cell_field21" ),
22, new XVar( "cell", "cell_field22" ),
23, new XVar( "cell", "cell_field23" ),
24, new XVar( "cell", "cell_field24" ),
25, new XVar( "cell", "cell_field25" ),
26, new XVar( "cell", "cell_field26" ),
27, new XVar( "cell", "cell_field27" ),
28, new XVar( "cell", "cell_field28" ),
29, new XVar( "cell", "cell_field29" ),
30, new XVar( "cell", "cell_field30" ),
31, new XVar( "cell", "cell_field31" ),
32, new XVar( "cell", "cell_field32" ),
33, new XVar( "cell", "cell_field33" ),
34, new XVar( "cell", "cell_field34" ),
35, new XVar( "cell", "cell_field35" ),
36, new XVar( "cell", "cell_field36" ) ) ),
2, new XVar( "cells", new XVar( 0, new XVar( "cell", "cell_dpreview",
"colspan", 37 ) ),
"section", "body" ),
3, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_field" ),
1, new XVar( "cell", "footcell_field1" ),
2, new XVar( "cell", "footcell_field2" ),
3, new XVar( "cell", "footcell_field3" ),
4, new XVar( "cell", "footcell_field4" ),
5, new XVar( "cell", "footcell_field5" ),
6, new XVar( "cell", "footcell_field6" ),
7, new XVar( "cell", "footcell_field7" ),
8, new XVar( "cell", "footcell_field8" ),
9, new XVar( "cell", "footcell_field9" ),
10, new XVar( "cell", "footcell_field10" ),
11, new XVar( "cell", "footcell_field11" ),
12, new XVar( "cell", "footcell_field12" ),
13, new XVar( "cell", "footcell_field13" ),
14, new XVar( "cell", "footcell_field14" ),
15, new XVar( "cell", "footcell_field15" ),
16, new XVar( "cell", "footcell_field16" ),
17, new XVar( "cell", "footcell_field17" ),
18, new XVar( "cell", "footcell_field18" ),
19, new XVar( "cell", "footcell_field19" ),
20, new XVar( "cell", "footcell_field20" ),
21, new XVar( "cell", "footcell_field21" ),
22, new XVar( "cell", "footcell_field22" ),
23, new XVar( "cell", "footcell_field23" ),
24, new XVar( "cell", "footcell_field24" ),
25, new XVar( "cell", "footcell_field25" ),
26, new XVar( "cell", "footcell_field26" ),
27, new XVar( "cell", "footcell_field27" ),
28, new XVar( "cell", "footcell_field28" ),
29, new XVar( "cell", "footcell_field29" ),
30, new XVar( "cell", "footcell_field30" ),
31, new XVar( "cell", "footcell_field31" ),
32, new XVar( "cell", "footcell_field32" ),
33, new XVar( "cell", "footcell_field33" ),
34, new XVar( "cell", "footcell_field34" ),
35, new XVar( "cell", "footcell_field35" ),
36, new XVar( "cell", "footcell_field36" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field37" ),
"field", "id",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "id",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field38" ),
"field", "SequenceRefCode",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "SequenceRefCode",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field39" ),
"field", "submissionDate",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "submissionDate",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field40" ),
"field", "AmountSubmitted",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "AmountSubmitted",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field41" ),
"field", "AmountSubmittedCur",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "AmountSubmittedCur",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field42" ),
"field", "PaymentMethod",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "PaymentMethod",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field43" ),
"field", "Status",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "Status",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field44" ),
"field", "PayerFees",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "PayerFees",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field8", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field45" ),
"field", "PayeeFxfees",
"columnName", "field" ),
"cell_field8", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "PayeeFxfees",
"columnName", "field" ),
"footcell_field8", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field9", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field46" ),
"field", "PayerFxfees",
"columnName", "field" ),
"cell_field9", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "PayerFxfees",
"columnName", "field" ),
"footcell_field9", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field10", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field47" ),
"field", "withdrawCurr",
"columnName", "field" ),
"cell_field10", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "withdrawCurr",
"columnName", "field" ),
"footcell_field10", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field11", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field48" ),
"field", "withdrawAmt",
"columnName", "field" ),
"cell_field11", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "withdrawAmt",
"columnName", "field" ),
"footcell_field11", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field12", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field49" ),
"field", "NetAmountCurr",
"columnName", "field" ),
"cell_field12", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "NetAmountCurr",
"columnName", "field" ),
"footcell_field12", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field13", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field50" ),
"field", "NetAmount",
"columnName", "field" ),
"cell_field13", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "NetAmount",
"columnName", "field" ),
"footcell_field13", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field14", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field51" ),
"field", "Message",
"columnName", "field" ),
"cell_field14", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field14" ),
"field", "Message",
"columnName", "field" ),
"footcell_field14", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field15", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field52" ),
"field", "BankingMessage",
"columnName", "field" ),
"cell_field15", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field15" ),
"field", "BankingMessage",
"columnName", "field" ),
"footcell_field15", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field16", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field53" ),
"field", "EmailSubject",
"columnName", "field" ),
"cell_field16", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field16" ),
"field", "EmailSubject",
"columnName", "field" ),
"footcell_field16", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field17", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field54" ),
"field", "TxnReference",
"columnName", "field" ),
"cell_field17", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field17" ),
"field", "TxnReference",
"columnName", "field" ),
"footcell_field17", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field18", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field55" ),
"field", "paymentcurr",
"columnName", "field" ),
"cell_field18", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field18" ),
"field", "paymentcurr",
"columnName", "field" ),
"footcell_field18", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field19", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field56" ),
"field", "PayerEntityName",
"columnName", "field" ),
"cell_field19", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field19" ),
"field", "PayerEntityName",
"columnName", "field" ),
"footcell_field19", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field20", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field57" ),
"field", "PayerEntityCountryISO",
"columnName", "field" ),
"cell_field20", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field20" ),
"field", "PayerEntityCountryISO",
"columnName", "field" ),
"footcell_field20", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field21", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field58" ),
"field", "Provider",
"columnName", "field" ),
"cell_field21", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field21" ),
"field", "Provider",
"columnName", "field" ),
"footcell_field21", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field22", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field59" ),
"field", "AccountIdentifier",
"columnName", "field" ),
"cell_field22", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field22" ),
"field", "AccountIdentifier",
"columnName", "field" ),
"footcell_field22", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field23", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field60" ),
"field", "PayerExchangeRate",
"columnName", "field" ),
"cell_field23", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field23" ),
"field", "PayerExchangeRate",
"columnName", "field" ),
"footcell_field23", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field24", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field61" ),
"field", "PaymentAmountInWithdrawCurrency",
"columnName", "field" ),
"cell_field24", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field24" ),
"field", "PaymentAmountInWithdrawCurrency",
"columnName", "field" ),
"footcell_field24", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field25", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field62" ),
"field", "vendor",
"columnName", "field" ),
"cell_field25", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field25" ),
"field", "vendor",
"columnName", "field" ),
"footcell_field25", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field26", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field63" ),
"field", "TxnDate",
"columnName", "field" ),
"cell_field26", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field26" ),
"field", "TxnDate",
"columnName", "field" ),
"footcell_field26", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field27", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field64" ),
"field", "posted",
"columnName", "field" ),
"cell_field27", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field27" ),
"field", "posted",
"columnName", "field" ),
"footcell_field27", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field28", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field65" ),
"field", "clientid",
"columnName", "field" ),
"cell_field28", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field28" ),
"field", "clientid",
"columnName", "field" ),
"footcell_field28", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field29", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field66" ),
"field", "trans_num",
"columnName", "field" ),
"cell_field29", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field29" ),
"field", "trans_num",
"columnName", "field" ),
"footcell_field29", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field30", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field67" ),
"field", "site_ref",
"columnName", "field" ),
"cell_field30", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field30" ),
"field", "site_ref",
"columnName", "field" ),
"footcell_field30", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field31", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field68" ),
"field", "rowpointer",
"columnName", "field" ),
"cell_field31", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field31" ),
"field", "rowpointer",
"columnName", "field" ),
"footcell_field31", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field32", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field69" ),
"field", "RelatedBills",
"columnName", "field" ),
"cell_field32", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field32" ),
"field", "RelatedBills",
"columnName", "field" ),
"footcell_field32", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field33", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field70" ),
"field", "err_msg",
"columnName", "field" ),
"cell_field33", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field33" ),
"field", "err_msg",
"columnName", "field" ),
"footcell_field33", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field34", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field71" ),
"field", "json_data",
"columnName", "field" ),
"cell_field34", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field34" ),
"field", "json_data",
"columnName", "field" ),
"footcell_field34", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field35", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field72" ),
"field", "jresult",
"columnName", "field" ),
"cell_field35", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field35" ),
"field", "jresult",
"columnName", "field" ),
"footcell_field35", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field36", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field73" ),
"field", "postdate",
"columnName", "field" ),
"cell_field36", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field36" ),
"field", "postdate",
"columnName", "field" ),
"footcell_field36", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"cell_dpreview", new XVar( "model", "cell_dpreview",
"items", new XVar( 0, "details_preview" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "print_header", new XVar( "type", "print_header" ),
"print_subheader", new XVar( "type", "print_subheader" ),
"print_pages", new XVar( "type", "print_pages" ),
"master_info", new XVar( "type", "master_info",
"tables", new XVar( "dbo.tp_vendor", "true" ) ),
"simple_grid_field", new XVar( "field", "id",
"type", "grid_field" ),
"simple_grid_field37", new XVar( "type", "grid_field_label",
"field", "id" ),
"simple_grid_field1", new XVar( "field", "SequenceRefCode",
"type", "grid_field" ),
"simple_grid_field38", new XVar( "type", "grid_field_label",
"field", "SequenceRefCode" ),
"simple_grid_field2", new XVar( "field", "submissionDate",
"type", "grid_field" ),
"simple_grid_field39", new XVar( "type", "grid_field_label",
"field", "submissionDate" ),
"simple_grid_field3", new XVar( "field", "AmountSubmitted",
"type", "grid_field" ),
"simple_grid_field40", new XVar( "type", "grid_field_label",
"field", "AmountSubmitted" ),
"simple_grid_field4", new XVar( "field", "AmountSubmittedCur",
"type", "grid_field" ),
"simple_grid_field41", new XVar( "type", "grid_field_label",
"field", "AmountSubmittedCur" ),
"simple_grid_field5", new XVar( "field", "PaymentMethod",
"type", "grid_field" ),
"simple_grid_field42", new XVar( "type", "grid_field_label",
"field", "PaymentMethod" ),
"simple_grid_field6", new XVar( "field", "Status",
"type", "grid_field" ),
"simple_grid_field43", new XVar( "type", "grid_field_label",
"field", "Status" ),
"simple_grid_field7", new XVar( "field", "PayerFees",
"type", "grid_field" ),
"simple_grid_field44", new XVar( "type", "grid_field_label",
"field", "PayerFees" ),
"simple_grid_field8", new XVar( "field", "PayeeFxfees",
"type", "grid_field" ),
"simple_grid_field45", new XVar( "type", "grid_field_label",
"field", "PayeeFxfees" ),
"simple_grid_field9", new XVar( "field", "PayerFxfees",
"type", "grid_field" ),
"simple_grid_field46", new XVar( "type", "grid_field_label",
"field", "PayerFxfees" ),
"simple_grid_field10", new XVar( "field", "withdrawCurr",
"type", "grid_field" ),
"simple_grid_field47", new XVar( "type", "grid_field_label",
"field", "withdrawCurr" ),
"simple_grid_field11", new XVar( "field", "withdrawAmt",
"type", "grid_field" ),
"simple_grid_field48", new XVar( "type", "grid_field_label",
"field", "withdrawAmt" ),
"simple_grid_field12", new XVar( "field", "NetAmountCurr",
"type", "grid_field" ),
"simple_grid_field49", new XVar( "type", "grid_field_label",
"field", "NetAmountCurr" ),
"simple_grid_field13", new XVar( "field", "NetAmount",
"type", "grid_field" ),
"simple_grid_field50", new XVar( "type", "grid_field_label",
"field", "NetAmount" ),
"simple_grid_field14", new XVar( "field", "Message",
"type", "grid_field" ),
"simple_grid_field51", new XVar( "type", "grid_field_label",
"field", "Message" ),
"simple_grid_field15", new XVar( "field", "BankingMessage",
"type", "grid_field" ),
"simple_grid_field52", new XVar( "type", "grid_field_label",
"field", "BankingMessage" ),
"simple_grid_field16", new XVar( "field", "EmailSubject",
"type", "grid_field" ),
"simple_grid_field53", new XVar( "type", "grid_field_label",
"field", "EmailSubject" ),
"simple_grid_field17", new XVar( "field", "TxnReference",
"type", "grid_field" ),
"simple_grid_field54", new XVar( "type", "grid_field_label",
"field", "TxnReference" ),
"simple_grid_field18", new XVar( "field", "paymentcurr",
"type", "grid_field" ),
"simple_grid_field55", new XVar( "type", "grid_field_label",
"field", "paymentcurr" ),
"simple_grid_field19", new XVar( "field", "PayerEntityName",
"type", "grid_field" ),
"simple_grid_field56", new XVar( "type", "grid_field_label",
"field", "PayerEntityName" ),
"simple_grid_field20", new XVar( "field", "PayerEntityCountryISO",
"type", "grid_field" ),
"simple_grid_field57", new XVar( "type", "grid_field_label",
"field", "PayerEntityCountryISO" ),
"simple_grid_field21", new XVar( "field", "Provider",
"type", "grid_field" ),
"simple_grid_field58", new XVar( "type", "grid_field_label",
"field", "Provider" ),
"simple_grid_field22", new XVar( "field", "AccountIdentifier",
"type", "grid_field" ),
"simple_grid_field59", new XVar( "type", "grid_field_label",
"field", "AccountIdentifier" ),
"simple_grid_field23", new XVar( "field", "PayerExchangeRate",
"type", "grid_field" ),
"simple_grid_field60", new XVar( "type", "grid_field_label",
"field", "PayerExchangeRate" ),
"simple_grid_field24", new XVar( "field", "PaymentAmountInWithdrawCurrency",
"type", "grid_field" ),
"simple_grid_field61", new XVar( "type", "grid_field_label",
"field", "PaymentAmountInWithdrawCurrency" ),
"simple_grid_field25", new XVar( "field", "vendor",
"type", "grid_field" ),
"simple_grid_field62", new XVar( "type", "grid_field_label",
"field", "vendor" ),
"simple_grid_field26", new XVar( "field", "TxnDate",
"type", "grid_field" ),
"simple_grid_field63", new XVar( "type", "grid_field_label",
"field", "TxnDate" ),
"simple_grid_field27", new XVar( "field", "posted",
"type", "grid_field" ),
"simple_grid_field64", new XVar( "type", "grid_field_label",
"field", "posted" ),
"simple_grid_field28", new XVar( "field", "clientid",
"type", "grid_field" ),
"simple_grid_field65", new XVar( "type", "grid_field_label",
"field", "clientid" ),
"simple_grid_field29", new XVar( "field", "trans_num",
"type", "grid_field" ),
"simple_grid_field66", new XVar( "type", "grid_field_label",
"field", "trans_num" ),
"simple_grid_field30", new XVar( "field", "site_ref",
"type", "grid_field" ),
"simple_grid_field67", new XVar( "type", "grid_field_label",
"field", "site_ref" ),
"simple_grid_field31", new XVar( "field", "rowpointer",
"type", "grid_field" ),
"simple_grid_field68", new XVar( "type", "grid_field_label",
"field", "rowpointer" ),
"simple_grid_field32", new XVar( "field", "RelatedBills",
"type", "grid_field" ),
"simple_grid_field69", new XVar( "type", "grid_field_label",
"field", "RelatedBills" ),
"simple_grid_field33", new XVar( "field", "err_msg",
"type", "grid_field" ),
"simple_grid_field70", new XVar( "type", "grid_field_label",
"field", "err_msg" ),
"simple_grid_field34", new XVar( "field", "json_data",
"type", "grid_field" ),
"simple_grid_field71", new XVar( "type", "grid_field_label",
"field", "json_data" ),
"simple_grid_field35", new XVar( "field", "jresult",
"type", "grid_field" ),
"simple_grid_field72", new XVar( "type", "grid_field_label",
"field", "jresult" ),
"simple_grid_field36", new XVar( "field", "postdate",
"type", "grid_field" ),
"simple_grid_field73", new XVar( "type", "grid_field_label",
"field", "postdate" ),
"details_preview", new XVar( "type", "details_preview",
"table", "dbo.tp_payments_lines_mst",
"items", XVar.Array(),
"popup", false ),
"inline_add", new XVar( "type", "inline_add",
"detailsOnly", true ),
"grid_inline_cancel", new XVar( "type", "grid_inline_cancel" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}