
		// dbo.tp_vendor_mst
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_tp_vendor_mst_search
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "site_ref",
1, "clientid",
2, "posted",
3, "posteddate",
4, "Alias",
5, "CompanyName",
6, "Email",
7, "FirstName",
8, "MiddleName",
9, "LastName",
10, "PaymentMethod",
11, "Street1",
12, "Street2",
13, "City",
14, "State",
15, "Zip",
16, "Country",
17, "Phone",
18, "PaymentCurrency",
19, "Payable",
20, "Status",
21, "StatusReason",
22, "StatusUpdateDate",
23, "PreferredPayerEntity",
24, "ActualPayerEntity",
25, "Idap",
26, "CountryName",
27, "ErpCurrency",
28, "EntityType",
29, "TaxFormStatus",
30, "PortalUser",
31, "WithholdingRate",
32, "TaxFormEntityType",
33, "TaxFormEntityName",
34, "TaxFormType",
35, "TaxFormSubmittedBy",
36, "TaxFormSubmittedDate",
37, "PaymentTermId",
38, "ApAccountExternalId",
39, "ExternalID",
40, "vendor_seq",
41, "is_1099",
42, "vend_num" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "site_ref", new XVar( 0, "integrated_search_field" ),
"clientid", new XVar( 0, "integrated_search_field1" ),
"posted", new XVar( 0, "integrated_search_field2" ),
"posteddate", new XVar( 0, "integrated_search_field3" ),
"Alias", new XVar( 0, "integrated_search_field4" ),
"CompanyName", new XVar( 0, "integrated_search_field5" ),
"Email", new XVar( 0, "integrated_search_field6" ),
"FirstName", new XVar( 0, "integrated_search_field7" ),
"MiddleName", new XVar( 0, "integrated_search_field8" ),
"LastName", new XVar( 0, "integrated_search_field9" ),
"PaymentMethod", new XVar( 0, "integrated_search_field10" ),
"Street1", new XVar( 0, "integrated_search_field11" ),
"Street2", new XVar( 0, "integrated_search_field12" ),
"City", new XVar( 0, "integrated_search_field13" ),
"State", new XVar( 0, "integrated_search_field14" ),
"Zip", new XVar( 0, "integrated_search_field15" ),
"Country", new XVar( 0, "integrated_search_field16" ),
"Phone", new XVar( 0, "integrated_search_field17" ),
"PaymentCurrency", new XVar( 0, "integrated_search_field18" ),
"Payable", new XVar( 0, "integrated_search_field19" ),
"Status", new XVar( 0, "integrated_search_field20" ),
"StatusReason", new XVar( 0, "integrated_search_field21" ),
"StatusUpdateDate", new XVar( 0, "integrated_search_field22" ),
"PreferredPayerEntity", new XVar( 0, "integrated_search_field23" ),
"ActualPayerEntity", new XVar( 0, "integrated_search_field24" ),
"Idap", new XVar( 0, "integrated_search_field25" ),
"CountryName", new XVar( 0, "integrated_search_field26" ),
"ErpCurrency", new XVar( 0, "integrated_search_field27" ),
"EntityType", new XVar( 0, "integrated_search_field28" ),
"TaxFormStatus", new XVar( 0, "integrated_search_field29" ),
"PortalUser", new XVar( 0, "integrated_search_field30" ),
"WithholdingRate", new XVar( 0, "integrated_search_field31" ),
"TaxFormEntityType", new XVar( 0, "integrated_search_field32" ),
"TaxFormEntityName", new XVar( 0, "integrated_search_field33" ),
"TaxFormType", new XVar( 0, "integrated_search_field34" ),
"TaxFormSubmittedBy", new XVar( 0, "integrated_search_field35" ),
"TaxFormSubmittedDate", new XVar( 0, "integrated_search_field36" ),
"PaymentTermId", new XVar( 0, "integrated_search_field37" ),
"ApAccountExternalId", new XVar( 0, "integrated_search_field38" ),
"ExternalID", new XVar( 0, "integrated_search_field39" ),
"vendor_seq", new XVar( 0, "integrated_search_field40" ),
"is_1099", new XVar( 0, "integrated_search_field41" ),
"vend_num", new XVar( 0, "integrated_search_field42" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "search_search",
1, "search_reset",
2, "search_back_list",
3, "search_cancel" ),
"top", new XVar( 0, "search_header" ),
"grid", new XVar( 0, "integrated_search_field",
1, "integrated_search_field1",
2, "integrated_search_field2",
3, "integrated_search_field3",
4, "integrated_search_field4",
5, "integrated_search_field5",
6, "integrated_search_field6",
7, "integrated_search_field7",
8, "integrated_search_field8",
9, "integrated_search_field9",
10, "integrated_search_field10",
11, "integrated_search_field11",
12, "integrated_search_field12",
13, "integrated_search_field13",
14, "integrated_search_field14",
15, "integrated_search_field15",
16, "integrated_search_field16",
17, "integrated_search_field17",
18, "integrated_search_field18",
19, "integrated_search_field19",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38",
39, "integrated_search_field39",
40, "integrated_search_field40",
41, "integrated_search_field41",
42, "integrated_search_field42" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array() ),
"itemForms", new XVar( "search_search", "below-grid",
"search_reset", "below-grid",
"search_back_list", "below-grid",
"search_cancel", "below-grid",
"search_header", "top",
"integrated_search_field", "grid",
"integrated_search_field1", "grid",
"integrated_search_field2", "grid",
"integrated_search_field3", "grid",
"integrated_search_field4", "grid",
"integrated_search_field5", "grid",
"integrated_search_field6", "grid",
"integrated_search_field7", "grid",
"integrated_search_field8", "grid",
"integrated_search_field9", "grid",
"integrated_search_field10", "grid",
"integrated_search_field11", "grid",
"integrated_search_field12", "grid",
"integrated_search_field13", "grid",
"integrated_search_field14", "grid",
"integrated_search_field15", "grid",
"integrated_search_field16", "grid",
"integrated_search_field17", "grid",
"integrated_search_field18", "grid",
"integrated_search_field19", "grid",
"integrated_search_field20", "grid",
"integrated_search_field21", "grid",
"integrated_search_field22", "grid",
"integrated_search_field23", "grid",
"integrated_search_field24", "grid",
"integrated_search_field25", "grid",
"integrated_search_field26", "grid",
"integrated_search_field27", "grid",
"integrated_search_field28", "grid",
"integrated_search_field29", "grid",
"integrated_search_field30", "grid",
"integrated_search_field31", "grid",
"integrated_search_field32", "grid",
"integrated_search_field33", "grid",
"integrated_search_field34", "grid",
"integrated_search_field35", "grid",
"integrated_search_field36", "grid",
"integrated_search_field37", "grid",
"integrated_search_field38", "grid",
"integrated_search_field39", "grid",
"integrated_search_field40", "grid",
"integrated_search_field41", "grid",
"integrated_search_field42", "grid" ),
"itemLocations", new XVar( "integrated_search_field", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field1", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field2", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field3", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field4", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field5", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field6", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field7", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field8", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field9", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field10", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field11", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field12", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field13", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field14", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field15", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field16", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field17", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field18", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field19", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field20", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field21", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field22", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field23", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field24", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field25", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field26", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field27", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field28", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field29", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field30", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field31", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field32", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field33", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field34", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field35", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field36", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field37", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field38", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field39", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field40", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field41", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field42", new XVar( "location", "grid",
"cellId", "c3" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "search_header", new XVar( 0, "search_header" ),
"search_reset", new XVar( 0, "search_reset" ),
"search_back_list", new XVar( 0, "search_back_list" ),
"search_search", new XVar( 0, "search_search" ),
"search_cancel", new XVar( 0, "search_cancel" ),
"integrated_search_field", new XVar( 0, "integrated_search_field",
1, "integrated_search_field1",
2, "integrated_search_field2",
3, "integrated_search_field3",
4, "integrated_search_field4",
5, "integrated_search_field5",
6, "integrated_search_field6",
7, "integrated_search_field7",
8, "integrated_search_field8",
9, "integrated_search_field9",
10, "integrated_search_field10",
11, "integrated_search_field11",
12, "integrated_search_field12",
13, "integrated_search_field13",
14, "integrated_search_field14",
15, "integrated_search_field15",
16, "integrated_search_field16",
17, "integrated_search_field17",
18, "integrated_search_field18",
19, "integrated_search_field19",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38",
39, "integrated_search_field39",
40, "integrated_search_field40",
41, "integrated_search_field41",
42, "integrated_search_field42" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_search_field",
1, "integrated_search_field1",
2, "integrated_search_field2",
3, "integrated_search_field3",
4, "integrated_search_field4",
5, "integrated_search_field5",
6, "integrated_search_field6",
7, "integrated_search_field7",
8, "integrated_search_field8",
9, "integrated_search_field9",
10, "integrated_search_field10",
11, "integrated_search_field11",
12, "integrated_search_field12",
13, "integrated_search_field13",
14, "integrated_search_field14",
15, "integrated_search_field15",
16, "integrated_search_field16",
17, "integrated_search_field17",
18, "integrated_search_field18",
19, "integrated_search_field19",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38",
39, "integrated_search_field39",
40, "integrated_search_field40",
41, "integrated_search_field41",
42, "integrated_search_field42" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "search",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "search",
"type", "search",
"layoutId", "nomenu",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "search-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1",
"colspan", 2 ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "search-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "search_search",
1, "search_reset",
2, "search_back_list",
3, "search_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "search-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "search_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-search",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ) ),
"section", "" ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_search_field",
1, "integrated_search_field1",
2, "integrated_search_field2",
3, "integrated_search_field3",
4, "integrated_search_field4",
5, "integrated_search_field5",
6, "integrated_search_field6",
7, "integrated_search_field7",
8, "integrated_search_field8",
9, "integrated_search_field9",
10, "integrated_search_field10",
11, "integrated_search_field11",
12, "integrated_search_field12",
13, "integrated_search_field13",
14, "integrated_search_field14",
15, "integrated_search_field15",
16, "integrated_search_field16",
17, "integrated_search_field17",
18, "integrated_search_field18",
19, "integrated_search_field19",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38",
39, "integrated_search_field39",
40, "integrated_search_field40",
41, "integrated_search_field41",
42, "integrated_search_field42" ) ) ),
"deferredItems", XVar.Array(),
"separateLabels", false ) ),
"items", new XVar( "search_header", new XVar( "type", "search_header" ),
"search_reset", new XVar( "type", "search_reset" ),
"search_back_list", new XVar( "type", "search_back_list" ),
"search_search", new XVar( "type", "search_search" ),
"search_cancel", new XVar( "type", "search_cancel" ),
"integrated_search_field", new XVar( "field", "site_ref",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field1", new XVar( "field", "clientid",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field2", new XVar( "field", "posted",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field3", new XVar( "field", "posteddate",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field4", new XVar( "field", "Alias",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field5", new XVar( "field", "CompanyName",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field6", new XVar( "field", "Email",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field7", new XVar( "field", "FirstName",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field8", new XVar( "field", "MiddleName",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field9", new XVar( "field", "LastName",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field10", new XVar( "field", "PaymentMethod",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field11", new XVar( "field", "Street1",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field12", new XVar( "field", "Street2",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field13", new XVar( "field", "City",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field14", new XVar( "field", "State",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field15", new XVar( "field", "Zip",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field16", new XVar( "field", "Country",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field17", new XVar( "field", "Phone",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field18", new XVar( "field", "PaymentCurrency",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field19", new XVar( "field", "Payable",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field20", new XVar( "field", "Status",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field21", new XVar( "field", "StatusReason",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field22", new XVar( "field", "StatusUpdateDate",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field23", new XVar( "field", "PreferredPayerEntity",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field24", new XVar( "field", "ActualPayerEntity",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field25", new XVar( "field", "Idap",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field26", new XVar( "field", "CountryName",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field27", new XVar( "field", "ErpCurrency",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field28", new XVar( "field", "EntityType",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field29", new XVar( "field", "TaxFormStatus",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field30", new XVar( "field", "PortalUser",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field31", new XVar( "field", "WithholdingRate",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field32", new XVar( "field", "TaxFormEntityType",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field33", new XVar( "field", "TaxFormEntityName",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field34", new XVar( "field", "TaxFormType",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field35", new XVar( "field", "TaxFormSubmittedBy",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field36", new XVar( "field", "TaxFormSubmittedDate",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field37", new XVar( "field", "PaymentTermId",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field38", new XVar( "field", "ApAccountExternalId",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field39", new XVar( "field", "ExternalID",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field40", new XVar( "field", "vendor_seq",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field41", new XVar( "field", "is_1099",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field42", new XVar( "field", "vend_num",
"type", "integrated_search_field",
"orientation", 0,
"required", false ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}