
		// dbo.tp_vendor
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_tp_vendor_export
			{
				static public XVar options()
				{
					return new XVar( "totals", new XVar( "clientid", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"tp_posted", new XVar( "totalsType", "" ),
"vend_num", new XVar( "totalsType", "" ),
"RowPointer", new XVar( "totalsType", "" ),
"contact", new XVar( "totalsType", "" ),
"phone", new XVar( "totalsType", "" ),
"vend_type", new XVar( "totalsType", "" ),
"terms_code", new XVar( "totalsType", "" ),
"ship_code", new XVar( "totalsType", "" ),
"stat", new XVar( "totalsType", "" ),
"curr_code", new XVar( "totalsType", "" ),
"bank_code", new XVar( "totalsType", "" ),
"pay_type", new XVar( "totalsType", "" ),
"delterm", new XVar( "totalsType", "" ),
"tax_code1", new XVar( "totalsType", "" ),
"tax_code2", new XVar( "totalsType", "" ),
"cust_num", new XVar( "totalsType", "" ),
"vend_bank", new XVar( "totalsType", "" ),
"name", new XVar( "totalsType", "" ),
"city", new XVar( "totalsType", "" ),
"state", new XVar( "totalsType", "" ),
"zip", new XVar( "totalsType", "" ),
"county", new XVar( "totalsType", "" ),
"country", new XVar( "totalsType", "" ),
"fax_num", new XVar( "totalsType", "" ),
"telex_num", new XVar( "totalsType", "" ),
"addr1", new XVar( "totalsType", "" ),
"addr2", new XVar( "totalsType", "" ),
"addr3", new XVar( "totalsType", "" ),
"addr4", new XVar( "totalsType", "" ),
"pay_hold", new XVar( "totalsType", "" ),
"internet_url", new XVar( "totalsType", "" ),
"internal_email_addr", new XVar( "totalsType", "" ),
"external_email_addr", new XVar( "totalsType", "" ),
"long_name", new XVar( "totalsType", "" ),
"vend_remit", new XVar( "totalsType", "" ),
"PendInv", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "clientid",
1, "site_ref",
2, "tp_posted",
3, "vend_num",
4, "RowPointer",
5, "contact",
6, "phone",
7, "vend_type",
8, "terms_code",
9, "ship_code",
10, "stat",
11, "curr_code",
12, "pay_type",
13, "delterm",
14, "tax_code1",
15, "tax_code2",
16, "cust_num",
17, "vend_bank",
18, "name",
19, "city",
20, "state",
21, "zip",
22, "county",
23, "country",
24, "fax_num",
25, "telex_num",
26, "addr1",
27, "addr2",
28, "addr3",
29, "addr4",
30, "internet_url",
31, "internal_email_addr",
32, "external_email_addr",
33, "long_name",
34, "vend_remit",
35, "PendInv" ),
"exportFields", new XVar( 0, "clientid",
1, "site_ref",
2, "tp_posted",
3, "vend_num",
4, "RowPointer",
5, "contact",
6, "phone",
7, "vend_type",
8, "terms_code",
9, "ship_code",
10, "stat",
11, "curr_code",
12, "pay_type",
13, "delterm",
14, "tax_code1",
15, "tax_code2",
16, "cust_num",
17, "vend_bank",
18, "name",
19, "city",
20, "state",
21, "zip",
22, "county",
23, "country",
24, "fax_num",
25, "telex_num",
26, "addr1",
27, "addr2",
28, "addr3",
29, "addr4",
30, "internet_url",
31, "internal_email_addr",
32, "external_email_addr",
33, "long_name",
34, "vend_remit",
35, "PendInv" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "clientid", new XVar( 0, "export_field" ),
"site_ref", new XVar( 0, "export_field1" ),
"tp_posted", new XVar( 0, "export_field2" ),
"vend_num", new XVar( 0, "export_field3" ),
"RowPointer", new XVar( 0, "export_field4" ),
"contact", new XVar( 0, "export_field5" ),
"phone", new XVar( 0, "export_field6" ),
"vend_type", new XVar( 0, "export_field7" ),
"terms_code", new XVar( 0, "export_field8" ),
"ship_code", new XVar( 0, "export_field9" ),
"stat", new XVar( 0, "export_field10" ),
"curr_code", new XVar( 0, "export_field11" ),
"pay_type", new XVar( 0, "export_field13" ),
"delterm", new XVar( 0, "export_field14" ),
"tax_code1", new XVar( 0, "export_field15" ),
"tax_code2", new XVar( 0, "export_field16" ),
"cust_num", new XVar( 0, "export_field17" ),
"vend_bank", new XVar( 0, "export_field18" ),
"name", new XVar( 0, "export_field19" ),
"city", new XVar( 0, "export_field20" ),
"state", new XVar( 0, "export_field21" ),
"zip", new XVar( 0, "export_field22" ),
"county", new XVar( 0, "export_field23" ),
"country", new XVar( 0, "export_field24" ),
"fax_num", new XVar( 0, "export_field25" ),
"telex_num", new XVar( 0, "export_field26" ),
"addr1", new XVar( 0, "export_field27" ),
"addr2", new XVar( 0, "export_field28" ),
"addr3", new XVar( 0, "export_field29" ),
"addr4", new XVar( 0, "export_field30" ),
"internet_url", new XVar( 0, "export_field32" ),
"internal_email_addr", new XVar( 0, "export_field33" ),
"external_email_addr", new XVar( 0, "export_field34" ),
"long_name", new XVar( 0, "export_field35" ),
"vend_remit", new XVar( 0, "export_field36" ),
"PendInv", new XVar( 0, "export_field12" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "export_header" ),
"grid", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field3",
4, "export_field4",
5, "export_field5",
6, "export_field6",
7, "export_field7",
8, "export_field8",
9, "export_field9",
10, "export_field10",
11, "export_field11",
12, "export_field13",
13, "export_field14",
14, "export_field15",
15, "export_field16",
16, "export_field17",
17, "export_field18",
18, "export_field19",
19, "export_field20",
20, "export_field21",
21, "export_field22",
22, "export_field23",
23, "export_field24",
24, "export_field25",
25, "export_field26",
26, "export_field27",
27, "export_field28",
28, "export_field29",
29, "export_field30",
30, "export_field32",
31, "export_field33",
32, "export_field34",
33, "export_field35",
34, "export_field36",
35, "export_field12" ),
"footer", new XVar( 0, "export_export",
1, "export_cancel" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "export_header", "top",
"export_field", "grid",
"export_field1", "grid",
"export_field2", "grid",
"export_field3", "grid",
"export_field4", "grid",
"export_field5", "grid",
"export_field6", "grid",
"export_field7", "grid",
"export_field8", "grid",
"export_field9", "grid",
"export_field10", "grid",
"export_field11", "grid",
"export_field13", "grid",
"export_field14", "grid",
"export_field15", "grid",
"export_field16", "grid",
"export_field17", "grid",
"export_field18", "grid",
"export_field19", "grid",
"export_field20", "grid",
"export_field21", "grid",
"export_field22", "grid",
"export_field23", "grid",
"export_field24", "grid",
"export_field25", "grid",
"export_field26", "grid",
"export_field27", "grid",
"export_field28", "grid",
"export_field29", "grid",
"export_field30", "grid",
"export_field32", "grid",
"export_field33", "grid",
"export_field34", "grid",
"export_field35", "grid",
"export_field36", "grid",
"export_field12", "grid",
"export_export", "footer",
"export_cancel", "footer" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "export_header", new XVar( 0, "export_header" ),
"export_export", new XVar( 0, "export_export" ),
"export_cancel", new XVar( 0, "export_cancel" ),
"export_field", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field3",
4, "export_field4",
5, "export_field5",
6, "export_field6",
7, "export_field7",
8, "export_field8",
9, "export_field9",
10, "export_field10",
11, "export_field11",
12, "export_field13",
13, "export_field14",
14, "export_field15",
15, "export_field16",
16, "export_field17",
17, "export_field18",
18, "export_field19",
19, "export_field20",
20, "export_field21",
21, "export_field22",
22, "export_field23",
23, "export_field24",
24, "export_field25",
25, "export_field26",
26, "export_field27",
27, "export_field28",
28, "export_field29",
29, "export_field30",
30, "export_field32",
31, "export_field33",
32, "export_field34",
33, "export_field35",
34, "export_field36",
35, "export_field12" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"export", new XVar( "format", 2,
"selectFields", false,
"delimiter", ",",
"selectDelimiter", false,
"exportFileTypes", new XVar( "excel", true,
"word", true,
"csv", true,
"xml", false ) ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "export",
"type", "export",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "export-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "export-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field3",
4, "export_field4",
5, "export_field5",
6, "export_field6",
7, "export_field7",
8, "export_field8",
9, "export_field9",
10, "export_field10",
11, "export_field11",
12, "export_field13",
13, "export_field14",
14, "export_field15",
15, "export_field16",
16, "export_field17",
17, "export_field18",
18, "export_field19",
19, "export_field20",
20, "export_field21",
21, "export_field22",
22, "export_field23",
23, "export_field24",
24, "export_field25",
25, "export_field26",
26, "export_field27",
27, "export_field28",
28, "export_field29",
29, "export_field30",
30, "export_field32",
31, "export_field33",
32, "export_field34",
33, "export_field35",
34, "export_field36",
35, "export_field12" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"footer", new XVar( "modelId", "export-footer",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "export_export",
1, "export_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "export_header", new XVar( "type", "export_header" ),
"export_export", new XVar( "type", "export_export" ),
"export_cancel", new XVar( "type", "export_cancel" ),
"export_field", new XVar( "field", "clientid",
"type", "export_field" ),
"export_field1", new XVar( "field", "site_ref",
"type", "export_field" ),
"export_field2", new XVar( "field", "tp_posted",
"type", "export_field" ),
"export_field3", new XVar( "field", "vend_num",
"type", "export_field" ),
"export_field4", new XVar( "field", "RowPointer",
"type", "export_field" ),
"export_field5", new XVar( "field", "contact",
"type", "export_field" ),
"export_field6", new XVar( "field", "phone",
"type", "export_field" ),
"export_field7", new XVar( "field", "vend_type",
"type", "export_field" ),
"export_field8", new XVar( "field", "terms_code",
"type", "export_field" ),
"export_field9", new XVar( "field", "ship_code",
"type", "export_field" ),
"export_field10", new XVar( "field", "stat",
"type", "export_field" ),
"export_field11", new XVar( "field", "curr_code",
"type", "export_field" ),
"export_field13", new XVar( "field", "pay_type",
"type", "export_field" ),
"export_field14", new XVar( "field", "delterm",
"type", "export_field" ),
"export_field15", new XVar( "field", "tax_code1",
"type", "export_field" ),
"export_field16", new XVar( "field", "tax_code2",
"type", "export_field" ),
"export_field17", new XVar( "field", "cust_num",
"type", "export_field" ),
"export_field18", new XVar( "field", "vend_bank",
"type", "export_field" ),
"export_field19", new XVar( "field", "name",
"type", "export_field" ),
"export_field20", new XVar( "field", "city",
"type", "export_field" ),
"export_field21", new XVar( "field", "state",
"type", "export_field" ),
"export_field22", new XVar( "field", "zip",
"type", "export_field" ),
"export_field23", new XVar( "field", "county",
"type", "export_field" ),
"export_field24", new XVar( "field", "country",
"type", "export_field" ),
"export_field25", new XVar( "field", "fax_num",
"type", "export_field" ),
"export_field26", new XVar( "field", "telex_num",
"type", "export_field" ),
"export_field27", new XVar( "field", "addr1",
"type", "export_field" ),
"export_field28", new XVar( "field", "addr2",
"type", "export_field" ),
"export_field29", new XVar( "field", "addr3",
"type", "export_field" ),
"export_field30", new XVar( "field", "addr4",
"type", "export_field" ),
"export_field32", new XVar( "field", "internet_url",
"type", "export_field" ),
"export_field33", new XVar( "field", "internal_email_addr",
"type", "export_field" ),
"export_field34", new XVar( "field", "external_email_addr",
"type", "export_field" ),
"export_field35", new XVar( "field", "long_name",
"type", "export_field" ),
"export_field36", new XVar( "field", "vend_remit",
"type", "export_field" ),
"export_field12", new XVar( "field", "PendInv",
"type", "export_field" ) ),
"dbProps", new XVar(  ),
"version", 14,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1,
"exportFormat", 2,
"exportDelimiter", ",",
"exportSelectDelimiter", false,
"exportSelectFields", false );
				}
			}
		}