
		// dbo.tp_vendor_not_match_tosyteline
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_tp_vendor_not_match_tosyteline_list
			{
				static public XVar options()
				{
					return new XVar( "list", new XVar( "inlineAdd", false,
"detailsAdd", false,
"inlineEdit", false,
"spreadsheetMode", false,
"reorderRows", false,
"addToBottom", false,
"delete", false,
"updateSelected", false,
"addInPopup", null,
"editInPopup", null,
"viewInPopup", null,
"clickSort", true,
"sortDropdown", false,
"showHideFields", false,
"reorderFields", false,
"fieldFilter", false,
"hideNumberOfRecords", false ),
"listSearch", new XVar( "alwaysOnPanelFields", XVar.Array(),
"searchPanel", true,
"fixedSearchPanel", false,
"simpleSearchOptions", false,
"searchSaving", false ),
"totals", new XVar( "clientid", new XVar( "totalsType", "" ),
"site_ref", new XVar( "totalsType", "" ),
"vend_num", new XVar( "totalsType", "" ),
"sl_name", new XVar( "totalsType", "" ),
"tp_name", new XVar( "totalsType", "" ),
"tp_street", new XVar( "totalsType", "" ),
"sl_street", new XVar( "totalsType", "" ),
"tp_city", new XVar( "totalsType", "" ),
"sl_city", new XVar( "totalsType", "" ),
"tp_state", new XVar( "totalsType", "" ),
"sl_state", new XVar( "totalsType", "" ),
"tp_zip", new XVar( "totalsType", "" ),
"sl_zip", new XVar( "totalsType", "" ),
"tp_country", new XVar( "totalsType", "" ),
"sl_country", new XVar( "totalsType", "" ),
"vendor_remit", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "clientid",
1, "site_ref",
2, "vend_num",
3, "sl_name",
4, "tp_name",
5, "tp_street",
6, "sl_street",
7, "tp_city",
8, "sl_city",
9, "tp_state",
10, "sl_state",
11, "tp_zip",
12, "sl_zip",
13, "tp_country",
14, "sl_country",
15, "vendor_remit" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", new XVar( 0, "clientid",
1, "vendor_remit",
2, "vend_num",
3, "tp_zip",
4, "tp_street",
5, "tp_state",
6, "tp_name",
7, "tp_country",
8, "tp_city",
9, "sl_zip",
10, "sl_street",
11, "sl_state",
12, "sl_name",
13, "sl_country",
14, "sl_city",
15, "site_ref" ),
"filterFields", XVar.Array(),
"inlineAddFields", XVar.Array(),
"inlineEditFields", XVar.Array(),
"fieldItems", new XVar( "clientid", new XVar( 0, "simple_grid_field",
1, "simple_grid_field16" ),
"site_ref", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field17" ),
"vend_num", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field18" ),
"sl_name", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field19" ),
"tp_name", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field20" ),
"tp_street", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field21" ),
"sl_street", new XVar( 0, "simple_grid_field6",
1, "simple_grid_field22" ),
"tp_city", new XVar( 0, "simple_grid_field7",
1, "simple_grid_field23" ),
"sl_city", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field24" ),
"tp_state", new XVar( 0, "simple_grid_field9",
1, "simple_grid_field25" ),
"sl_state", new XVar( 0, "simple_grid_field10",
1, "simple_grid_field26" ),
"tp_zip", new XVar( 0, "simple_grid_field11",
1, "simple_grid_field27" ),
"sl_zip", new XVar( 0, "simple_grid_field12",
1, "simple_grid_field28" ),
"tp_country", new XVar( 0, "simple_grid_field13",
1, "simple_grid_field29" ),
"sl_country", new XVar( 0, "simple_grid_field14",
1, "simple_grid_field30" ),
"vendor_remit", new XVar( 0, "simple_grid_field15",
1, "simple_grid_field31" ) ),
"hideEmptyFields", XVar.Array(),
"fieldFilterFields", XVar.Array() ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", true ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "details_found",
1, "page_size",
2, "print_panel" ),
"below-grid", new XVar( 0, "pagination" ),
"left", new XVar( 0, "logo",
1, "expand_button",
2, "menu",
3, "search_panel" ),
"supertop", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb",
3, "simple_search",
4, "list_options",
5, "loginform_login",
6, "username_button" ),
"grid", new XVar( 0, "simple_grid_field16",
1, "simple_grid_field",
2, "simple_grid_field17",
3, "simple_grid_field1",
4, "simple_grid_field18",
5, "simple_grid_field2",
6, "simple_grid_field19",
7, "simple_grid_field3",
8, "simple_grid_field20",
9, "simple_grid_field4",
10, "simple_grid_field21",
11, "simple_grid_field5",
12, "simple_grid_field22",
13, "simple_grid_field6",
14, "simple_grid_field23",
15, "simple_grid_field7",
16, "simple_grid_field24",
17, "simple_grid_field8",
18, "simple_grid_field25",
19, "simple_grid_field9",
20, "simple_grid_field26",
21, "simple_grid_field10",
22, "simple_grid_field27",
23, "simple_grid_field11",
24, "simple_grid_field28",
25, "simple_grid_field12",
26, "simple_grid_field29",
27, "simple_grid_field13",
28, "simple_grid_field30",
29, "simple_grid_field14",
30, "simple_grid_field31",
31, "simple_grid_field15",
32, "grid_checkbox_head",
33, "grid_checkbox",
34, "custom_button" ),
"top", XVar.Array() ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "details_found",
1, "recsPerPage",
2, "print_friendly" ),
"below-grid", new XVar( 0, "pagination" ),
"top", XVar.Array() ),
"itemForms", new XVar( "details_found", "above-grid",
"page_size", "above-grid",
"print_panel", "above-grid",
"pagination", "below-grid",
"logo", "left",
"expand_button", "left",
"menu", "left",
"search_panel", "left",
"expand_menu_button", "supertop",
"collapse_button", "supertop",
"breadcrumb", "supertop",
"simple_search", "supertop",
"list_options", "supertop",
"loginform_login", "supertop",
"username_button", "supertop",
"simple_grid_field16", "grid",
"simple_grid_field", "grid",
"simple_grid_field17", "grid",
"simple_grid_field1", "grid",
"simple_grid_field18", "grid",
"simple_grid_field2", "grid",
"simple_grid_field19", "grid",
"simple_grid_field3", "grid",
"simple_grid_field20", "grid",
"simple_grid_field4", "grid",
"simple_grid_field21", "grid",
"simple_grid_field5", "grid",
"simple_grid_field22", "grid",
"simple_grid_field6", "grid",
"simple_grid_field23", "grid",
"simple_grid_field7", "grid",
"simple_grid_field24", "grid",
"simple_grid_field8", "grid",
"simple_grid_field25", "grid",
"simple_grid_field9", "grid",
"simple_grid_field26", "grid",
"simple_grid_field10", "grid",
"simple_grid_field27", "grid",
"simple_grid_field11", "grid",
"simple_grid_field28", "grid",
"simple_grid_field12", "grid",
"simple_grid_field29", "grid",
"simple_grid_field13", "grid",
"simple_grid_field30", "grid",
"simple_grid_field14", "grid",
"simple_grid_field31", "grid",
"simple_grid_field15", "grid",
"grid_checkbox_head", "grid",
"grid_checkbox", "grid",
"custom_button", "grid" ),
"itemLocations", new XVar( "simple_grid_field16", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field17", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field18", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field19", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field20", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field21", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field22", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field23", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"simple_grid_field24", new XVar( "location", "grid",
"cellId", "headcell_field8" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "cell_field8" ),
"simple_grid_field25", new XVar( "location", "grid",
"cellId", "headcell_field9" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "cell_field9" ),
"simple_grid_field26", new XVar( "location", "grid",
"cellId", "headcell_field10" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "cell_field10" ),
"simple_grid_field27", new XVar( "location", "grid",
"cellId", "headcell_field11" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "cell_field11" ),
"simple_grid_field28", new XVar( "location", "grid",
"cellId", "headcell_field12" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "cell_field12" ),
"simple_grid_field29", new XVar( "location", "grid",
"cellId", "headcell_field13" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "cell_field13" ),
"simple_grid_field30", new XVar( "location", "grid",
"cellId", "headcell_field14" ),
"simple_grid_field14", new XVar( "location", "grid",
"cellId", "cell_field14" ),
"simple_grid_field31", new XVar( "location", "grid",
"cellId", "headcell_field15" ),
"simple_grid_field15", new XVar( "location", "grid",
"cellId", "cell_field15" ),
"grid_checkbox_head", new XVar( "location", "grid",
"cellId", "headcell_checkbox" ),
"grid_checkbox", new XVar( "location", "grid",
"cellId", "cell_checkbox" ),
"custom_button", new XVar( "location", "grid",
"cellId", "headcell_checkbox2" ) ),
"itemVisiblity", new XVar( "breadcrumb", 5,
"expand_menu_button", 2,
"print_panel", 5,
"expand_button", 5 ) ),
"itemsByType", new XVar( "page_size", new XVar( 0, "page_size" ),
"breadcrumb", new XVar( 0, "breadcrumb" ),
"logo", new XVar( 0, "logo" ),
"menu", new XVar( 0, "menu" ),
"simple_search", new XVar( 0, "simple_search" ),
"pagination", new XVar( 0, "pagination" ),
"grid_checkbox", new XVar( 0, "grid_checkbox" ),
"grid_checkbox_head", new XVar( 0, "grid_checkbox_head" ),
"details_found", new XVar( 0, "details_found" ),
"search_panel", new XVar( 0, "search_panel" ),
"list_options", new XVar( 0, "list_options" ),
"show_search_panel", new XVar( 0, "show_search_panel" ),
"hide_search_panel", new XVar( 0, "hide_search_panel" ),
"search_panel_field", new XVar( 0, "search_panel_field",
1, "search_panel_field1",
2, "search_panel_field2",
3, "search_panel_field3",
4, "search_panel_field4",
5, "search_panel_field5",
6, "search_panel_field6",
7, "search_panel_field7",
8, "search_panel_field8",
9, "search_panel_field9",
10, "search_panel_field10",
11, "search_panel_field11",
12, "search_panel_field12",
13, "search_panel_field13",
14, "search_panel_field14",
15, "search_panel_field15" ),
"username_button", new XVar( 0, "username_button" ),
"loginform_login", new XVar( 0, "loginform_login" ),
"userinfo_link", new XVar( 0, "userinfo_link" ),
"logout_link", new XVar( 0, "logout_link" ),
"adminarea_link", new XVar( 0, "adminarea_link" ),
"changepassword_link", new XVar( 0, "changepassword_link" ),
"expand_menu_button", new XVar( 0, "expand_menu_button" ),
"collapse_button", new XVar( 0, "collapse_button" ),
"print_panel", new XVar( 0, "print_panel" ),
"print_scope", new XVar( 0, "print_scope" ),
"print_button", new XVar( 0, "print_button" ),
"print_records", new XVar( 0, "print_records" ),
"export", new XVar( 0, "export" ),
"-", new XVar( 0, "-",
1, "-1",
2, "-2" ),
"import", new XVar( 0, "import" ),
"advsearch_link", new XVar( 0, "advsearch_link" ),
"grid_field", new XVar( 0, "simple_grid_field",
1, "simple_grid_field1",
2, "simple_grid_field2",
3, "simple_grid_field3",
4, "simple_grid_field4",
5, "simple_grid_field5",
6, "simple_grid_field6",
7, "simple_grid_field7",
8, "simple_grid_field8",
9, "simple_grid_field9",
10, "simple_grid_field10",
11, "simple_grid_field11",
12, "simple_grid_field12",
13, "simple_grid_field13",
14, "simple_grid_field14",
15, "simple_grid_field15" ),
"grid_field_label", new XVar( 0, "simple_grid_field16",
1, "simple_grid_field17",
2, "simple_grid_field18",
3, "simple_grid_field19",
4, "simple_grid_field20",
5, "simple_grid_field21",
6, "simple_grid_field22",
7, "simple_grid_field23",
8, "simple_grid_field24",
9, "simple_grid_field25",
10, "simple_grid_field26",
11, "simple_grid_field27",
12, "simple_grid_field28",
13, "simple_grid_field29",
14, "simple_grid_field30",
15, "simple_grid_field31" ),
"custom_button", new XVar( 0, "custom_button" ),
"expand_button", new XVar( 0, "expand_button" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_checkbox", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox_head" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_checkbox1", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "clientid_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field16" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "site_ref_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field17" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "vend_num_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field18" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "sl_name_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field19" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_name_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field20" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_street_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field21" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "sl_street_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field22" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_city_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field23" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field8", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "sl_city_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field24" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field9", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_state_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field25" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field10", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "sl_state_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field26" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field11", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_zip_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field27" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field12", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "sl_zip_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field28" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field13", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "tp_country_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field29" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field14", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "sl_country_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field30" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field15", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "vendor_remit_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field31" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_checkbox", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_checkbox2", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", true,
"fixedAtClient", true ),
"cell_field", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "clientid_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "site_ref_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "vend_num_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "sl_name_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_name_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_street_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "sl_street_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_city_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field8", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "sl_city_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field9", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_state_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field10", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "sl_state_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field11", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_zip_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field12", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "sl_zip_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field13", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "tp_country_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field14", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "sl_country_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field14" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field15", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "vendor_remit_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field15" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_checkbox", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_checkbox3", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field8", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field9", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field10", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field11", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field12", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field13", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field14", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field15", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 18,
"height", 3 ) ) ),
"loginForm", new XVar( "loginForm", 0 ),
"page", new XVar( "verticalBar", true,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar( "details_found", new XVar( "tag", "DISPLAYING",
"type", 2 ) ) ),
"gridType", 0,
"recsPerRow", 1,
"hasCustomButtons", true,
"customButtons", new XVar( 0, "New_Button_For_Post" ),
"hasNotifications", false,
"menus", new XVar( 0, new XVar( "id", "main",
"horizontal", false ) ),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "list",
"breadcrumb", true ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", new XVar( 0, "New_Button_For_Post" ) ),
"dataGrid", new XVar( "groupFields", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "list",
"type", "list",
"layoutId", "leftbar",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "list-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "details_found",
1, "page_size",
2, "print_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "list-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "pagination" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"left", new XVar( "modelId", "leftbar-menu",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c0" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c0", new XVar( "model", "c0",
"items", new XVar( 0, "logo",
1, "expand_button" ) ),
"c1", new XVar( "model", "c1",
"items", new XVar( 0, "menu",
1, "search_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"supertop", new XVar( "modelId", "leftbar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "simple_search",
1, "list_options",
2, "loginform_login",
3, "username_button" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_checkbox" ),
1, new XVar( "cell", "headcell_checkbox1" ),
2, new XVar( "cell", "headcell_field" ),
3, new XVar( "cell", "headcell_field1" ),
4, new XVar( "cell", "headcell_field2" ),
5, new XVar( "cell", "headcell_field3" ),
6, new XVar( "cell", "headcell_field4" ),
7, new XVar( "cell", "headcell_field5" ),
8, new XVar( "cell", "headcell_field6" ),
9, new XVar( "cell", "headcell_field7" ),
10, new XVar( "cell", "headcell_field8" ),
11, new XVar( "cell", "headcell_field9" ),
12, new XVar( "cell", "headcell_field10" ),
13, new XVar( "cell", "headcell_field11" ),
14, new XVar( "cell", "headcell_field12" ),
15, new XVar( "cell", "headcell_field13" ),
16, new XVar( "cell", "headcell_field14" ),
17, new XVar( "cell", "headcell_field15" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_checkbox" ),
1, new XVar( "cell", "headcell_checkbox2" ),
2, new XVar( "cell", "cell_field" ),
3, new XVar( "cell", "cell_field1" ),
4, new XVar( "cell", "cell_field2" ),
5, new XVar( "cell", "cell_field3" ),
6, new XVar( "cell", "cell_field4" ),
7, new XVar( "cell", "cell_field5" ),
8, new XVar( "cell", "cell_field6" ),
9, new XVar( "cell", "cell_field7" ),
10, new XVar( "cell", "cell_field8" ),
11, new XVar( "cell", "cell_field9" ),
12, new XVar( "cell", "cell_field10" ),
13, new XVar( "cell", "cell_field11" ),
14, new XVar( "cell", "cell_field12" ),
15, new XVar( "cell", "cell_field13" ),
16, new XVar( "cell", "cell_field14" ),
17, new XVar( "cell", "cell_field15" ) ) ),
2, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_checkbox" ),
1, new XVar( "cell", "headcell_checkbox3" ),
2, new XVar( "cell", "footcell_field" ),
3, new XVar( "cell", "footcell_field1" ),
4, new XVar( "cell", "footcell_field2" ),
5, new XVar( "cell", "footcell_field3" ),
6, new XVar( "cell", "footcell_field4" ),
7, new XVar( "cell", "footcell_field5" ),
8, new XVar( "cell", "footcell_field6" ),
9, new XVar( "cell", "footcell_field7" ),
10, new XVar( "cell", "footcell_field8" ),
11, new XVar( "cell", "footcell_field9" ),
12, new XVar( "cell", "footcell_field10" ),
13, new XVar( "cell", "footcell_field11" ),
14, new XVar( "cell", "footcell_field12" ),
15, new XVar( "cell", "footcell_field13" ),
16, new XVar( "cell", "footcell_field14" ),
17, new XVar( "cell", "footcell_field15" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field16" ),
"field", "clientid",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "clientid",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field17" ),
"field", "site_ref",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "site_ref",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field18" ),
"field", "vend_num",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "vend_num",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field19" ),
"field", "sl_name",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "sl_name",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field20" ),
"field", "tp_name",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "tp_name",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field21" ),
"field", "tp_street",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "tp_street",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field22" ),
"field", "sl_street",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "sl_street",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field23" ),
"field", "tp_city",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "tp_city",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field8", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field24" ),
"field", "sl_city",
"columnName", "field" ),
"cell_field8", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "sl_city",
"columnName", "field" ),
"footcell_field8", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field9", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field25" ),
"field", "tp_state",
"columnName", "field" ),
"cell_field9", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "tp_state",
"columnName", "field" ),
"footcell_field9", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field10", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field26" ),
"field", "sl_state",
"columnName", "field" ),
"cell_field10", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "sl_state",
"columnName", "field" ),
"footcell_field10", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field11", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field27" ),
"field", "tp_zip",
"columnName", "field" ),
"cell_field11", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "tp_zip",
"columnName", "field" ),
"footcell_field11", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field12", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field28" ),
"field", "sl_zip",
"columnName", "field" ),
"cell_field12", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "sl_zip",
"columnName", "field" ),
"footcell_field12", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field13", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field29" ),
"field", "tp_country",
"columnName", "field" ),
"cell_field13", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "tp_country",
"columnName", "field" ),
"footcell_field13", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field14", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field30" ),
"field", "sl_country",
"columnName", "field" ),
"cell_field14", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field14" ),
"field", "sl_country",
"columnName", "field" ),
"footcell_field14", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field15", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field31" ),
"field", "vendor_remit",
"columnName", "field" ),
"cell_field15", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field15" ),
"field", "vendor_remit",
"columnName", "field" ),
"footcell_field15", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_checkbox", new XVar( "model", "headcell_checkbox",
"items", new XVar( 0, "grid_checkbox_head" ) ),
"cell_checkbox", new XVar( "model", "cell_checkbox",
"items", new XVar( 0, "grid_checkbox" ) ),
"footcell_checkbox", new XVar( "model", "footcell_checkbox",
"items", XVar.Array() ),
"headcell_checkbox1", new XVar( "model", "headcell_checkbox",
"items", XVar.Array() ),
"headcell_checkbox2", new XVar( "model", "cell_checkbox",
"items", new XVar( 0, "custom_button" ) ),
"headcell_checkbox3", new XVar( "model", "footcell_checkbox",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "list-sidebar-top",
"grid", XVar.Array(),
"cells", new XVar(  ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "page_size", new XVar( "type", "page_size" ),
"breadcrumb", new XVar( "type", "breadcrumb" ),
"logo", new XVar( "type", "logo" ),
"menu", new XVar( "type", "menu" ),
"simple_search", new XVar( "type", "simple_search" ),
"pagination", new XVar( "type", "pagination" ),
"grid_checkbox", new XVar( "type", "grid_checkbox" ),
"grid_checkbox_head", new XVar( "type", "grid_checkbox_head" ),
"details_found", new XVar( "type", "details_found" ),
"search_panel", new XVar( "type", "search_panel",
"items", new XVar( 0, "search_panel_field",
1, "search_panel_field15",
2, "search_panel_field14",
3, "search_panel_field13",
4, "search_panel_field12",
5, "search_panel_field11",
6, "search_panel_field10",
7, "search_panel_field9",
8, "search_panel_field8",
9, "search_panel_field7",
10, "search_panel_field6",
11, "search_panel_field5",
12, "search_panel_field4",
13, "search_panel_field3",
14, "search_panel_field2",
15, "search_panel_field1" ) ),
"list_options", new XVar( "type", "list_options",
"items", new XVar( 0, "advsearch_link",
1, "show_search_panel",
2, "hide_search_panel",
3, "-2",
4, "export",
5, "-1",
6, "import" ) ),
"show_search_panel", new XVar( "type", "show_search_panel" ),
"hide_search_panel", new XVar( "type", "hide_search_panel" ),
"search_panel_field", new XVar( "field", "clientid",
"type", "search_panel_field",
"required", false ),
"search_panel_field1", new XVar( "field", "site_ref",
"type", "search_panel_field",
"required", false ),
"search_panel_field2", new XVar( "field", "sl_city",
"type", "search_panel_field",
"required", false ),
"search_panel_field3", new XVar( "field", "sl_country",
"type", "search_panel_field",
"required", false ),
"search_panel_field4", new XVar( "field", "sl_name",
"type", "search_panel_field",
"required", false ),
"search_panel_field5", new XVar( "field", "sl_state",
"type", "search_panel_field",
"required", false ),
"search_panel_field6", new XVar( "field", "sl_street",
"type", "search_panel_field",
"required", false ),
"search_panel_field7", new XVar( "field", "sl_zip",
"type", "search_panel_field",
"required", false ),
"search_panel_field8", new XVar( "field", "tp_city",
"type", "search_panel_field",
"required", false ),
"search_panel_field9", new XVar( "field", "tp_country",
"type", "search_panel_field",
"required", false ),
"search_panel_field10", new XVar( "field", "tp_name",
"type", "search_panel_field",
"required", false ),
"search_panel_field11", new XVar( "field", "tp_state",
"type", "search_panel_field",
"required", false ),
"search_panel_field12", new XVar( "field", "tp_street",
"type", "search_panel_field",
"required", false ),
"search_panel_field13", new XVar( "field", "tp_zip",
"type", "search_panel_field",
"required", false ),
"search_panel_field14", new XVar( "field", "vend_num",
"type", "search_panel_field",
"required", false ),
"search_panel_field15", new XVar( "field", "vendor_remit",
"type", "search_panel_field",
"required", false ),
"username_button", new XVar( "type", "username_button",
"items", new XVar( 0, "userinfo_link",
1, "logout_link",
2, "adminarea_link",
3, "changepassword_link" ) ),
"loginform_login", new XVar( "type", "loginform_login",
"popup", false ),
"userinfo_link", new XVar( "type", "userinfo_link" ),
"logout_link", new XVar( "type", "logout_link" ),
"adminarea_link", new XVar( "type", "adminarea_link" ),
"changepassword_link", new XVar( "type", "changepassword_link" ),
"expand_menu_button", new XVar( "type", "expand_menu_button" ),
"collapse_button", new XVar( "type", "collapse_button" ),
"print_panel", new XVar( "type", "print_panel",
"items", new XVar( 0, "print_scope",
1, "print_records",
2, "print_button" ) ),
"print_scope", new XVar( "type", "print_scope" ),
"print_button", new XVar( "type", "print_button" ),
"print_records", new XVar( "type", "print_records" ),
"export", new XVar( "type", "export" ),
"-", new XVar( "type", "-" ),
"import", new XVar( "type", "import" ),
"-1", new XVar( "type", "-" ),
"advsearch_link", new XVar( "type", "advsearch_link" ),
"-2", new XVar( "type", "-" ),
"simple_grid_field", new XVar( "field", "clientid",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field1", new XVar( "field", "site_ref",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field2", new XVar( "field", "vend_num",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field3", new XVar( "field", "sl_name",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field4", new XVar( "field", "tp_name",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field5", new XVar( "field", "tp_street",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field6", new XVar( "field", "sl_street",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field7", new XVar( "field", "tp_city",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field8", new XVar( "field", "sl_city",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field9", new XVar( "field", "tp_state",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field10", new XVar( "field", "sl_state",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field11", new XVar( "field", "tp_zip",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field12", new XVar( "field", "sl_zip",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field13", new XVar( "field", "tp_country",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field14", new XVar( "field", "sl_country",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field15", new XVar( "field", "vendor_remit",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field16", new XVar( "type", "grid_field_label",
"field", "clientid" ),
"simple_grid_field17", new XVar( "type", "grid_field_label",
"field", "site_ref" ),
"simple_grid_field18", new XVar( "type", "grid_field_label",
"field", "vend_num" ),
"simple_grid_field19", new XVar( "type", "grid_field_label",
"field", "sl_name" ),
"simple_grid_field20", new XVar( "type", "grid_field_label",
"field", "tp_name" ),
"simple_grid_field21", new XVar( "type", "grid_field_label",
"field", "tp_street" ),
"simple_grid_field22", new XVar( "type", "grid_field_label",
"field", "sl_street" ),
"simple_grid_field23", new XVar( "type", "grid_field_label",
"field", "tp_city" ),
"simple_grid_field24", new XVar( "type", "grid_field_label",
"field", "sl_city" ),
"simple_grid_field25", new XVar( "type", "grid_field_label",
"field", "tp_state" ),
"simple_grid_field26", new XVar( "type", "grid_field_label",
"field", "sl_state" ),
"simple_grid_field27", new XVar( "type", "grid_field_label",
"field", "tp_zip" ),
"simple_grid_field28", new XVar( "type", "grid_field_label",
"field", "sl_zip" ),
"simple_grid_field29", new XVar( "type", "grid_field_label",
"field", "tp_country" ),
"simple_grid_field30", new XVar( "type", "grid_field_label",
"field", "sl_country" ),
"simple_grid_field31", new XVar( "type", "grid_field_label",
"field", "vendor_remit" ),
"custom_button", new XVar( "eventId", "New_Button_For_Post",
"label", new XVar( "text", "Post",
"type", 0 ),
"type", "custom_button",
"buttonStyle", "primary" ),
"expand_button", new XVar( "type", "expand_button" ) ),
"dbProps", new XVar(  ),
"spreadsheetGrid", false,
"version", 14,
"reorderRows", false,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}