using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_auditlog_mst
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["auditlog_mst"] = SettingsMap.GetArray();
			tdataArray["auditlog_mst"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["auditlog_mst"][".ShortName"] = "auditlog_mst";
			tdataArray["auditlog_mst"][".OwnerID"] = "clientid";
			tdataArray["auditlog_mst"][".OriginalTable"] = "dbo.auditlog_mst";
			tdataArray["auditlog_mst"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}"));
			tdataArray["auditlog_mst"][".originalPagesByType"] = tdataArray["auditlog_mst"][".pagesByType"];
			tdataArray["auditlog_mst"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}")));
			tdataArray["auditlog_mst"][".originalPages"] = tdataArray["auditlog_mst"][".pages"];
			tdataArray["auditlog_mst"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\",\"view\":\"view\"}"));
			tdataArray["auditlog_mst"][".originalDefaultPages"] = tdataArray["auditlog_mst"][".defaultPages"];
			fieldLabelsArray["auditlog_mst"] = SettingsMap.GetArray();
			fieldToolTipsArray["auditlog_mst"] = SettingsMap.GetArray();
			pageTitlesArray["auditlog_mst"] = SettingsMap.GetArray();
			placeHoldersArray["auditlog_mst"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["auditlog_mst"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["auditlog_mst"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["auditlog_mst"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["auditlog_mst"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["auditlog_mst"]["English"]["clientid"] = "Client";
				fieldToolTipsArray["auditlog_mst"]["English"]["clientid"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["clientid"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["seq"] = "Seq";
				fieldToolTipsArray["auditlog_mst"]["English"]["seq"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["seq"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["payload"] = "Payload";
				fieldToolTipsArray["auditlog_mst"]["English"]["payload"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["payload"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["create_date"] = "Create Date";
				fieldToolTipsArray["auditlog_mst"]["English"]["create_date"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["create_date"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["posted"] = "Posted";
				fieldToolTipsArray["auditlog_mst"]["English"]["posted"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["posted"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["ref_num"] = "Ref Num";
				fieldToolTipsArray["auditlog_mst"]["English"]["ref_num"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["ref_num"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["process"] = "Process";
				fieldToolTipsArray["auditlog_mst"]["English"]["process"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["process"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["rowpointer"] = "Rowpointer";
				fieldToolTipsArray["auditlog_mst"]["English"]["rowpointer"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["rowpointer"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["logId"] = "Log Id";
				fieldToolTipsArray["auditlog_mst"]["English"]["logId"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["logId"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["response"] = "Response";
				fieldToolTipsArray["auditlog_mst"]["English"]["response"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["response"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["refrowpointer"] = "Refrowpointer";
				fieldToolTipsArray["auditlog_mst"]["English"]["refrowpointer"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["refrowpointer"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["status"] = "Status";
				fieldToolTipsArray["auditlog_mst"]["English"]["status"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["status"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["statusmessage"] = "Statusmessage";
				fieldToolTipsArray["auditlog_mst"]["English"]["statusmessage"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["statusmessage"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["app"] = "App";
				fieldToolTipsArray["auditlog_mst"]["English"]["app"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["app"] = "";
				fieldLabelsArray["auditlog_mst"]["English"]["tz_create_date"] = "Tz Create Date";
				fieldToolTipsArray["auditlog_mst"]["English"]["tz_create_date"] = "";
				placeHoldersArray["auditlog_mst"]["English"]["tz_create_date"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["auditlog_mst"]["English"])))
				{
					tdataArray["auditlog_mst"][".isUseToolTips"] = true;
				}
			}
			tdataArray["auditlog_mst"][".NCSearch"] = true;
			tdataArray["auditlog_mst"][".shortTableName"] = "auditlog_mst";
			tdataArray["auditlog_mst"][".nSecOptions"] = 1;
			tdataArray["auditlog_mst"][".mainTableOwnerID"] = "clientid";
			tdataArray["auditlog_mst"][".entityType"] = 0;
			tdataArray["auditlog_mst"][".connId"] = "Hubkoratec218206166241compute1";
			tdataArray["auditlog_mst"][".strOriginalTableName"] = "dbo.auditlog_mst";
			tdataArray["auditlog_mst"][".showAddInPopup"] = false;
			tdataArray["auditlog_mst"][".showEditInPopup"] = false;
			tdataArray["auditlog_mst"][".showViewInPopup"] = false;
			tdataArray["auditlog_mst"][".listAjax"] = false;
			tdataArray["auditlog_mst"][".audit"] = true;
			tdataArray["auditlog_mst"][".locking"] = false;
			GlobalVars.pages = tdataArray["auditlog_mst"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["auditlog_mst"][".edit"] = true;
				tdataArray["auditlog_mst"][".afterEditAction"] = 1;
				tdataArray["auditlog_mst"][".closePopupAfterEdit"] = 1;
				tdataArray["auditlog_mst"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["auditlog_mst"][".add"] = true;
				tdataArray["auditlog_mst"][".afterAddAction"] = 1;
				tdataArray["auditlog_mst"][".closePopupAfterAdd"] = 1;
				tdataArray["auditlog_mst"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["auditlog_mst"][".list"] = true;
			}
			tdataArray["auditlog_mst"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["auditlog_mst"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["auditlog_mst"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["auditlog_mst"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["auditlog_mst"][".printFriendly"] = true;
			}
			tdataArray["auditlog_mst"][".showSimpleSearchOptions"] = true;
			tdataArray["auditlog_mst"][".allowShowHideFields"] = true;
			tdataArray["auditlog_mst"][".allowFieldsReordering"] = true;
			tdataArray["auditlog_mst"][".isUseAjaxSuggest"] = true;


			tdataArray["auditlog_mst"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["auditlog_mst"][".buttonsAdded"] = false;
			tdataArray["auditlog_mst"][".addPageEvents"] = false;
			tdataArray["auditlog_mst"][".isUseTimeForSearch"] = false;
			tdataArray["auditlog_mst"][".badgeColor"] = "edca00";
			tdataArray["auditlog_mst"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["auditlog_mst"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["auditlog_mst"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["auditlog_mst"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("clientid");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("seq");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("payload");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("create_date");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("tz_create_date");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("posted");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("ref_num");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("process");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("rowpointer");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("logId");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("response");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("refrowpointer");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("status");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("statusmessage");
			tdataArray["auditlog_mst"][".googleLikeFields"].Add("app");
			tdataArray["auditlog_mst"][".tableType"] = "list";
			tdataArray["auditlog_mst"][".printerPageOrientation"] = 0;
			tdataArray["auditlog_mst"][".nPrinterPageScale"] = 100;
			tdataArray["auditlog_mst"][".nPrinterSplitRecords"] = 40;
			tdataArray["auditlog_mst"][".geocodingEnabled"] = false;
			tdataArray["auditlog_mst"][".pageSize"] = 20;
			tdataArray["auditlog_mst"][".warnLeavingPages"] = true;
			tstrOrderBy = "order by seq desc";
			tdataArray["auditlog_mst"][".strOrderBy"] = tstrOrderBy;
			tdataArray["auditlog_mst"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["auditlog_mst"][".orderindexes"].Add(new XVar(0, 2, 1, (XVar.Pack(0) ? XVar.Pack("ASC") : XVar.Pack("DESC")), 2, "seq"));
			tdataArray["auditlog_mst"][".sqlHead"] = "SELECT clientid,  	seq,  	payload,  	create_date,  dbo.HK_TimeZone(':session.user_name',create_date) tz_create_date,  	posted,  	ref_num,  	process,  	rowpointer,  	logId,  	response,  	refrowpointer,  	status,  	statusmessage,  	app";
			tdataArray["auditlog_mst"][".sqlFrom"] = "FROM dbo.auditlog_mst";
			tdataArray["auditlog_mst"][".sqlWhereExpr"] = "";
			tdataArray["auditlog_mst"][".sqlTail"] = "";
			arrGridTabs = SettingsMap.GetArray();
			arrGridTabs.Add(new XVar("tabId", "", "name", "All data", "nameType", "Text", "where", "", "showRowCount", 0, "hideEmpty", 0));
			tdataArray["auditlog_mst"][".arrGridTabs"] = arrGridTabs;
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["auditlog_mst"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["auditlog_mst"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["auditlog_mst"][".highlightSearchResults"] = true;
			tableKeysArray["auditlog_mst"] = SettingsMap.GetArray();
			tableKeysArray["auditlog_mst"].Add("seq");
			tdataArray["auditlog_mst"][".Keys"] = tableKeysArray["auditlog_mst"];
			tdataArray["auditlog_mst"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "clientid";
			fdata["GoodName"] = "clientid";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","clientid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "clientid";
			fdata["sourceSingle"] = "clientid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "clientid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["clientid"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("clientid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "seq";
			fdata["GoodName"] = "seq";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","seq");
			fdata["FieldType"] = 20;
			fdata["AutoInc"] = true;
			fdata["strField"] = "seq";
			fdata["sourceSingle"] = "seq";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "seq";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["seq"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("seq");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "payload";
			fdata["GoodName"] = "payload";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","payload");
			fdata["FieldType"] = 202;
			fdata["strField"] = "payload";
			fdata["sourceSingle"] = "payload";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "payload";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["payload"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("payload");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "create_date";
			fdata["GoodName"] = "create_date";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","create_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "create_date";
			fdata["sourceSingle"] = "create_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "create_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Datetime");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "Invalid week day", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 5;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["create_date"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("create_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "tz_create_date";
			fdata["GoodName"] = "tz_create_date";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","tz_create_date");
			fdata["FieldType"] = 200;
			fdata["strField"] = "tz_create_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "dbo.HK_TimeZone(':session.user_name',create_date)";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["tz_create_date"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("tz_create_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "posted";
			fdata["GoodName"] = "posted";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","posted");
			fdata["FieldType"] = 16;
			fdata["strField"] = "posted";
			fdata["sourceSingle"] = "posted";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "posted";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["posted"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("posted");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "ref_num";
			fdata["GoodName"] = "ref_num";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","ref_num");
			fdata["FieldType"] = 202;
			fdata["strField"] = "ref_num";
			fdata["sourceSingle"] = "ref_num";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ref_num";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["ref_num"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("ref_num");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "process";
			fdata["GoodName"] = "process";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","process");
			fdata["FieldType"] = 202;
			fdata["strField"] = "process";
			fdata["sourceSingle"] = "process";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "process";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["process"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("process");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "rowpointer";
			fdata["GoodName"] = "rowpointer";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","rowpointer");
			fdata["FieldType"] = 72;
			fdata["strField"] = "rowpointer";
			fdata["sourceSingle"] = "rowpointer";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "rowpointer";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["rowpointer"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("rowpointer");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "logId";
			fdata["GoodName"] = "logId";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","logId");
			fdata["FieldType"] = 202;
			fdata["strField"] = "logId";
			fdata["sourceSingle"] = "logId";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "logId";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["logId"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("logId");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "response";
			fdata["GoodName"] = "response";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","response");
			fdata["FieldType"] = 202;
			fdata["strField"] = "response";
			fdata["sourceSingle"] = "response";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "response";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["response"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("response");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "refrowpointer";
			fdata["GoodName"] = "refrowpointer";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","refrowpointer");
			fdata["FieldType"] = 72;
			fdata["strField"] = "refrowpointer";
			fdata["sourceSingle"] = "refrowpointer";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "refrowpointer";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["refrowpointer"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("refrowpointer");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "status";
			fdata["GoodName"] = "status";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","status");
			fdata["FieldType"] = 202;
			fdata["strField"] = "status";
			fdata["sourceSingle"] = "status";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "status";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["status"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("status");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 14;
			fdata["strName"] = "statusmessage";
			fdata["GoodName"] = "statusmessage";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","statusmessage");
			fdata["FieldType"] = 202;
			fdata["strField"] = "statusmessage";
			fdata["sourceSingle"] = "statusmessage";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "statusmessage";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=500");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["statusmessage"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("statusmessage");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 15;
			fdata["strName"] = "app";
			fdata["GoodName"] = "app";
			fdata["ownerTable"] = "dbo.auditlog_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_auditlog_mst","app");
			fdata["FieldType"] = 202;
			fdata["strField"] = "app";
			fdata["sourceSingle"] = "app";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "app";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["auditlog_mst"]["app"] = fdata;
			tdataArray["auditlog_mst"][".searchableFields"].Add("app");
			GlobalVars.tables_data["dbo.auditlog_mst"] = tdataArray["auditlog_mst"];
			GlobalVars.field_labels["dbo_auditlog_mst"] = fieldLabelsArray["auditlog_mst"];
			GlobalVars.fieldToolTips["dbo_auditlog_mst"] = fieldToolTipsArray["auditlog_mst"];
			GlobalVars.placeHolders["dbo_auditlog_mst"] = placeHoldersArray["auditlog_mst"];
			GlobalVars.page_titles["dbo_auditlog_mst"] = pageTitlesArray["auditlog_mst"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.auditlog_mst"));
			GlobalVars.detailsTablesData["dbo.auditlog_mst"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.auditlog_mst"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "clientid,  	seq,  	payload,  	create_date,  dbo.HK_TimeZone(':session.user_name',create_date) tz_create_date,  	posted,  	ref_num,  	process,  	rowpointer,  	logId,  	response,  	refrowpointer,  	status,  	statusmessage,  	app";
protoArray["0"]["m_strFrom"] = "FROM dbo.auditlog_mst";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "order by seq desc";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "clientid", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["6"]["m_sql"] = "clientid";
protoArray["6"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "seq", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["8"]["m_sql"] = "seq";
protoArray["8"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "payload", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["10"]["m_sql"] = "payload";
protoArray["10"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "create_date", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["12"]["m_sql"] = "create_date";
protoArray["12"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
protoArray["15"] = SettingsMap.GetArray();
protoArray["15"]["m_functiontype"] = "SQLF_CUSTOM";
protoArray["15"]["m_arguments"] = SettingsMap.GetArray();
obj = new SQLNonParsed(new XVar("m_sql", "':session.user_name'"));

protoArray["15"]["m_arguments"].Add(obj);
obj = new SQLNonParsed(new XVar("m_sql", "create_date"));

protoArray["15"]["m_arguments"].Add(obj);
protoArray["15"]["m_strFunctionName"] = "dbo.HK_TimeZone";
obj = new SQLFunctionCall(protoArray["15"]);

protoArray["14"]["m_sql"] = "dbo.HK_TimeZone(':session.user_name',create_date)";
protoArray["14"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "tz_create_date";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "posted", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["18"]["m_sql"] = "posted";
protoArray["18"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ref_num", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["20"]["m_sql"] = "ref_num";
protoArray["20"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "process", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["22"]["m_sql"] = "process";
protoArray["22"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "rowpointer", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["24"]["m_sql"] = "rowpointer";
protoArray["24"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "logId", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["26"]["m_sql"] = "logId";
protoArray["26"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "response", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["28"]["m_sql"] = "response";
protoArray["28"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "refrowpointer", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["30"]["m_sql"] = "refrowpointer";
protoArray["30"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["32"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "status", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["32"]["m_sql"] = "status";
protoArray["32"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["32"]["m_expr"] = obj;
protoArray["32"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["32"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["34"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "statusmessage", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["34"]["m_sql"] = "statusmessage";
protoArray["34"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["34"]["m_expr"] = obj;
protoArray["34"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["34"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["36"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "app", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["36"]["m_sql"] = "app";
protoArray["36"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["36"]["m_expr"] = obj;
protoArray["36"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["36"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["38"] = SettingsMap.GetArray();
protoArray["38"]["m_link"] = "SQLL_MAIN";
protoArray["39"] = SettingsMap.GetArray();
protoArray["39"]["m_strName"] = "dbo.auditlog_mst";
protoArray["39"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["39"]["m_columns"] = SettingsMap.GetArray();
protoArray["39"]["m_columns"].Add("clientid");
protoArray["39"]["m_columns"].Add("seq");
protoArray["39"]["m_columns"].Add("payload");
protoArray["39"]["m_columns"].Add("create_date");
protoArray["39"]["m_columns"].Add("posted");
protoArray["39"]["m_columns"].Add("ref_num");
protoArray["39"]["m_columns"].Add("process");
protoArray["39"]["m_columns"].Add("rowpointer");
protoArray["39"]["m_columns"].Add("logId");
protoArray["39"]["m_columns"].Add("response");
protoArray["39"]["m_columns"].Add("refrowpointer");
protoArray["39"]["m_columns"].Add("status");
protoArray["39"]["m_columns"].Add("statusmessage");
protoArray["39"]["m_columns"].Add("app");
obj = new SQLTable(protoArray["39"]);

protoArray["38"]["m_table"] = obj;
protoArray["38"]["m_sql"] = "dbo.auditlog_mst";
protoArray["38"]["m_alias"] = "";
protoArray["38"]["m_srcTableName"] = "dbo.auditlog_mst";
protoArray["40"] = SettingsMap.GetArray();
protoArray["40"]["m_sql"] = "";
protoArray["40"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["40"]["m_column"] = obj;
protoArray["40"]["m_contained"] = SettingsMap.GetArray();
protoArray["40"]["m_strCase"] = "";
protoArray["40"]["m_havingmode"] = false;
protoArray["40"]["m_inBrackets"] = false;
protoArray["40"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["40"]);

protoArray["38"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["38"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["42"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "seq", "m_strTable", "dbo.auditlog_mst", "m_srcTableName", "dbo.auditlog_mst"));

protoArray["42"]["m_column"] = obj;
protoArray["42"]["m_bAsc"] = 0;
protoArray["42"]["m_nColumn"] = 0;
obj = new SQLOrderByItem(protoArray["42"]);

protoArray["0"]["m_orderby"].Add(obj);
protoArray["0"]["m_srcTableName"] = "dbo.auditlog_mst";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["auditlog_mst"] = obj;

				
		
			tdataArray["auditlog_mst"][".sqlquery"] = queryData_Array["auditlog_mst"];
			tdataArray["auditlog_mst"][".hasEvents"] = false;
		}
	}

}
