using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_client_apps
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["client_apps"] = SettingsMap.GetArray();
			tdataArray["client_apps"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["client_apps"][".ShortName"] = "client_apps";
			tdataArray["client_apps"][".OwnerID"] = "client";
			tdataArray["client_apps"][".OriginalTable"] = "dbo.client_apps";
			tdataArray["client_apps"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"masterlist\":[\"masterlist\"],\"masterprint\":[\"masterprint\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}"));
			tdataArray["client_apps"][".originalPagesByType"] = tdataArray["client_apps"][".pagesByType"];
			tdataArray["client_apps"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"masterlist\":[\"masterlist\"],\"masterprint\":[\"masterprint\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}")));
			tdataArray["client_apps"][".originalPages"] = tdataArray["client_apps"][".pages"];
			tdataArray["client_apps"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"edit\":\"edit\",\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"masterlist\":\"masterlist\",\"masterprint\":\"masterprint\",\"print\":\"print\",\"search\":\"search\",\"view\":\"view\"}"));
			tdataArray["client_apps"][".originalDefaultPages"] = tdataArray["client_apps"][".defaultPages"];
			fieldLabelsArray["client_apps"] = SettingsMap.GetArray();
			fieldToolTipsArray["client_apps"] = SettingsMap.GetArray();
			pageTitlesArray["client_apps"] = SettingsMap.GetArray();
			placeHoldersArray["client_apps"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["client_apps"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["client_apps"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["client_apps"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["client_apps"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["client_apps"]["English"]["client"] = "Client";
				fieldToolTipsArray["client_apps"]["English"]["client"] = "";
				placeHoldersArray["client_apps"]["English"]["client"] = "";
				fieldLabelsArray["client_apps"]["English"]["app"] = "App";
				fieldToolTipsArray["client_apps"]["English"]["app"] = "";
				placeHoldersArray["client_apps"]["English"]["app"] = "";
				fieldLabelsArray["client_apps"]["English"]["active"] = "Active";
				fieldToolTipsArray["client_apps"]["English"]["active"] = "";
				placeHoldersArray["client_apps"]["English"]["active"] = "";
				fieldLabelsArray["client_apps"]["English"]["profile_id"] = "Profile Id";
				fieldToolTipsArray["client_apps"]["English"]["profile_id"] = "";
				placeHoldersArray["client_apps"]["English"]["profile_id"] = "";
				fieldLabelsArray["client_apps"]["English"]["effective_date"] = "Effective Date";
				fieldToolTipsArray["client_apps"]["English"]["effective_date"] = "";
				placeHoldersArray["client_apps"]["English"]["effective_date"] = "";
				fieldLabelsArray["client_apps"]["English"]["termination_date"] = "Termination Date";
				fieldToolTipsArray["client_apps"]["English"]["termination_date"] = "";
				placeHoldersArray["client_apps"]["English"]["termination_date"] = "";
				fieldLabelsArray["client_apps"]["English"]["email_flash"] = "Email Flash";
				fieldToolTipsArray["client_apps"]["English"]["email_flash"] = "";
				placeHoldersArray["client_apps"]["English"]["email_flash"] = "";
				fieldLabelsArray["client_apps"]["English"]["status"] = "Status";
				fieldToolTipsArray["client_apps"]["English"]["status"] = "";
				placeHoldersArray["client_apps"]["English"]["status"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["client_apps"]["English"])))
				{
					tdataArray["client_apps"][".isUseToolTips"] = true;
				}
			}
			tdataArray["client_apps"][".NCSearch"] = true;
			tdataArray["client_apps"][".shortTableName"] = "client_apps";
			tdataArray["client_apps"][".nSecOptions"] = 1;
			tdataArray["client_apps"][".mainTableOwnerID"] = "client";
			tdataArray["client_apps"][".entityType"] = 0;
			tdataArray["client_apps"][".connId"] = "Hubkoratec218206166241compute1";
			tdataArray["client_apps"][".strOriginalTableName"] = "dbo.client_apps";
			tdataArray["client_apps"][".showAddInPopup"] = false;
			tdataArray["client_apps"][".showEditInPopup"] = false;
			tdataArray["client_apps"][".showViewInPopup"] = false;
			tdataArray["client_apps"][".listAjax"] = false;
			tdataArray["client_apps"][".audit"] = true;
			tdataArray["client_apps"][".locking"] = false;
			GlobalVars.pages = tdataArray["client_apps"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["client_apps"][".edit"] = true;
				tdataArray["client_apps"][".afterEditAction"] = 1;
				tdataArray["client_apps"][".closePopupAfterEdit"] = 1;
				tdataArray["client_apps"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["client_apps"][".add"] = true;
				tdataArray["client_apps"][".afterAddAction"] = 1;
				tdataArray["client_apps"][".closePopupAfterAdd"] = 1;
				tdataArray["client_apps"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["client_apps"][".list"] = true;
			}
			tdataArray["client_apps"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["client_apps"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["client_apps"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["client_apps"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["client_apps"][".printFriendly"] = true;
			}
			tdataArray["client_apps"][".showSimpleSearchOptions"] = true;
			tdataArray["client_apps"][".allowShowHideFields"] = true;
			tdataArray["client_apps"][".allowFieldsReordering"] = true;
			tdataArray["client_apps"][".isUseAjaxSuggest"] = true;


			tdataArray["client_apps"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["client_apps"][".buttonsAdded"] = false;
			tdataArray["client_apps"][".addPageEvents"] = false;
			tdataArray["client_apps"][".isUseTimeForSearch"] = false;
			tdataArray["client_apps"][".badgeColor"] = "9acd32";
			tdataArray["client_apps"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["client_apps"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["client_apps"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["client_apps"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["client_apps"][".googleLikeFields"].Add("client");
			tdataArray["client_apps"][".googleLikeFields"].Add("app");
			tdataArray["client_apps"][".googleLikeFields"].Add("active");
			tdataArray["client_apps"][".googleLikeFields"].Add("profile_id");
			tdataArray["client_apps"][".googleLikeFields"].Add("effective_date");
			tdataArray["client_apps"][".googleLikeFields"].Add("termination_date");
			tdataArray["client_apps"][".googleLikeFields"].Add("email_flash");
			tdataArray["client_apps"][".googleLikeFields"].Add("status");
			tdataArray["client_apps"][".tableType"] = "list";
			tdataArray["client_apps"][".printerPageOrientation"] = 0;
			tdataArray["client_apps"][".nPrinterPageScale"] = 100;
			tdataArray["client_apps"][".nPrinterSplitRecords"] = 40;
			tdataArray["client_apps"][".geocodingEnabled"] = false;
			tdataArray["client_apps"][".pageSize"] = 20;
			tdataArray["client_apps"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["client_apps"][".strOrderBy"] = tstrOrderBy;
			tdataArray["client_apps"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["client_apps"][".sqlHead"] = "SELECT client,  	app,  	active,  	profile_id,  	effective_date,  	termination_date,  	email_flash,  	status";
			tdataArray["client_apps"][".sqlFrom"] = "FROM dbo.client_apps";
			tdataArray["client_apps"][".sqlWhereExpr"] = "";
			tdataArray["client_apps"][".sqlTail"] = "";
			arrGridTabs = SettingsMap.GetArray();
			arrGridTabs.Add(new XVar("tabId", "", "name", "All data", "nameType", "Text", "where", "", "showRowCount", 0, "hideEmpty", 0));
			tdataArray["client_apps"][".arrGridTabs"] = arrGridTabs;
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["client_apps"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["client_apps"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["client_apps"][".highlightSearchResults"] = true;
			tableKeysArray["client_apps"] = SettingsMap.GetArray();
			tableKeysArray["client_apps"].Add("client");
			tableKeysArray["client_apps"].Add("app");
			tdataArray["client_apps"][".Keys"] = tableKeysArray["client_apps"];
			tdataArray["client_apps"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "client";
			fdata["GoodName"] = "client";
			fdata["ownerTable"] = "dbo.client_apps";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_client_apps","client");
			fdata["FieldType"] = 202;
			fdata["strField"] = "client";
			fdata["sourceSingle"] = "client";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "client";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 2;
			edata["LookupTable"] = "dbo.clients";
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LinkField"] = "shortcode";
			edata["LinkFieldType"] = 0;
			edata["DisplayField"] = "name";
			edata["LookupOrderBy"] = "";
			edata["DependentLookups"] = SettingsMap.GetArray();
			edata["DependentLookups"].Add("profile_id");
			edata["SelectSize"] = 1;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["client_apps"]["client"] = fdata;
			tdataArray["client_apps"][".searchableFields"].Add("client");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "app";
			fdata["GoodName"] = "app";
			fdata["ownerTable"] = "dbo.client_apps";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_client_apps","app");
			fdata["FieldType"] = 202;
			fdata["strField"] = "app";
			fdata["sourceSingle"] = "app";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "app";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 2;
			edata["LookupTable"] = "dbo.apps";
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LinkField"] = "code";
			edata["LinkFieldType"] = 0;
			edata["DisplayField"] = "name";
			edata["LookupOrderBy"] = "";
			edata["DependentLookups"] = SettingsMap.GetArray();
			edata["DependentLookups"].Add("profile_id");
			edata["SelectSize"] = 1;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["client_apps"]["app"] = fdata;
			tdataArray["client_apps"][".searchableFields"].Add("app");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "active";
			fdata["GoodName"] = "active";
			fdata["ownerTable"] = "dbo.client_apps";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_client_apps","active");
			fdata["FieldType"] = 11;
			fdata["strField"] = "active";
			fdata["sourceSingle"] = "active";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "active";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Checkbox");
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Checkbox");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterFormat"] = "Options list";
			fdata["showCollapsed"] = false;
			fdata["filterCheckedMessageType"] = "Text";
			fdata["filterCheckedMessageText"] = "Checked";
			fdata["filterUncheckedMessageType"] = "Text";
			fdata["filterUncheckedMessageText"] = "Unchecked";
			tdataArray["client_apps"]["active"] = fdata;
			tdataArray["client_apps"][".searchableFields"].Add("active");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "profile_id";
			fdata["GoodName"] = "profile_id";
			fdata["ownerTable"] = "dbo.client_apps";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_client_apps","profile_id");
			fdata["FieldType"] = 202;
			fdata["strField"] = "profile_id";
			fdata["sourceSingle"] = "profile_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "profile_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 2;
			edata["LookupTable"] = "dbo.client_connections";
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LinkField"] = "profileid";
			edata["LinkFieldType"] = 0;
			edata["DisplayField"] = "profileid";
			edata["LookupOrderBy"] = "";
			edata["UseCategory"] = true;
			edata["categoryFields"] = SettingsMap.GetArray();
			edata["categoryFields"].Add(new XVar("main", "client", "lookup", "client"));
			edata["categoryFields"].Add(new XVar("main", "app", "lookup", "app"));
			edata["SelectSize"] = 1;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["client_apps"]["profile_id"] = fdata;
			tdataArray["client_apps"][".searchableFields"].Add("profile_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "effective_date";
			fdata["GoodName"] = "effective_date";
			fdata["ownerTable"] = "dbo.client_apps";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_client_apps","effective_date");
			fdata["FieldType"] = 7;
			fdata["strField"] = "effective_date";
			fdata["sourceSingle"] = "effective_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "effective_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["client_apps"]["effective_date"] = fdata;
			tdataArray["client_apps"][".searchableFields"].Add("effective_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "termination_date";
			fdata["GoodName"] = "termination_date";
			fdata["ownerTable"] = "dbo.client_apps";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_client_apps","termination_date");
			fdata["FieldType"] = 7;
			fdata["strField"] = "termination_date";
			fdata["sourceSingle"] = "termination_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "termination_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["client_apps"]["termination_date"] = fdata;
			tdataArray["client_apps"][".searchableFields"].Add("termination_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "email_flash";
			fdata["GoodName"] = "email_flash";
			fdata["ownerTable"] = "dbo.client_apps";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_client_apps","email_flash");
			fdata["FieldType"] = 202;
			fdata["strField"] = "email_flash";
			fdata["sourceSingle"] = "email_flash";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "email_flash";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 10;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=1000");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterTotalFields"] = "client";
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["client_apps"]["email_flash"] = fdata;
			tdataArray["client_apps"][".searchableFields"].Add("email_flash");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "status";
			fdata["GoodName"] = "status";
			fdata["ownerTable"] = "dbo.client_apps";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_client_apps","status");
			fdata["FieldType"] = 202;
			fdata["strField"] = "status";
			fdata["sourceSingle"] = "status";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "status";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Custom");
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 0;
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LookupValues"] = SettingsMap.GetArray();
			edata["LookupValues"].Add("Green");
			edata["LookupValues"].Add("Red");
			edata["LookupValues"].Add("Orange");
			edata["SelectSize"] = 1;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["client_apps"]["status"] = fdata;
			tdataArray["client_apps"][".searchableFields"].Add("status");
			GlobalVars.tables_data["dbo.client_apps"] = tdataArray["client_apps"];
			GlobalVars.field_labels["dbo_client_apps"] = fieldLabelsArray["client_apps"];
			GlobalVars.fieldToolTips["dbo_client_apps"] = fieldToolTipsArray["client_apps"];
			GlobalVars.placeHolders["dbo_client_apps"] = placeHoldersArray["client_apps"];
			GlobalVars.page_titles["dbo_client_apps"] = pageTitlesArray["client_apps"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.client_apps"));
			GlobalVars.detailsTablesData["dbo.client_apps"] = SettingsMap.GetArray();


			dIndex = 0;
			detailsParam = SettingsMap.GetArray();
			detailsParam["dDataSourceTable"] = "dbo.client_apps_table";
			detailsParam["dOriginalTable"] = "dbo.client_apps_table";
			detailsParam["dType"] = Constants.PAGE_LIST;
			detailsParam["dShortTable"] = "client_apps_table";
			detailsParam["dCaptionTable"] = CommonFunctions.GetTableCaption(new XVar("dbo_client_apps_table"));
			detailsParam["masterKeys"] = SettingsMap.GetArray();
			detailsParam["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex] = detailsParam;
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["masterKeys"].Add("client");
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["masterKeys"].Add("app");
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["detailKeys"].Add("client");
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["detailKeys"].Add("app");


			dIndex = 1;
			detailsParam = SettingsMap.GetArray();
			detailsParam["dDataSourceTable"] = "dbo.client_connections";
			detailsParam["dOriginalTable"] = "dbo.client_connections";
			detailsParam["dType"] = Constants.PAGE_LIST;
			detailsParam["dShortTable"] = "client_connections";
			detailsParam["dCaptionTable"] = CommonFunctions.GetTableCaption(new XVar("dbo_client_connections"));
			detailsParam["masterKeys"] = SettingsMap.GetArray();
			detailsParam["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex] = detailsParam;
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["masterKeys"].Add("profile_id");
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["detailKeys"].Add("profileid");


			dIndex = 2;
			detailsParam = SettingsMap.GetArray();
			detailsParam["dDataSourceTable"] = "dbo.hk_client_inv_items";
			detailsParam["dOriginalTable"] = "dbo.hk_client_inv_items";
			detailsParam["dType"] = Constants.PAGE_LIST;
			detailsParam["dShortTable"] = "hk_client_inv_items";
			detailsParam["dCaptionTable"] = CommonFunctions.GetTableCaption(new XVar("dbo_hk_client_inv_items"));
			detailsParam["masterKeys"] = SettingsMap.GetArray();
			detailsParam["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex] = detailsParam;
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["masterKeys"].Add("client");
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["masterKeys"].Add("app");
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["detailKeys"].Add("clientid");
			GlobalVars.detailsTablesData["dbo.client_apps"][dIndex]["detailKeys"].Add("app");
			GlobalVars.masterTablesData["dbo.client_apps"] = SettingsMap.GetArray();


			strOriginalDetailsTable = "dbo.clients";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "dbo.clients";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "clients";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo.client_apps"][0] = masterParams;
			GlobalVars.masterTablesData["dbo.client_apps"][0]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.client_apps"][0]["masterKeys"].Add("shortcode");
			GlobalVars.masterTablesData["dbo.client_apps"][0]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.client_apps"][0]["detailKeys"].Add("client");


			strOriginalDetailsTable = "dbo.apps";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "dbo.apps";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "apps";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo.client_apps"][1] = masterParams;
			GlobalVars.masterTablesData["dbo.client_apps"][1]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.client_apps"][1]["masterKeys"].Add("code");
			GlobalVars.masterTablesData["dbo.client_apps"][1]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.client_apps"][1]["detailKeys"].Add("app");


			strOriginalDetailsTable = "dbo.Clients_provisioning";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "dbo.Clients_provisioning";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "clients_provisioning";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo.client_apps"][2] = masterParams;
			GlobalVars.masterTablesData["dbo.client_apps"][2]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.client_apps"][2]["masterKeys"].Add("shortcode");
			GlobalVars.masterTablesData["dbo.client_apps"][2]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.client_apps"][2]["detailKeys"].Add("client");

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "client,  	app,  	active,  	profile_id,  	effective_date,  	termination_date,  	email_flash,  	status";
protoArray["0"]["m_strFrom"] = "FROM dbo.client_apps";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "client", "m_strTable", "dbo.client_apps", "m_srcTableName", "dbo.client_apps"));

protoArray["6"]["m_sql"] = "client";
protoArray["6"]["m_srcTableName"] = "dbo.client_apps";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "app", "m_strTable", "dbo.client_apps", "m_srcTableName", "dbo.client_apps"));

protoArray["8"]["m_sql"] = "app";
protoArray["8"]["m_srcTableName"] = "dbo.client_apps";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "active", "m_strTable", "dbo.client_apps", "m_srcTableName", "dbo.client_apps"));

protoArray["10"]["m_sql"] = "active";
protoArray["10"]["m_srcTableName"] = "dbo.client_apps";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "profile_id", "m_strTable", "dbo.client_apps", "m_srcTableName", "dbo.client_apps"));

protoArray["12"]["m_sql"] = "profile_id";
protoArray["12"]["m_srcTableName"] = "dbo.client_apps";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "effective_date", "m_strTable", "dbo.client_apps", "m_srcTableName", "dbo.client_apps"));

protoArray["14"]["m_sql"] = "effective_date";
protoArray["14"]["m_srcTableName"] = "dbo.client_apps";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "termination_date", "m_strTable", "dbo.client_apps", "m_srcTableName", "dbo.client_apps"));

protoArray["16"]["m_sql"] = "termination_date";
protoArray["16"]["m_srcTableName"] = "dbo.client_apps";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "email_flash", "m_strTable", "dbo.client_apps", "m_srcTableName", "dbo.client_apps"));

protoArray["18"]["m_sql"] = "email_flash";
protoArray["18"]["m_srcTableName"] = "dbo.client_apps";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "status", "m_strTable", "dbo.client_apps", "m_srcTableName", "dbo.client_apps"));

protoArray["20"]["m_sql"] = "status";
protoArray["20"]["m_srcTableName"] = "dbo.client_apps";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["22"] = SettingsMap.GetArray();
protoArray["22"]["m_link"] = "SQLL_MAIN";
protoArray["23"] = SettingsMap.GetArray();
protoArray["23"]["m_strName"] = "dbo.client_apps";
protoArray["23"]["m_srcTableName"] = "dbo.client_apps";
protoArray["23"]["m_columns"] = SettingsMap.GetArray();
protoArray["23"]["m_columns"].Add("client");
protoArray["23"]["m_columns"].Add("app");
protoArray["23"]["m_columns"].Add("active");
protoArray["23"]["m_columns"].Add("profile_id");
protoArray["23"]["m_columns"].Add("effective_date");
protoArray["23"]["m_columns"].Add("termination_date");
protoArray["23"]["m_columns"].Add("email_flash");
protoArray["23"]["m_columns"].Add("status");
obj = new SQLTable(protoArray["23"]);

protoArray["22"]["m_table"] = obj;
protoArray["22"]["m_sql"] = "dbo.client_apps";
protoArray["22"]["m_alias"] = "";
protoArray["22"]["m_srcTableName"] = "dbo.client_apps";
protoArray["24"] = SettingsMap.GetArray();
protoArray["24"]["m_sql"] = "";
protoArray["24"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["24"]["m_column"] = obj;
protoArray["24"]["m_contained"] = SettingsMap.GetArray();
protoArray["24"]["m_strCase"] = "";
protoArray["24"]["m_havingmode"] = false;
protoArray["24"]["m_inBrackets"] = false;
protoArray["24"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["24"]);

protoArray["22"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["22"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.client_apps";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["client_apps"] = obj;

				
		
			tdataArray["client_apps"][".sqlquery"] = queryData_Array["client_apps"];
			tdataArray["client_apps"][".hasEvents"] = false;
		}
	}

}
