using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_csi_unitcd1_mst
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["csi_unitcd1_mst"] = SettingsMap.GetArray();
			tdataArray["csi_unitcd1_mst"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["csi_unitcd1_mst"][".ShortName"] = "csi_unitcd1_mst";
			tdataArray["csi_unitcd1_mst"][".OwnerID"] = "clientid";
			tdataArray["csi_unitcd1_mst"][".OriginalTable"] = "dbo.csi_unitcd1_mst";
			tdataArray["csi_unitcd1_mst"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}"));
			tdataArray["csi_unitcd1_mst"][".originalPagesByType"] = tdataArray["csi_unitcd1_mst"][".pagesByType"];
			tdataArray["csi_unitcd1_mst"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}")));
			tdataArray["csi_unitcd1_mst"][".originalPages"] = tdataArray["csi_unitcd1_mst"][".pages"];
			tdataArray["csi_unitcd1_mst"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"export\":\"export\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\"}"));
			tdataArray["csi_unitcd1_mst"][".originalDefaultPages"] = tdataArray["csi_unitcd1_mst"][".defaultPages"];
			fieldLabelsArray["csi_unitcd1_mst"] = SettingsMap.GetArray();
			fieldToolTipsArray["csi_unitcd1_mst"] = SettingsMap.GetArray();
			pageTitlesArray["csi_unitcd1_mst"] = SettingsMap.GetArray();
			placeHoldersArray["csi_unitcd1_mst"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["csi_unitcd1_mst"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["csi_unitcd1_mst"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["csi_unitcd1_mst"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["csi_unitcd1_mst"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["clientid"] = "Clientid";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["clientid"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["clientid"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["VariationNumber"] = "Variation Number";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["VariationNumber"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["VariationNumber"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["unit1"] = "Unit1";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["unit1"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["unit1"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["site_ref"] = "Site Ref";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["site_ref"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["site_ref"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["CreateDate"] = "Create Date";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["CreateDate"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["CreateDate"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["CreatedBy"] = "Created By";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["CreatedBy"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["CreatedBy"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["description"] = "Description";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["description"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["description"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["InWorkflow"] = "In Workflow";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["InWorkflow"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["InWorkflow"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["NoteExistsFlag"] = "Note Exists Flag";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["NoteExistsFlag"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["NoteExistsFlag"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["RecordDate"] = "Record Date";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["RecordDate"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["RecordDate"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["RowPointer"] = "Row Pointer";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["RowPointer"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["RowPointer"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["UpdatedBy"] = "Updated By";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["UpdatedBy"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["UpdatedBy"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["DLDeleteIndicator"] = "DLDelete Indicator";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["DLDeleteIndicator"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["DLDeleteIndicator"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["tp_id"] = "Tp Id";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["tp_id"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["tp_id"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["tp_posted"] = "Tp Posted";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["tp_posted"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["tp_posted"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["sc_id"] = "Sc Id";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["sc_id"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["sc_id"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["sc_posted"] = "Sc Posted";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["sc_posted"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["sc_posted"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["sf_id"] = "Sf Id";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["sf_id"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["sf_id"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["sf_posted"] = "Sf Posted";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["sf_posted"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["sf_posted"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["mg_id"] = "Mg Id";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["mg_id"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["mg_id"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["mg_posted"] = "Mg Posted";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["mg_posted"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["mg_posted"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["uf_uet1"] = "Uf Uet1";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["uf_uet1"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["uf_uet1"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["uf_uet2"] = "Uf Uet2";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["uf_uet2"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["uf_uet2"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["uf_uet3"] = "Uf Uet3";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["uf_uet3"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["uf_uet3"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["uf_uet4"] = "Uf Uet4";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["uf_uet4"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["uf_uet4"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["uf_uet5"] = "Uf Uet5";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["uf_uet5"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["uf_uet5"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["uf_uet6"] = "Uf Uet6";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["uf_uet6"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["uf_uet6"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["uf_uet7"] = "Uf Uet7";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["uf_uet7"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["uf_uet7"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["uf_uet8"] = "Uf Uet8";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["uf_uet8"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["uf_uet8"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["uf_uet9"] = "Uf Uet9";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["uf_uet9"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["uf_uet9"] = "";
				fieldLabelsArray["csi_unitcd1_mst"]["English"]["uf_uet10"] = "Uf Uet10";
				fieldToolTipsArray["csi_unitcd1_mst"]["English"]["uf_uet10"] = "";
				placeHoldersArray["csi_unitcd1_mst"]["English"]["uf_uet10"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["csi_unitcd1_mst"]["English"])))
				{
					tdataArray["csi_unitcd1_mst"][".isUseToolTips"] = true;
				}
			}
			tdataArray["csi_unitcd1_mst"][".NCSearch"] = true;
			tdataArray["csi_unitcd1_mst"][".shortTableName"] = "csi_unitcd1_mst";
			tdataArray["csi_unitcd1_mst"][".nSecOptions"] = 1;
			tdataArray["csi_unitcd1_mst"][".mainTableOwnerID"] = "clientid";
			tdataArray["csi_unitcd1_mst"][".entityType"] = 0;
			tdataArray["csi_unitcd1_mst"][".connId"] = "Hubkoratec218206166241compute1";
			tdataArray["csi_unitcd1_mst"][".strOriginalTableName"] = "dbo.csi_unitcd1_mst";
			tdataArray["csi_unitcd1_mst"][".showAddInPopup"] = false;
			tdataArray["csi_unitcd1_mst"][".showEditInPopup"] = false;
			tdataArray["csi_unitcd1_mst"][".showViewInPopup"] = false;
			tdataArray["csi_unitcd1_mst"][".listAjax"] = false;
			tdataArray["csi_unitcd1_mst"][".audit"] = false;
			tdataArray["csi_unitcd1_mst"][".locking"] = false;
			GlobalVars.pages = tdataArray["csi_unitcd1_mst"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["csi_unitcd1_mst"][".edit"] = true;
				tdataArray["csi_unitcd1_mst"][".afterEditAction"] = 1;
				tdataArray["csi_unitcd1_mst"][".closePopupAfterEdit"] = 1;
				tdataArray["csi_unitcd1_mst"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["csi_unitcd1_mst"][".add"] = true;
				tdataArray["csi_unitcd1_mst"][".afterAddAction"] = 1;
				tdataArray["csi_unitcd1_mst"][".closePopupAfterAdd"] = 1;
				tdataArray["csi_unitcd1_mst"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["csi_unitcd1_mst"][".list"] = true;
			}
			tdataArray["csi_unitcd1_mst"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["csi_unitcd1_mst"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["csi_unitcd1_mst"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["csi_unitcd1_mst"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["csi_unitcd1_mst"][".printFriendly"] = true;
			}
			tdataArray["csi_unitcd1_mst"][".showSimpleSearchOptions"] = true;
			tdataArray["csi_unitcd1_mst"][".allowShowHideFields"] = true;
			tdataArray["csi_unitcd1_mst"][".allowFieldsReordering"] = true;
			tdataArray["csi_unitcd1_mst"][".isUseAjaxSuggest"] = true;


			tdataArray["csi_unitcd1_mst"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["csi_unitcd1_mst"][".buttonsAdded"] = false;
			tdataArray["csi_unitcd1_mst"][".addPageEvents"] = false;
			tdataArray["csi_unitcd1_mst"][".isUseTimeForSearch"] = false;
			tdataArray["csi_unitcd1_mst"][".badgeColor"] = "6493EA";
			tdataArray["csi_unitcd1_mst"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["csi_unitcd1_mst"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["csi_unitcd1_mst"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("clientid");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("VariationNumber");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("unit1");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("site_ref");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("CreateDate");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("CreatedBy");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("description");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("InWorkflow");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("NoteExistsFlag");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("RecordDate");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("RowPointer");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("UpdatedBy");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("DLDeleteIndicator");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("tp_id");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("tp_posted");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("sc_id");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("sc_posted");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("sf_id");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("sf_posted");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("mg_id");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("mg_posted");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("uf_uet1");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("uf_uet2");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("uf_uet3");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("uf_uet4");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("uf_uet5");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("uf_uet6");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("uf_uet7");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("uf_uet8");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("uf_uet9");
			tdataArray["csi_unitcd1_mst"][".googleLikeFields"].Add("uf_uet10");
			tdataArray["csi_unitcd1_mst"][".tableType"] = "list";
			tdataArray["csi_unitcd1_mst"][".printerPageOrientation"] = 0;
			tdataArray["csi_unitcd1_mst"][".nPrinterPageScale"] = 100;
			tdataArray["csi_unitcd1_mst"][".nPrinterSplitRecords"] = 40;
			tdataArray["csi_unitcd1_mst"][".geocodingEnabled"] = false;
			tdataArray["csi_unitcd1_mst"][".pageSize"] = 20;
			tdataArray["csi_unitcd1_mst"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["csi_unitcd1_mst"][".strOrderBy"] = tstrOrderBy;
			tdataArray["csi_unitcd1_mst"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["csi_unitcd1_mst"][".sqlHead"] = "SELECT clientid,  	VariationNumber,  	unit1,  	site_ref,  	CreateDate,  	CreatedBy,  	description,  	InWorkflow,  	NoteExistsFlag,  	RecordDate,  	RowPointer,  	UpdatedBy,  	DLDeleteIndicator,  	tp_id,  	tp_posted,  	sc_id,  	sc_posted,  	sf_id,  	sf_posted,  	mg_id,  	mg_posted,  	uf_uet1,  	uf_uet2,  	uf_uet3,  	uf_uet4,  	uf_uet5,  	uf_uet6,  	uf_uet7,  	uf_uet8,  	uf_uet9,  	uf_uet10";
			tdataArray["csi_unitcd1_mst"][".sqlFrom"] = "FROM dbo.csi_unitcd1_mst";
			tdataArray["csi_unitcd1_mst"][".sqlWhereExpr"] = "";
			tdataArray["csi_unitcd1_mst"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["csi_unitcd1_mst"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["csi_unitcd1_mst"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["csi_unitcd1_mst"][".highlightSearchResults"] = true;
			tableKeysArray["csi_unitcd1_mst"] = SettingsMap.GetArray();
			tableKeysArray["csi_unitcd1_mst"].Add("RowPointer");
			tdataArray["csi_unitcd1_mst"][".Keys"] = tableKeysArray["csi_unitcd1_mst"];
			tdataArray["csi_unitcd1_mst"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "clientid";
			fdata["GoodName"] = "clientid";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","clientid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "clientid";
			fdata["sourceSingle"] = "clientid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "clientid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["clientid"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("clientid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "VariationNumber";
			fdata["GoodName"] = "VariationNumber";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","VariationNumber");
			fdata["FieldType"] = 20;
			fdata["strField"] = "VariationNumber";
			fdata["sourceSingle"] = "VariationNumber";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "VariationNumber";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["VariationNumber"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("VariationNumber");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "unit1";
			fdata["GoodName"] = "unit1";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","unit1");
			fdata["FieldType"] = 202;
			fdata["strField"] = "unit1";
			fdata["sourceSingle"] = "unit1";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "unit1";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=4");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["unit1"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("unit1");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "site_ref";
			fdata["GoodName"] = "site_ref";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","site_ref");
			fdata["FieldType"] = 202;
			fdata["strField"] = "site_ref";
			fdata["sourceSingle"] = "site_ref";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "site_ref";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=8");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["site_ref"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("site_ref");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "CreateDate";
			fdata["GoodName"] = "CreateDate";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","CreateDate");
			fdata["FieldType"] = 135;
			fdata["strField"] = "CreateDate";
			fdata["sourceSingle"] = "CreateDate";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "CreateDate";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["CreateDate"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("CreateDate");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "CreatedBy";
			fdata["GoodName"] = "CreatedBy";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","CreatedBy");
			fdata["FieldType"] = 202;
			fdata["strField"] = "CreatedBy";
			fdata["sourceSingle"] = "CreatedBy";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "CreatedBy";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=128");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["CreatedBy"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("CreatedBy");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "description";
			fdata["GoodName"] = "description";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","description");
			fdata["FieldType"] = 202;
			fdata["strField"] = "description";
			fdata["sourceSingle"] = "description";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "description";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=40");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["description"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("description");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "InWorkflow";
			fdata["GoodName"] = "InWorkflow";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","InWorkflow");
			fdata["FieldType"] = 20;
			fdata["strField"] = "InWorkflow";
			fdata["sourceSingle"] = "InWorkflow";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "InWorkflow";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["InWorkflow"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("InWorkflow");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "NoteExistsFlag";
			fdata["GoodName"] = "NoteExistsFlag";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","NoteExistsFlag");
			fdata["FieldType"] = 20;
			fdata["strField"] = "NoteExistsFlag";
			fdata["sourceSingle"] = "NoteExistsFlag";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "NoteExistsFlag";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["NoteExistsFlag"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("NoteExistsFlag");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "RecordDate";
			fdata["GoodName"] = "RecordDate";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","RecordDate");
			fdata["FieldType"] = 135;
			fdata["strField"] = "RecordDate";
			fdata["sourceSingle"] = "RecordDate";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "RecordDate";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["RecordDate"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("RecordDate");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "RowPointer";
			fdata["GoodName"] = "RowPointer";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","RowPointer");
			fdata["FieldType"] = 202;
			fdata["strField"] = "RowPointer";
			fdata["sourceSingle"] = "RowPointer";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "RowPointer";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=36");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["RowPointer"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("RowPointer");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "UpdatedBy";
			fdata["GoodName"] = "UpdatedBy";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","UpdatedBy");
			fdata["FieldType"] = 202;
			fdata["strField"] = "UpdatedBy";
			fdata["sourceSingle"] = "UpdatedBy";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "UpdatedBy";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=128");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["UpdatedBy"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("UpdatedBy");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "DLDeleteIndicator";
			fdata["GoodName"] = "DLDeleteIndicator";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","DLDeleteIndicator");
			fdata["FieldType"] = 20;
			fdata["strField"] = "DLDeleteIndicator";
			fdata["sourceSingle"] = "DLDeleteIndicator";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "DLDeleteIndicator";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["DLDeleteIndicator"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("DLDeleteIndicator");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 14;
			fdata["strName"] = "tp_id";
			fdata["GoodName"] = "tp_id";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","tp_id");
			fdata["FieldType"] = 202;
			fdata["strField"] = "tp_id";
			fdata["sourceSingle"] = "tp_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "tp_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["tp_id"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("tp_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 15;
			fdata["strName"] = "tp_posted";
			fdata["GoodName"] = "tp_posted";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","tp_posted");
			fdata["FieldType"] = 16;
			fdata["strField"] = "tp_posted";
			fdata["sourceSingle"] = "tp_posted";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "tp_posted";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["tp_posted"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("tp_posted");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 16;
			fdata["strName"] = "sc_id";
			fdata["GoodName"] = "sc_id";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","sc_id");
			fdata["FieldType"] = 202;
			fdata["strField"] = "sc_id";
			fdata["sourceSingle"] = "sc_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "sc_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["sc_id"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("sc_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 17;
			fdata["strName"] = "sc_posted";
			fdata["GoodName"] = "sc_posted";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","sc_posted");
			fdata["FieldType"] = 16;
			fdata["strField"] = "sc_posted";
			fdata["sourceSingle"] = "sc_posted";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "sc_posted";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["sc_posted"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("sc_posted");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 18;
			fdata["strName"] = "sf_id";
			fdata["GoodName"] = "sf_id";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","sf_id");
			fdata["FieldType"] = 202;
			fdata["strField"] = "sf_id";
			fdata["sourceSingle"] = "sf_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "sf_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["sf_id"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("sf_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 19;
			fdata["strName"] = "sf_posted";
			fdata["GoodName"] = "sf_posted";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","sf_posted");
			fdata["FieldType"] = 16;
			fdata["strField"] = "sf_posted";
			fdata["sourceSingle"] = "sf_posted";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "sf_posted";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["sf_posted"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("sf_posted");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 20;
			fdata["strName"] = "mg_id";
			fdata["GoodName"] = "mg_id";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","mg_id");
			fdata["FieldType"] = 202;
			fdata["strField"] = "mg_id";
			fdata["sourceSingle"] = "mg_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "mg_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["mg_id"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("mg_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 21;
			fdata["strName"] = "mg_posted";
			fdata["GoodName"] = "mg_posted";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","mg_posted");
			fdata["FieldType"] = 16;
			fdata["strField"] = "mg_posted";
			fdata["sourceSingle"] = "mg_posted";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "mg_posted";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["mg_posted"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("mg_posted");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 22;
			fdata["strName"] = "uf_uet1";
			fdata["GoodName"] = "uf_uet1";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","uf_uet1");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet1";
			fdata["sourceSingle"] = "uf_uet1";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet1";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["uf_uet1"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("uf_uet1");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 23;
			fdata["strName"] = "uf_uet2";
			fdata["GoodName"] = "uf_uet2";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","uf_uet2");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet2";
			fdata["sourceSingle"] = "uf_uet2";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet2";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["uf_uet2"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("uf_uet2");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 24;
			fdata["strName"] = "uf_uet3";
			fdata["GoodName"] = "uf_uet3";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","uf_uet3");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet3";
			fdata["sourceSingle"] = "uf_uet3";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet3";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["uf_uet3"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("uf_uet3");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 25;
			fdata["strName"] = "uf_uet4";
			fdata["GoodName"] = "uf_uet4";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","uf_uet4");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet4";
			fdata["sourceSingle"] = "uf_uet4";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet4";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["uf_uet4"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("uf_uet4");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 26;
			fdata["strName"] = "uf_uet5";
			fdata["GoodName"] = "uf_uet5";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","uf_uet5");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet5";
			fdata["sourceSingle"] = "uf_uet5";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet5";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["uf_uet5"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("uf_uet5");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 27;
			fdata["strName"] = "uf_uet6";
			fdata["GoodName"] = "uf_uet6";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","uf_uet6");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet6";
			fdata["sourceSingle"] = "uf_uet6";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet6";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["uf_uet6"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("uf_uet6");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 28;
			fdata["strName"] = "uf_uet7";
			fdata["GoodName"] = "uf_uet7";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","uf_uet7");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet7";
			fdata["sourceSingle"] = "uf_uet7";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet7";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["uf_uet7"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("uf_uet7");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 29;
			fdata["strName"] = "uf_uet8";
			fdata["GoodName"] = "uf_uet8";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","uf_uet8");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet8";
			fdata["sourceSingle"] = "uf_uet8";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet8";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["uf_uet8"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("uf_uet8");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 30;
			fdata["strName"] = "uf_uet9";
			fdata["GoodName"] = "uf_uet9";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","uf_uet9");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet9";
			fdata["sourceSingle"] = "uf_uet9";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet9";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["uf_uet9"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("uf_uet9");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 31;
			fdata["strName"] = "uf_uet10";
			fdata["GoodName"] = "uf_uet10";
			fdata["ownerTable"] = "dbo.csi_unitcd1_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_unitcd1_mst","uf_uet10");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet10";
			fdata["sourceSingle"] = "uf_uet10";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet10";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_unitcd1_mst"]["uf_uet10"] = fdata;
			tdataArray["csi_unitcd1_mst"][".searchableFields"].Add("uf_uet10");
			GlobalVars.tables_data["dbo.csi_unitcd1_mst"] = tdataArray["csi_unitcd1_mst"];
			GlobalVars.field_labels["dbo_csi_unitcd1_mst"] = fieldLabelsArray["csi_unitcd1_mst"];
			GlobalVars.fieldToolTips["dbo_csi_unitcd1_mst"] = fieldToolTipsArray["csi_unitcd1_mst"];
			GlobalVars.placeHolders["dbo_csi_unitcd1_mst"] = placeHoldersArray["csi_unitcd1_mst"];
			GlobalVars.page_titles["dbo_csi_unitcd1_mst"] = pageTitlesArray["csi_unitcd1_mst"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.csi_unitcd1_mst"));
			GlobalVars.detailsTablesData["dbo.csi_unitcd1_mst"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.csi_unitcd1_mst"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "clientid,  	VariationNumber,  	unit1,  	site_ref,  	CreateDate,  	CreatedBy,  	description,  	InWorkflow,  	NoteExistsFlag,  	RecordDate,  	RowPointer,  	UpdatedBy,  	DLDeleteIndicator,  	tp_id,  	tp_posted,  	sc_id,  	sc_posted,  	sf_id,  	sf_posted,  	mg_id,  	mg_posted,  	uf_uet1,  	uf_uet2,  	uf_uet3,  	uf_uet4,  	uf_uet5,  	uf_uet6,  	uf_uet7,  	uf_uet8,  	uf_uet9,  	uf_uet10";
protoArray["0"]["m_strFrom"] = "FROM dbo.csi_unitcd1_mst";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "clientid", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["6"]["m_sql"] = "clientid";
protoArray["6"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "VariationNumber", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["8"]["m_sql"] = "VariationNumber";
protoArray["8"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "unit1", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["10"]["m_sql"] = "unit1";
protoArray["10"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "site_ref", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["12"]["m_sql"] = "site_ref";
protoArray["12"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "CreateDate", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["14"]["m_sql"] = "CreateDate";
protoArray["14"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "CreatedBy", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["16"]["m_sql"] = "CreatedBy";
protoArray["16"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "description", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["18"]["m_sql"] = "description";
protoArray["18"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "InWorkflow", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["20"]["m_sql"] = "InWorkflow";
protoArray["20"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "NoteExistsFlag", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["22"]["m_sql"] = "NoteExistsFlag";
protoArray["22"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "RecordDate", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["24"]["m_sql"] = "RecordDate";
protoArray["24"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "RowPointer", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["26"]["m_sql"] = "RowPointer";
protoArray["26"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "UpdatedBy", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["28"]["m_sql"] = "UpdatedBy";
protoArray["28"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "DLDeleteIndicator", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["30"]["m_sql"] = "DLDeleteIndicator";
protoArray["30"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["32"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "tp_id", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["32"]["m_sql"] = "tp_id";
protoArray["32"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["32"]["m_expr"] = obj;
protoArray["32"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["32"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["34"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "tp_posted", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["34"]["m_sql"] = "tp_posted";
protoArray["34"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["34"]["m_expr"] = obj;
protoArray["34"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["34"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["36"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "sc_id", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["36"]["m_sql"] = "sc_id";
protoArray["36"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["36"]["m_expr"] = obj;
protoArray["36"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["36"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["38"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "sc_posted", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["38"]["m_sql"] = "sc_posted";
protoArray["38"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["38"]["m_expr"] = obj;
protoArray["38"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["38"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["40"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "sf_id", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["40"]["m_sql"] = "sf_id";
protoArray["40"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["40"]["m_expr"] = obj;
protoArray["40"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["40"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["42"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "sf_posted", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["42"]["m_sql"] = "sf_posted";
protoArray["42"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["42"]["m_expr"] = obj;
protoArray["42"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["42"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["44"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "mg_id", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["44"]["m_sql"] = "mg_id";
protoArray["44"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["44"]["m_expr"] = obj;
protoArray["44"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["44"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["46"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "mg_posted", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["46"]["m_sql"] = "mg_posted";
protoArray["46"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["46"]["m_expr"] = obj;
protoArray["46"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["46"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["48"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet1", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["48"]["m_sql"] = "uf_uet1";
protoArray["48"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["48"]["m_expr"] = obj;
protoArray["48"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["48"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["50"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet2", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["50"]["m_sql"] = "uf_uet2";
protoArray["50"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["50"]["m_expr"] = obj;
protoArray["50"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["50"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["52"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet3", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["52"]["m_sql"] = "uf_uet3";
protoArray["52"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["52"]["m_expr"] = obj;
protoArray["52"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["52"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["54"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet4", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["54"]["m_sql"] = "uf_uet4";
protoArray["54"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["54"]["m_expr"] = obj;
protoArray["54"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["54"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["56"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet5", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["56"]["m_sql"] = "uf_uet5";
protoArray["56"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["56"]["m_expr"] = obj;
protoArray["56"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["56"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["58"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet6", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["58"]["m_sql"] = "uf_uet6";
protoArray["58"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["58"]["m_expr"] = obj;
protoArray["58"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["58"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["60"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet7", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["60"]["m_sql"] = "uf_uet7";
protoArray["60"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["60"]["m_expr"] = obj;
protoArray["60"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["60"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["62"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet8", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["62"]["m_sql"] = "uf_uet8";
protoArray["62"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["62"]["m_expr"] = obj;
protoArray["62"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["62"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["64"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet9", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["64"]["m_sql"] = "uf_uet9";
protoArray["64"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["64"]["m_expr"] = obj;
protoArray["64"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["64"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["66"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet10", "m_strTable", "dbo.csi_unitcd1_mst", "m_srcTableName", "dbo.csi_unitcd1_mst"));

protoArray["66"]["m_sql"] = "uf_uet10";
protoArray["66"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["66"]["m_expr"] = obj;
protoArray["66"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["66"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["68"] = SettingsMap.GetArray();
protoArray["68"]["m_link"] = "SQLL_MAIN";
protoArray["69"] = SettingsMap.GetArray();
protoArray["69"]["m_strName"] = "dbo.csi_unitcd1_mst";
protoArray["69"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["69"]["m_columns"] = SettingsMap.GetArray();
protoArray["69"]["m_columns"].Add("clientid");
protoArray["69"]["m_columns"].Add("VariationNumber");
protoArray["69"]["m_columns"].Add("unit1");
protoArray["69"]["m_columns"].Add("site_ref");
protoArray["69"]["m_columns"].Add("CreateDate");
protoArray["69"]["m_columns"].Add("CreatedBy");
protoArray["69"]["m_columns"].Add("description");
protoArray["69"]["m_columns"].Add("InWorkflow");
protoArray["69"]["m_columns"].Add("NoteExistsFlag");
protoArray["69"]["m_columns"].Add("RecordDate");
protoArray["69"]["m_columns"].Add("RowPointer");
protoArray["69"]["m_columns"].Add("UpdatedBy");
protoArray["69"]["m_columns"].Add("DLDeleteIndicator");
protoArray["69"]["m_columns"].Add("tp_id");
protoArray["69"]["m_columns"].Add("tp_posted");
protoArray["69"]["m_columns"].Add("sc_id");
protoArray["69"]["m_columns"].Add("sc_posted");
protoArray["69"]["m_columns"].Add("sf_id");
protoArray["69"]["m_columns"].Add("sf_posted");
protoArray["69"]["m_columns"].Add("mg_id");
protoArray["69"]["m_columns"].Add("mg_posted");
protoArray["69"]["m_columns"].Add("uf_uet1");
protoArray["69"]["m_columns"].Add("uf_uet2");
protoArray["69"]["m_columns"].Add("uf_uet3");
protoArray["69"]["m_columns"].Add("uf_uet4");
protoArray["69"]["m_columns"].Add("uf_uet5");
protoArray["69"]["m_columns"].Add("uf_uet6");
protoArray["69"]["m_columns"].Add("uf_uet7");
protoArray["69"]["m_columns"].Add("uf_uet8");
protoArray["69"]["m_columns"].Add("uf_uet9");
protoArray["69"]["m_columns"].Add("uf_uet10");
obj = new SQLTable(protoArray["69"]);

protoArray["68"]["m_table"] = obj;
protoArray["68"]["m_sql"] = "dbo.csi_unitcd1_mst";
protoArray["68"]["m_alias"] = "";
protoArray["68"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
protoArray["70"] = SettingsMap.GetArray();
protoArray["70"]["m_sql"] = "";
protoArray["70"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["70"]["m_column"] = obj;
protoArray["70"]["m_contained"] = SettingsMap.GetArray();
protoArray["70"]["m_strCase"] = "";
protoArray["70"]["m_havingmode"] = false;
protoArray["70"]["m_inBrackets"] = false;
protoArray["70"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["70"]);

protoArray["68"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["68"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.csi_unitcd1_mst";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["csi_unitcd1_mst"] = obj;

				
		
			tdataArray["csi_unitcd1_mst"][".sqlquery"] = queryData_Array["csi_unitcd1_mst"];
			tdataArray["csi_unitcd1_mst"][".hasEvents"] = false;
		}
	}

}
