using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_csi_site_mst
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["csi_site_mst"] = SettingsMap.GetArray();
			tdataArray["csi_site_mst"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["csi_site_mst"][".ShortName"] = "csi_site_mst";
			tdataArray["csi_site_mst"][".OwnerID"] = "";
			tdataArray["csi_site_mst"][".OriginalTable"] = "dbo.csi_site_mst";
			tdataArray["csi_site_mst"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}"));
			tdataArray["csi_site_mst"][".originalPagesByType"] = tdataArray["csi_site_mst"][".pagesByType"];
			tdataArray["csi_site_mst"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}")));
			tdataArray["csi_site_mst"][".originalPages"] = tdataArray["csi_site_mst"][".pages"];
			tdataArray["csi_site_mst"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\"}"));
			tdataArray["csi_site_mst"][".originalDefaultPages"] = tdataArray["csi_site_mst"][".defaultPages"];
			fieldLabelsArray["csi_site_mst"] = SettingsMap.GetArray();
			fieldToolTipsArray["csi_site_mst"] = SettingsMap.GetArray();
			pageTitlesArray["csi_site_mst"] = SettingsMap.GetArray();
			placeHoldersArray["csi_site_mst"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["csi_site_mst"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["csi_site_mst"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["csi_site_mst"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["csi_site_mst"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["csi_site_mst"]["English"]["clientid"] = "Clientid";
				fieldToolTipsArray["csi_site_mst"]["English"]["clientid"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["clientid"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["site_ref"] = "Site Ref";
				fieldToolTipsArray["csi_site_mst"]["English"]["site_ref"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["site_ref"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["tp_payer_entity_name"] = "Tp Payer Entity Name";
				fieldToolTipsArray["csi_site_mst"]["English"]["tp_payer_entity_name"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["tp_payer_entity_name"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["RowPointer"] = "Row Pointer";
				fieldToolTipsArray["csi_site_mst"]["English"]["RowPointer"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["RowPointer"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["VariationNumber"] = "Variation Number";
				fieldToolTipsArray["csi_site_mst"]["English"]["VariationNumber"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["VariationNumber"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["uf_uet1"] = "Uf Uet1";
				fieldToolTipsArray["csi_site_mst"]["English"]["uf_uet1"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["uf_uet1"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["uf_uet2"] = "Uf Uet2";
				fieldToolTipsArray["csi_site_mst"]["English"]["uf_uet2"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["uf_uet2"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["uf_uet3"] = "Uf Uet3";
				fieldToolTipsArray["csi_site_mst"]["English"]["uf_uet3"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["uf_uet3"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["uf_uet4"] = "Uf Uet4";
				fieldToolTipsArray["csi_site_mst"]["English"]["uf_uet4"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["uf_uet4"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["uf_uet5"] = "Uf Uet5";
				fieldToolTipsArray["csi_site_mst"]["English"]["uf_uet5"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["uf_uet5"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["uf_uet6"] = "Uf Uet6";
				fieldToolTipsArray["csi_site_mst"]["English"]["uf_uet6"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["uf_uet6"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["uf_uet7"] = "Uf Uet7";
				fieldToolTipsArray["csi_site_mst"]["English"]["uf_uet7"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["uf_uet7"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["uf_uet8"] = "Uf Uet8";
				fieldToolTipsArray["csi_site_mst"]["English"]["uf_uet8"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["uf_uet8"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["uf_uet9"] = "Uf Uet9";
				fieldToolTipsArray["csi_site_mst"]["English"]["uf_uet9"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["uf_uet9"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["uf_uet10"] = "Uf Uet10";
				fieldToolTipsArray["csi_site_mst"]["English"]["uf_uet10"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["uf_uet10"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["tp_bankcode"] = "Tp Bankcode";
				fieldToolTipsArray["csi_site_mst"]["English"]["tp_bankcode"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["tp_bankcode"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["sf_entity_name"] = "Sf Entity Name";
				fieldToolTipsArray["csi_site_mst"]["English"]["sf_entity_name"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["sf_entity_name"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["site_prefix"] = "Site Prefix";
				fieldToolTipsArray["csi_site_mst"]["English"]["site_prefix"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["site_prefix"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["mg_whse"] = "Mg Whse";
				fieldToolTipsArray["csi_site_mst"]["English"]["mg_whse"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["mg_whse"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["mg_quest_vend_num"] = "Mg Quest Vend Num";
				fieldToolTipsArray["csi_site_mst"]["English"]["mg_quest_vend_num"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["mg_quest_vend_num"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["sc_entity_name"] = "Sc Entity Name";
				fieldToolTipsArray["csi_site_mst"]["English"]["sc_entity_name"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["sc_entity_name"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["tp_active"] = "Tp Active";
				fieldToolTipsArray["csi_site_mst"]["English"]["tp_active"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["tp_active"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["tp_vend_stat_pre"] = "Tp Vend Stat Pre";
				fieldToolTipsArray["csi_site_mst"]["English"]["tp_vend_stat_pre"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["tp_vend_stat_pre"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["tp_vend_stat_post"] = "Tp Vend Stat Post";
				fieldToolTipsArray["csi_site_mst"]["English"]["tp_vend_stat_post"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["tp_vend_stat_post"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["tp_vend_post_to_sl"] = "Tp Vend Post To Sl";
				fieldToolTipsArray["csi_site_mst"]["English"]["tp_vend_post_to_sl"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["tp_vend_post_to_sl"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["exp_entity_name"] = "Exp Entity Name";
				fieldToolTipsArray["csi_site_mst"]["English"]["exp_entity_name"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["exp_entity_name"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["exp_journal"] = "Exp Journal";
				fieldToolTipsArray["csi_site_mst"]["English"]["exp_journal"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["exp_journal"] = "";
				fieldLabelsArray["csi_site_mst"]["English"]["tp_lc_active"] = "Tp Lc Active";
				fieldToolTipsArray["csi_site_mst"]["English"]["tp_lc_active"] = "";
				placeHoldersArray["csi_site_mst"]["English"]["tp_lc_active"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["csi_site_mst"]["English"])))
				{
					tdataArray["csi_site_mst"][".isUseToolTips"] = true;
				}
			}
			tdataArray["csi_site_mst"][".NCSearch"] = true;
			tdataArray["csi_site_mst"][".shortTableName"] = "csi_site_mst";
			tdataArray["csi_site_mst"][".nSecOptions"] = 0;
			tdataArray["csi_site_mst"][".mainTableOwnerID"] = "";
			tdataArray["csi_site_mst"][".entityType"] = 0;
			tdataArray["csi_site_mst"][".connId"] = "Hubkoratec218206166241compute1";
			tdataArray["csi_site_mst"][".strOriginalTableName"] = "dbo.csi_site_mst";
			tdataArray["csi_site_mst"][".showAddInPopup"] = false;
			tdataArray["csi_site_mst"][".showEditInPopup"] = false;
			tdataArray["csi_site_mst"][".showViewInPopup"] = false;
			tdataArray["csi_site_mst"][".listAjax"] = false;
			tdataArray["csi_site_mst"][".audit"] = true;
			tdataArray["csi_site_mst"][".locking"] = false;
			GlobalVars.pages = tdataArray["csi_site_mst"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["csi_site_mst"][".edit"] = true;
				tdataArray["csi_site_mst"][".afterEditAction"] = 1;
				tdataArray["csi_site_mst"][".closePopupAfterEdit"] = 1;
				tdataArray["csi_site_mst"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["csi_site_mst"][".add"] = true;
				tdataArray["csi_site_mst"][".afterAddAction"] = 1;
				tdataArray["csi_site_mst"][".closePopupAfterAdd"] = 1;
				tdataArray["csi_site_mst"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["csi_site_mst"][".list"] = true;
			}
			tdataArray["csi_site_mst"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["csi_site_mst"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["csi_site_mst"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["csi_site_mst"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["csi_site_mst"][".printFriendly"] = true;
			}
			tdataArray["csi_site_mst"][".showSimpleSearchOptions"] = true;
			tdataArray["csi_site_mst"][".allowShowHideFields"] = true;
			tdataArray["csi_site_mst"][".allowFieldsReordering"] = true;
			tdataArray["csi_site_mst"][".isUseAjaxSuggest"] = true;


			tdataArray["csi_site_mst"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["csi_site_mst"][".buttonsAdded"] = false;
			tdataArray["csi_site_mst"][".addPageEvents"] = false;
			tdataArray["csi_site_mst"][".isUseTimeForSearch"] = false;
			tdataArray["csi_site_mst"][".badgeColor"] = "6493ea";
			tdataArray["csi_site_mst"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["csi_site_mst"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["csi_site_mst"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["csi_site_mst"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("clientid");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("site_ref");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("tp_payer_entity_name");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("RowPointer");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("VariationNumber");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("uf_uet1");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("uf_uet2");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("uf_uet3");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("uf_uet4");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("uf_uet5");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("uf_uet6");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("uf_uet7");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("uf_uet8");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("uf_uet9");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("uf_uet10");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("tp_bankcode");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("sf_entity_name");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("site_prefix");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("mg_whse");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("mg_quest_vend_num");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("sc_entity_name");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("exp_entity_name");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("exp_journal");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("tp_active");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("tp_vend_stat_pre");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("tp_vend_stat_post");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("tp_vend_post_to_sl");
			tdataArray["csi_site_mst"][".googleLikeFields"].Add("tp_lc_active");
			tdataArray["csi_site_mst"][".tableType"] = "list";
			tdataArray["csi_site_mst"][".printerPageOrientation"] = 0;
			tdataArray["csi_site_mst"][".nPrinterPageScale"] = 100;
			tdataArray["csi_site_mst"][".nPrinterSplitRecords"] = 40;
			tdataArray["csi_site_mst"][".geocodingEnabled"] = false;
			tdataArray["csi_site_mst"][".pageSize"] = 20;
			tdataArray["csi_site_mst"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["csi_site_mst"][".strOrderBy"] = tstrOrderBy;
			tdataArray["csi_site_mst"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["csi_site_mst"][".sqlHead"] = "SELECT clientid,  	site_ref,  	tp_payer_entity_name,  	RowPointer,  	VariationNumber,  	uf_uet1,  	uf_uet2,  	uf_uet3,  	uf_uet4,  	uf_uet5,  	uf_uet6,  	uf_uet7,  	uf_uet8,  	uf_uet9,  	uf_uet10,  	tp_bankcode,  	sf_entity_name,  	site_prefix,  	mg_whse,  	mg_quest_vend_num,  	sc_entity_name,  	exp_entity_name,  	exp_journal,  	tp_active,  	tp_vend_stat_pre,  	tp_vend_stat_post,  	tp_vend_post_to_sl,  	tp_lc_active";
			tdataArray["csi_site_mst"][".sqlFrom"] = "FROM dbo.csi_site_mst";
			tdataArray["csi_site_mst"][".sqlWhereExpr"] = "";
			tdataArray["csi_site_mst"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["csi_site_mst"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["csi_site_mst"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["csi_site_mst"][".highlightSearchResults"] = true;
			tableKeysArray["csi_site_mst"] = SettingsMap.GetArray();
			tableKeysArray["csi_site_mst"].Add("clientid");
			tableKeysArray["csi_site_mst"].Add("site_ref");
			tdataArray["csi_site_mst"][".Keys"] = tableKeysArray["csi_site_mst"];
			tdataArray["csi_site_mst"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "clientid";
			fdata["GoodName"] = "clientid";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","clientid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "clientid";
			fdata["sourceSingle"] = "clientid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "clientid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["clientid"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("clientid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "site_ref";
			fdata["GoodName"] = "site_ref";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","site_ref");
			fdata["FieldType"] = 202;
			fdata["strField"] = "site_ref";
			fdata["sourceSingle"] = "site_ref";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "site_ref";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=40");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["site_ref"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("site_ref");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "tp_payer_entity_name";
			fdata["GoodName"] = "tp_payer_entity_name";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","tp_payer_entity_name");
			fdata["FieldType"] = 202;
			fdata["strField"] = "tp_payer_entity_name";
			fdata["sourceSingle"] = "tp_payer_entity_name";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "tp_payer_entity_name";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["tp_payer_entity_name"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("tp_payer_entity_name");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "RowPointer";
			fdata["GoodName"] = "RowPointer";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","RowPointer");
			fdata["FieldType"] = 72;
			fdata["strField"] = "RowPointer";
			fdata["sourceSingle"] = "RowPointer";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "RowPointer";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["RowPointer"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("RowPointer");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "VariationNumber";
			fdata["GoodName"] = "VariationNumber";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","VariationNumber");
			fdata["FieldType"] = 20;
			fdata["strField"] = "VariationNumber";
			fdata["sourceSingle"] = "VariationNumber";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "VariationNumber";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["VariationNumber"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("VariationNumber");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "uf_uet1";
			fdata["GoodName"] = "uf_uet1";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","uf_uet1");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet1";
			fdata["sourceSingle"] = "uf_uet1";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet1";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["uf_uet1"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("uf_uet1");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "uf_uet2";
			fdata["GoodName"] = "uf_uet2";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","uf_uet2");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet2";
			fdata["sourceSingle"] = "uf_uet2";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet2";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["uf_uet2"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("uf_uet2");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "uf_uet3";
			fdata["GoodName"] = "uf_uet3";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","uf_uet3");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet3";
			fdata["sourceSingle"] = "uf_uet3";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet3";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["uf_uet3"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("uf_uet3");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "uf_uet4";
			fdata["GoodName"] = "uf_uet4";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","uf_uet4");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet4";
			fdata["sourceSingle"] = "uf_uet4";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet4";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["uf_uet4"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("uf_uet4");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "uf_uet5";
			fdata["GoodName"] = "uf_uet5";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","uf_uet5");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet5";
			fdata["sourceSingle"] = "uf_uet5";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet5";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["uf_uet5"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("uf_uet5");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "uf_uet6";
			fdata["GoodName"] = "uf_uet6";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","uf_uet6");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet6";
			fdata["sourceSingle"] = "uf_uet6";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet6";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["uf_uet6"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("uf_uet6");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "uf_uet7";
			fdata["GoodName"] = "uf_uet7";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","uf_uet7");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet7";
			fdata["sourceSingle"] = "uf_uet7";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet7";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["uf_uet7"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("uf_uet7");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "uf_uet8";
			fdata["GoodName"] = "uf_uet8";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","uf_uet8");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet8";
			fdata["sourceSingle"] = "uf_uet8";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet8";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["uf_uet8"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("uf_uet8");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 14;
			fdata["strName"] = "uf_uet9";
			fdata["GoodName"] = "uf_uet9";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","uf_uet9");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet9";
			fdata["sourceSingle"] = "uf_uet9";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet9";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["uf_uet9"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("uf_uet9");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 15;
			fdata["strName"] = "uf_uet10";
			fdata["GoodName"] = "uf_uet10";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","uf_uet10");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uf_uet10";
			fdata["sourceSingle"] = "uf_uet10";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uf_uet10";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["uf_uet10"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("uf_uet10");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 16;
			fdata["strName"] = "tp_bankcode";
			fdata["GoodName"] = "tp_bankcode";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","tp_bankcode");
			fdata["FieldType"] = 202;
			fdata["strField"] = "tp_bankcode";
			fdata["sourceSingle"] = "tp_bankcode";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "tp_bankcode";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["tp_bankcode"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("tp_bankcode");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 17;
			fdata["strName"] = "sf_entity_name";
			fdata["GoodName"] = "sf_entity_name";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","sf_entity_name");
			fdata["FieldType"] = 202;
			fdata["strField"] = "sf_entity_name";
			fdata["sourceSingle"] = "sf_entity_name";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "sf_entity_name";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=120");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["sf_entity_name"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("sf_entity_name");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 18;
			fdata["strName"] = "site_prefix";
			fdata["GoodName"] = "site_prefix";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","site_prefix");
			fdata["FieldType"] = 202;
			fdata["strField"] = "site_prefix";
			fdata["sourceSingle"] = "site_prefix";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "site_prefix";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=5");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["site_prefix"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("site_prefix");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 19;
			fdata["strName"] = "mg_whse";
			fdata["GoodName"] = "mg_whse";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","mg_whse");
			fdata["FieldType"] = 202;
			fdata["strField"] = "mg_whse";
			fdata["sourceSingle"] = "mg_whse";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "mg_whse";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["mg_whse"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("mg_whse");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 20;
			fdata["strName"] = "mg_quest_vend_num";
			fdata["GoodName"] = "mg_quest_vend_num";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","mg_quest_vend_num");
			fdata["FieldType"] = 202;
			fdata["strField"] = "mg_quest_vend_num";
			fdata["sourceSingle"] = "mg_quest_vend_num";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "mg_quest_vend_num";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["mg_quest_vend_num"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("mg_quest_vend_num");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 21;
			fdata["strName"] = "sc_entity_name";
			fdata["GoodName"] = "sc_entity_name";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","sc_entity_name");
			fdata["FieldType"] = 202;
			fdata["strField"] = "sc_entity_name";
			fdata["sourceSingle"] = "sc_entity_name";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "sc_entity_name";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=120");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["sc_entity_name"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("sc_entity_name");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 22;
			fdata["strName"] = "exp_entity_name";
			fdata["GoodName"] = "exp_entity_name";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","exp_entity_name");
			fdata["FieldType"] = 202;
			fdata["strField"] = "exp_entity_name";
			fdata["sourceSingle"] = "exp_entity_name";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "exp_entity_name";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["exp_entity_name"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("exp_entity_name");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 23;
			fdata["strName"] = "exp_journal";
			fdata["GoodName"] = "exp_journal";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","exp_journal");
			fdata["FieldType"] = 202;
			fdata["strField"] = "exp_journal";
			fdata["sourceSingle"] = "exp_journal";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "exp_journal";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["exp_journal"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("exp_journal");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 24;
			fdata["strName"] = "tp_active";
			fdata["GoodName"] = "tp_active";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","tp_active");
			fdata["FieldType"] = 16;
			fdata["strField"] = "tp_active";
			fdata["sourceSingle"] = "tp_active";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "tp_active";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Checkbox");
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Checkbox");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["tp_active"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("tp_active");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 25;
			fdata["strName"] = "tp_vend_stat_pre";
			fdata["GoodName"] = "tp_vend_stat_pre";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","tp_vend_stat_pre");
			fdata["FieldType"] = 202;
			fdata["strField"] = "tp_vend_stat_pre";
			fdata["sourceSingle"] = "tp_vend_stat_pre";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "tp_vend_stat_pre";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=1");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["tp_vend_stat_pre"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("tp_vend_stat_pre");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 26;
			fdata["strName"] = "tp_vend_stat_post";
			fdata["GoodName"] = "tp_vend_stat_post";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","tp_vend_stat_post");
			fdata["FieldType"] = 202;
			fdata["strField"] = "tp_vend_stat_post";
			fdata["sourceSingle"] = "tp_vend_stat_post";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "tp_vend_stat_post";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=1");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["tp_vend_stat_post"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("tp_vend_stat_post");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 27;
			fdata["strName"] = "tp_vend_post_to_sl";
			fdata["GoodName"] = "tp_vend_post_to_sl";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","tp_vend_post_to_sl");
			fdata["FieldType"] = 16;
			fdata["strField"] = "tp_vend_post_to_sl";
			fdata["sourceSingle"] = "tp_vend_post_to_sl";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "tp_vend_post_to_sl";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["tp_vend_post_to_sl"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("tp_vend_post_to_sl");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 28;
			fdata["strName"] = "tp_lc_active";
			fdata["GoodName"] = "tp_lc_active";
			fdata["ownerTable"] = "dbo.csi_site_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_csi_site_mst","tp_lc_active");
			fdata["FieldType"] = 16;
			fdata["strField"] = "tp_lc_active";
			fdata["sourceSingle"] = "tp_lc_active";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "tp_lc_active";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["csi_site_mst"]["tp_lc_active"] = fdata;
			tdataArray["csi_site_mst"][".searchableFields"].Add("tp_lc_active");
			GlobalVars.tables_data["dbo.csi_site_mst"] = tdataArray["csi_site_mst"];
			GlobalVars.field_labels["dbo_csi_site_mst"] = fieldLabelsArray["csi_site_mst"];
			GlobalVars.fieldToolTips["dbo_csi_site_mst"] = fieldToolTipsArray["csi_site_mst"];
			GlobalVars.placeHolders["dbo_csi_site_mst"] = placeHoldersArray["csi_site_mst"];
			GlobalVars.page_titles["dbo_csi_site_mst"] = pageTitlesArray["csi_site_mst"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.csi_site_mst"));
			GlobalVars.detailsTablesData["dbo.csi_site_mst"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.csi_site_mst"] = SettingsMap.GetArray();


			strOriginalDetailsTable = "dbo.clients";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "dbo.clients";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "clients";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo.csi_site_mst"][0] = masterParams;
			GlobalVars.masterTablesData["dbo.csi_site_mst"][0]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.csi_site_mst"][0]["masterKeys"].Add("shortcode");
			GlobalVars.masterTablesData["dbo.csi_site_mst"][0]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.csi_site_mst"][0]["detailKeys"].Add("clientid");

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "clientid,  	site_ref,  	tp_payer_entity_name,  	RowPointer,  	VariationNumber,  	uf_uet1,  	uf_uet2,  	uf_uet3,  	uf_uet4,  	uf_uet5,  	uf_uet6,  	uf_uet7,  	uf_uet8,  	uf_uet9,  	uf_uet10,  	tp_bankcode,  	sf_entity_name,  	site_prefix,  	mg_whse,  	mg_quest_vend_num,  	sc_entity_name,  	exp_entity_name,  	exp_journal,  	tp_active,  	tp_vend_stat_pre,  	tp_vend_stat_post,  	tp_vend_post_to_sl,  	tp_lc_active";
protoArray["0"]["m_strFrom"] = "FROM dbo.csi_site_mst";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "clientid", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["6"]["m_sql"] = "clientid";
protoArray["6"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "site_ref", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["8"]["m_sql"] = "site_ref";
protoArray["8"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "tp_payer_entity_name", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["10"]["m_sql"] = "tp_payer_entity_name";
protoArray["10"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "RowPointer", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["12"]["m_sql"] = "RowPointer";
protoArray["12"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "VariationNumber", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["14"]["m_sql"] = "VariationNumber";
protoArray["14"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet1", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["16"]["m_sql"] = "uf_uet1";
protoArray["16"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet2", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["18"]["m_sql"] = "uf_uet2";
protoArray["18"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet3", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["20"]["m_sql"] = "uf_uet3";
protoArray["20"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet4", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["22"]["m_sql"] = "uf_uet4";
protoArray["22"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet5", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["24"]["m_sql"] = "uf_uet5";
protoArray["24"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet6", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["26"]["m_sql"] = "uf_uet6";
protoArray["26"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet7", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["28"]["m_sql"] = "uf_uet7";
protoArray["28"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet8", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["30"]["m_sql"] = "uf_uet8";
protoArray["30"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["32"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet9", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["32"]["m_sql"] = "uf_uet9";
protoArray["32"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["32"]["m_expr"] = obj;
protoArray["32"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["32"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["34"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uf_uet10", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["34"]["m_sql"] = "uf_uet10";
protoArray["34"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["34"]["m_expr"] = obj;
protoArray["34"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["34"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["36"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "tp_bankcode", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["36"]["m_sql"] = "tp_bankcode";
protoArray["36"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["36"]["m_expr"] = obj;
protoArray["36"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["36"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["38"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "sf_entity_name", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["38"]["m_sql"] = "sf_entity_name";
protoArray["38"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["38"]["m_expr"] = obj;
protoArray["38"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["38"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["40"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "site_prefix", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["40"]["m_sql"] = "site_prefix";
protoArray["40"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["40"]["m_expr"] = obj;
protoArray["40"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["40"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["42"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "mg_whse", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["42"]["m_sql"] = "mg_whse";
protoArray["42"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["42"]["m_expr"] = obj;
protoArray["42"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["42"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["44"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "mg_quest_vend_num", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["44"]["m_sql"] = "mg_quest_vend_num";
protoArray["44"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["44"]["m_expr"] = obj;
protoArray["44"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["44"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["46"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "sc_entity_name", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["46"]["m_sql"] = "sc_entity_name";
protoArray["46"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["46"]["m_expr"] = obj;
protoArray["46"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["46"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["48"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "exp_entity_name", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["48"]["m_sql"] = "exp_entity_name";
protoArray["48"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["48"]["m_expr"] = obj;
protoArray["48"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["48"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["50"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "exp_journal", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["50"]["m_sql"] = "exp_journal";
protoArray["50"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["50"]["m_expr"] = obj;
protoArray["50"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["50"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["52"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "tp_active", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["52"]["m_sql"] = "tp_active";
protoArray["52"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["52"]["m_expr"] = obj;
protoArray["52"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["52"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["54"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "tp_vend_stat_pre", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["54"]["m_sql"] = "tp_vend_stat_pre";
protoArray["54"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["54"]["m_expr"] = obj;
protoArray["54"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["54"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["56"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "tp_vend_stat_post", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["56"]["m_sql"] = "tp_vend_stat_post";
protoArray["56"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["56"]["m_expr"] = obj;
protoArray["56"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["56"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["58"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "tp_vend_post_to_sl", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["58"]["m_sql"] = "tp_vend_post_to_sl";
protoArray["58"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["58"]["m_expr"] = obj;
protoArray["58"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["58"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["60"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "tp_lc_active", "m_strTable", "dbo.csi_site_mst", "m_srcTableName", "dbo.csi_site_mst"));

protoArray["60"]["m_sql"] = "tp_lc_active";
protoArray["60"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["60"]["m_expr"] = obj;
protoArray["60"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["60"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["62"] = SettingsMap.GetArray();
protoArray["62"]["m_link"] = "SQLL_MAIN";
protoArray["63"] = SettingsMap.GetArray();
protoArray["63"]["m_strName"] = "dbo.csi_site_mst";
protoArray["63"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["63"]["m_columns"] = SettingsMap.GetArray();
protoArray["63"]["m_columns"].Add("clientid");
protoArray["63"]["m_columns"].Add("site_ref");
protoArray["63"]["m_columns"].Add("tp_payer_entity_name");
protoArray["63"]["m_columns"].Add("RowPointer");
protoArray["63"]["m_columns"].Add("VariationNumber");
protoArray["63"]["m_columns"].Add("uf_uet1");
protoArray["63"]["m_columns"].Add("uf_uet2");
protoArray["63"]["m_columns"].Add("uf_uet3");
protoArray["63"]["m_columns"].Add("uf_uet4");
protoArray["63"]["m_columns"].Add("uf_uet5");
protoArray["63"]["m_columns"].Add("uf_uet6");
protoArray["63"]["m_columns"].Add("uf_uet7");
protoArray["63"]["m_columns"].Add("uf_uet8");
protoArray["63"]["m_columns"].Add("uf_uet9");
protoArray["63"]["m_columns"].Add("uf_uet10");
protoArray["63"]["m_columns"].Add("tp_bankcode");
protoArray["63"]["m_columns"].Add("sf_entity_name");
protoArray["63"]["m_columns"].Add("site_prefix");
protoArray["63"]["m_columns"].Add("mg_whse");
protoArray["63"]["m_columns"].Add("mg_quest_vend_num");
protoArray["63"]["m_columns"].Add("sc_entity_name");
protoArray["63"]["m_columns"].Add("exp_entity_name");
protoArray["63"]["m_columns"].Add("exp_journal");
protoArray["63"]["m_columns"].Add("tp_active");
protoArray["63"]["m_columns"].Add("tp_vend_stat_pre");
protoArray["63"]["m_columns"].Add("tp_vend_stat_post");
protoArray["63"]["m_columns"].Add("tp_vend_post_to_sl");
protoArray["63"]["m_columns"].Add("tp_lc_active");
obj = new SQLTable(protoArray["63"]);

protoArray["62"]["m_table"] = obj;
protoArray["62"]["m_sql"] = "dbo.csi_site_mst";
protoArray["62"]["m_alias"] = "";
protoArray["62"]["m_srcTableName"] = "dbo.csi_site_mst";
protoArray["64"] = SettingsMap.GetArray();
protoArray["64"]["m_sql"] = "";
protoArray["64"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["64"]["m_column"] = obj;
protoArray["64"]["m_contained"] = SettingsMap.GetArray();
protoArray["64"]["m_strCase"] = "";
protoArray["64"]["m_havingmode"] = false;
protoArray["64"]["m_inBrackets"] = false;
protoArray["64"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["64"]);

protoArray["62"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["62"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.csi_site_mst";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["csi_site_mst"] = obj;

				
		
			tdataArray["csi_site_mst"][".sqlquery"] = queryData_Array["csi_site_mst"];
			tdataArray["csi_site_mst"][".hasEvents"] = false;
		}
	}

}
