using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_incoming
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["incoming"] = SettingsMap.GetArray();
			tdataArray["incoming"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["incoming"][".ShortName"] = "incoming";
			tdataArray["incoming"][".OwnerID"] = "client";
			tdataArray["incoming"][".OriginalTable"] = "dbo.incoming";
			tdataArray["incoming"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}"));
			tdataArray["incoming"][".originalPagesByType"] = tdataArray["incoming"][".pagesByType"];
			tdataArray["incoming"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}")));
			tdataArray["incoming"][".originalPages"] = tdataArray["incoming"][".pages"];
			tdataArray["incoming"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\",\"view\":\"view\"}"));
			tdataArray["incoming"][".originalDefaultPages"] = tdataArray["incoming"][".defaultPages"];
			fieldLabelsArray["incoming"] = SettingsMap.GetArray();
			fieldToolTipsArray["incoming"] = SettingsMap.GetArray();
			pageTitlesArray["incoming"] = SettingsMap.GetArray();
			placeHoldersArray["incoming"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["incoming"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["incoming"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["incoming"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["incoming"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["incoming"]["English"]["post_id"] = "Post Id";
				fieldToolTipsArray["incoming"]["English"]["post_id"] = "";
				placeHoldersArray["incoming"]["English"]["post_id"] = "";
				fieldLabelsArray["incoming"]["English"]["client"] = "Client";
				fieldToolTipsArray["incoming"]["English"]["client"] = "";
				placeHoldersArray["incoming"]["English"]["client"] = "";
				fieldLabelsArray["incoming"]["English"]["payload"] = "Payload";
				fieldToolTipsArray["incoming"]["English"]["payload"] = "";
				placeHoldersArray["incoming"]["English"]["payload"] = "";
				fieldLabelsArray["incoming"]["English"]["topic"] = "Topic";
				fieldToolTipsArray["incoming"]["English"]["topic"] = "";
				placeHoldersArray["incoming"]["English"]["topic"] = "";
				fieldLabelsArray["incoming"]["English"]["createdate"] = "Createdate";
				fieldToolTipsArray["incoming"]["English"]["createdate"] = "";
				placeHoldersArray["incoming"]["English"]["createdate"] = "";
				fieldLabelsArray["incoming"]["English"]["posted"] = "Posted";
				fieldToolTipsArray["incoming"]["English"]["posted"] = "";
				placeHoldersArray["incoming"]["English"]["posted"] = "";
				fieldLabelsArray["incoming"]["English"]["ref_num"] = "Ref Num";
				fieldToolTipsArray["incoming"]["English"]["ref_num"] = "";
				placeHoldersArray["incoming"]["English"]["ref_num"] = "";
				fieldLabelsArray["incoming"]["English"]["rowpointer"] = "Rowpointer";
				fieldToolTipsArray["incoming"]["English"]["rowpointer"] = "";
				placeHoldersArray["incoming"]["English"]["rowpointer"] = "";
				fieldLabelsArray["incoming"]["English"]["process"] = "Process";
				fieldToolTipsArray["incoming"]["English"]["process"] = "";
				placeHoldersArray["incoming"]["English"]["process"] = "";
				fieldLabelsArray["incoming"]["English"]["recordname"] = "Recordname";
				fieldToolTipsArray["incoming"]["English"]["recordname"] = "";
				placeHoldersArray["incoming"]["English"]["recordname"] = "";
				fieldLabelsArray["incoming"]["English"]["app"] = "App";
				fieldToolTipsArray["incoming"]["English"]["app"] = "";
				placeHoldersArray["incoming"]["English"]["app"] = "";
				fieldLabelsArray["incoming"]["English"]["site"] = "Site";
				fieldToolTipsArray["incoming"]["English"]["site"] = "";
				placeHoldersArray["incoming"]["English"]["site"] = "";
				fieldLabelsArray["incoming"]["English"]["tz_create_date"] = "Tz Create Date";
				fieldToolTipsArray["incoming"]["English"]["tz_create_date"] = "";
				placeHoldersArray["incoming"]["English"]["tz_create_date"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["incoming"]["English"])))
				{
					tdataArray["incoming"][".isUseToolTips"] = true;
				}
			}
			tdataArray["incoming"][".NCSearch"] = true;
			tdataArray["incoming"][".shortTableName"] = "incoming";
			tdataArray["incoming"][".nSecOptions"] = 1;
			tdataArray["incoming"][".mainTableOwnerID"] = "client";
			tdataArray["incoming"][".entityType"] = 0;
			tdataArray["incoming"][".connId"] = "Hubkoratec218206166241compute1";
			tdataArray["incoming"][".strOriginalTableName"] = "dbo.incoming";
			tdataArray["incoming"][".showAddInPopup"] = false;
			tdataArray["incoming"][".showEditInPopup"] = false;
			tdataArray["incoming"][".showViewInPopup"] = false;
			tdataArray["incoming"][".listAjax"] = false;
			tdataArray["incoming"][".audit"] = true;
			tdataArray["incoming"][".locking"] = false;
			GlobalVars.pages = tdataArray["incoming"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["incoming"][".edit"] = true;
				tdataArray["incoming"][".afterEditAction"] = 1;
				tdataArray["incoming"][".closePopupAfterEdit"] = 1;
				tdataArray["incoming"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["incoming"][".add"] = true;
				tdataArray["incoming"][".afterAddAction"] = 1;
				tdataArray["incoming"][".closePopupAfterAdd"] = 1;
				tdataArray["incoming"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["incoming"][".list"] = true;
			}
			tdataArray["incoming"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["incoming"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["incoming"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["incoming"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["incoming"][".printFriendly"] = true;
			}
			tdataArray["incoming"][".showSimpleSearchOptions"] = true;
			tdataArray["incoming"][".allowShowHideFields"] = true;
			tdataArray["incoming"][".allowFieldsReordering"] = true;
			tdataArray["incoming"][".isUseAjaxSuggest"] = true;


			tdataArray["incoming"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["incoming"][".buttonsAdded"] = false;
			tdataArray["incoming"][".addPageEvents"] = true;
			tdataArray["incoming"][".isUseTimeForSearch"] = false;
			tdataArray["incoming"][".badgeColor"] = "cd5c5c";
			tdataArray["incoming"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["incoming"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["incoming"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["incoming"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["incoming"][".googleLikeFields"].Add("post_id");
			tdataArray["incoming"][".googleLikeFields"].Add("client");
			tdataArray["incoming"][".googleLikeFields"].Add("payload");
			tdataArray["incoming"][".googleLikeFields"].Add("topic");
			tdataArray["incoming"][".googleLikeFields"].Add("createdate");
			tdataArray["incoming"][".googleLikeFields"].Add("tz_create_date");
			tdataArray["incoming"][".googleLikeFields"].Add("posted");
			tdataArray["incoming"][".googleLikeFields"].Add("ref_num");
			tdataArray["incoming"][".googleLikeFields"].Add("rowpointer");
			tdataArray["incoming"][".googleLikeFields"].Add("process");
			tdataArray["incoming"][".googleLikeFields"].Add("recordname");
			tdataArray["incoming"][".googleLikeFields"].Add("app");
			tdataArray["incoming"][".googleLikeFields"].Add("site");
			tdataArray["incoming"][".tableType"] = "list";
			tdataArray["incoming"][".printerPageOrientation"] = 0;
			tdataArray["incoming"][".nPrinterPageScale"] = 100;
			tdataArray["incoming"][".nPrinterSplitRecords"] = 40;
			tdataArray["incoming"][".geocodingEnabled"] = false;
			tdataArray["incoming"][".pageSize"] = 20;
			tdataArray["incoming"][".warnLeavingPages"] = true;
			tstrOrderBy = "ORDER BY post_id DESC";
			tdataArray["incoming"][".strOrderBy"] = tstrOrderBy;
			tdataArray["incoming"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["incoming"][".orderindexes"].Add(new XVar(0, 1, 1, (XVar.Pack(0) ? XVar.Pack("ASC") : XVar.Pack("DESC")), 2, "post_id"));
			tdataArray["incoming"][".sqlHead"] = "SELECT post_id,  client,  payload,  topic,  createdate,  dbo.HK_TimeZone(':session.user_name',createdate) tz_create_date,  posted,  ref_num,  rowpointer,  process,  recordname,  app,  site";
			tdataArray["incoming"][".sqlFrom"] = "FROM dbo.incoming";
			tdataArray["incoming"][".sqlWhereExpr"] = "";
			tdataArray["incoming"][".sqlTail"] = "";
			arrGridTabs = SettingsMap.GetArray();
			arrGridTabs.Add(new XVar("tabId", "custaddr", "name", "No Posted", "nameType", "Text", "where", "isnull(posted,0) = 0", "showRowCount", 1, "hideEmpty", 0));
			arrGridTabs.Add(new XVar("tabId", "", "name", "All data", "nameType", "Text", "where", "", "showRowCount", 1, "hideEmpty", 0));
			tdataArray["incoming"][".arrGridTabs"] = arrGridTabs;
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["incoming"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["incoming"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["incoming"][".highlightSearchResults"] = true;
			tableKeysArray["incoming"] = SettingsMap.GetArray();
			tableKeysArray["incoming"].Add("post_id");
			tdataArray["incoming"][".Keys"] = tableKeysArray["incoming"];
			tdataArray["incoming"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "post_id";
			fdata["GoodName"] = "post_id";
			fdata["ownerTable"] = "dbo.incoming";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","post_id");
			fdata["FieldType"] = 20;
			fdata["AutoInc"] = true;
			fdata["strField"] = "post_id";
			fdata["sourceSingle"] = "post_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "post_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["post_id"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("post_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "client";
			fdata["GoodName"] = "client";
			fdata["ownerTable"] = "dbo.incoming";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","client");
			fdata["FieldType"] = 202;
			fdata["strField"] = "client";
			fdata["sourceSingle"] = "client";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "client";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["client"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("client");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "payload";
			fdata["GoodName"] = "payload";
			fdata["ownerTable"] = "dbo.incoming";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","payload");
			fdata["FieldType"] = 202;
			fdata["strField"] = "payload";
			fdata["sourceSingle"] = "payload";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "payload";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Custom");
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=2147483647");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["payload"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("payload");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "topic";
			fdata["GoodName"] = "topic";
			fdata["ownerTable"] = "dbo.incoming";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","topic");
			fdata["FieldType"] = 202;
			fdata["strField"] = "topic";
			fdata["sourceSingle"] = "topic";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "topic";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["topic"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("topic");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "createdate";
			fdata["GoodName"] = "createdate";
			fdata["ownerTable"] = "dbo.incoming";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","createdate");
			fdata["FieldType"] = 135;
			fdata["strField"] = "createdate";
			fdata["sourceSingle"] = "createdate";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "createdate";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Datetime");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "Invalid week day", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 5;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["createdate"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("createdate");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "tz_create_date";
			fdata["GoodName"] = "tz_create_date";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","tz_create_date");
			fdata["FieldType"] = 200;
			fdata["strField"] = "tz_create_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "dbo.HK_TimeZone(':session.user_name',createdate)";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["tz_create_date"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("tz_create_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "posted";
			fdata["GoodName"] = "posted";
			fdata["ownerTable"] = "dbo.incoming";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","posted");
			fdata["FieldType"] = 200;
			fdata["strField"] = "posted";
			fdata["sourceSingle"] = "posted";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "posted";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Checkbox");
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Checkbox");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["posted"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("posted");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "ref_num";
			fdata["GoodName"] = "ref_num";
			fdata["ownerTable"] = "dbo.incoming";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","ref_num");
			fdata["FieldType"] = 202;
			fdata["strField"] = "ref_num";
			fdata["sourceSingle"] = "ref_num";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ref_num";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["ref_num"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("ref_num");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "rowpointer";
			fdata["GoodName"] = "rowpointer";
			fdata["ownerTable"] = "dbo.incoming";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","rowpointer");
			fdata["FieldType"] = 72;
			fdata["strField"] = "rowpointer";
			fdata["sourceSingle"] = "rowpointer";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "rowpointer";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["rowpointer"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("rowpointer");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "process";
			fdata["GoodName"] = "process";
			fdata["ownerTable"] = "dbo.incoming";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","process");
			fdata["FieldType"] = 202;
			fdata["strField"] = "process";
			fdata["sourceSingle"] = "process";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "process";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=40");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["process"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("process");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "recordname";
			fdata["GoodName"] = "recordname";
			fdata["ownerTable"] = "dbo.incoming";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","recordname");
			fdata["FieldType"] = 202;
			fdata["strField"] = "recordname";
			fdata["sourceSingle"] = "recordname";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "recordname";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["recordname"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("recordname");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "app";
			fdata["GoodName"] = "app";
			fdata["ownerTable"] = "dbo.incoming";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","app");
			fdata["FieldType"] = 202;
			fdata["strField"] = "app";
			fdata["sourceSingle"] = "app";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "app";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["app"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("app");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "site";
			fdata["GoodName"] = "site";
			fdata["ownerTable"] = "dbo.incoming";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_incoming","site");
			fdata["FieldType"] = 202;
			fdata["strField"] = "site";
			fdata["sourceSingle"] = "site";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "site";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["incoming"]["site"] = fdata;
			tdataArray["incoming"][".searchableFields"].Add("site");
			GlobalVars.tables_data["dbo.incoming"] = tdataArray["incoming"];
			GlobalVars.field_labels["dbo_incoming"] = fieldLabelsArray["incoming"];
			GlobalVars.fieldToolTips["dbo_incoming"] = fieldToolTipsArray["incoming"];
			GlobalVars.placeHolders["dbo_incoming"] = placeHoldersArray["incoming"];
			GlobalVars.page_titles["dbo_incoming"] = pageTitlesArray["incoming"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.incoming"));
			GlobalVars.detailsTablesData["dbo.incoming"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.incoming"] = SettingsMap.GetArray();


			strOriginalDetailsTable = "dbo.recordcounts";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "dbo.recordcounts";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "recordcounts";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo.incoming"][0] = masterParams;
			GlobalVars.masterTablesData["dbo.incoming"][0]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.incoming"][0]["masterKeys"].Add("clientid");
			GlobalVars.masterTablesData["dbo.incoming"][0]["masterKeys"].Add("table_name");
			GlobalVars.masterTablesData["dbo.incoming"][0]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.incoming"][0]["detailKeys"].Add("client");
			GlobalVars.masterTablesData["dbo.incoming"][0]["detailKeys"].Add("recordname");

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "post_id,  client,  payload,  topic,  createdate,  dbo.HK_TimeZone(':session.user_name',createdate) tz_create_date,  posted,  ref_num,  rowpointer,  process,  recordname,  app,  site";
protoArray["0"]["m_strFrom"] = "FROM dbo.incoming";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "ORDER BY post_id DESC";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "post_id", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["6"]["m_sql"] = "post_id";
protoArray["6"]["m_srcTableName"] = "dbo.incoming";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "client", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["8"]["m_sql"] = "client";
protoArray["8"]["m_srcTableName"] = "dbo.incoming";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "payload", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["10"]["m_sql"] = "payload";
protoArray["10"]["m_srcTableName"] = "dbo.incoming";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "topic", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["12"]["m_sql"] = "topic";
protoArray["12"]["m_srcTableName"] = "dbo.incoming";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "createdate", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["14"]["m_sql"] = "createdate";
protoArray["14"]["m_srcTableName"] = "dbo.incoming";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
protoArray["17"] = SettingsMap.GetArray();
protoArray["17"]["m_functiontype"] = "SQLF_CUSTOM";
protoArray["17"]["m_arguments"] = SettingsMap.GetArray();
obj = new SQLNonParsed(new XVar("m_sql", "':session.user_name'"));

protoArray["17"]["m_arguments"].Add(obj);
obj = new SQLNonParsed(new XVar("m_sql", "createdate"));

protoArray["17"]["m_arguments"].Add(obj);
protoArray["17"]["m_strFunctionName"] = "dbo.HK_TimeZone";
obj = new SQLFunctionCall(protoArray["17"]);

protoArray["16"]["m_sql"] = "dbo.HK_TimeZone(':session.user_name',createdate)";
protoArray["16"]["m_srcTableName"] = "dbo.incoming";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "tz_create_date";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "posted", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["20"]["m_sql"] = "posted";
protoArray["20"]["m_srcTableName"] = "dbo.incoming";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ref_num", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["22"]["m_sql"] = "ref_num";
protoArray["22"]["m_srcTableName"] = "dbo.incoming";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "rowpointer", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["24"]["m_sql"] = "rowpointer";
protoArray["24"]["m_srcTableName"] = "dbo.incoming";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "process", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["26"]["m_sql"] = "process";
protoArray["26"]["m_srcTableName"] = "dbo.incoming";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "recordname", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["28"]["m_sql"] = "recordname";
protoArray["28"]["m_srcTableName"] = "dbo.incoming";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "app", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["30"]["m_sql"] = "app";
protoArray["30"]["m_srcTableName"] = "dbo.incoming";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["32"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "site", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["32"]["m_sql"] = "site";
protoArray["32"]["m_srcTableName"] = "dbo.incoming";
protoArray["32"]["m_expr"] = obj;
protoArray["32"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["32"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["34"] = SettingsMap.GetArray();
protoArray["34"]["m_link"] = "SQLL_MAIN";
protoArray["35"] = SettingsMap.GetArray();
protoArray["35"]["m_strName"] = "dbo.incoming";
protoArray["35"]["m_srcTableName"] = "dbo.incoming";
protoArray["35"]["m_columns"] = SettingsMap.GetArray();
protoArray["35"]["m_columns"].Add("post_id");
protoArray["35"]["m_columns"].Add("client");
protoArray["35"]["m_columns"].Add("payload");
protoArray["35"]["m_columns"].Add("topic");
protoArray["35"]["m_columns"].Add("createdate");
protoArray["35"]["m_columns"].Add("posted");
protoArray["35"]["m_columns"].Add("ref_num");
protoArray["35"]["m_columns"].Add("rowpointer");
protoArray["35"]["m_columns"].Add("process");
protoArray["35"]["m_columns"].Add("recordname");
protoArray["35"]["m_columns"].Add("app");
protoArray["35"]["m_columns"].Add("site");
obj = new SQLTable(protoArray["35"]);

protoArray["34"]["m_table"] = obj;
protoArray["34"]["m_sql"] = "dbo.incoming";
protoArray["34"]["m_alias"] = "";
protoArray["34"]["m_srcTableName"] = "dbo.incoming";
protoArray["36"] = SettingsMap.GetArray();
protoArray["36"]["m_sql"] = "";
protoArray["36"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["36"]["m_column"] = obj;
protoArray["36"]["m_contained"] = SettingsMap.GetArray();
protoArray["36"]["m_strCase"] = "";
protoArray["36"]["m_havingmode"] = false;
protoArray["36"]["m_inBrackets"] = false;
protoArray["36"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["36"]);

protoArray["34"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["34"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["38"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "post_id", "m_strTable", "dbo.incoming", "m_srcTableName", "dbo.incoming"));

protoArray["38"]["m_column"] = obj;
protoArray["38"]["m_bAsc"] = 0;
protoArray["38"]["m_nColumn"] = 0;
obj = new SQLOrderByItem(protoArray["38"]);

protoArray["0"]["m_orderby"].Add(obj);
protoArray["0"]["m_srcTableName"] = "dbo.incoming";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["incoming"] = obj;

				
		
			tdataArray["incoming"][".sqlquery"] = queryData_Array["incoming"];
			tdataArray["incoming"][".hasEvents"] = true;
		}
	}

}
