using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_mg_customer_mst
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["mg_customer_mst"] = SettingsMap.GetArray();
			tdataArray["mg_customer_mst"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["mg_customer_mst"][".ShortName"] = "mg_customer_mst";
			tdataArray["mg_customer_mst"][".OwnerID"] = "clientid";
			tdataArray["mg_customer_mst"][".OriginalTable"] = "dbo.mg_customer_mst";
			tdataArray["mg_customer_mst"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"list\":[\"list\"],\"search\":[\"search\"]}"));
			tdataArray["mg_customer_mst"][".originalPagesByType"] = tdataArray["mg_customer_mst"][".pagesByType"];
			tdataArray["mg_customer_mst"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"list\":[\"list\"],\"search\":[\"search\"]}")));
			tdataArray["mg_customer_mst"][".originalPages"] = tdataArray["mg_customer_mst"][".pages"];
			tdataArray["mg_customer_mst"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"export\":\"export\",\"list\":\"list\",\"search\":\"search\"}"));
			tdataArray["mg_customer_mst"][".originalDefaultPages"] = tdataArray["mg_customer_mst"][".defaultPages"];
			fieldLabelsArray["mg_customer_mst"] = SettingsMap.GetArray();
			fieldToolTipsArray["mg_customer_mst"] = SettingsMap.GetArray();
			pageTitlesArray["mg_customer_mst"] = SettingsMap.GetArray();
			placeHoldersArray["mg_customer_mst"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["mg_customer_mst"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["mg_customer_mst"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["mg_customer_mst"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["mg_customer_mst"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["mg_customer_mst"]["English"]["clientid"] = "Clientid";
				fieldToolTipsArray["mg_customer_mst"]["English"]["clientid"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["clientid"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["site_ref"] = "Site Ref";
				fieldToolTipsArray["mg_customer_mst"]["English"]["site_ref"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["site_ref"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["customer_id"] = "Customer Id";
				fieldToolTipsArray["mg_customer_mst"]["English"]["customer_id"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["customer_id"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["cust_num"] = "Cust Num";
				fieldToolTipsArray["mg_customer_mst"]["English"]["cust_num"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["cust_num"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["cust_seq"] = "Cust Seq";
				fieldToolTipsArray["mg_customer_mst"]["English"]["cust_seq"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["cust_seq"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["name"] = "Name";
				fieldToolTipsArray["mg_customer_mst"]["English"]["name"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["name"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["city"] = "City";
				fieldToolTipsArray["mg_customer_mst"]["English"]["city"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["city"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["state"] = "State";
				fieldToolTipsArray["mg_customer_mst"]["English"]["state"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["state"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["zip"] = "Zip";
				fieldToolTipsArray["mg_customer_mst"]["English"]["zip"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["zip"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["country"] = "Country";
				fieldToolTipsArray["mg_customer_mst"]["English"]["country"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["country"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["addr1"] = "Addr1";
				fieldToolTipsArray["mg_customer_mst"]["English"]["addr1"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["addr1"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["addr2"] = "Addr2";
				fieldToolTipsArray["mg_customer_mst"]["English"]["addr2"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["addr2"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["addr3"] = "Addr3";
				fieldToolTipsArray["mg_customer_mst"]["English"]["addr3"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["addr3"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["addr4"] = "Addr4";
				fieldToolTipsArray["mg_customer_mst"]["English"]["addr4"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["addr4"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["email"] = "Email";
				fieldToolTipsArray["mg_customer_mst"]["English"]["email"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["email"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["posted"] = "Posted";
				fieldToolTipsArray["mg_customer_mst"]["English"]["posted"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["posted"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["address_id"] = "Address Id";
				fieldToolTipsArray["mg_customer_mst"]["English"]["address_id"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["address_id"] = "";
				fieldLabelsArray["mg_customer_mst"]["English"]["telephone"] = "Telephone";
				fieldToolTipsArray["mg_customer_mst"]["English"]["telephone"] = "";
				placeHoldersArray["mg_customer_mst"]["English"]["telephone"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["mg_customer_mst"]["English"])))
				{
					tdataArray["mg_customer_mst"][".isUseToolTips"] = true;
				}
			}
			tdataArray["mg_customer_mst"][".NCSearch"] = true;
			tdataArray["mg_customer_mst"][".shortTableName"] = "mg_customer_mst";
			tdataArray["mg_customer_mst"][".nSecOptions"] = 1;
			tdataArray["mg_customer_mst"][".mainTableOwnerID"] = "clientid";
			tdataArray["mg_customer_mst"][".entityType"] = 0;
			tdataArray["mg_customer_mst"][".connId"] = "Hubkoratec218206166241compute1";
			tdataArray["mg_customer_mst"][".strOriginalTableName"] = "dbo.mg_customer_mst";
			tdataArray["mg_customer_mst"][".showAddInPopup"] = false;
			tdataArray["mg_customer_mst"][".showEditInPopup"] = false;
			tdataArray["mg_customer_mst"][".showViewInPopup"] = false;
			tdataArray["mg_customer_mst"][".listAjax"] = false;
			tdataArray["mg_customer_mst"][".audit"] = false;
			tdataArray["mg_customer_mst"][".locking"] = false;
			GlobalVars.pages = tdataArray["mg_customer_mst"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["mg_customer_mst"][".edit"] = true;
				tdataArray["mg_customer_mst"][".afterEditAction"] = 1;
				tdataArray["mg_customer_mst"][".closePopupAfterEdit"] = 1;
				tdataArray["mg_customer_mst"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["mg_customer_mst"][".add"] = true;
				tdataArray["mg_customer_mst"][".afterAddAction"] = 1;
				tdataArray["mg_customer_mst"][".closePopupAfterAdd"] = 1;
				tdataArray["mg_customer_mst"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["mg_customer_mst"][".list"] = true;
			}
			tdataArray["mg_customer_mst"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["mg_customer_mst"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["mg_customer_mst"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["mg_customer_mst"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["mg_customer_mst"][".printFriendly"] = true;
			}
			tdataArray["mg_customer_mst"][".showSimpleSearchOptions"] = true;
			tdataArray["mg_customer_mst"][".allowShowHideFields"] = true;
			tdataArray["mg_customer_mst"][".allowFieldsReordering"] = true;
			tdataArray["mg_customer_mst"][".isUseAjaxSuggest"] = true;


			tdataArray["mg_customer_mst"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["mg_customer_mst"][".buttonsAdded"] = false;
			tdataArray["mg_customer_mst"][".addPageEvents"] = false;
			tdataArray["mg_customer_mst"][".isUseTimeForSearch"] = false;
			tdataArray["mg_customer_mst"][".badgeColor"] = "008B8B";
			tdataArray["mg_customer_mst"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["mg_customer_mst"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["mg_customer_mst"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["mg_customer_mst"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("clientid");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("site_ref");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("customer_id");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("cust_num");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("cust_seq");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("name");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("city");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("state");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("zip");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("country");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("addr1");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("addr2");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("addr3");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("addr4");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("email");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("posted");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("address_id");
			tdataArray["mg_customer_mst"][".googleLikeFields"].Add("telephone");
			tdataArray["mg_customer_mst"][".tableType"] = "list";
			tdataArray["mg_customer_mst"][".printerPageOrientation"] = 0;
			tdataArray["mg_customer_mst"][".nPrinterPageScale"] = 100;
			tdataArray["mg_customer_mst"][".nPrinterSplitRecords"] = 40;
			tdataArray["mg_customer_mst"][".geocodingEnabled"] = false;
			tdataArray["mg_customer_mst"][".pageSize"] = 20;
			tdataArray["mg_customer_mst"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["mg_customer_mst"][".strOrderBy"] = tstrOrderBy;
			tdataArray["mg_customer_mst"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["mg_customer_mst"][".sqlHead"] = "SELECT clientid,  	site_ref,  	customer_id,  	cust_num,  	cust_seq,  	name,  	city,  	[state],  	zip,  	country,  	addr1,  	addr2,  	addr3,  	addr4,  	email,  	posted,  	address_id,  	telephone";
			tdataArray["mg_customer_mst"][".sqlFrom"] = "FROM dbo.mg_customer_mst";
			tdataArray["mg_customer_mst"][".sqlWhereExpr"] = "";
			tdataArray["mg_customer_mst"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["mg_customer_mst"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["mg_customer_mst"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["mg_customer_mst"][".highlightSearchResults"] = true;
			tableKeysArray["mg_customer_mst"] = SettingsMap.GetArray();
			tableKeysArray["mg_customer_mst"].Add("clientid");
			tableKeysArray["mg_customer_mst"].Add("site_ref");
			tdataArray["mg_customer_mst"][".Keys"] = tableKeysArray["mg_customer_mst"];
			tdataArray["mg_customer_mst"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "clientid";
			fdata["GoodName"] = "clientid";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","clientid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "clientid";
			fdata["sourceSingle"] = "clientid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "clientid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["clientid"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("clientid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "site_ref";
			fdata["GoodName"] = "site_ref";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","site_ref");
			fdata["FieldType"] = 202;
			fdata["strField"] = "site_ref";
			fdata["sourceSingle"] = "site_ref";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "site_ref";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["site_ref"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("site_ref");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "customer_id";
			fdata["GoodName"] = "customer_id";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","customer_id");
			fdata["FieldType"] = 3;
			fdata["strField"] = "customer_id";
			fdata["sourceSingle"] = "customer_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "customer_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["customer_id"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("customer_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "cust_num";
			fdata["GoodName"] = "cust_num";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","cust_num");
			fdata["FieldType"] = 202;
			fdata["strField"] = "cust_num";
			fdata["sourceSingle"] = "cust_num";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "cust_num";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=7");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["cust_num"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("cust_num");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "cust_seq";
			fdata["GoodName"] = "cust_seq";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","cust_seq");
			fdata["FieldType"] = 3;
			fdata["strField"] = "cust_seq";
			fdata["sourceSingle"] = "cust_seq";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "cust_seq";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["cust_seq"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("cust_seq");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "name";
			fdata["GoodName"] = "name";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","name");
			fdata["FieldType"] = 202;
			fdata["strField"] = "name";
			fdata["sourceSingle"] = "name";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "name";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["name"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("name");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "city";
			fdata["GoodName"] = "city";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","city");
			fdata["FieldType"] = 202;
			fdata["strField"] = "city";
			fdata["sourceSingle"] = "city";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "city";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["city"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("city");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "state";
			fdata["GoodName"] = "state";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","state");
			fdata["FieldType"] = 202;
			fdata["strField"] = "state";
			fdata["sourceSingle"] = "state";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "[state]";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["state"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("state");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "zip";
			fdata["GoodName"] = "zip";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","zip");
			fdata["FieldType"] = 202;
			fdata["strField"] = "zip";
			fdata["sourceSingle"] = "zip";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "zip";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["zip"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("zip");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "country";
			fdata["GoodName"] = "country";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","country");
			fdata["FieldType"] = 202;
			fdata["strField"] = "country";
			fdata["sourceSingle"] = "country";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "country";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["country"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("country");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "addr1";
			fdata["GoodName"] = "addr1";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","addr1");
			fdata["FieldType"] = 202;
			fdata["strField"] = "addr1";
			fdata["sourceSingle"] = "addr1";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "addr1";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["addr1"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("addr1");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "addr2";
			fdata["GoodName"] = "addr2";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","addr2");
			fdata["FieldType"] = 202;
			fdata["strField"] = "addr2";
			fdata["sourceSingle"] = "addr2";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "addr2";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["addr2"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("addr2");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "addr3";
			fdata["GoodName"] = "addr3";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","addr3");
			fdata["FieldType"] = 202;
			fdata["strField"] = "addr3";
			fdata["sourceSingle"] = "addr3";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "addr3";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["addr3"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("addr3");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 14;
			fdata["strName"] = "addr4";
			fdata["GoodName"] = "addr4";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","addr4");
			fdata["FieldType"] = 202;
			fdata["strField"] = "addr4";
			fdata["sourceSingle"] = "addr4";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "addr4";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["addr4"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("addr4");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 15;
			fdata["strName"] = "email";
			fdata["GoodName"] = "email";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","email");
			fdata["FieldType"] = 202;
			fdata["strField"] = "email";
			fdata["sourceSingle"] = "email";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "email";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["email"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("email");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 16;
			fdata["strName"] = "posted";
			fdata["GoodName"] = "posted";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","posted");
			fdata["FieldType"] = 16;
			fdata["strField"] = "posted";
			fdata["sourceSingle"] = "posted";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "posted";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Checkbox");
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Checkbox");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["posted"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("posted");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 17;
			fdata["strName"] = "address_id";
			fdata["GoodName"] = "address_id";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","address_id");
			fdata["FieldType"] = 3;
			fdata["strField"] = "address_id";
			fdata["sourceSingle"] = "address_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "address_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["address_id"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("address_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 18;
			fdata["strName"] = "telephone";
			fdata["GoodName"] = "telephone";
			fdata["ownerTable"] = "dbo.mg_customer_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_customer_mst","telephone");
			fdata["FieldType"] = 202;
			fdata["strField"] = "telephone";
			fdata["sourceSingle"] = "telephone";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "telephone";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=40");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_customer_mst"]["telephone"] = fdata;
			tdataArray["mg_customer_mst"][".searchableFields"].Add("telephone");
			GlobalVars.tables_data["dbo.mg_customer_mst"] = tdataArray["mg_customer_mst"];
			GlobalVars.field_labels["dbo_mg_customer_mst"] = fieldLabelsArray["mg_customer_mst"];
			GlobalVars.fieldToolTips["dbo_mg_customer_mst"] = fieldToolTipsArray["mg_customer_mst"];
			GlobalVars.placeHolders["dbo_mg_customer_mst"] = placeHoldersArray["mg_customer_mst"];
			GlobalVars.page_titles["dbo_mg_customer_mst"] = pageTitlesArray["mg_customer_mst"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.mg_customer_mst"));
			GlobalVars.detailsTablesData["dbo.mg_customer_mst"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.mg_customer_mst"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "clientid,  	site_ref,  	customer_id,  	cust_num,  	cust_seq,  	name,  	city,  	[state],  	zip,  	country,  	addr1,  	addr2,  	addr3,  	addr4,  	email,  	posted,  	address_id,  	telephone";
protoArray["0"]["m_strFrom"] = "FROM dbo.mg_customer_mst";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "clientid", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["6"]["m_sql"] = "clientid";
protoArray["6"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "site_ref", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["8"]["m_sql"] = "site_ref";
protoArray["8"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "customer_id", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["10"]["m_sql"] = "customer_id";
protoArray["10"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "cust_num", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["12"]["m_sql"] = "cust_num";
protoArray["12"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "cust_seq", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["14"]["m_sql"] = "cust_seq";
protoArray["14"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "name", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["16"]["m_sql"] = "name";
protoArray["16"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "city", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["18"]["m_sql"] = "city";
protoArray["18"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "state", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["20"]["m_sql"] = "[state]";
protoArray["20"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "zip", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["22"]["m_sql"] = "zip";
protoArray["22"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "country", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["24"]["m_sql"] = "country";
protoArray["24"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "addr1", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["26"]["m_sql"] = "addr1";
protoArray["26"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "addr2", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["28"]["m_sql"] = "addr2";
protoArray["28"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "addr3", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["30"]["m_sql"] = "addr3";
protoArray["30"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["32"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "addr4", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["32"]["m_sql"] = "addr4";
protoArray["32"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["32"]["m_expr"] = obj;
protoArray["32"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["32"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["34"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "email", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["34"]["m_sql"] = "email";
protoArray["34"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["34"]["m_expr"] = obj;
protoArray["34"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["34"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["36"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "posted", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["36"]["m_sql"] = "posted";
protoArray["36"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["36"]["m_expr"] = obj;
protoArray["36"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["36"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["38"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "address_id", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["38"]["m_sql"] = "address_id";
protoArray["38"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["38"]["m_expr"] = obj;
protoArray["38"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["38"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["40"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "telephone", "m_strTable", "dbo.mg_customer_mst", "m_srcTableName", "dbo.mg_customer_mst"));

protoArray["40"]["m_sql"] = "telephone";
protoArray["40"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["40"]["m_expr"] = obj;
protoArray["40"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["40"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["42"] = SettingsMap.GetArray();
protoArray["42"]["m_link"] = "SQLL_MAIN";
protoArray["43"] = SettingsMap.GetArray();
protoArray["43"]["m_strName"] = "dbo.mg_customer_mst";
protoArray["43"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["43"]["m_columns"] = SettingsMap.GetArray();
protoArray["43"]["m_columns"].Add("clientid");
protoArray["43"]["m_columns"].Add("site_ref");
protoArray["43"]["m_columns"].Add("customer_id");
protoArray["43"]["m_columns"].Add("cust_num");
protoArray["43"]["m_columns"].Add("cust_seq");
protoArray["43"]["m_columns"].Add("name");
protoArray["43"]["m_columns"].Add("city");
protoArray["43"]["m_columns"].Add("state");
protoArray["43"]["m_columns"].Add("zip");
protoArray["43"]["m_columns"].Add("country");
protoArray["43"]["m_columns"].Add("addr1");
protoArray["43"]["m_columns"].Add("addr2");
protoArray["43"]["m_columns"].Add("addr3");
protoArray["43"]["m_columns"].Add("addr4");
protoArray["43"]["m_columns"].Add("email");
protoArray["43"]["m_columns"].Add("posted");
protoArray["43"]["m_columns"].Add("address_id");
protoArray["43"]["m_columns"].Add("telephone");
obj = new SQLTable(protoArray["43"]);

protoArray["42"]["m_table"] = obj;
protoArray["42"]["m_sql"] = "dbo.mg_customer_mst";
protoArray["42"]["m_alias"] = "";
protoArray["42"]["m_srcTableName"] = "dbo.mg_customer_mst";
protoArray["44"] = SettingsMap.GetArray();
protoArray["44"]["m_sql"] = "";
protoArray["44"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["44"]["m_column"] = obj;
protoArray["44"]["m_contained"] = SettingsMap.GetArray();
protoArray["44"]["m_strCase"] = "";
protoArray["44"]["m_havingmode"] = false;
protoArray["44"]["m_inBrackets"] = false;
protoArray["44"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["44"]);

protoArray["42"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["42"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.mg_customer_mst";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["mg_customer_mst"] = obj;

				
		
			tdataArray["mg_customer_mst"][".sqlquery"] = queryData_Array["mg_customer_mst"];
			tdataArray["mg_customer_mst"][".hasEvents"] = false;
		}
	}

}
