using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_mg_order_lines_mst
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["mg_order_lines_mst"] = SettingsMap.GetArray();
			tdataArray["mg_order_lines_mst"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["mg_order_lines_mst"][".ShortName"] = "mg_order_lines_mst";
			tdataArray["mg_order_lines_mst"][".OwnerID"] = "";
			tdataArray["mg_order_lines_mst"][".OriginalTable"] = "dbo.mg_order_lines_mst";
			tdataArray["mg_order_lines_mst"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}"));
			tdataArray["mg_order_lines_mst"][".originalPagesByType"] = tdataArray["mg_order_lines_mst"][".pagesByType"];
			tdataArray["mg_order_lines_mst"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}")));
			tdataArray["mg_order_lines_mst"][".originalPages"] = tdataArray["mg_order_lines_mst"][".pages"];
			tdataArray["mg_order_lines_mst"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\"}"));
			tdataArray["mg_order_lines_mst"][".originalDefaultPages"] = tdataArray["mg_order_lines_mst"][".defaultPages"];
			fieldLabelsArray["mg_order_lines_mst"] = SettingsMap.GetArray();
			fieldToolTipsArray["mg_order_lines_mst"] = SettingsMap.GetArray();
			pageTitlesArray["mg_order_lines_mst"] = SettingsMap.GetArray();
			placeHoldersArray["mg_order_lines_mst"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["mg_order_lines_mst"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["mg_order_lines_mst"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["mg_order_lines_mst"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["mg_order_lines_mst"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["mg_order_lines_mst"]["English"]["clientid"] = "Clientid";
				fieldToolTipsArray["mg_order_lines_mst"]["English"]["clientid"] = "";
				placeHoldersArray["mg_order_lines_mst"]["English"]["clientid"] = "";
				fieldLabelsArray["mg_order_lines_mst"]["English"]["site_ref"] = "Site Ref";
				fieldToolTipsArray["mg_order_lines_mst"]["English"]["site_ref"] = "";
				placeHoldersArray["mg_order_lines_mst"]["English"]["site_ref"] = "";
				fieldLabelsArray["mg_order_lines_mst"]["English"]["co_num"] = "Co Num";
				fieldToolTipsArray["mg_order_lines_mst"]["English"]["co_num"] = "";
				placeHoldersArray["mg_order_lines_mst"]["English"]["co_num"] = "";
				fieldLabelsArray["mg_order_lines_mst"]["English"]["co_line"] = "Co Line";
				fieldToolTipsArray["mg_order_lines_mst"]["English"]["co_line"] = "";
				placeHoldersArray["mg_order_lines_mst"]["English"]["co_line"] = "";
				fieldLabelsArray["mg_order_lines_mst"]["English"]["item"] = "Item";
				fieldToolTipsArray["mg_order_lines_mst"]["English"]["item"] = "";
				placeHoldersArray["mg_order_lines_mst"]["English"]["item"] = "";
				fieldLabelsArray["mg_order_lines_mst"]["English"]["description"] = "Description";
				fieldToolTipsArray["mg_order_lines_mst"]["English"]["description"] = "";
				placeHoldersArray["mg_order_lines_mst"]["English"]["description"] = "";
				fieldLabelsArray["mg_order_lines_mst"]["English"]["qty_ordered"] = "Qty Ordered";
				fieldToolTipsArray["mg_order_lines_mst"]["English"]["qty_ordered"] = "";
				placeHoldersArray["mg_order_lines_mst"]["English"]["qty_ordered"] = "";
				fieldLabelsArray["mg_order_lines_mst"]["English"]["u_m"] = "U M";
				fieldToolTipsArray["mg_order_lines_mst"]["English"]["u_m"] = "";
				placeHoldersArray["mg_order_lines_mst"]["English"]["u_m"] = "";
				fieldLabelsArray["mg_order_lines_mst"]["English"]["discount"] = "Discount";
				fieldToolTipsArray["mg_order_lines_mst"]["English"]["discount"] = "";
				placeHoldersArray["mg_order_lines_mst"]["English"]["discount"] = "";
				fieldLabelsArray["mg_order_lines_mst"]["English"]["price"] = "Price";
				fieldToolTipsArray["mg_order_lines_mst"]["English"]["price"] = "";
				placeHoldersArray["mg_order_lines_mst"]["English"]["price"] = "";
				fieldLabelsArray["mg_order_lines_mst"]["English"]["whse"] = "Whse";
				fieldToolTipsArray["mg_order_lines_mst"]["English"]["whse"] = "";
				placeHoldersArray["mg_order_lines_mst"]["English"]["whse"] = "";
				fieldLabelsArray["mg_order_lines_mst"]["English"]["extprice"] = "Extprice";
				fieldToolTipsArray["mg_order_lines_mst"]["English"]["extprice"] = "";
				placeHoldersArray["mg_order_lines_mst"]["English"]["extprice"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["mg_order_lines_mst"]["English"])))
				{
					tdataArray["mg_order_lines_mst"][".isUseToolTips"] = true;
				}
			}
			tdataArray["mg_order_lines_mst"][".NCSearch"] = true;
			tdataArray["mg_order_lines_mst"][".shortTableName"] = "mg_order_lines_mst";
			tdataArray["mg_order_lines_mst"][".nSecOptions"] = 0;
			tdataArray["mg_order_lines_mst"][".mainTableOwnerID"] = "";
			tdataArray["mg_order_lines_mst"][".entityType"] = 0;
			tdataArray["mg_order_lines_mst"][".connId"] = "Hubkoratec218206166241compute1";
			tdataArray["mg_order_lines_mst"][".strOriginalTableName"] = "dbo.mg_order_lines_mst";
			tdataArray["mg_order_lines_mst"][".showAddInPopup"] = false;
			tdataArray["mg_order_lines_mst"][".showEditInPopup"] = false;
			tdataArray["mg_order_lines_mst"][".showViewInPopup"] = false;
			tdataArray["mg_order_lines_mst"][".listAjax"] = false;
			tdataArray["mg_order_lines_mst"][".audit"] = true;
			tdataArray["mg_order_lines_mst"][".locking"] = false;
			GlobalVars.pages = tdataArray["mg_order_lines_mst"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["mg_order_lines_mst"][".edit"] = true;
				tdataArray["mg_order_lines_mst"][".afterEditAction"] = 1;
				tdataArray["mg_order_lines_mst"][".closePopupAfterEdit"] = 1;
				tdataArray["mg_order_lines_mst"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["mg_order_lines_mst"][".add"] = true;
				tdataArray["mg_order_lines_mst"][".afterAddAction"] = 1;
				tdataArray["mg_order_lines_mst"][".closePopupAfterAdd"] = 1;
				tdataArray["mg_order_lines_mst"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["mg_order_lines_mst"][".list"] = true;
			}
			tdataArray["mg_order_lines_mst"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["mg_order_lines_mst"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["mg_order_lines_mst"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["mg_order_lines_mst"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["mg_order_lines_mst"][".printFriendly"] = true;
			}
			tdataArray["mg_order_lines_mst"][".showSimpleSearchOptions"] = true;
			tdataArray["mg_order_lines_mst"][".allowShowHideFields"] = true;
			tdataArray["mg_order_lines_mst"][".allowFieldsReordering"] = true;
			tdataArray["mg_order_lines_mst"][".isUseAjaxSuggest"] = true;


			tdataArray["mg_order_lines_mst"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["mg_order_lines_mst"][".buttonsAdded"] = false;
			tdataArray["mg_order_lines_mst"][".addPageEvents"] = false;
			tdataArray["mg_order_lines_mst"][".isUseTimeForSearch"] = false;
			tdataArray["mg_order_lines_mst"][".badgeColor"] = "5f9ea0";
			tdataArray["mg_order_lines_mst"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["mg_order_lines_mst"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["mg_order_lines_mst"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["mg_order_lines_mst"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["mg_order_lines_mst"][".googleLikeFields"].Add("clientid");
			tdataArray["mg_order_lines_mst"][".googleLikeFields"].Add("site_ref");
			tdataArray["mg_order_lines_mst"][".googleLikeFields"].Add("co_num");
			tdataArray["mg_order_lines_mst"][".googleLikeFields"].Add("co_line");
			tdataArray["mg_order_lines_mst"][".googleLikeFields"].Add("item");
			tdataArray["mg_order_lines_mst"][".googleLikeFields"].Add("description");
			tdataArray["mg_order_lines_mst"][".googleLikeFields"].Add("qty_ordered");
			tdataArray["mg_order_lines_mst"][".googleLikeFields"].Add("u_m");
			tdataArray["mg_order_lines_mst"][".googleLikeFields"].Add("discount");
			tdataArray["mg_order_lines_mst"][".googleLikeFields"].Add("price");
			tdataArray["mg_order_lines_mst"][".googleLikeFields"].Add("whse");
			tdataArray["mg_order_lines_mst"][".googleLikeFields"].Add("extprice");
			tdataArray["mg_order_lines_mst"][".tableType"] = "list";
			tdataArray["mg_order_lines_mst"][".printerPageOrientation"] = 0;
			tdataArray["mg_order_lines_mst"][".nPrinterPageScale"] = 100;
			tdataArray["mg_order_lines_mst"][".nPrinterSplitRecords"] = 40;
			tdataArray["mg_order_lines_mst"][".geocodingEnabled"] = false;
			tdataArray["mg_order_lines_mst"][".pageSize"] = 20;
			tdataArray["mg_order_lines_mst"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["mg_order_lines_mst"][".strOrderBy"] = tstrOrderBy;
			tdataArray["mg_order_lines_mst"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["mg_order_lines_mst"][".sqlHead"] = "SELECT clientid,  	site_ref,  	co_num,  	co_line,  	item,  	description,  	qty_ordered,  	u_m,  	discount,  	price,  	whse,  	qty_ordered * 	price extprice";
			tdataArray["mg_order_lines_mst"][".sqlFrom"] = "FROM dbo.mg_order_lines_mst";
			tdataArray["mg_order_lines_mst"][".sqlWhereExpr"] = "";
			tdataArray["mg_order_lines_mst"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["mg_order_lines_mst"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["mg_order_lines_mst"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["mg_order_lines_mst"][".highlightSearchResults"] = true;
			tableKeysArray["mg_order_lines_mst"] = SettingsMap.GetArray();
			tableKeysArray["mg_order_lines_mst"].Add("co_num");
			tableKeysArray["mg_order_lines_mst"].Add("co_line");
			tdataArray["mg_order_lines_mst"][".Keys"] = tableKeysArray["mg_order_lines_mst"];
			tdataArray["mg_order_lines_mst"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "clientid";
			fdata["GoodName"] = "clientid";
			fdata["ownerTable"] = "dbo.mg_order_lines_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_order_lines_mst","clientid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "clientid";
			fdata["sourceSingle"] = "clientid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "clientid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_order_lines_mst"]["clientid"] = fdata;
			tdataArray["mg_order_lines_mst"][".searchableFields"].Add("clientid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "site_ref";
			fdata["GoodName"] = "site_ref";
			fdata["ownerTable"] = "dbo.mg_order_lines_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_order_lines_mst","site_ref");
			fdata["FieldType"] = 202;
			fdata["strField"] = "site_ref";
			fdata["sourceSingle"] = "site_ref";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "site_ref";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_order_lines_mst"]["site_ref"] = fdata;
			tdataArray["mg_order_lines_mst"][".searchableFields"].Add("site_ref");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "co_num";
			fdata["GoodName"] = "co_num";
			fdata["ownerTable"] = "dbo.mg_order_lines_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_order_lines_mst","co_num");
			fdata["FieldType"] = 202;
			fdata["strField"] = "co_num";
			fdata["sourceSingle"] = "co_num";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "co_num";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_order_lines_mst"]["co_num"] = fdata;
			tdataArray["mg_order_lines_mst"][".searchableFields"].Add("co_num");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "co_line";
			fdata["GoodName"] = "co_line";
			fdata["ownerTable"] = "dbo.mg_order_lines_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_order_lines_mst","co_line");
			fdata["FieldType"] = 3;
			fdata["strField"] = "co_line";
			fdata["sourceSingle"] = "co_line";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "co_line";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_order_lines_mst"]["co_line"] = fdata;
			tdataArray["mg_order_lines_mst"][".searchableFields"].Add("co_line");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "item";
			fdata["GoodName"] = "item";
			fdata["ownerTable"] = "dbo.mg_order_lines_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_order_lines_mst","item");
			fdata["FieldType"] = 202;
			fdata["strField"] = "item";
			fdata["sourceSingle"] = "item";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "item";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_order_lines_mst"]["item"] = fdata;
			tdataArray["mg_order_lines_mst"][".searchableFields"].Add("item");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "description";
			fdata["GoodName"] = "description";
			fdata["ownerTable"] = "dbo.mg_order_lines_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_order_lines_mst","description");
			fdata["FieldType"] = 202;
			fdata["strField"] = "description";
			fdata["sourceSingle"] = "description";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "description";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=40");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_order_lines_mst"]["description"] = fdata;
			tdataArray["mg_order_lines_mst"][".searchableFields"].Add("description");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "qty_ordered";
			fdata["GoodName"] = "qty_ordered";
			fdata["ownerTable"] = "dbo.mg_order_lines_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_order_lines_mst","qty_ordered");
			fdata["FieldType"] = 3;
			fdata["strField"] = "qty_ordered";
			fdata["sourceSingle"] = "qty_ordered";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "qty_ordered";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_order_lines_mst"]["qty_ordered"] = fdata;
			tdataArray["mg_order_lines_mst"][".searchableFields"].Add("qty_ordered");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "u_m";
			fdata["GoodName"] = "u_m";
			fdata["ownerTable"] = "dbo.mg_order_lines_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_order_lines_mst","u_m");
			fdata["FieldType"] = 202;
			fdata["strField"] = "u_m";
			fdata["sourceSingle"] = "u_m";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "u_m";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_order_lines_mst"]["u_m"] = fdata;
			tdataArray["mg_order_lines_mst"][".searchableFields"].Add("u_m");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "discount";
			fdata["GoodName"] = "discount";
			fdata["ownerTable"] = "dbo.mg_order_lines_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_order_lines_mst","discount");
			fdata["FieldType"] = 14;
			fdata["strField"] = "discount";
			fdata["sourceSingle"] = "discount";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "discount";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_order_lines_mst"]["discount"] = fdata;
			tdataArray["mg_order_lines_mst"][".searchableFields"].Add("discount");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "price";
			fdata["GoodName"] = "price";
			fdata["ownerTable"] = "dbo.mg_order_lines_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_order_lines_mst","price");
			fdata["FieldType"] = 14;
			fdata["strField"] = "price";
			fdata["sourceSingle"] = "price";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "price";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Currency");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_order_lines_mst"]["price"] = fdata;
			tdataArray["mg_order_lines_mst"][".searchableFields"].Add("price");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "whse";
			fdata["GoodName"] = "whse";
			fdata["ownerTable"] = "dbo.mg_order_lines_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_order_lines_mst","whse");
			fdata["FieldType"] = 202;
			fdata["strField"] = "whse";
			fdata["sourceSingle"] = "whse";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "whse";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_order_lines_mst"]["whse"] = fdata;
			tdataArray["mg_order_lines_mst"][".searchableFields"].Add("whse");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "extprice";
			fdata["GoodName"] = "extprice";
			fdata["ownerTable"] = "";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_order_lines_mst","extprice");
			fdata["FieldType"] = 131;
			fdata["strField"] = "extprice";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "qty_ordered * 	price";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Currency");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_order_lines_mst"]["extprice"] = fdata;
			tdataArray["mg_order_lines_mst"][".searchableFields"].Add("extprice");
			GlobalVars.tables_data["dbo.mg_order_lines_mst"] = tdataArray["mg_order_lines_mst"];
			GlobalVars.field_labels["dbo_mg_order_lines_mst"] = fieldLabelsArray["mg_order_lines_mst"];
			GlobalVars.fieldToolTips["dbo_mg_order_lines_mst"] = fieldToolTipsArray["mg_order_lines_mst"];
			GlobalVars.placeHolders["dbo_mg_order_lines_mst"] = placeHoldersArray["mg_order_lines_mst"];
			GlobalVars.page_titles["dbo_mg_order_lines_mst"] = pageTitlesArray["mg_order_lines_mst"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.mg_order_lines_mst"));
			GlobalVars.detailsTablesData["dbo.mg_order_lines_mst"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.mg_order_lines_mst"] = SettingsMap.GetArray();


			strOriginalDetailsTable = "dbo.mg_order_mst";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "dbo.mg_order_mst";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "mg_order_mst";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo.mg_order_lines_mst"][0] = masterParams;
			GlobalVars.masterTablesData["dbo.mg_order_lines_mst"][0]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.mg_order_lines_mst"][0]["masterKeys"].Add("co_num");
			GlobalVars.masterTablesData["dbo.mg_order_lines_mst"][0]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.mg_order_lines_mst"][0]["detailKeys"].Add("co_num");

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "clientid,  	site_ref,  	co_num,  	co_line,  	item,  	description,  	qty_ordered,  	u_m,  	discount,  	price,  	whse,  	qty_ordered * 	price extprice";
protoArray["0"]["m_strFrom"] = "FROM dbo.mg_order_lines_mst";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "clientid", "m_strTable", "dbo.mg_order_lines_mst", "m_srcTableName", "dbo.mg_order_lines_mst"));

protoArray["6"]["m_sql"] = "clientid";
protoArray["6"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "site_ref", "m_strTable", "dbo.mg_order_lines_mst", "m_srcTableName", "dbo.mg_order_lines_mst"));

protoArray["8"]["m_sql"] = "site_ref";
protoArray["8"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "co_num", "m_strTable", "dbo.mg_order_lines_mst", "m_srcTableName", "dbo.mg_order_lines_mst"));

protoArray["10"]["m_sql"] = "co_num";
protoArray["10"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "co_line", "m_strTable", "dbo.mg_order_lines_mst", "m_srcTableName", "dbo.mg_order_lines_mst"));

protoArray["12"]["m_sql"] = "co_line";
protoArray["12"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "item", "m_strTable", "dbo.mg_order_lines_mst", "m_srcTableName", "dbo.mg_order_lines_mst"));

protoArray["14"]["m_sql"] = "item";
protoArray["14"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "description", "m_strTable", "dbo.mg_order_lines_mst", "m_srcTableName", "dbo.mg_order_lines_mst"));

protoArray["16"]["m_sql"] = "description";
protoArray["16"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "qty_ordered", "m_strTable", "dbo.mg_order_lines_mst", "m_srcTableName", "dbo.mg_order_lines_mst"));

protoArray["18"]["m_sql"] = "qty_ordered";
protoArray["18"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "u_m", "m_strTable", "dbo.mg_order_lines_mst", "m_srcTableName", "dbo.mg_order_lines_mst"));

protoArray["20"]["m_sql"] = "u_m";
protoArray["20"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "discount", "m_strTable", "dbo.mg_order_lines_mst", "m_srcTableName", "dbo.mg_order_lines_mst"));

protoArray["22"]["m_sql"] = "discount";
protoArray["22"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "price", "m_strTable", "dbo.mg_order_lines_mst", "m_srcTableName", "dbo.mg_order_lines_mst"));

protoArray["24"]["m_sql"] = "price";
protoArray["24"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "whse", "m_strTable", "dbo.mg_order_lines_mst", "m_srcTableName", "dbo.mg_order_lines_mst"));

protoArray["26"]["m_sql"] = "whse";
protoArray["26"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLNonParsed(new XVar("m_sql", "qty_ordered * 	price"));

protoArray["28"]["m_sql"] = "qty_ordered * 	price";
protoArray["28"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "extprice";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["30"] = SettingsMap.GetArray();
protoArray["30"]["m_link"] = "SQLL_MAIN";
protoArray["31"] = SettingsMap.GetArray();
protoArray["31"]["m_strName"] = "dbo.mg_order_lines_mst";
protoArray["31"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["31"]["m_columns"] = SettingsMap.GetArray();
protoArray["31"]["m_columns"].Add("clientid");
protoArray["31"]["m_columns"].Add("site_ref");
protoArray["31"]["m_columns"].Add("co_num");
protoArray["31"]["m_columns"].Add("co_line");
protoArray["31"]["m_columns"].Add("item");
protoArray["31"]["m_columns"].Add("description");
protoArray["31"]["m_columns"].Add("qty_ordered");
protoArray["31"]["m_columns"].Add("u_m");
protoArray["31"]["m_columns"].Add("discount");
protoArray["31"]["m_columns"].Add("price");
protoArray["31"]["m_columns"].Add("whse");
protoArray["31"]["m_columns"].Add("increment_id");
protoArray["31"]["m_columns"].Add("due_date");
protoArray["31"]["m_columns"].Add("tax_code1");
protoArray["31"]["m_columns"].Add("item_id");
protoArray["31"]["m_columns"].Add("product_type");
obj = new SQLTable(protoArray["31"]);

protoArray["30"]["m_table"] = obj;
protoArray["30"]["m_sql"] = "dbo.mg_order_lines_mst";
protoArray["30"]["m_alias"] = "";
protoArray["30"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
protoArray["32"] = SettingsMap.GetArray();
protoArray["32"]["m_sql"] = "";
protoArray["32"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["32"]["m_column"] = obj;
protoArray["32"]["m_contained"] = SettingsMap.GetArray();
protoArray["32"]["m_strCase"] = "";
protoArray["32"]["m_havingmode"] = false;
protoArray["32"]["m_inBrackets"] = false;
protoArray["32"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["32"]);

protoArray["30"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["30"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.mg_order_lines_mst";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["mg_order_lines_mst"] = obj;

				
		
			tdataArray["mg_order_lines_mst"][".sqlquery"] = queryData_Array["mg_order_lines_mst"];
			tdataArray["mg_order_lines_mst"][".hasEvents"] = false;
		}
	}

}
