using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_mg_products_mst
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["mg_products_mst"] = SettingsMap.GetArray();
			tdataArray["mg_products_mst"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["mg_products_mst"][".ShortName"] = "mg_products_mst";
			tdataArray["mg_products_mst"][".OwnerID"] = "";
			tdataArray["mg_products_mst"][".OriginalTable"] = "dbo.mg_products_mst";
			tdataArray["mg_products_mst"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}"));
			tdataArray["mg_products_mst"][".originalPagesByType"] = tdataArray["mg_products_mst"][".pagesByType"];
			tdataArray["mg_products_mst"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}")));
			tdataArray["mg_products_mst"][".originalPages"] = tdataArray["mg_products_mst"][".pages"];
			tdataArray["mg_products_mst"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\",\"view\":\"view\"}"));
			tdataArray["mg_products_mst"][".originalDefaultPages"] = tdataArray["mg_products_mst"][".defaultPages"];
			fieldLabelsArray["mg_products_mst"] = SettingsMap.GetArray();
			fieldToolTipsArray["mg_products_mst"] = SettingsMap.GetArray();
			pageTitlesArray["mg_products_mst"] = SettingsMap.GetArray();
			placeHoldersArray["mg_products_mst"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["mg_products_mst"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["mg_products_mst"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["mg_products_mst"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["mg_products_mst"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["mg_products_mst"]["English"]["clientid"] = "Clientid";
				fieldToolTipsArray["mg_products_mst"]["English"]["clientid"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["clientid"] = "";
				fieldLabelsArray["mg_products_mst"]["English"]["site_ref"] = "Site Ref";
				fieldToolTipsArray["mg_products_mst"]["English"]["site_ref"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["site_ref"] = "";
				fieldLabelsArray["mg_products_mst"]["English"]["id"] = "Id";
				fieldToolTipsArray["mg_products_mst"]["English"]["id"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["id"] = "";
				fieldLabelsArray["mg_products_mst"]["English"]["sku"] = "Sku";
				fieldToolTipsArray["mg_products_mst"]["English"]["sku"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["sku"] = "";
				fieldLabelsArray["mg_products_mst"]["English"]["attribute_set_id"] = "Attribute Set Id";
				fieldToolTipsArray["mg_products_mst"]["English"]["attribute_set_id"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["attribute_set_id"] = "";
				fieldLabelsArray["mg_products_mst"]["English"]["price"] = "Price";
				fieldToolTipsArray["mg_products_mst"]["English"]["price"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["price"] = "";
				fieldLabelsArray["mg_products_mst"]["English"]["status"] = "Status";
				fieldToolTipsArray["mg_products_mst"]["English"]["status"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["status"] = "";
				fieldLabelsArray["mg_products_mst"]["English"]["visibility"] = "Visibility";
				fieldToolTipsArray["mg_products_mst"]["English"]["visibility"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["visibility"] = "";
				fieldLabelsArray["mg_products_mst"]["English"]["type_id"] = "Type Id";
				fieldToolTipsArray["mg_products_mst"]["English"]["type_id"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["type_id"] = "";
				fieldLabelsArray["mg_products_mst"]["English"]["created_at"] = "Created At";
				fieldToolTipsArray["mg_products_mst"]["English"]["created_at"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["created_at"] = "";
				fieldLabelsArray["mg_products_mst"]["English"]["updated_at"] = "Updated At";
				fieldToolTipsArray["mg_products_mst"]["English"]["updated_at"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["updated_at"] = "";
				fieldLabelsArray["mg_products_mst"]["English"]["weight"] = "Weight";
				fieldToolTipsArray["mg_products_mst"]["English"]["weight"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["weight"] = "";
				fieldLabelsArray["mg_products_mst"]["English"]["custom_attributes"] = "Custom Attributes";
				fieldToolTipsArray["mg_products_mst"]["English"]["custom_attributes"] = "";
				placeHoldersArray["mg_products_mst"]["English"]["custom_attributes"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["mg_products_mst"]["English"])))
				{
					tdataArray["mg_products_mst"][".isUseToolTips"] = true;
				}
			}
			tdataArray["mg_products_mst"][".NCSearch"] = true;
			tdataArray["mg_products_mst"][".shortTableName"] = "mg_products_mst";
			tdataArray["mg_products_mst"][".nSecOptions"] = 0;
			tdataArray["mg_products_mst"][".mainTableOwnerID"] = "";
			tdataArray["mg_products_mst"][".entityType"] = 0;
			tdataArray["mg_products_mst"][".connId"] = "Hubkoratec218206166241compute1";
			tdataArray["mg_products_mst"][".strOriginalTableName"] = "dbo.mg_products_mst";
			tdataArray["mg_products_mst"][".showAddInPopup"] = false;
			tdataArray["mg_products_mst"][".showEditInPopup"] = false;
			tdataArray["mg_products_mst"][".showViewInPopup"] = false;
			tdataArray["mg_products_mst"][".listAjax"] = false;
			tdataArray["mg_products_mst"][".audit"] = true;
			tdataArray["mg_products_mst"][".locking"] = false;
			GlobalVars.pages = tdataArray["mg_products_mst"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["mg_products_mst"][".edit"] = true;
				tdataArray["mg_products_mst"][".afterEditAction"] = 1;
				tdataArray["mg_products_mst"][".closePopupAfterEdit"] = 1;
				tdataArray["mg_products_mst"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["mg_products_mst"][".add"] = true;
				tdataArray["mg_products_mst"][".afterAddAction"] = 1;
				tdataArray["mg_products_mst"][".closePopupAfterAdd"] = 1;
				tdataArray["mg_products_mst"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["mg_products_mst"][".list"] = true;
			}
			tdataArray["mg_products_mst"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["mg_products_mst"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["mg_products_mst"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["mg_products_mst"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["mg_products_mst"][".printFriendly"] = true;
			}
			tdataArray["mg_products_mst"][".showSimpleSearchOptions"] = true;
			tdataArray["mg_products_mst"][".allowShowHideFields"] = true;
			tdataArray["mg_products_mst"][".allowFieldsReordering"] = true;
			tdataArray["mg_products_mst"][".isUseAjaxSuggest"] = true;


			tdataArray["mg_products_mst"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["mg_products_mst"][".buttonsAdded"] = false;
			tdataArray["mg_products_mst"][".addPageEvents"] = false;
			tdataArray["mg_products_mst"][".isUseTimeForSearch"] = false;
			tdataArray["mg_products_mst"][".badgeColor"] = "2F4F4F";
			tdataArray["mg_products_mst"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["mg_products_mst"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["mg_products_mst"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["mg_products_mst"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("clientid");
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("site_ref");
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("id");
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("sku");
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("attribute_set_id");
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("price");
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("status");
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("visibility");
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("type_id");
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("created_at");
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("updated_at");
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("weight");
			tdataArray["mg_products_mst"][".googleLikeFields"].Add("custom_attributes");
			tdataArray["mg_products_mst"][".tableType"] = "list";
			tdataArray["mg_products_mst"][".printerPageOrientation"] = 0;
			tdataArray["mg_products_mst"][".nPrinterPageScale"] = 100;
			tdataArray["mg_products_mst"][".nPrinterSplitRecords"] = 40;
			tdataArray["mg_products_mst"][".geocodingEnabled"] = false;
			tdataArray["mg_products_mst"][".pageSize"] = 20;
			tdataArray["mg_products_mst"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["mg_products_mst"][".strOrderBy"] = tstrOrderBy;
			tdataArray["mg_products_mst"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["mg_products_mst"][".sqlHead"] = "SELECT clientid,  	site_ref,  	id,  	sku,  	attribute_set_id,  	price,  	status,  	visibility,  	type_id,  	created_at,  	updated_at,  	weight,  	custom_attributes";
			tdataArray["mg_products_mst"][".sqlFrom"] = "FROM dbo.mg_products_mst";
			tdataArray["mg_products_mst"][".sqlWhereExpr"] = "";
			tdataArray["mg_products_mst"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["mg_products_mst"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["mg_products_mst"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["mg_products_mst"][".highlightSearchResults"] = true;
			tableKeysArray["mg_products_mst"] = SettingsMap.GetArray();
			tableKeysArray["mg_products_mst"].Add("id");
			tdataArray["mg_products_mst"][".Keys"] = tableKeysArray["mg_products_mst"];
			tdataArray["mg_products_mst"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "clientid";
			fdata["GoodName"] = "clientid";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","clientid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "clientid";
			fdata["sourceSingle"] = "clientid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "clientid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=40");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["clientid"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("clientid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "site_ref";
			fdata["GoodName"] = "site_ref";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","site_ref");
			fdata["FieldType"] = 202;
			fdata["strField"] = "site_ref";
			fdata["sourceSingle"] = "site_ref";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "site_ref";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["site_ref"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("site_ref");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "id";
			fdata["GoodName"] = "id";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","id");
			fdata["FieldType"] = 202;
			fdata["strField"] = "id";
			fdata["sourceSingle"] = "id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["id"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "sku";
			fdata["GoodName"] = "sku";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","sku");
			fdata["FieldType"] = 202;
			fdata["strField"] = "sku";
			fdata["sourceSingle"] = "sku";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "sku";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=500");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["sku"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("sku");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "attribute_set_id";
			fdata["GoodName"] = "attribute_set_id";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","attribute_set_id");
			fdata["FieldType"] = 202;
			fdata["strField"] = "attribute_set_id";
			fdata["sourceSingle"] = "attribute_set_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "attribute_set_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["attribute_set_id"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("attribute_set_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "price";
			fdata["GoodName"] = "price";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","price");
			fdata["FieldType"] = 14;
			fdata["strField"] = "price";
			fdata["sourceSingle"] = "price";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "price";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["price"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("price");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "status";
			fdata["GoodName"] = "status";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","status");
			fdata["FieldType"] = 202;
			fdata["strField"] = "status";
			fdata["sourceSingle"] = "status";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "status";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["status"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("status");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "visibility";
			fdata["GoodName"] = "visibility";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","visibility");
			fdata["FieldType"] = 202;
			fdata["strField"] = "visibility";
			fdata["sourceSingle"] = "visibility";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "visibility";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["visibility"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("visibility");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "type_id";
			fdata["GoodName"] = "type_id";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","type_id");
			fdata["FieldType"] = 202;
			fdata["strField"] = "type_id";
			fdata["sourceSingle"] = "type_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "type_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["type_id"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("type_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "created_at";
			fdata["GoodName"] = "created_at";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","created_at");
			fdata["FieldType"] = 202;
			fdata["strField"] = "created_at";
			fdata["sourceSingle"] = "created_at";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "created_at";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["created_at"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("created_at");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "updated_at";
			fdata["GoodName"] = "updated_at";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","updated_at");
			fdata["FieldType"] = 202;
			fdata["strField"] = "updated_at";
			fdata["sourceSingle"] = "updated_at";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "updated_at";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["updated_at"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("updated_at");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "weight";
			fdata["GoodName"] = "weight";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","weight");
			fdata["FieldType"] = 202;
			fdata["strField"] = "weight";
			fdata["sourceSingle"] = "weight";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "weight";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["weight"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("weight");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "custom_attributes";
			fdata["GoodName"] = "custom_attributes";
			fdata["ownerTable"] = "dbo.mg_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_mg_products_mst","custom_attributes");
			fdata["FieldType"] = 202;
			fdata["strField"] = "custom_attributes";
			fdata["sourceSingle"] = "custom_attributes";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "custom_attributes";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["mg_products_mst"]["custom_attributes"] = fdata;
			tdataArray["mg_products_mst"][".searchableFields"].Add("custom_attributes");
			GlobalVars.tables_data["dbo.mg_products_mst"] = tdataArray["mg_products_mst"];
			GlobalVars.field_labels["dbo_mg_products_mst"] = fieldLabelsArray["mg_products_mst"];
			GlobalVars.fieldToolTips["dbo_mg_products_mst"] = fieldToolTipsArray["mg_products_mst"];
			GlobalVars.placeHolders["dbo_mg_products_mst"] = placeHoldersArray["mg_products_mst"];
			GlobalVars.page_titles["dbo_mg_products_mst"] = pageTitlesArray["mg_products_mst"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.mg_products_mst"));
			GlobalVars.detailsTablesData["dbo.mg_products_mst"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.mg_products_mst"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "clientid,  	site_ref,  	id,  	sku,  	attribute_set_id,  	price,  	status,  	visibility,  	type_id,  	created_at,  	updated_at,  	weight,  	custom_attributes";
protoArray["0"]["m_strFrom"] = "FROM dbo.mg_products_mst";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "clientid", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["6"]["m_sql"] = "clientid";
protoArray["6"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "site_ref", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["8"]["m_sql"] = "site_ref";
protoArray["8"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "id", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["10"]["m_sql"] = "id";
protoArray["10"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "sku", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["12"]["m_sql"] = "sku";
protoArray["12"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "attribute_set_id", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["14"]["m_sql"] = "attribute_set_id";
protoArray["14"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "price", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["16"]["m_sql"] = "price";
protoArray["16"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "status", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["18"]["m_sql"] = "status";
protoArray["18"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "visibility", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["20"]["m_sql"] = "visibility";
protoArray["20"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "type_id", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["22"]["m_sql"] = "type_id";
protoArray["22"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "created_at", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["24"]["m_sql"] = "created_at";
protoArray["24"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "updated_at", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["26"]["m_sql"] = "updated_at";
protoArray["26"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "weight", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["28"]["m_sql"] = "weight";
protoArray["28"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "custom_attributes", "m_strTable", "dbo.mg_products_mst", "m_srcTableName", "dbo.mg_products_mst"));

protoArray["30"]["m_sql"] = "custom_attributes";
protoArray["30"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["32"] = SettingsMap.GetArray();
protoArray["32"]["m_link"] = "SQLL_MAIN";
protoArray["33"] = SettingsMap.GetArray();
protoArray["33"]["m_strName"] = "dbo.mg_products_mst";
protoArray["33"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["33"]["m_columns"] = SettingsMap.GetArray();
protoArray["33"]["m_columns"].Add("clientid");
protoArray["33"]["m_columns"].Add("site_ref");
protoArray["33"]["m_columns"].Add("id");
protoArray["33"]["m_columns"].Add("sku");
protoArray["33"]["m_columns"].Add("attribute_set_id");
protoArray["33"]["m_columns"].Add("price");
protoArray["33"]["m_columns"].Add("status");
protoArray["33"]["m_columns"].Add("visibility");
protoArray["33"]["m_columns"].Add("type_id");
protoArray["33"]["m_columns"].Add("created_at");
protoArray["33"]["m_columns"].Add("updated_at");
protoArray["33"]["m_columns"].Add("weight");
protoArray["33"]["m_columns"].Add("custom_attributes");
obj = new SQLTable(protoArray["33"]);

protoArray["32"]["m_table"] = obj;
protoArray["32"]["m_sql"] = "dbo.mg_products_mst";
protoArray["32"]["m_alias"] = "";
protoArray["32"]["m_srcTableName"] = "dbo.mg_products_mst";
protoArray["34"] = SettingsMap.GetArray();
protoArray["34"]["m_sql"] = "";
protoArray["34"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["34"]["m_column"] = obj;
protoArray["34"]["m_contained"] = SettingsMap.GetArray();
protoArray["34"]["m_strCase"] = "";
protoArray["34"]["m_havingmode"] = false;
protoArray["34"]["m_inBrackets"] = false;
protoArray["34"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["34"]);

protoArray["32"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["32"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.mg_products_mst";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["mg_products_mst"] = obj;

				
		
			tdataArray["mg_products_mst"][".sqlquery"] = queryData_Array["mg_products_mst"];
			tdataArray["mg_products_mst"][".hasEvents"] = false;
		}
	}

}
