using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_sc_expensereport_mst
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["sc_expensereport_mst"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_mst"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_mst"][".ShortName"] = "sc_expensereport_mst";
			tdataArray["sc_expensereport_mst"][".OwnerID"] = "clientid";
			tdataArray["sc_expensereport_mst"][".OriginalTable"] = "dbo.sc_expensereport_mst";
			tdataArray["sc_expensereport_mst"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"masterlist\":[\"masterlist\"],\"masterprint\":[\"masterprint\"],\"print\":[\"print\"],\"search\":[\"search\"]}"));
			tdataArray["sc_expensereport_mst"][".originalPagesByType"] = tdataArray["sc_expensereport_mst"][".pagesByType"];
			tdataArray["sc_expensereport_mst"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"masterlist\":[\"masterlist\"],\"masterprint\":[\"masterprint\"],\"print\":[\"print\"],\"search\":[\"search\"]}")));
			tdataArray["sc_expensereport_mst"][".originalPages"] = tdataArray["sc_expensereport_mst"][".pages"];
			tdataArray["sc_expensereport_mst"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"masterlist\":\"masterlist\",\"masterprint\":\"masterprint\",\"print\":\"print\",\"search\":\"search\"}"));
			tdataArray["sc_expensereport_mst"][".originalDefaultPages"] = tdataArray["sc_expensereport_mst"][".defaultPages"];
			fieldLabelsArray["sc_expensereport_mst"] = SettingsMap.GetArray();
			fieldToolTipsArray["sc_expensereport_mst"] = SettingsMap.GetArray();
			pageTitlesArray["sc_expensereport_mst"] = SettingsMap.GetArray();
			placeHoldersArray["sc_expensereport_mst"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["sc_expensereport_mst"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["sc_expensereport_mst"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["sc_expensereport_mst"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["sc_expensereport_mst"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["sc_expensereport_mst"]["English"]["site_ref"] = "Site Ref";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["site_ref"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["site_ref"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["report_id"] = "Report Id";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["report_id"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["report_id"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["uri"] = "Uri";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["uri"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["uri"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["name"] = "Name";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["name"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["name"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["total"] = "Total";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["total"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["total"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["curr_code"] = "Curr Code";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["curr_code"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["curr_code"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["clientid"] = "Clientid";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["clientid"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["clientid"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["createdate"] = "Createdate";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["createdate"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["createdate"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["submitdate"] = "Submitdate";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["submitdate"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["submitdate"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["ownerloginid"] = "Ownerloginid";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["ownerloginid"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["ownerloginid"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["ownername"] = "Ownername";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["ownername"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["ownername"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["country"] = "Country";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["country"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["country"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["reportdate"] = "Reportdate";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["reportdate"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["reportdate"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["concuruserid"] = "Concuruserid";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["concuruserid"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["concuruserid"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["vend_num"] = "Vend Num";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["vend_num"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["vend_num"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["trans_num"] = "Trans Num";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["trans_num"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["trans_num"] = "";
				fieldLabelsArray["sc_expensereport_mst"]["English"]["posted"] = "Posted";
				fieldToolTipsArray["sc_expensereport_mst"]["English"]["posted"] = "";
				placeHoldersArray["sc_expensereport_mst"]["English"]["posted"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["sc_expensereport_mst"]["English"])))
				{
					tdataArray["sc_expensereport_mst"][".isUseToolTips"] = true;
				}
			}
			tdataArray["sc_expensereport_mst"][".NCSearch"] = true;
			tdataArray["sc_expensereport_mst"][".shortTableName"] = "sc_expensereport_mst";
			tdataArray["sc_expensereport_mst"][".nSecOptions"] = 1;
			tdataArray["sc_expensereport_mst"][".mainTableOwnerID"] = "clientid";
			tdataArray["sc_expensereport_mst"][".entityType"] = 0;
			tdataArray["sc_expensereport_mst"][".connId"] = "Hubkoratec218206166241compute1";
			tdataArray["sc_expensereport_mst"][".strOriginalTableName"] = "dbo.sc_expensereport_mst";
			tdataArray["sc_expensereport_mst"][".showAddInPopup"] = false;
			tdataArray["sc_expensereport_mst"][".showEditInPopup"] = false;
			tdataArray["sc_expensereport_mst"][".showViewInPopup"] = false;
			tdataArray["sc_expensereport_mst"][".listAjax"] = false;
			tdataArray["sc_expensereport_mst"][".audit"] = false;
			tdataArray["sc_expensereport_mst"][".locking"] = false;
			GlobalVars.pages = tdataArray["sc_expensereport_mst"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["sc_expensereport_mst"][".edit"] = true;
				tdataArray["sc_expensereport_mst"][".afterEditAction"] = 1;
				tdataArray["sc_expensereport_mst"][".closePopupAfterEdit"] = 1;
				tdataArray["sc_expensereport_mst"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["sc_expensereport_mst"][".add"] = true;
				tdataArray["sc_expensereport_mst"][".afterAddAction"] = 1;
				tdataArray["sc_expensereport_mst"][".closePopupAfterAdd"] = 1;
				tdataArray["sc_expensereport_mst"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["sc_expensereport_mst"][".list"] = true;
			}
			tdataArray["sc_expensereport_mst"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["sc_expensereport_mst"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["sc_expensereport_mst"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["sc_expensereport_mst"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["sc_expensereport_mst"][".printFriendly"] = true;
			}
			tdataArray["sc_expensereport_mst"][".showSimpleSearchOptions"] = true;
			tdataArray["sc_expensereport_mst"][".allowShowHideFields"] = true;
			tdataArray["sc_expensereport_mst"][".allowFieldsReordering"] = true;
			tdataArray["sc_expensereport_mst"][".isUseAjaxSuggest"] = true;


			tdataArray["sc_expensereport_mst"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["sc_expensereport_mst"][".buttonsAdded"] = false;
			tdataArray["sc_expensereport_mst"][".addPageEvents"] = false;
			tdataArray["sc_expensereport_mst"][".isUseTimeForSearch"] = false;
			tdataArray["sc_expensereport_mst"][".badgeColor"] = "EDCA00";
			tdataArray["sc_expensereport_mst"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_mst"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_mst"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_mst"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("site_ref");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("report_id");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("uri");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("name");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("total");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("curr_code");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("clientid");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("createdate");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("submitdate");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("ownerloginid");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("ownername");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("country");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("reportdate");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("concuruserid");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("vend_num");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("trans_num");
			tdataArray["sc_expensereport_mst"][".googleLikeFields"].Add("posted");
			tdataArray["sc_expensereport_mst"][".tableType"] = "list";
			tdataArray["sc_expensereport_mst"][".printerPageOrientation"] = 0;
			tdataArray["sc_expensereport_mst"][".nPrinterPageScale"] = 100;
			tdataArray["sc_expensereport_mst"][".nPrinterSplitRecords"] = 40;
			tdataArray["sc_expensereport_mst"][".geocodingEnabled"] = false;
			tdataArray["sc_expensereport_mst"][".pageSize"] = 20;
			tdataArray["sc_expensereport_mst"][".warnLeavingPages"] = true;
			tstrOrderBy = "order by trans_num";
			tdataArray["sc_expensereport_mst"][".strOrderBy"] = tstrOrderBy;
			tdataArray["sc_expensereport_mst"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_mst"][".orderindexes"].Add(new XVar(0, 16, 1, (XVar.Pack(1) ? XVar.Pack("ASC") : XVar.Pack("DESC")), 2, "trans_num"));
			tdataArray["sc_expensereport_mst"][".sqlHead"] = "SELECT site_ref,  	report_id,  	uri,  	name,  	total,  	curr_code,  	clientid,  	createdate,  	submitdate,  	ownerloginid,  	ownername,  	country,  	reportdate,  	concuruserid,  	vend_num,  	trans_num,  	posted";
			tdataArray["sc_expensereport_mst"][".sqlFrom"] = "FROM dbo.sc_expensereport_mst";
			tdataArray["sc_expensereport_mst"][".sqlWhereExpr"] = "";
			tdataArray["sc_expensereport_mst"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["sc_expensereport_mst"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["sc_expensereport_mst"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["sc_expensereport_mst"][".highlightSearchResults"] = true;
			tableKeysArray["sc_expensereport_mst"] = SettingsMap.GetArray();
			tableKeysArray["sc_expensereport_mst"].Add("report_id");
			tdataArray["sc_expensereport_mst"][".Keys"] = tableKeysArray["sc_expensereport_mst"];
			tdataArray["sc_expensereport_mst"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "site_ref";
			fdata["GoodName"] = "site_ref";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","site_ref");
			fdata["FieldType"] = 202;
			fdata["strField"] = "site_ref";
			fdata["sourceSingle"] = "site_ref";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "site_ref";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["site_ref"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("site_ref");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "report_id";
			fdata["GoodName"] = "report_id";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","report_id");
			fdata["FieldType"] = 202;
			fdata["strField"] = "report_id";
			fdata["sourceSingle"] = "report_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "report_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["report_id"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("report_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "uri";
			fdata["GoodName"] = "uri";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","uri");
			fdata["FieldType"] = 202;
			fdata["strField"] = "uri";
			fdata["sourceSingle"] = "uri";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "uri";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=200");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["uri"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("uri");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "name";
			fdata["GoodName"] = "name";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","name");
			fdata["FieldType"] = 202;
			fdata["strField"] = "name";
			fdata["sourceSingle"] = "name";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "name";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["name"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("name");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "total";
			fdata["GoodName"] = "total";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","total");
			fdata["FieldType"] = 14;
			fdata["strField"] = "total";
			fdata["sourceSingle"] = "total";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "total";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Currency");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["total"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("total");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "curr_code";
			fdata["GoodName"] = "curr_code";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","curr_code");
			fdata["FieldType"] = 202;
			fdata["strField"] = "curr_code";
			fdata["sourceSingle"] = "curr_code";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "curr_code";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["curr_code"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("curr_code");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "clientid";
			fdata["GoodName"] = "clientid";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","clientid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "clientid";
			fdata["sourceSingle"] = "clientid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "clientid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["clientid"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("clientid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "createdate";
			fdata["GoodName"] = "createdate";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","createdate");
			fdata["FieldType"] = 135;
			fdata["strField"] = "createdate";
			fdata["sourceSingle"] = "createdate";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "createdate";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["createdate"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("createdate");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "submitdate";
			fdata["GoodName"] = "submitdate";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","submitdate");
			fdata["FieldType"] = 135;
			fdata["strField"] = "submitdate";
			fdata["sourceSingle"] = "submitdate";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "submitdate";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["submitdate"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("submitdate");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "ownerloginid";
			fdata["GoodName"] = "ownerloginid";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","ownerloginid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "ownerloginid";
			fdata["sourceSingle"] = "ownerloginid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ownerloginid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["ownerloginid"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("ownerloginid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "ownername";
			fdata["GoodName"] = "ownername";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","ownername");
			fdata["FieldType"] = 202;
			fdata["strField"] = "ownername";
			fdata["sourceSingle"] = "ownername";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ownername";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["ownername"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("ownername");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "country";
			fdata["GoodName"] = "country";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","country");
			fdata["FieldType"] = 202;
			fdata["strField"] = "country";
			fdata["sourceSingle"] = "country";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "country";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["country"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("country");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "reportdate";
			fdata["GoodName"] = "reportdate";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","reportdate");
			fdata["FieldType"] = 135;
			fdata["strField"] = "reportdate";
			fdata["sourceSingle"] = "reportdate";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "reportdate";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["reportdate"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("reportdate");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 14;
			fdata["strName"] = "concuruserid";
			fdata["GoodName"] = "concuruserid";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","concuruserid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "concuruserid";
			fdata["sourceSingle"] = "concuruserid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "concuruserid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["concuruserid"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("concuruserid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 15;
			fdata["strName"] = "vend_num";
			fdata["GoodName"] = "vend_num";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","vend_num");
			fdata["FieldType"] = 202;
			fdata["strField"] = "vend_num";
			fdata["sourceSingle"] = "vend_num";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "vend_num";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["vend_num"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("vend_num");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 16;
			fdata["strName"] = "trans_num";
			fdata["GoodName"] = "trans_num";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","trans_num");
			fdata["FieldType"] = 20;
			fdata["AutoInc"] = true;
			fdata["strField"] = "trans_num";
			fdata["sourceSingle"] = "trans_num";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "trans_num";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["trans_num"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("trans_num");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 17;
			fdata["strName"] = "posted";
			fdata["GoodName"] = "posted";
			fdata["ownerTable"] = "dbo.sc_expensereport_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_mst","posted");
			fdata["FieldType"] = 16;
			fdata["strField"] = "posted";
			fdata["sourceSingle"] = "posted";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "posted";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Checkbox");
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_mst"]["posted"] = fdata;
			tdataArray["sc_expensereport_mst"][".searchableFields"].Add("posted");
			GlobalVars.tables_data["dbo.sc_expensereport_mst"] = tdataArray["sc_expensereport_mst"];
			GlobalVars.field_labels["dbo_sc_expensereport_mst"] = fieldLabelsArray["sc_expensereport_mst"];
			GlobalVars.fieldToolTips["dbo_sc_expensereport_mst"] = fieldToolTipsArray["sc_expensereport_mst"];
			GlobalVars.placeHolders["dbo_sc_expensereport_mst"] = placeHoldersArray["sc_expensereport_mst"];
			GlobalVars.page_titles["dbo_sc_expensereport_mst"] = pageTitlesArray["sc_expensereport_mst"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.sc_expensereport_mst"));
			GlobalVars.detailsTablesData["dbo.sc_expensereport_mst"] = SettingsMap.GetArray();


			dIndex = 0;
			detailsParam = SettingsMap.GetArray();
			detailsParam["dDataSourceTable"] = "dbo.sc_expensereport_line_mst";
			detailsParam["dOriginalTable"] = "dbo.sc_expensereport_line_mst";
			detailsParam["dType"] = Constants.PAGE_LIST;
			detailsParam["dShortTable"] = "sc_expensereport_line_mst";
			detailsParam["dCaptionTable"] = CommonFunctions.GetTableCaption(new XVar("dbo_sc_expensereport_line_mst"));
			detailsParam["masterKeys"] = SettingsMap.GetArray();
			detailsParam["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.sc_expensereport_mst"][dIndex] = detailsParam;
			GlobalVars.detailsTablesData["dbo.sc_expensereport_mst"][dIndex]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.sc_expensereport_mst"][dIndex]["masterKeys"].Add("report_id");
			GlobalVars.detailsTablesData["dbo.sc_expensereport_mst"][dIndex]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.detailsTablesData["dbo.sc_expensereport_mst"][dIndex]["detailKeys"].Add("report_id");
			GlobalVars.masterTablesData["dbo.sc_expensereport_mst"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "site_ref,  	report_id,  	uri,  	name,  	total,  	curr_code,  	clientid,  	createdate,  	submitdate,  	ownerloginid,  	ownername,  	country,  	reportdate,  	concuruserid,  	vend_num,  	trans_num,  	posted";
protoArray["0"]["m_strFrom"] = "FROM dbo.sc_expensereport_mst";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "order by trans_num";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "site_ref", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["6"]["m_sql"] = "site_ref";
protoArray["6"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "report_id", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["8"]["m_sql"] = "report_id";
protoArray["8"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "uri", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["10"]["m_sql"] = "uri";
protoArray["10"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "name", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["12"]["m_sql"] = "name";
protoArray["12"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "total", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["14"]["m_sql"] = "total";
protoArray["14"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "curr_code", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["16"]["m_sql"] = "curr_code";
protoArray["16"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "clientid", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["18"]["m_sql"] = "clientid";
protoArray["18"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "createdate", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["20"]["m_sql"] = "createdate";
protoArray["20"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "submitdate", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["22"]["m_sql"] = "submitdate";
protoArray["22"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ownerloginid", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["24"]["m_sql"] = "ownerloginid";
protoArray["24"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ownername", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["26"]["m_sql"] = "ownername";
protoArray["26"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "country", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["28"]["m_sql"] = "country";
protoArray["28"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "reportdate", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["30"]["m_sql"] = "reportdate";
protoArray["30"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["32"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "concuruserid", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["32"]["m_sql"] = "concuruserid";
protoArray["32"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["32"]["m_expr"] = obj;
protoArray["32"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["32"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["34"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "vend_num", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["34"]["m_sql"] = "vend_num";
protoArray["34"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["34"]["m_expr"] = obj;
protoArray["34"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["34"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["36"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "trans_num", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["36"]["m_sql"] = "trans_num";
protoArray["36"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["36"]["m_expr"] = obj;
protoArray["36"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["36"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["38"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "posted", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["38"]["m_sql"] = "posted";
protoArray["38"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["38"]["m_expr"] = obj;
protoArray["38"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["38"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["40"] = SettingsMap.GetArray();
protoArray["40"]["m_link"] = "SQLL_MAIN";
protoArray["41"] = SettingsMap.GetArray();
protoArray["41"]["m_strName"] = "dbo.sc_expensereport_mst";
protoArray["41"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["41"]["m_columns"] = SettingsMap.GetArray();
protoArray["41"]["m_columns"].Add("site_ref");
protoArray["41"]["m_columns"].Add("report_id");
protoArray["41"]["m_columns"].Add("uri");
protoArray["41"]["m_columns"].Add("name");
protoArray["41"]["m_columns"].Add("total");
protoArray["41"]["m_columns"].Add("curr_code");
protoArray["41"]["m_columns"].Add("clientid");
protoArray["41"]["m_columns"].Add("createdate");
protoArray["41"]["m_columns"].Add("submitdate");
protoArray["41"]["m_columns"].Add("ownerloginid");
protoArray["41"]["m_columns"].Add("ownername");
protoArray["41"]["m_columns"].Add("country");
protoArray["41"]["m_columns"].Add("reportdate");
protoArray["41"]["m_columns"].Add("concuruserid");
protoArray["41"]["m_columns"].Add("vend_num");
protoArray["41"]["m_columns"].Add("trans_num");
protoArray["41"]["m_columns"].Add("posted");
protoArray["41"]["m_columns"].Add("lastmodifieddate");
obj = new SQLTable(protoArray["41"]);

protoArray["40"]["m_table"] = obj;
protoArray["40"]["m_sql"] = "dbo.sc_expensereport_mst";
protoArray["40"]["m_alias"] = "";
protoArray["40"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
protoArray["42"] = SettingsMap.GetArray();
protoArray["42"]["m_sql"] = "";
protoArray["42"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["42"]["m_column"] = obj;
protoArray["42"]["m_contained"] = SettingsMap.GetArray();
protoArray["42"]["m_strCase"] = "";
protoArray["42"]["m_havingmode"] = false;
protoArray["42"]["m_inBrackets"] = false;
protoArray["42"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["42"]);

protoArray["40"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["40"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["44"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "trans_num", "m_strTable", "dbo.sc_expensereport_mst", "m_srcTableName", "dbo.sc_expensereport_mst"));

protoArray["44"]["m_column"] = obj;
protoArray["44"]["m_bAsc"] = 1;
protoArray["44"]["m_nColumn"] = 0;
obj = new SQLOrderByItem(protoArray["44"]);

protoArray["0"]["m_orderby"].Add(obj);
protoArray["0"]["m_srcTableName"] = "dbo.sc_expensereport_mst";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["sc_expensereport_mst"] = obj;

				
		
			tdataArray["sc_expensereport_mst"][".sqlquery"] = queryData_Array["sc_expensereport_mst"];
			tdataArray["sc_expensereport_mst"][".hasEvents"] = false;
		}
	}

}
