using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_sc_expensereport_line_mst
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["sc_expensereport_line_mst"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_line_mst"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_line_mst"][".ShortName"] = "sc_expensereport_line_mst";
			tdataArray["sc_expensereport_line_mst"][".OwnerID"] = "";
			tdataArray["sc_expensereport_line_mst"][".OriginalTable"] = "dbo.sc_expensereport_line_mst";
			tdataArray["sc_expensereport_line_mst"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}"));
			tdataArray["sc_expensereport_line_mst"][".originalPagesByType"] = tdataArray["sc_expensereport_line_mst"][".pagesByType"];
			tdataArray["sc_expensereport_line_mst"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}")));
			tdataArray["sc_expensereport_line_mst"][".originalPages"] = tdataArray["sc_expensereport_line_mst"][".pages"];
			tdataArray["sc_expensereport_line_mst"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\"}"));
			tdataArray["sc_expensereport_line_mst"][".originalDefaultPages"] = tdataArray["sc_expensereport_line_mst"][".defaultPages"];
			fieldLabelsArray["sc_expensereport_line_mst"] = SettingsMap.GetArray();
			fieldToolTipsArray["sc_expensereport_line_mst"] = SettingsMap.GetArray();
			pageTitlesArray["sc_expensereport_line_mst"] = SettingsMap.GetArray();
			placeHoldersArray["sc_expensereport_line_mst"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["sc_expensereport_line_mst"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["sc_expensereport_line_mst"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["sc_expensereport_line_mst"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["site_ref"] = "Site Ref";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["site_ref"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["site_ref"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["report_id"] = "Report Id";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["report_id"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["report_id"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["amount"] = "Amount";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["amount"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["amount"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["curr_code"] = "Curr Code";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["curr_code"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["curr_code"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["clientid"] = "Clientid";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["clientid"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["clientid"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["account"] = "Account";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["account"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["account"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["unitcd1"] = "Unitcd1";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["unitcd1"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["unitcd1"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["unitcd2"] = "Unitcd2";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["unitcd2"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["unitcd2"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["unitcd3"] = "Unitcd3";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["unitcd3"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["unitcd3"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["unitcd4"] = "Unitcd4";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["unitcd4"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["unitcd4"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["expenseid"] = "Expenseid";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["expenseid"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["expenseid"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["ispersonalexpense"] = "Ispersonalexpense";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["ispersonalexpense"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["ispersonalexpense"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["expenseurl"] = "Expenseurl";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["expenseurl"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["expenseurl"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["rel"] = "Rel";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["rel"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["rel"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["seq"] = "Seq";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["seq"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["seq"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["project"] = "Project";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["project"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["project"] = "";
				fieldLabelsArray["sc_expensereport_line_mst"]["English"]["task"] = "Task";
				fieldToolTipsArray["sc_expensereport_line_mst"]["English"]["task"] = "";
				placeHoldersArray["sc_expensereport_line_mst"]["English"]["task"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["sc_expensereport_line_mst"]["English"])))
				{
					tdataArray["sc_expensereport_line_mst"][".isUseToolTips"] = true;
				}
			}
			tdataArray["sc_expensereport_line_mst"][".NCSearch"] = true;
			tdataArray["sc_expensereport_line_mst"][".shortTableName"] = "sc_expensereport_line_mst";
			tdataArray["sc_expensereport_line_mst"][".nSecOptions"] = 0;
			tdataArray["sc_expensereport_line_mst"][".mainTableOwnerID"] = "";
			tdataArray["sc_expensereport_line_mst"][".entityType"] = 0;
			tdataArray["sc_expensereport_line_mst"][".connId"] = "Hubkoratec218206166241compute1";
			tdataArray["sc_expensereport_line_mst"][".strOriginalTableName"] = "dbo.sc_expensereport_line_mst";
			tdataArray["sc_expensereport_line_mst"][".showAddInPopup"] = false;
			tdataArray["sc_expensereport_line_mst"][".showEditInPopup"] = false;
			tdataArray["sc_expensereport_line_mst"][".showViewInPopup"] = false;
			tdataArray["sc_expensereport_line_mst"][".listAjax"] = false;
			tdataArray["sc_expensereport_line_mst"][".audit"] = false;
			tdataArray["sc_expensereport_line_mst"][".locking"] = false;
			GlobalVars.pages = tdataArray["sc_expensereport_line_mst"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["sc_expensereport_line_mst"][".edit"] = true;
				tdataArray["sc_expensereport_line_mst"][".afterEditAction"] = 1;
				tdataArray["sc_expensereport_line_mst"][".closePopupAfterEdit"] = 1;
				tdataArray["sc_expensereport_line_mst"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["sc_expensereport_line_mst"][".add"] = true;
				tdataArray["sc_expensereport_line_mst"][".afterAddAction"] = 1;
				tdataArray["sc_expensereport_line_mst"][".closePopupAfterAdd"] = 1;
				tdataArray["sc_expensereport_line_mst"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["sc_expensereport_line_mst"][".list"] = true;
			}
			tdataArray["sc_expensereport_line_mst"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["sc_expensereport_line_mst"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["sc_expensereport_line_mst"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["sc_expensereport_line_mst"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["sc_expensereport_line_mst"][".printFriendly"] = true;
			}
			tdataArray["sc_expensereport_line_mst"][".showSimpleSearchOptions"] = true;
			tdataArray["sc_expensereport_line_mst"][".allowShowHideFields"] = true;
			tdataArray["sc_expensereport_line_mst"][".allowFieldsReordering"] = true;
			tdataArray["sc_expensereport_line_mst"][".isUseAjaxSuggest"] = true;


			tdataArray["sc_expensereport_line_mst"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["sc_expensereport_line_mst"][".buttonsAdded"] = false;
			tdataArray["sc_expensereport_line_mst"][".addPageEvents"] = false;
			tdataArray["sc_expensereport_line_mst"][".isUseTimeForSearch"] = false;
			tdataArray["sc_expensereport_line_mst"][".badgeColor"] = "b22222";
			tdataArray["sc_expensereport_line_mst"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_line_mst"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_line_mst"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("site_ref");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("report_id");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("amount");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("curr_code");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("clientid");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("account");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("unitcd1");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("unitcd2");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("unitcd3");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("unitcd4");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("expenseid");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("ispersonalexpense");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("expenseurl");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("rel");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("seq");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("project");
			tdataArray["sc_expensereport_line_mst"][".googleLikeFields"].Add("task");
			tdataArray["sc_expensereport_line_mst"][".tableType"] = "list";
			tdataArray["sc_expensereport_line_mst"][".printerPageOrientation"] = 0;
			tdataArray["sc_expensereport_line_mst"][".nPrinterPageScale"] = 100;
			tdataArray["sc_expensereport_line_mst"][".nPrinterSplitRecords"] = 40;
			tdataArray["sc_expensereport_line_mst"][".geocodingEnabled"] = false;
			tdataArray["sc_expensereport_line_mst"][".pageSize"] = 20;
			tdataArray["sc_expensereport_line_mst"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["sc_expensereport_line_mst"][".strOrderBy"] = tstrOrderBy;
			tdataArray["sc_expensereport_line_mst"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["sc_expensereport_line_mst"][".sqlHead"] = "SELECT site_ref,  	report_id,  	amount,  	curr_code,  	clientid,  	account,  	unitcd1,  	unitcd2,  	unitcd3,  	unitcd4,  	expenseid,  	ispersonalexpense,  	expenseurl,  	rel,  	seq,  	project,  	task";
			tdataArray["sc_expensereport_line_mst"][".sqlFrom"] = "FROM dbo.sc_expensereport_line_mst";
			tdataArray["sc_expensereport_line_mst"][".sqlWhereExpr"] = "";
			tdataArray["sc_expensereport_line_mst"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["sc_expensereport_line_mst"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["sc_expensereport_line_mst"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["sc_expensereport_line_mst"][".highlightSearchResults"] = true;
			tableKeysArray["sc_expensereport_line_mst"] = SettingsMap.GetArray();
			tableKeysArray["sc_expensereport_line_mst"].Add("report_id");
			tableKeysArray["sc_expensereport_line_mst"].Add("seq");
			tdataArray["sc_expensereport_line_mst"][".Keys"] = tableKeysArray["sc_expensereport_line_mst"];
			tdataArray["sc_expensereport_line_mst"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "site_ref";
			fdata["GoodName"] = "site_ref";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","site_ref");
			fdata["FieldType"] = 202;
			fdata["strField"] = "site_ref";
			fdata["sourceSingle"] = "site_ref";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "site_ref";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["site_ref"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("site_ref");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "report_id";
			fdata["GoodName"] = "report_id";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","report_id");
			fdata["FieldType"] = 202;
			fdata["strField"] = "report_id";
			fdata["sourceSingle"] = "report_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "report_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["report_id"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("report_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "amount";
			fdata["GoodName"] = "amount";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","amount");
			fdata["FieldType"] = 14;
			fdata["strField"] = "amount";
			fdata["sourceSingle"] = "amount";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "amount";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Currency");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["amount"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("amount");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "curr_code";
			fdata["GoodName"] = "curr_code";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","curr_code");
			fdata["FieldType"] = 202;
			fdata["strField"] = "curr_code";
			fdata["sourceSingle"] = "curr_code";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "curr_code";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["curr_code"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("curr_code");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "clientid";
			fdata["GoodName"] = "clientid";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","clientid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "clientid";
			fdata["sourceSingle"] = "clientid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "clientid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["clientid"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("clientid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "account";
			fdata["GoodName"] = "account";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","account");
			fdata["FieldType"] = 202;
			fdata["strField"] = "account";
			fdata["sourceSingle"] = "account";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "account";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["account"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("account");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "unitcd1";
			fdata["GoodName"] = "unitcd1";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","unitcd1");
			fdata["FieldType"] = 202;
			fdata["strField"] = "unitcd1";
			fdata["sourceSingle"] = "unitcd1";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "unitcd1";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=4");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["unitcd1"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("unitcd1");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "unitcd2";
			fdata["GoodName"] = "unitcd2";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","unitcd2");
			fdata["FieldType"] = 202;
			fdata["strField"] = "unitcd2";
			fdata["sourceSingle"] = "unitcd2";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "unitcd2";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=4");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["unitcd2"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("unitcd2");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "unitcd3";
			fdata["GoodName"] = "unitcd3";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","unitcd3");
			fdata["FieldType"] = 202;
			fdata["strField"] = "unitcd3";
			fdata["sourceSingle"] = "unitcd3";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "unitcd3";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=4");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["unitcd3"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("unitcd3");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "unitcd4";
			fdata["GoodName"] = "unitcd4";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","unitcd4");
			fdata["FieldType"] = 202;
			fdata["strField"] = "unitcd4";
			fdata["sourceSingle"] = "unitcd4";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "unitcd4";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=4");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["unitcd4"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("unitcd4");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "expenseid";
			fdata["GoodName"] = "expenseid";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","expenseid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "expenseid";
			fdata["sourceSingle"] = "expenseid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "expenseid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["expenseid"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("expenseid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "ispersonalexpense";
			fdata["GoodName"] = "ispersonalexpense";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","ispersonalexpense");
			fdata["FieldType"] = 11;
			fdata["strField"] = "ispersonalexpense";
			fdata["sourceSingle"] = "ispersonalexpense";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ispersonalexpense";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Checkbox");
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Checkbox");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterFormat"] = "Options list";
			fdata["showCollapsed"] = false;
			fdata["filterCheckedMessageType"] = "Text";
			fdata["filterCheckedMessageText"] = "Checked";
			fdata["filterUncheckedMessageType"] = "Text";
			fdata["filterUncheckedMessageText"] = "Unchecked";
			tdataArray["sc_expensereport_line_mst"]["ispersonalexpense"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("ispersonalexpense");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "expenseurl";
			fdata["GoodName"] = "expenseurl";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","expenseurl");
			fdata["FieldType"] = 202;
			fdata["strField"] = "expenseurl";
			fdata["sourceSingle"] = "expenseurl";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "expenseurl";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["expenseurl"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("expenseurl");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 14;
			fdata["strName"] = "rel";
			fdata["GoodName"] = "rel";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","rel");
			fdata["FieldType"] = 202;
			fdata["strField"] = "rel";
			fdata["sourceSingle"] = "rel";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "rel";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["rel"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("rel");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 15;
			fdata["strName"] = "seq";
			fdata["GoodName"] = "seq";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","seq");
			fdata["FieldType"] = 3;
			fdata["strField"] = "seq";
			fdata["sourceSingle"] = "seq";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "seq";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["seq"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("seq");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 16;
			fdata["strName"] = "project";
			fdata["GoodName"] = "project";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","project");
			fdata["FieldType"] = 202;
			fdata["strField"] = "project";
			fdata["sourceSingle"] = "project";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "project";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["project"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("project");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 17;
			fdata["strName"] = "task";
			fdata["GoodName"] = "task";
			fdata["ownerTable"] = "dbo.sc_expensereport_line_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sc_expensereport_line_mst","task");
			fdata["FieldType"] = 202;
			fdata["strField"] = "task";
			fdata["sourceSingle"] = "task";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "task";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sc_expensereport_line_mst"]["task"] = fdata;
			tdataArray["sc_expensereport_line_mst"][".searchableFields"].Add("task");
			GlobalVars.tables_data["dbo.sc_expensereport_line_mst"] = tdataArray["sc_expensereport_line_mst"];
			GlobalVars.field_labels["dbo_sc_expensereport_line_mst"] = fieldLabelsArray["sc_expensereport_line_mst"];
			GlobalVars.fieldToolTips["dbo_sc_expensereport_line_mst"] = fieldToolTipsArray["sc_expensereport_line_mst"];
			GlobalVars.placeHolders["dbo_sc_expensereport_line_mst"] = placeHoldersArray["sc_expensereport_line_mst"];
			GlobalVars.page_titles["dbo_sc_expensereport_line_mst"] = pageTitlesArray["sc_expensereport_line_mst"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.sc_expensereport_line_mst"));
			GlobalVars.detailsTablesData["dbo.sc_expensereport_line_mst"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.sc_expensereport_line_mst"] = SettingsMap.GetArray();


			strOriginalDetailsTable = "dbo.sc_expensereport_mst";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "dbo.sc_expensereport_mst";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "sc_expensereport_mst";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo.sc_expensereport_line_mst"][0] = masterParams;
			GlobalVars.masterTablesData["dbo.sc_expensereport_line_mst"][0]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.sc_expensereport_line_mst"][0]["masterKeys"].Add("report_id");
			GlobalVars.masterTablesData["dbo.sc_expensereport_line_mst"][0]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.sc_expensereport_line_mst"][0]["detailKeys"].Add("report_id");

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "site_ref,  	report_id,  	amount,  	curr_code,  	clientid,  	account,  	unitcd1,  	unitcd2,  	unitcd3,  	unitcd4,  	expenseid,  	ispersonalexpense,  	expenseurl,  	rel,  	seq,  	project,  	task";
protoArray["0"]["m_strFrom"] = "FROM dbo.sc_expensereport_line_mst";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "site_ref", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["6"]["m_sql"] = "site_ref";
protoArray["6"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "report_id", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["8"]["m_sql"] = "report_id";
protoArray["8"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "amount", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["10"]["m_sql"] = "amount";
protoArray["10"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "curr_code", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["12"]["m_sql"] = "curr_code";
protoArray["12"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "clientid", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["14"]["m_sql"] = "clientid";
protoArray["14"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "account", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["16"]["m_sql"] = "account";
protoArray["16"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "unitcd1", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["18"]["m_sql"] = "unitcd1";
protoArray["18"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "unitcd2", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["20"]["m_sql"] = "unitcd2";
protoArray["20"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "unitcd3", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["22"]["m_sql"] = "unitcd3";
protoArray["22"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "unitcd4", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["24"]["m_sql"] = "unitcd4";
protoArray["24"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "expenseid", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["26"]["m_sql"] = "expenseid";
protoArray["26"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ispersonalexpense", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["28"]["m_sql"] = "ispersonalexpense";
protoArray["28"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "expenseurl", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["30"]["m_sql"] = "expenseurl";
protoArray["30"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["32"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "rel", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["32"]["m_sql"] = "rel";
protoArray["32"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["32"]["m_expr"] = obj;
protoArray["32"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["32"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["34"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "seq", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["34"]["m_sql"] = "seq";
protoArray["34"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["34"]["m_expr"] = obj;
protoArray["34"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["34"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["36"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "project", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["36"]["m_sql"] = "project";
protoArray["36"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["36"]["m_expr"] = obj;
protoArray["36"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["36"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["38"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "task", "m_strTable", "dbo.sc_expensereport_line_mst", "m_srcTableName", "dbo.sc_expensereport_line_mst"));

protoArray["38"]["m_sql"] = "task";
protoArray["38"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["38"]["m_expr"] = obj;
protoArray["38"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["38"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["40"] = SettingsMap.GetArray();
protoArray["40"]["m_link"] = "SQLL_MAIN";
protoArray["41"] = SettingsMap.GetArray();
protoArray["41"]["m_strName"] = "dbo.sc_expensereport_line_mst";
protoArray["41"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["41"]["m_columns"] = SettingsMap.GetArray();
protoArray["41"]["m_columns"].Add("site_ref");
protoArray["41"]["m_columns"].Add("report_id");
protoArray["41"]["m_columns"].Add("amount");
protoArray["41"]["m_columns"].Add("curr_code");
protoArray["41"]["m_columns"].Add("clientid");
protoArray["41"]["m_columns"].Add("account");
protoArray["41"]["m_columns"].Add("unitcd1");
protoArray["41"]["m_columns"].Add("unitcd2");
protoArray["41"]["m_columns"].Add("unitcd3");
protoArray["41"]["m_columns"].Add("unitcd4");
protoArray["41"]["m_columns"].Add("expenseid");
protoArray["41"]["m_columns"].Add("ispersonalexpense");
protoArray["41"]["m_columns"].Add("expenseurl");
protoArray["41"]["m_columns"].Add("rel");
protoArray["41"]["m_columns"].Add("seq");
protoArray["41"]["m_columns"].Add("project");
protoArray["41"]["m_columns"].Add("task");
obj = new SQLTable(protoArray["41"]);

protoArray["40"]["m_table"] = obj;
protoArray["40"]["m_sql"] = "dbo.sc_expensereport_line_mst";
protoArray["40"]["m_alias"] = "";
protoArray["40"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
protoArray["42"] = SettingsMap.GetArray();
protoArray["42"]["m_sql"] = "";
protoArray["42"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["42"]["m_column"] = obj;
protoArray["42"]["m_contained"] = SettingsMap.GetArray();
protoArray["42"]["m_strCase"] = "";
protoArray["42"]["m_havingmode"] = false;
protoArray["42"]["m_inBrackets"] = false;
protoArray["42"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["42"]);

protoArray["40"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["40"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.sc_expensereport_line_mst";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["sc_expensereport_line_mst"] = obj;

				
		
			tdataArray["sc_expensereport_line_mst"][".sqlquery"] = queryData_Array["sc_expensereport_line_mst"];
			tdataArray["sc_expensereport_line_mst"][".hasEvents"] = false;
		}
	}

}
