using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_sh_products_mst
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["sh_products_mst"] = SettingsMap.GetArray();
			tdataArray["sh_products_mst"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["sh_products_mst"][".ShortName"] = "sh_products_mst";
			tdataArray["sh_products_mst"][".OwnerID"] = "";
			tdataArray["sh_products_mst"][".OriginalTable"] = "dbo.sh_products_mst";
			tdataArray["sh_products_mst"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}"));
			tdataArray["sh_products_mst"][".originalPagesByType"] = tdataArray["sh_products_mst"][".pagesByType"];
			tdataArray["sh_products_mst"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}")));
			tdataArray["sh_products_mst"][".originalPages"] = tdataArray["sh_products_mst"][".pages"];
			tdataArray["sh_products_mst"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"add\":\"add\",\"edit\":\"edit\",\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\"}"));
			tdataArray["sh_products_mst"][".originalDefaultPages"] = tdataArray["sh_products_mst"][".defaultPages"];
			fieldLabelsArray["sh_products_mst"] = SettingsMap.GetArray();
			fieldToolTipsArray["sh_products_mst"] = SettingsMap.GetArray();
			pageTitlesArray["sh_products_mst"] = SettingsMap.GetArray();
			placeHoldersArray["sh_products_mst"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["sh_products_mst"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["sh_products_mst"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["sh_products_mst"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["sh_products_mst"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["sh_products_mst"]["English"]["clientid"] = "Clientid";
				fieldToolTipsArray["sh_products_mst"]["English"]["clientid"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["clientid"] = "";
				fieldLabelsArray["sh_products_mst"]["English"]["id"] = "Id";
				fieldToolTipsArray["sh_products_mst"]["English"]["id"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["id"] = "";
				fieldLabelsArray["sh_products_mst"]["English"]["title"] = "Title";
				fieldToolTipsArray["sh_products_mst"]["English"]["title"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["title"] = "";
				fieldLabelsArray["sh_products_mst"]["English"]["price"] = "Price";
				fieldToolTipsArray["sh_products_mst"]["English"]["price"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["price"] = "";
				fieldLabelsArray["sh_products_mst"]["English"]["quantity"] = "Quantity";
				fieldToolTipsArray["sh_products_mst"]["English"]["quantity"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["quantity"] = "";
				fieldLabelsArray["sh_products_mst"]["English"]["item"] = "Item";
				fieldToolTipsArray["sh_products_mst"]["English"]["item"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["item"] = "";
				fieldLabelsArray["sh_products_mst"]["English"]["posted"] = "Posted";
				fieldToolTipsArray["sh_products_mst"]["English"]["posted"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["posted"] = "";
				fieldLabelsArray["sh_products_mst"]["English"]["location_name"] = "Location Name";
				fieldToolTipsArray["sh_products_mst"]["English"]["location_name"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["location_name"] = "";
				fieldLabelsArray["sh_products_mst"]["English"]["rowpointer"] = "Rowpointer";
				fieldToolTipsArray["sh_products_mst"]["English"]["rowpointer"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["rowpointer"] = "";
				fieldLabelsArray["sh_products_mst"]["English"]["create_date"] = "Create Date";
				fieldToolTipsArray["sh_products_mst"]["English"]["create_date"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["create_date"] = "";
				fieldLabelsArray["sh_products_mst"]["English"]["trans_num"] = "Trans Num";
				fieldToolTipsArray["sh_products_mst"]["English"]["trans_num"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["trans_num"] = "";
				fieldLabelsArray["sh_products_mst"]["English"]["jresult"] = "Jresult";
				fieldToolTipsArray["sh_products_mst"]["English"]["jresult"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["jresult"] = "";
				fieldLabelsArray["sh_products_mst"]["English"]["site_ref"] = "Site Ref";
				fieldToolTipsArray["sh_products_mst"]["English"]["site_ref"] = "";
				placeHoldersArray["sh_products_mst"]["English"]["site_ref"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["sh_products_mst"]["English"])))
				{
					tdataArray["sh_products_mst"][".isUseToolTips"] = true;
				}
			}
			tdataArray["sh_products_mst"][".NCSearch"] = true;
			tdataArray["sh_products_mst"][".shortTableName"] = "sh_products_mst";
			tdataArray["sh_products_mst"][".nSecOptions"] = 0;
			tdataArray["sh_products_mst"][".mainTableOwnerID"] = "";
			tdataArray["sh_products_mst"][".entityType"] = 0;
			tdataArray["sh_products_mst"][".connId"] = "Hubkoratec218206166241compute1";
			tdataArray["sh_products_mst"][".strOriginalTableName"] = "dbo.sh_products_mst";
			tdataArray["sh_products_mst"][".showAddInPopup"] = false;
			tdataArray["sh_products_mst"][".showEditInPopup"] = false;
			tdataArray["sh_products_mst"][".showViewInPopup"] = false;
			tdataArray["sh_products_mst"][".listAjax"] = false;
			tdataArray["sh_products_mst"][".audit"] = false;
			tdataArray["sh_products_mst"][".locking"] = false;
			GlobalVars.pages = tdataArray["sh_products_mst"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["sh_products_mst"][".edit"] = true;
				tdataArray["sh_products_mst"][".afterEditAction"] = 1;
				tdataArray["sh_products_mst"][".closePopupAfterEdit"] = 1;
				tdataArray["sh_products_mst"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["sh_products_mst"][".add"] = true;
				tdataArray["sh_products_mst"][".afterAddAction"] = 1;
				tdataArray["sh_products_mst"][".closePopupAfterAdd"] = 1;
				tdataArray["sh_products_mst"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["sh_products_mst"][".list"] = true;
			}
			tdataArray["sh_products_mst"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["sh_products_mst"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["sh_products_mst"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["sh_products_mst"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["sh_products_mst"][".printFriendly"] = true;
			}
			tdataArray["sh_products_mst"][".showSimpleSearchOptions"] = true;
			tdataArray["sh_products_mst"][".allowShowHideFields"] = true;
			tdataArray["sh_products_mst"][".allowFieldsReordering"] = true;
			tdataArray["sh_products_mst"][".isUseAjaxSuggest"] = true;


			tdataArray["sh_products_mst"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["sh_products_mst"][".buttonsAdded"] = false;
			tdataArray["sh_products_mst"][".addPageEvents"] = false;
			tdataArray["sh_products_mst"][".isUseTimeForSearch"] = false;
			tdataArray["sh_products_mst"][".badgeColor"] = "DAA520";
			tdataArray["sh_products_mst"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["sh_products_mst"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["sh_products_mst"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["sh_products_mst"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("clientid");
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("id");
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("price");
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("quantity");
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("item");
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("title");
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("posted");
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("location_name");
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("rowpointer");
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("create_date");
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("trans_num");
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("jresult");
			tdataArray["sh_products_mst"][".googleLikeFields"].Add("site_ref");
			tdataArray["sh_products_mst"][".tableType"] = "list";
			tdataArray["sh_products_mst"][".printerPageOrientation"] = 0;
			tdataArray["sh_products_mst"][".nPrinterPageScale"] = 100;
			tdataArray["sh_products_mst"][".nPrinterSplitRecords"] = 40;
			tdataArray["sh_products_mst"][".geocodingEnabled"] = false;
			tdataArray["sh_products_mst"][".pageSize"] = 20;
			tdataArray["sh_products_mst"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["sh_products_mst"][".strOrderBy"] = tstrOrderBy;
			tdataArray["sh_products_mst"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["sh_products_mst"][".sqlHead"] = "SELECT clientid,  	id,  	price,  	quantity,  	item,  	title,  	posted,  	location_name,  	rowpointer,  	create_date,  	trans_num,  	jresult,  	site_ref";
			tdataArray["sh_products_mst"][".sqlFrom"] = "FROM dbo.sh_products_mst";
			tdataArray["sh_products_mst"][".sqlWhereExpr"] = "";
			tdataArray["sh_products_mst"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["sh_products_mst"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["sh_products_mst"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["sh_products_mst"][".highlightSearchResults"] = true;
			tableKeysArray["sh_products_mst"] = SettingsMap.GetArray();
			tableKeysArray["sh_products_mst"].Add("clientid");
			tdataArray["sh_products_mst"][".Keys"] = tableKeysArray["sh_products_mst"];
			tdataArray["sh_products_mst"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "clientid";
			fdata["GoodName"] = "clientid";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","clientid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "clientid";
			fdata["sourceSingle"] = "clientid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "clientid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["clientid"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("clientid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "id";
			fdata["GoodName"] = "id";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","id");
			fdata["FieldType"] = 202;
			fdata["strField"] = "id";
			fdata["sourceSingle"] = "id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["id"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "price";
			fdata["GoodName"] = "price";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","price");
			fdata["FieldType"] = 14;
			fdata["strField"] = "price";
			fdata["sourceSingle"] = "price";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "price";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 8;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["price"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("price");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "quantity";
			fdata["GoodName"] = "quantity";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","quantity");
			fdata["FieldType"] = 3;
			fdata["strField"] = "quantity";
			fdata["sourceSingle"] = "quantity";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "quantity";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["quantity"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("quantity");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "item";
			fdata["GoodName"] = "item";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","item");
			fdata["FieldType"] = 202;
			fdata["strField"] = "item";
			fdata["sourceSingle"] = "item";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "item";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["item"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("item");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "title";
			fdata["GoodName"] = "title";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","title");
			fdata["FieldType"] = 202;
			fdata["strField"] = "title";
			fdata["sourceSingle"] = "title";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "title";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["title"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("title");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "posted";
			fdata["GoodName"] = "posted";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","posted");
			fdata["FieldType"] = 16;
			fdata["strField"] = "posted";
			fdata["sourceSingle"] = "posted";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "posted";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["posted"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("posted");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "location_name";
			fdata["GoodName"] = "location_name";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","location_name");
			fdata["FieldType"] = 202;
			fdata["strField"] = "location_name";
			fdata["sourceSingle"] = "location_name";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "location_name";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["location_name"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("location_name");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "rowpointer";
			fdata["GoodName"] = "rowpointer";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","rowpointer");
			fdata["FieldType"] = 72;
			fdata["strField"] = "rowpointer";
			fdata["sourceSingle"] = "rowpointer";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "rowpointer";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["rowpointer"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("rowpointer");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "create_date";
			fdata["GoodName"] = "create_date";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","create_date");
			fdata["FieldType"] = 135;
			fdata["strField"] = "create_date";
			fdata["sourceSingle"] = "create_date";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "create_date";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["create_date"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("create_date");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "trans_num";
			fdata["GoodName"] = "trans_num";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","trans_num");
			fdata["FieldType"] = 3;
			fdata["AutoInc"] = true;
			fdata["strField"] = "trans_num";
			fdata["sourceSingle"] = "trans_num";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "trans_num";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["trans_num"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("trans_num");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "jresult";
			fdata["GoodName"] = "jresult";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","jresult");
			fdata["FieldType"] = 202;
			fdata["strField"] = "jresult";
			fdata["sourceSingle"] = "jresult";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "jresult";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["jresult"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("jresult");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "site_ref";
			fdata["GoodName"] = "site_ref";
			fdata["ownerTable"] = "dbo.sh_products_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_sh_products_mst","site_ref");
			fdata["FieldType"] = 202;
			fdata["strField"] = "site_ref";
			fdata["sourceSingle"] = "site_ref";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "site_ref";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["sh_products_mst"]["site_ref"] = fdata;
			tdataArray["sh_products_mst"][".searchableFields"].Add("site_ref");
			GlobalVars.tables_data["dbo.sh_products_mst"] = tdataArray["sh_products_mst"];
			GlobalVars.field_labels["dbo_sh_products_mst"] = fieldLabelsArray["sh_products_mst"];
			GlobalVars.fieldToolTips["dbo_sh_products_mst"] = fieldToolTipsArray["sh_products_mst"];
			GlobalVars.placeHolders["dbo_sh_products_mst"] = placeHoldersArray["sh_products_mst"];
			GlobalVars.page_titles["dbo_sh_products_mst"] = pageTitlesArray["sh_products_mst"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.sh_products_mst"));
			GlobalVars.detailsTablesData["dbo.sh_products_mst"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.sh_products_mst"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "clientid,  	id,  	price,  	quantity,  	item,  	title,  	posted,  	location_name,  	rowpointer,  	create_date,  	trans_num,  	jresult,  	site_ref";
protoArray["0"]["m_strFrom"] = "FROM dbo.sh_products_mst";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "clientid", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["6"]["m_sql"] = "clientid";
protoArray["6"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "id", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["8"]["m_sql"] = "id";
protoArray["8"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "price", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["10"]["m_sql"] = "price";
protoArray["10"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "quantity", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["12"]["m_sql"] = "quantity";
protoArray["12"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "item", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["14"]["m_sql"] = "item";
protoArray["14"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "title", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["16"]["m_sql"] = "title";
protoArray["16"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "posted", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["18"]["m_sql"] = "posted";
protoArray["18"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "location_name", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["20"]["m_sql"] = "location_name";
protoArray["20"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "rowpointer", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["22"]["m_sql"] = "rowpointer";
protoArray["22"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "create_date", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["24"]["m_sql"] = "create_date";
protoArray["24"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "trans_num", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["26"]["m_sql"] = "trans_num";
protoArray["26"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "jresult", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["28"]["m_sql"] = "jresult";
protoArray["28"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "site_ref", "m_strTable", "dbo.sh_products_mst", "m_srcTableName", "dbo.sh_products_mst"));

protoArray["30"]["m_sql"] = "site_ref";
protoArray["30"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["32"] = SettingsMap.GetArray();
protoArray["32"]["m_link"] = "SQLL_MAIN";
protoArray["33"] = SettingsMap.GetArray();
protoArray["33"]["m_strName"] = "dbo.sh_products_mst";
protoArray["33"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["33"]["m_columns"] = SettingsMap.GetArray();
protoArray["33"]["m_columns"].Add("clientid");
protoArray["33"]["m_columns"].Add("id");
protoArray["33"]["m_columns"].Add("price");
protoArray["33"]["m_columns"].Add("quantity");
protoArray["33"]["m_columns"].Add("item");
protoArray["33"]["m_columns"].Add("title");
protoArray["33"]["m_columns"].Add("posted");
protoArray["33"]["m_columns"].Add("location_name");
protoArray["33"]["m_columns"].Add("rowpointer");
protoArray["33"]["m_columns"].Add("create_date");
protoArray["33"]["m_columns"].Add("trans_num");
protoArray["33"]["m_columns"].Add("jresult");
protoArray["33"]["m_columns"].Add("site_ref");
obj = new SQLTable(protoArray["33"]);

protoArray["32"]["m_table"] = obj;
protoArray["32"]["m_sql"] = "dbo.sh_products_mst";
protoArray["32"]["m_alias"] = "";
protoArray["32"]["m_srcTableName"] = "dbo.sh_products_mst";
protoArray["34"] = SettingsMap.GetArray();
protoArray["34"]["m_sql"] = "";
protoArray["34"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["34"]["m_column"] = obj;
protoArray["34"]["m_contained"] = SettingsMap.GetArray();
protoArray["34"]["m_strCase"] = "";
protoArray["34"]["m_havingmode"] = false;
protoArray["34"]["m_inBrackets"] = false;
protoArray["34"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["34"]);

protoArray["32"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["32"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.sh_products_mst";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["sh_products_mst"] = obj;

				
		
			tdataArray["sh_products_mst"][".sqlquery"] = queryData_Array["sh_products_mst"];
			tdataArray["sh_products_mst"][".hasEvents"] = false;
		}
	}

}
