using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_tp_po_mst
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["tp_po_mst"] = SettingsMap.GetArray();
			tdataArray["tp_po_mst"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["tp_po_mst"][".ShortName"] = "tp_po_mst";
			tdataArray["tp_po_mst"][".OwnerID"] = "clientid";
			tdataArray["tp_po_mst"][".OriginalTable"] = "dbo.tp_po_mst";
			tdataArray["tp_po_mst"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}"));
			tdataArray["tp_po_mst"][".originalPagesByType"] = tdataArray["tp_po_mst"][".pagesByType"];
			tdataArray["tp_po_mst"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"]}")));
			tdataArray["tp_po_mst"][".originalPages"] = tdataArray["tp_po_mst"][".pages"];
			tdataArray["tp_po_mst"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\"}"));
			tdataArray["tp_po_mst"][".originalDefaultPages"] = tdataArray["tp_po_mst"][".defaultPages"];
			fieldLabelsArray["tp_po_mst"] = SettingsMap.GetArray();
			fieldToolTipsArray["tp_po_mst"] = SettingsMap.GetArray();
			pageTitlesArray["tp_po_mst"] = SettingsMap.GetArray();
			placeHoldersArray["tp_po_mst"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["tp_po_mst"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["tp_po_mst"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["tp_po_mst"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["tp_po_mst"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["tp_po_mst"]["English"]["clientid"] = "Clientid";
				fieldToolTipsArray["tp_po_mst"]["English"]["clientid"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["clientid"] = "";
				fieldLabelsArray["tp_po_mst"]["English"]["seq"] = "Seq";
				fieldToolTipsArray["tp_po_mst"]["English"]["seq"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["seq"] = "";
				fieldLabelsArray["tp_po_mst"]["English"]["vend_num"] = "Vend Num";
				fieldToolTipsArray["tp_po_mst"]["English"]["vend_num"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["vend_num"] = "";
				fieldLabelsArray["tp_po_mst"]["English"]["po_num"] = "Po Num";
				fieldToolTipsArray["tp_po_mst"]["English"]["po_num"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["po_num"] = "";
				fieldLabelsArray["tp_po_mst"]["English"]["status"] = "Status";
				fieldToolTipsArray["tp_po_mst"]["English"]["status"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["status"] = "";
				fieldLabelsArray["tp_po_mst"]["English"]["orderdate"] = "Orderdate";
				fieldToolTipsArray["tp_po_mst"]["English"]["orderdate"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["orderdate"] = "";
				fieldLabelsArray["tp_po_mst"]["English"]["currency"] = "Currency";
				fieldToolTipsArray["tp_po_mst"]["English"]["currency"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["currency"] = "";
				fieldLabelsArray["tp_po_mst"]["English"]["payerentity"] = "Payerentity";
				fieldToolTipsArray["tp_po_mst"]["English"]["payerentity"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["payerentity"] = "";
				fieldLabelsArray["tp_po_mst"]["English"]["createdate"] = "Createdate";
				fieldToolTipsArray["tp_po_mst"]["English"]["createdate"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["createdate"] = "";
				fieldLabelsArray["tp_po_mst"]["English"]["recorddate"] = "Recorddate";
				fieldToolTipsArray["tp_po_mst"]["English"]["recorddate"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["recorddate"] = "";
				fieldLabelsArray["tp_po_mst"]["English"]["posted"] = "Posted";
				fieldToolTipsArray["tp_po_mst"]["English"]["posted"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["posted"] = "";
				fieldLabelsArray["tp_po_mst"]["English"]["payload"] = "Payload";
				fieldToolTipsArray["tp_po_mst"]["English"]["payload"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["payload"] = "";
				fieldLabelsArray["tp_po_mst"]["English"]["response"] = "Response";
				fieldToolTipsArray["tp_po_mst"]["English"]["response"] = "";
				placeHoldersArray["tp_po_mst"]["English"]["response"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["tp_po_mst"]["English"])))
				{
					tdataArray["tp_po_mst"][".isUseToolTips"] = true;
				}
			}
			tdataArray["tp_po_mst"][".NCSearch"] = true;
			tdataArray["tp_po_mst"][".shortTableName"] = "tp_po_mst";
			tdataArray["tp_po_mst"][".nSecOptions"] = 1;
			tdataArray["tp_po_mst"][".mainTableOwnerID"] = "clientid";
			tdataArray["tp_po_mst"][".entityType"] = 0;
			tdataArray["tp_po_mst"][".connId"] = "Hubkoratec218206166241compute1";
			tdataArray["tp_po_mst"][".strOriginalTableName"] = "dbo.tp_po_mst";
			tdataArray["tp_po_mst"][".showAddInPopup"] = false;
			tdataArray["tp_po_mst"][".showEditInPopup"] = false;
			tdataArray["tp_po_mst"][".showViewInPopup"] = false;
			tdataArray["tp_po_mst"][".listAjax"] = false;
			tdataArray["tp_po_mst"][".audit"] = false;
			tdataArray["tp_po_mst"][".locking"] = false;
			GlobalVars.pages = tdataArray["tp_po_mst"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["tp_po_mst"][".edit"] = true;
				tdataArray["tp_po_mst"][".afterEditAction"] = 1;
				tdataArray["tp_po_mst"][".closePopupAfterEdit"] = 1;
				tdataArray["tp_po_mst"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["tp_po_mst"][".add"] = true;
				tdataArray["tp_po_mst"][".afterAddAction"] = 1;
				tdataArray["tp_po_mst"][".closePopupAfterAdd"] = 1;
				tdataArray["tp_po_mst"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["tp_po_mst"][".list"] = true;
			}
			tdataArray["tp_po_mst"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["tp_po_mst"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["tp_po_mst"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["tp_po_mst"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["tp_po_mst"][".printFriendly"] = true;
			}
			tdataArray["tp_po_mst"][".showSimpleSearchOptions"] = true;
			tdataArray["tp_po_mst"][".allowShowHideFields"] = true;
			tdataArray["tp_po_mst"][".allowFieldsReordering"] = true;
			tdataArray["tp_po_mst"][".isUseAjaxSuggest"] = true;


			tdataArray["tp_po_mst"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["tp_po_mst"][".buttonsAdded"] = false;
			tdataArray["tp_po_mst"][".addPageEvents"] = false;
			tdataArray["tp_po_mst"][".isUseTimeForSearch"] = false;
			tdataArray["tp_po_mst"][".badgeColor"] = "4682b4";
			tdataArray["tp_po_mst"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["tp_po_mst"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["tp_po_mst"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["tp_po_mst"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("clientid");
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("seq");
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("vend_num");
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("po_num");
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("status");
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("orderdate");
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("currency");
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("payerentity");
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("createdate");
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("recorddate");
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("posted");
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("payload");
			tdataArray["tp_po_mst"][".googleLikeFields"].Add("response");
			tdataArray["tp_po_mst"][".tableType"] = "list";
			tdataArray["tp_po_mst"][".printerPageOrientation"] = 0;
			tdataArray["tp_po_mst"][".nPrinterPageScale"] = 100;
			tdataArray["tp_po_mst"][".nPrinterSplitRecords"] = 40;
			tdataArray["tp_po_mst"][".geocodingEnabled"] = false;
			tdataArray["tp_po_mst"][".pageSize"] = 20;
			tdataArray["tp_po_mst"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["tp_po_mst"][".strOrderBy"] = tstrOrderBy;
			tdataArray["tp_po_mst"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["tp_po_mst"][".sqlHead"] = "SELECT clientid,  	seq,  	vend_num,  	po_num,  	status,  	orderdate,  	currency,  	payerentity,  	createdate,  	recorddate,  	posted,  	payload,  	response";
			tdataArray["tp_po_mst"][".sqlFrom"] = "FROM dbo.tp_po_mst";
			tdataArray["tp_po_mst"][".sqlWhereExpr"] = "";
			tdataArray["tp_po_mst"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["tp_po_mst"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["tp_po_mst"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["tp_po_mst"][".highlightSearchResults"] = true;
			tableKeysArray["tp_po_mst"] = SettingsMap.GetArray();
			tdataArray["tp_po_mst"][".Keys"] = tableKeysArray["tp_po_mst"];
			tdataArray["tp_po_mst"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "clientid";
			fdata["GoodName"] = "clientid";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","clientid");
			fdata["FieldType"] = 202;
			fdata["strField"] = "clientid";
			fdata["sourceSingle"] = "clientid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "clientid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=20");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["clientid"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("clientid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "seq";
			fdata["GoodName"] = "seq";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","seq");
			fdata["FieldType"] = 20;
			fdata["AutoInc"] = true;
			fdata["strField"] = "seq";
			fdata["sourceSingle"] = "seq";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "seq";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["seq"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("seq");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "vend_num";
			fdata["GoodName"] = "vend_num";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","vend_num");
			fdata["FieldType"] = 202;
			fdata["strField"] = "vend_num";
			fdata["sourceSingle"] = "vend_num";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "vend_num";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=40");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["vend_num"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("vend_num");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "po_num";
			fdata["GoodName"] = "po_num";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","po_num");
			fdata["FieldType"] = 202;
			fdata["strField"] = "po_num";
			fdata["sourceSingle"] = "po_num";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "po_num";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["po_num"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("po_num");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "status";
			fdata["GoodName"] = "status";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","status");
			fdata["FieldType"] = 202;
			fdata["strField"] = "status";
			fdata["sourceSingle"] = "status";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "status";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=10");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["status"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("status");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "orderdate";
			fdata["GoodName"] = "orderdate";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","orderdate");
			fdata["FieldType"] = 202;
			fdata["strField"] = "orderdate";
			fdata["sourceSingle"] = "orderdate";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "orderdate";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["orderdate"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("orderdate");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "currency";
			fdata["GoodName"] = "currency";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","currency");
			fdata["FieldType"] = 202;
			fdata["strField"] = "currency";
			fdata["sourceSingle"] = "currency";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "currency";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["currency"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("currency");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "payerentity";
			fdata["GoodName"] = "payerentity";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","payerentity");
			fdata["FieldType"] = 202;
			fdata["strField"] = "payerentity";
			fdata["sourceSingle"] = "payerentity";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "payerentity";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=30");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["payerentity"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("payerentity");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "createdate";
			fdata["GoodName"] = "createdate";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","createdate");
			fdata["FieldType"] = 135;
			fdata["strField"] = "createdate";
			fdata["sourceSingle"] = "createdate";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "createdate";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["createdate"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("createdate");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "recorddate";
			fdata["GoodName"] = "recorddate";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","recorddate");
			fdata["FieldType"] = 135;
			fdata["strField"] = "recorddate";
			fdata["sourceSingle"] = "recorddate";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "recorddate";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["recorddate"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("recorddate");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "posted";
			fdata["GoodName"] = "posted";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","posted");
			fdata["FieldType"] = 16;
			fdata["strField"] = "posted";
			fdata["sourceSingle"] = "posted";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "posted";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["posted"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("posted");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "payload";
			fdata["GoodName"] = "payload";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","payload");
			fdata["FieldType"] = 202;
			fdata["strField"] = "payload";
			fdata["sourceSingle"] = "payload";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "payload";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["payload"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("payload");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "response";
			fdata["GoodName"] = "response";
			fdata["ownerTable"] = "dbo.tp_po_mst";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_tp_po_mst","response");
			fdata["FieldType"] = 202;
			fdata["strField"] = "response";
			fdata["sourceSingle"] = "response";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "response";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["tp_po_mst"]["response"] = fdata;
			tdataArray["tp_po_mst"][".searchableFields"].Add("response");
			GlobalVars.tables_data["dbo.tp_po_mst"] = tdataArray["tp_po_mst"];
			GlobalVars.field_labels["dbo_tp_po_mst"] = fieldLabelsArray["tp_po_mst"];
			GlobalVars.fieldToolTips["dbo_tp_po_mst"] = fieldToolTipsArray["tp_po_mst"];
			GlobalVars.placeHolders["dbo_tp_po_mst"] = placeHoldersArray["tp_po_mst"];
			GlobalVars.page_titles["dbo_tp_po_mst"] = pageTitlesArray["tp_po_mst"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.tp_po_mst"));
			GlobalVars.detailsTablesData["dbo.tp_po_mst"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.tp_po_mst"] = SettingsMap.GetArray();


			strOriginalDetailsTable = "dbo.tp_po";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "dbo.tp_po";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "tp_po";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo.tp_po_mst"][0] = masterParams;
			GlobalVars.masterTablesData["dbo.tp_po_mst"][0]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.tp_po_mst"][0]["masterKeys"].Add("clientid");
			GlobalVars.masterTablesData["dbo.tp_po_mst"][0]["masterKeys"].Add("po_num");
			GlobalVars.masterTablesData["dbo.tp_po_mst"][0]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.tp_po_mst"][0]["detailKeys"].Add("clientid");
			GlobalVars.masterTablesData["dbo.tp_po_mst"][0]["detailKeys"].Add("po_num");

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "clientid,  	seq,  	vend_num,  	po_num,  	status,  	orderdate,  	currency,  	payerentity,  	createdate,  	recorddate,  	posted,  	payload,  	response";
protoArray["0"]["m_strFrom"] = "FROM dbo.tp_po_mst";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "clientid", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["6"]["m_sql"] = "clientid";
protoArray["6"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "seq", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["8"]["m_sql"] = "seq";
protoArray["8"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "vend_num", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["10"]["m_sql"] = "vend_num";
protoArray["10"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "po_num", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["12"]["m_sql"] = "po_num";
protoArray["12"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "status", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["14"]["m_sql"] = "status";
protoArray["14"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "orderdate", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["16"]["m_sql"] = "orderdate";
protoArray["16"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "currency", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["18"]["m_sql"] = "currency";
protoArray["18"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "payerentity", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["20"]["m_sql"] = "payerentity";
protoArray["20"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "createdate", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["22"]["m_sql"] = "createdate";
protoArray["22"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "recorddate", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["24"]["m_sql"] = "recorddate";
protoArray["24"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "posted", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["26"]["m_sql"] = "posted";
protoArray["26"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "payload", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["28"]["m_sql"] = "payload";
protoArray["28"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "response", "m_strTable", "dbo.tp_po_mst", "m_srcTableName", "dbo.tp_po_mst"));

protoArray["30"]["m_sql"] = "response";
protoArray["30"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["32"] = SettingsMap.GetArray();
protoArray["32"]["m_link"] = "SQLL_MAIN";
protoArray["33"] = SettingsMap.GetArray();
protoArray["33"]["m_strName"] = "dbo.tp_po_mst";
protoArray["33"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["33"]["m_columns"] = SettingsMap.GetArray();
protoArray["33"]["m_columns"].Add("clientid");
protoArray["33"]["m_columns"].Add("seq");
protoArray["33"]["m_columns"].Add("vend_num");
protoArray["33"]["m_columns"].Add("po_num");
protoArray["33"]["m_columns"].Add("status");
protoArray["33"]["m_columns"].Add("orderdate");
protoArray["33"]["m_columns"].Add("currency");
protoArray["33"]["m_columns"].Add("payerentity");
protoArray["33"]["m_columns"].Add("createdate");
protoArray["33"]["m_columns"].Add("recorddate");
protoArray["33"]["m_columns"].Add("posted");
protoArray["33"]["m_columns"].Add("payload");
protoArray["33"]["m_columns"].Add("response");
obj = new SQLTable(protoArray["33"]);

protoArray["32"]["m_table"] = obj;
protoArray["32"]["m_sql"] = "dbo.tp_po_mst";
protoArray["32"]["m_alias"] = "";
protoArray["32"]["m_srcTableName"] = "dbo.tp_po_mst";
protoArray["34"] = SettingsMap.GetArray();
protoArray["34"]["m_sql"] = "";
protoArray["34"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["34"]["m_column"] = obj;
protoArray["34"]["m_contained"] = SettingsMap.GetArray();
protoArray["34"]["m_strCase"] = "";
protoArray["34"]["m_havingmode"] = false;
protoArray["34"]["m_inBrackets"] = false;
protoArray["34"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["34"]);

protoArray["32"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["32"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.tp_po_mst";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["tp_po_mst"] = obj;

				
		
			tdataArray["tp_po_mst"][".sqlquery"] = queryData_Array["tp_po_mst"];
			tdataArray["tp_po_mst"][".hasEvents"] = false;
		}
	}

}
